

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	Review of CubeCart - Read User Reviews &amp; Feature Listings for CubeCart Shopping Cart
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<link href="../App_Themes/Cart/StyleSheet.css" type="text/css" rel="stylesheet" /><meta name="Description" content="Recent User Review: Moving to cubecart was the worst decision I have ever made for my online shop, I have lost tens of thousands of pounds in orders.

On the face of it, it looks ok, easy enough to use, but the back end is terrible.

The supposedly search engine URLS it generates causes google to think it has 2 URLS, so we lost our place on google within weeks of switching to cube. Also there is a bug in it where people keep on trying to log in and it logs them out again; the only way round this is to delete your cookies, but I dread to think how many of our customers gave up.

The language tool, which we have now disabled, also created even more duplicate pages for you to lose your place even further on google.

Do not touch Cube Cart with a barge poll, it is awful."></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./Cubecart.aspx?cartname=Cubecart" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE2OTE4OTY5NTcPZBYCZg9kFgICAw9kFgICAg9kFgRmD2QWdGYPDxYCHgRUZXh0BRg8aDE+Q3ViZUNhcnQgUmV2aWV3PC9oMT5kZAIBDw8WAh8ABUk8YSBocmVmPSIvcmV2aWV3LmFzcHg/Y2FydD1DdWJlY2FydCIgcmVsPSJub2ZvbGxvdyI+UmV2aWV3IHRoaXMgY2FydCE8L2E+ZGQCAg8PFgIfAAWUATxhIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vd3d3LmN1YmVjYXJ0LmNvbS8iIG9uQ2xpY2s9Il9nYXEucHVzaChbJ190cmFja0V2ZW50JywnT3V0Ym91bmRTdG9yZXMnLCAnQ2xpY2snLCAnQ3ViZUNhcnQnXSk7Ij5EZXZlbGxpb24gTGltaXRlZDwvYT5kZAIDDw8WAh8ABTg8ZGl2IGNsYXNzPSJpdGVtIj48c3BhbiBjbGFzcz0iZm4iPkN1YmVDYXJ0PC9zcGFuPjwvZGl2PmRkAgQPDxYCHwAFAzMuMGRkAgUPDxYCHwAFaDxhIHJlbD0ibm9mb2xsb3ciIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vd3d3LnNtYXJ0cG9wcHkuY29tLmF1LyI+aHR0cDovL3d3dy5zbWFydHBvcHB5LmNvbS5hdS88L2E+ZGQCBg8PFgIfAAVaPGEgcmVsPSJub2ZvbGxvdyIgdGFyZ2V0PSJfYmxhbmsiIGhyZWY9Imh0dHA6Ly93d3cuZXppbXAzLmNvbS8iPmh0dHA6Ly93d3cuZXppbXAzLmNvbS88L2E+ZGQCBw8PFgIfAGVkZAIIDw8WAh8ABQUkVVM2OWRkAgkPDxYCHwAFwwM8ZGl2IGNsYXNzPSJyYXRpbmciPjxzcGFuIGNsYXNzPSJhdmVyYWdlIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHRpdGxlPSIyLjUgc3RhciByYXRpbmciIGFsdD0iMi41IHN0YXIgcmF0aW5nIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUhhbGYuZ2lmIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiPkF2ZXJhZ2U6IDIuNTwvc3Bhbj48L2Rpdj4oPHNwYW4gY2xhc3M9ImNvdW50Ij4xODwvc3Bhbj4pZGQCCg8PFgIfAAXTjwFSZXZpZXdlZCBieTogQ2hyaXM8YnIgLz4iTW92aW5nIHRvIGN1YmVjYXJ0IHdhcyB0aGUgd29yc3QgZGVjaXNpb24gSSBoYXZlIGV2ZXIgbWFkZSBmb3IgbXkgb25saW5lIHNob3AsIEkgaGF2ZSBsb3N0IHRlbnMgb2YgdGhvdXNhbmRzIG9mIHBvdW5kcyBpbiBvcmRlcnMuDQoNCk9uIHRoZSBmYWNlIG9mIGl0LCBpdCBsb29rcyBvaywgZWFzeSBlbm91Z2ggdG8gdXNlLCBidXQgdGhlIGJhY2sgZW5kIGlzIHRlcnJpYmxlLg0KDQpUaGUgc3VwcG9zZWRseSBzZWFyY2ggZW5naW5lIFVSTFMgaXQgZ2VuZXJhdGVzIGNhdXNlcyBnb29nbGUgdG8gdGhpbmsgaXQgaGFzIDIgVVJMUywgc28gd2UgbG9zdCBvdXIgcGxhY2Ugb24gZ29vZ2xlIHdpdGhpbiB3ZWVrcyBvZiBzd2l0Y2hpbmcgdG8gY3ViZS4gQWxzbyB0aGVyZSBpcyBhIGJ1ZyBpbiBpdCB3aGVyZSBwZW9wbGUga2VlcCBvbiB0cnlpbmcgdG8gbG9nIGluIGFuZCBpdCBsb2dzIHRoZW0gb3V0IGFnYWluOyB0aGUgb25seSB3YXkgcm91bmQgdGhpcyBpcyB0byBkZWxldGUgeW91ciBjb29raWVzLCBidXQgSSBkcmVhZCB0byB0aGluayBob3cgbWFueSBvZiBvdXIgY3VzdG9tZXJzIGdhdmUgdXAuDQoNClRoZSBsYW5ndWFnZSB0b29sLCB3aGljaCB3ZSBoYXZlIG5vdyBkaXNhYmxlZCwgYWxzbyBjcmVhdGVkIGV2ZW4gbW9yZSBkdXBsaWNhdGUgcGFnZXMgZm9yIHlvdSB0byBsb3NlIHlvdXIgcGxhY2UgZXZlbiBmdXJ0aGVyIG9uIGdvb2dsZS4NCg0KRG8gbm90IHRvdWNoIEN1YmUgQ2FydCB3aXRoIGEgYmFyZ2UgcG9sbCwgaXQgaXMgYXdmdWwuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IE9jdG9iZXIsIDIwMTUgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogMy4wPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IE5pa2kgQnVza2VsbDxiciAvPiJDdWJlIENhcnQgaXMgYSB2ZXJ5IHNpbXBsZSBhbmQgZWZmZWN0aXZlIG9ubGluZSBzdG9yZSBhdCBhIGdyZWF0IHByaWNlLiBUaGUgQmFjayBlbmQgaXMgdmVyeSB1c2VmdWwgZm9yIHJldGFpbGVycy4NCg0KSSBmb3VuZCB0aGUgc3VwcG9ydCBxdWljayBhbmQgZWZmZWN0aXZlIGFuZCB0aGUgZm9ydW1zIGVxdWFsbHkgaGVscGZ1bC4gVGhlIHByb2JsZW1zIEkgaW5jdXJyZWQgd2VyZSByZXNvbHZlZCBzd2lmdGx5LiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKYW51YXJ5LCAyMDEzICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IDMuMDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBMaWxpYW48YnIgLz4iU3RlZXIgY2xlYXIgZnJvbSBDdWJlY2FydC4gWW91IG5ldmVyIGtub3cgZm9yIGhvdyBsb25nIHlvdXIgc3RvcmUgd2lsbCBiZSB3b3JraW5nIHByb3Blcmx5LiBFdmVyeSB1cGdyYWRlIGlzIGZ1bGwgb2YgYnVncywgc28geW91IGhhdmUgdG8gdGVzdCB0aGUgZW50aXJlIHN0b3JlIGFsbCBvdmVyIGFnYWluIHRvIGF2b2lkIHByb2JsZW1zLCBsZXQgYWxvbmUgeW91IHdpbGwgbmVlZCB0byBjdXN0b21pemUgc2lkZSBib3hlcyBhbmQgdGVtcGxhdGVzIGFsbCBvdmVyIGFnYWluLiBJIGxvc3QgY3VzdG9tZXJzLCBtb25leSBhbmQgbW9udGhzIG9mIGhhcmQgd29yayB1cGxvYWRpbmcgcHJvZHVjdHMgYW5kIGN1c3RvbWl6aW5nLiBJJ20gY2xvc2luZyB0aGUgc3RvcmUgYW5kIHN3aXRjaGluZyBwcm92aWRlci4gIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IE9jdG9iZXIsIDIwMTIgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogMy4wPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IERhdmlkIEFuc2NvbWI8YnIgLz4iVmVyeSBmcnVzdHJhdGluZyBleHBlcmllbmNlLCB3b3JrcyBvbiBhIHZlcnkgY3J1ZGUgbGV2ZWwgaWYgdGhhdCdzIGFsbCB5b3UgbmVlZCwgdGhvdWdoIG5vIGJldHRlciB0aGFuIGZyZWUgY2FydHMsIHBvb3Igc3VwcG9ydCwgdmVyeSBidWdneSx0aGUgZGV2ZWxvcGVycyBzZWVtIHRvIGJlIG92ZXJ3aGVsbWVkLCBhbmQgYXJlIHRoZXJlZm9yZSBub3QgdmVyeSBoZWxwZnVsLiBldmVuIHRoZSBidWcgdHJhY2tlciBkaWRuJ3Qgd29yayBsYXN0IHRpbWUgaSB1c2VkIGl0LiBTby0gYW4gb2sgYmFzaWMgc3lzdGVtLCBidXQgbm8gYmV0dGVyIHRoYW4gZnJlZSBjYXJ0cyBvdXQgdGhlcmUuIFJlYWQgdGhlaXIgc3VwcG9ydCBmb3J1bXMgYmVmb3JlIGNvbW1pdHRpbmcuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEphbnVhcnksIDIwMTIgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogMy4wPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IFBldGVyPGJyIC8+IlRlcnJpYmxlLiAgVGhlIHVwZ3JhZGUgYnJva2Ugb3VyIGNhcnQgYW5kIHdlIHdyb3RlIHRoZW0gZm9yIGEgcmVmdW5kLCBkZW5pZWQuICBObyBjdXN0b21lciBzZXJ2aWNlIGF0IGFsbC4gIEEgZnVuY3Rpb25pbmcgYnVzeSBjYXJ0IGRvd24gYmVjYXVzZSBvZiBicm9rZW4gY29kZS4gIFN0YXkgYXdheSBmcm9tIGN1YmVjYXJ0LiAgT25lIGRheSB0aGVpciBzZXJ2ZXIgd2VudCBkb3duIGFuZCBXRSBjb3VsZCBub3QgbG9naW4gdGhlIGFkbWluIG9mIE9VUiBzaXRlIGFzIGl0IGdldHMgYXBwcm92YWwgZmlyc3QgZnJvbSB0aGVpciBzZXJ2ZXIuICBEdW1iLi4uLmp1c3QgZHVtYi4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogTm92ZW1iZXIsIDIwMTEgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogMy4wPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEphc29uPGJyIC8+IldpdGhvdXQgZG91YnQgQ3ViZUNhcnQgaXMgdGhlIG1vc3QgdXNlcmZyaWVuZGx5IGNhcnQgaSd2ZSBldmVyIHVzZWQgYnV0IHRoYXRzIHdoZXJlIGl0IGVuZHMuDQoNClYzIGlzIHZlcnkgYmFzaWMgYnV0IGEgZ29vZCBzdGFydGluZyBwb2ludC4gVGhlIHByb2JsZW0gd2l0aCBWMyBpcyBpdCBpcyB0aGUgbW9zdCBiYXNpYyBjYXJ0IG9uIHRoZSBtYXJrZXQsIGV2ZW4gb3BlbmNhcnQgaGFzIG1vcmUgZmVhdHVyZXMhIFRoaXMgbGVhdmVzIHlvdSB3aXRoIG5vIGNob2ljZSBidXQgdG8gYnV5IG1vZHMgYnV0IG9uY2UgeW91dmUgbW9kZGVkIHRoZSBjb2RlIHN1cHBvcnQgaXMgcmVmdXNlZC4NCg0KVjQgaXMgZmFyIG1vcmUgZmVhdHVyZSByaWNoIGJ1dCBhcyBidWdneSBhcyBoZWxsISBJIHNlbGwgbXAzJ3MgYW5kIGkgY2hvc2UgY3ViZWNhcnQgYmVjYXVzZSBpdCBkb3dubG9hZGFibGUgcHJvZHVjdHMgY2FwYWJpbGl0eSBidXQgd2hlbiBWNCB3YXMgcmVsZWFzZWQgaXQgd2FzIGFuZCBzdGlsbCBpcyBhZHZlcnRpc2VkIGFzIGhhdmluZyB0aGUgYWJpbGl0eSB0byBtYW51YWxseSBjcmVhdGUgb3JkZXJzLiBUaGlzIHdhcyByZWFsbHkgZXhjaXRpbmcgdG8gbWUgc28gaSBwYWlkIHRoZSAkMTMwIHRvIGdldCB0aGUgdXBncmFkZS4gU2FkbHkgdGhpcyBmZWF0dXJlIGRvZXNuJ3QgYWN0dWFsbHkgd29yayBmb3IgZGlnaXRhbCBkb3dubG9hZHMhIFRoZXJlIGhhdmUgYmVlbiBjb21wbGFpbnRzIG9uIHRoZSBmb3J1bSBhYm91dCB0aGlzIGFuZCBzb21lb25lIG9mZmljaWFsbHkgcmVwb3J0ZWQgaXQgYXMgYSBidWcgb24gdGhlaXIgYnVnIHNpdGUgYnV0IHRoZSBkZXZlbG9wZXJzIHJlZnVzZSB0byBhY2NlcHQgaXRzIGEgYnVnIGFuZCBzYXkgaXRzIGEgZmVhdHVyZSByZXF1ZXN0ISBIb3cgY2FuIHlvdSBhZHZlcnRpc2UgYSBmZWF0dXJlIHdoaWNoIGlzIGFuIGV4Y2VsbGVudCBzZWxsaW5nIHBvaW50IGJ1dCBub3QgYWN0dWFsbHkgbWFrZSBpdCB3b3JrPyBUaGUgcHJvYmxlbSBpcyB3aGlsZSB5b3UgY2FuIG1hbnVhbGx5IGNyZWF0ZSBhbiBvcmRlciwgYSBkb3dubG9hZCBsaW5rIGlzbid0IGNyZWF0ZWQgc28gdGhlcmVzIG5vIHdheSBmb3IgeW91ciBjdXN0b21lciB0byBkb3dubG9hZCB0aGVpciBwdXJjaGFzZSENClRoZW4gdGhlcmUncyB0aGUgY2FydCBlbXB0eWluZyBpc3N1ZSB3aGVyZSBhIGxvdCBvZiBwZW9wbGUsIGluY2x1ZGluZyBteXNlbGYgYXJlIGZpbmRpbmcgdGhhdCBjdXN0b21lcnMgYXJlIHJlcG9ydGluZyBsb3NpbmcgdGhlaXIgY2FydCBjb250ZW50cyBhbmQgaGF2aW5nIHRvIHN0YXJ0IGFnYWluIGJ1dCBvYnZpb3VzbHkgbm8gb25lIGlzIGdvaW5nIHRvIHN0YXJ0IGFnYWluIGFuZCB3aG8gYmxhbWVzIHRoZW0hIElmIGl0cyBub3QgdGhlIGNhcnQgZW1wdHlpbmcgdGhlbiBpdHMgcGVvcGxlIHdobyBsb2dpbiB0byB0aGVpciBhY2NvdW50LCBjbGljayBvbiB0aGUgYWNjb3VudCBsaW5rIGFuZCBnZXQgbG9nZ2VkIG91dC4gQWdhaW4gYWxsIHRoaXMgaXMgcmVwb3J0ZWQgYnV0IG5vdGhpbmcgaXMgZG9uZSBhYm91dCBpdC4gVGhleSBhcmUgbm93IHdvcmtpbmcgb24gVmVyc2lvbiA1LiBIb3cgY2FuIHRoZXkgc3RhcnQgd29ya2luZyBvbiBhIG5ldyB2ZXJzaW9uIGJlZm9yZSBmaXhpbmcgdGhlIGN1cnJlbnQgb25lPw0KDQpJIHdhcyB1c2luZyBhIGN1c3RvbWlzZWQgdmVyc2lvbiBvZiB0aGVpciBDbGFzc2ljIHNraW4gd2hpY2ggd2FzIGN1c3RvbWlzZWQgc28gbXVjaCB0aGF0IHlvdSB3b3VsZG4ndCBrbm93IGl0IHdhcyBDdWJlQ2FydC4gSSB0aGVuIGFzayBmb3Igc3VwcG9ydCBhYm91dCB0aGUgcHJvYmxlbXMgYW5kIHN1cHBvcnQgaXMgaW5zdGFudGx5IHJlZnVzZWQgYmVjYXVzZSBpbSB1c2luZyBhIGN1c3RvbSBza2luIHNvIGkgZ2V0IHRvbGQgdG8gY29udGFjdCB0aGUgc2tpbiBkZXNpZ25lciBidXQgaSBkaWQgaXQuIEltIG5vdyBnb2luIHRvIG1hZ2VudG8hDQoNCkRvbnQgd2FzdGUgeW91ciBtIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKdW5lLCAyMDA5PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IFZjYW5maWVsZDxiciAvPiJJIHdhcyBpbXByZXNzZWQgd2l0aCB0aGlzIGNhcnQgdW50aWwgSSBmb3VuZCBvdXQgSSBjb3VsZCBub3QgYWN0dWFsbHkgYWRkIGl0IHRvIG15IHNpdGUgdW5sZXNzIEkga25ldyBzb21lIGNvZGluZy4gIFRoaXMgaXMgbm90IGZvciB0aGUgYmVnaW5uZXIgdW5sZXNzIHlvdSBhcmUgd2lsbGluZyB0byBsZXQgdGhlIGNhcnQgYWN0IGFzIHlvdXIgd2Vic2l0ZS4gIEkgY291bGQgYmUgd3Jvbmcgb24gdGhpcywgYnV0IGN1c3RvbWl6aW5nIGl0IHRha2VzIG1vcmUga25vd2xlZGdlIHRoZW4gdGhlIGF2ZXJhZ2UgSm9lIGtub3dzLiAgSSB3b3VsZCBoYXZlIGdpdmVuIGl0IGEgZm91ciBpZiBJIGNvdWxkIGN1c3RvbWl6ZSBpdCB3aXRob3V0IGV4dGVuc2l2ZSBodG1sIGtub3dsZWRnZS4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKYW51YXJ5LCAyMDA4PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IENhcnRidWlsZGVyMjU8YnIgLz4iSSB1c2VkIHRoaXMgY2FydCBmb3IgYWJvdXQgYSB5ZWFyIGFuZCBJIGhhZCBteSBmYWlyIHNoYXJlIG9mIHByb2JsZW1zIHdpdGggaXQuIEl0J3MgYnVnZ3kgYW5kIHlvdSBuZWVkIGEgbG90IG9mIGV4dHJhIHdvcmsgdG8gY3VzdG9taXplIHRoZSBsb29rIGFuZCBmdW5jdGlvbmFsaXR5LiBUaGUgZmVhdHVyZXMgb2ZmZXJlZCBhcmUgdmVyeSBiYXNpYyBhbmQgeW91IG5lZWQgdG8gYWRkIGEgbG90IG9mIDNyZCBwYXJ0eSBtb2RzKHdoaWNoIGFyZSBub3QgZnJlZSkgaWYgeW91IHdhbnQgbW9yZSB0aGFuIHRoZSBiYXNpYyBzdHVmZi4gDQpJIHdvdWxkIG5vdCByZWNvbW1lbmQgdGhpcyBjYXJ0LCBjdXJyZW50bHkgSSdtIGxvb2tpbmcgZm9yIGEgcmVwbGFjZW1lbnQuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBPY3RvYmVyLCAyMDA3PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEtsYXVzPGJyIC8+IldhcyBzZWFyY2hpbmcgZmFyIGFuZCB3aWRlIGZvciBhIHNob3BwaW5nIGNhcnQsIGFuZCB3ZSBsdWNraWx5IHN0dW1ibGVkIHVwb24gY3ViZWNhcnQsIEkgYWdyZWUgd2l0aCB2ZXJzaW9uIDMgYWxvdCBvZiBmZWF0dXJlcyB5b3Ugd291bGQgbGlrZSBhcmUgbm90IG1pc3NpbmcgYW5kIG5lZWQgdG8gYnV5IGFkZG9ucywgYnV0IHZlcnNpb24gNCBzZWVtcyB0byBoYXZlIGZpeGVkIGFsb3Qgb2YgdGhpcywgYW5kIGl0cyBzbyBlYXN5IHRvIHVwZGF0ZSBhbmQgY2hhbmdlLCBmb3IgdGhlIHByaWNlLCB5b3UgY2FudCByZWFsbHkgYXNrIGZvciBtb3JlISI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogU2VwdGVtYmVyLCAyMDA3PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEsuTC4gUGhhaXI8YnIgLz4iSSBzYXcgYSBsb3Qgb2YgY29tcGxhaW50cyBoZXJlIGFib3R1IEN1YmVDYXJ0LCBidXQgYWxzbyBnb29kIHJldmlld3MuIEN1YmVDYXJ0IGlzIGV4Y2VsbGVudCBpZiB5b3Uga25vdyBob3cgdG8gcHJvZ3JhbSBpdC4gVGhhdHMgdGhlIGtleSwga25pb3dpbmcgaG93IHRvIHByb2dyYW0gaXQuIFllcyB0aGUgTW9kcyBhbmQgQWRkIG9ucyBjb3N0IG1vbmV5LCBidXQgd2hhdCBkb2VzbnQ/IEJ5IGZhciBDYXViZUNhcnQgb2ZmZXJzIGEgdmVyeSBwb3dlcmZ1bCBzb2x1dGlvbiB3aXRob3V0IGJlaW5nIGNvbXBsZXguIEV2ZW4gaWYgeW91IGFyZSBub3QgYSBwcm9ncmFtbWVyLCBDYXViZUNhcnQgY25hIHN0aWxsIHdvcmsgZm9yIHlvdSwgYmVjYXVzZSB0aGUgYWRkIG9ucyBjYW4gYmUgaW5zdGFsbGVkIGZvciB5b3UgZm9yIGEgZmVlIHRoYXQgaXMgbGlzdGVkIGJ5IHRoZSBzZWxsZXIuIEN1YmVDYXJ0IGJ5IGZhciBpcyB0aGUgbW9zdCBjdXNvbWl6ZWFibGUgd2l0aCBzb21lIGdyZWF0IGZlYXR1cmVzIGFuZCBpcyBhIGdyZWF0IGJ1eSBmb3IgdGhlIG1vbmV5LiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogTWFyY2gsIDIwMDc8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogSmltPGJyIC8+IkkgaGFkIG5vdGhpbmcgYnV0IHByb2JsZW1zIHdpdGggdGhpcyBjYXJ0LiBJdCB3YXMgb25lIHRoaW5nIGFmdGVyIGFub3RoZXIuIFRoZSBzdXBwb3J0IHdhcyBnb29kLCBidXQgeW91IHNob3VsZG4ndCBuZWVkIHN1cHBvcnQgdGhhdCBvZnRlbi4uIEkgcHVyY2hhc2VkIENTLUNhcnQgYW5kIGhhdmUgaGFkIHZlcnkgbGl0dGxlIHByb2JsZW1zIGFuZCBhIHRvbiBtb3JlIGZlYXR1cmVzLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBGZWJydWFyeSwgMjAwNzwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBTb3VsbWFuPGJyIC8+IlVnbHkuIE1hbiwgZ29pbmcgdGhyb3VnaCB0aGUgd2Vic2l0ZXMgdXNpbmcgdGhpcyBzaG9wcGluZyBjYXJ0IGlzIGxpa2UgdHJhdmVsaW5nIHRoZSBiaXphcnJvIHdvcmxkLiBPbmUgdWdseSBzaXRlIGFmdGVyIGFub3RoZXIuIFBlb3BsZSBwbGVhc2UhISEiPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogT2N0b2JlciwgMjAwNjwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBBbmRpPGJyIC8+IkkgbW92ZWQgdG8gQ3ViZUNhcnQgbmVhcmx5IGEgeWVhciBhZ28gZnJvbSBvU2NvbW1lcmNlIGFuZCBjb3VsZG50IGJlIGhhcHBpZXIuICBBcyBwcmV2aW91c2x5IG1lbnRpb25lZCBpdCBkb2VzIGN1cnJlbnRseSBtaXNzIHNvbWUgZmVhdHVyZXMgbGlrZSBkaXNjb3VudCBjb3Vwb25zIGJ1dCB0aGUgdGhpcmQgcGFydHkgbW9kcyBhcmUgdmVyeSBjaGVhcCBhbmQgdmVyeSBzaW1wbGUgdG8gaW5zdGFsbC4gIFRoZSB0ZW1wbGF0ZSBzeXN0ZW0gaXMgaXRzIGJlc3QgZmVhdHVyZSwgdXNpbmcgSFRNTCBhbmQgLkNTUyB3aGljaCBtYWtlcyBmb3IgZWFzeSBjdXN0b21pc2F0aW9uLg0KDQpUaGVyZSBoYXZlIGJlZW4gc29tZSBzZWN1cml0eSBpc3N1ZXMgYnV0IHRoZXkgYXJlIGFkZHJlc3NlZCBpbW1lZGlhdGVseSB3aXRoIGEgcGF0Y2ggcmVsZWFzZWQgd2l0aGluIGhvdXJzLiAgVGhlIG5leHQgdmVyc2lvbiAoMy4xLjApIHdpbGwgYmUgZmVhdHVyZSByaWNoIGFjY29yZGluZyB0byB0aGVpciBibG9nIGFuZCB0aGUgc3VwcG9ydCBoYXMgYmVlbiBleGNlbGxlbnQuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBTZXB0ZW1iZXIsIDIwMDY8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogSGVydWxlczxiciAvPiJGb3IgaW5zdGFsbGF0aW9uIG9uIFdpbmRvd3MgdXNpbmcgTXlTUUwgNSwgc29tZSB0eXBlIGVycm9ycyBoYXBwZW5lZC4gQWNjb3JkaW5nIHRvIHRoZWlyIHN0YWZmLCBpdCB3b3JrcyBvbiBMaW51eCBzeXN0ZW0uIERvIHRoZXkgb25seSBzZXJ2ZSBMaW51eCB1c2Vycz8gSXQncyBhIHByb2JsZW0uIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBBdWd1c3QsIDIwMDY8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogTWFyaWU8YnIgLz4iSXQncyBhbiBvayBiYXNpYyBjYXJ0LCBidXQgYSBiaXQgYnVnZ3kuIFRoZSBmZWF0dXJlcyBvdXQgb2YgdGhlIGJveCBhcmUgdmVyeSBzaW1wbGUsIGl0J3MgbWlzc2luZyB3aGF0IEkgd291bGQgY29uc2lkZXIgYmFzaWMgZmVhdHVyZXMgKHN1Y2ggYXMgZGlzY291bnQgY291cG9ucykuIFRoZXJlIGFyZSBhIGxvdCBvZiAibW9kcyIgYXZhaWxhYmxlIHRvIGFkZCBleHRyYSBmdW5jdGlvbnMsIGJ1dCBhICJtb2QiIG1lYW5zIG1vZGlmeWluZyB0aGUgc291cmNlIGNvZGUsIHdoaWNoIGlzbid0IGZvciB0aGUgYmVnaW5uZXIgYW5kIGNyZWF0ZXMgcHJvYmxlbXMgd2hlbiB5b3Ugd2FudCB0byB1cGdyYWRlIHRvIGEgbmV3ZXIgdmVyc2lvbiBvZiBjdWJlY2FydC4NCg0KSWYgeW91IHdhbnQgc29tZXRoaW5nIHN1cGVyIGJhc2ljIGFuZCBoYXZlIGdvdCBzb21lIGJhc2ljIHRlY2huaWNhbCBza2lsbHMsIGl0J3MgYSBnb29kIGNob2ljZSwgYnV0IGZvciBhbnlvbmUgb3RoZXIgdGhhbiB0aGF0LCBrZWVwIGxvb2tpbmcuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKYW51YXJ5LCAyMDA2PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IERlZ3NleTxiciAvPiJUaGlzIHNob3BwaW5nIGNhcnQgaXMgb25lIG9mIHRoZSBtb3N0IHVzZXIgZnJpZW5kbHkgaWYgeW91IHdhbnQgdG8gbW9kIHlvdXIgc3RvcmUgeW91ciBzZWxmLiBVbmxpa2Ugb3Njb21tZXJjZSB5b3UgY2FuIGdldCBuZXcgc2tpbnMgYXQgYSByZWFzb25hYmxlIHByaWNlIGFuZCB0aGUgZm9ydW1zIGFyZSBpbmZvcm1hdGl2ZSBhbmQgZnJpZW5kbHkuIFRoZSBhZG1pbiBhcmVhIGlzIGVhc3kgdG8gdXNlIGFuZCB0aGVyZSBhcmUgbm8gY29tcGxpY2F0aW9ucywgYSB0ZXh0IGVkaXRvciBpcyBpbmNsdWRlZC4NClRoZSBsaWNlbnNlIGZlZSBvZiAkNjkgaXMgYSBzdGVhbCBidXQgeW91IGRvIG5vdCBoYXZlIHRvIHBheSBmb3IgaXQgdG8gZ2V0IGEgZnVsbHkgZnVuY3Rpb25hbCBzaG9wcGluZyBjYXJ0LiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogTm92ZW1iZXIsIDIwMDU8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogQWRhbTxiciAvPiJJIGhhZCBxdWl0ZSBhIGxvb2sgYXQgcXVpdGUgYSBmZXcgY2FydHMgYmVmb3JlIHNldHRsaW5nIG9uIGN1YmUgY2FydC4gSXQncyBub3QgdGhlIG1vc3QgZmVhdHVyZSByaWNoIG9yIG1vc3QgcG93ZXJmdWwsIGluIGZhY3Qgb3V0IG9mIHRoZSBib3ggaXQncyBmYWlybHkgYmFzaWMuIFdoYXQgaXQgZG9lcyBoYXZlICBnb2luZyBmb3IgaXQgaXMgYSBsb3ZlbHkgc2ltcGxpY2l0eSB0aGF0J3MgZWFzeSB0byB1c2UsIHNraW5uaW5nIHRoYXQgcHV0cyB0aGUgcmVzdCBvZiB0aGUgaW5kdXN0cnkgIHRvIHNoYW1lLCBhbiBleHRlbnNpdmUgcmFuZ2Ugb2YgM3JkIHBhcnR5IGFkZCBvbnMgdGhhdCBhZGQgdGhlIGZ1bmN0aW9uYWxpdHkgdGhlIGNvcmUgc29mdHdhcmUgZG9lc24ndCBoYXZlLCBhbmQgYSB2ZXJ5IGJ1c3ksIGZyaWVuZGx5IHVzZXIgZm9ydW0uIFRob3NlIHRoaW5ncyBtb3JlIHRoYW4gbWFrZSB1cCBmb3IgdGhlIHdlYWtuZXNzZXMuDQoNClVubGVzcyB5b3VyIG5lZWRzIGFyZSB2ZXJ5IGJhc2ljLCB5b3Ugc2hvdWxkIGJ1ZGdldCB0byBzcGVuZCBhIGJpdCBtb3JlIG1vbmV5IG9uIDNyZCBwYXJ0eSBhZGQgb25zIGFzIHdlbGwgKHR5cGljYWxseSAkMjAgLSAkMzAgZWFjaCksIGJ1dCBpdCdzIHN0aWxsIGNoZWFwIGluY2x1ZGluZyB0aGVtLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBOb3ZlbWJlciwgMjAwNTwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBQZXRlPGJyIC8+IkN1YmVDYXJ0MyBnb2VzIGJleW9uZCB0aGUgc3RhbmRhcmRzIG9mIEVjb21tZXJjZSBzb2x1dGlvbnMsIGJ5IGFsbG93aW5nIFhIVE1ML0NTUzIgbGF5b3V0cywgZnVsbCBwYXltZW50IGdhdGV3YXkgb3B0aW9ucyhpbmNsdWRpbmcgb3JkZXJmb3JtIG9wdGlvbiksYW5kIG1vcmUuIEZlYXR1cmUgcGFja2VkLCBlYXN5IHRvIGluc3RhbGwgYW5kIHNldHVwLCBDdWJlQ2FydCBpcyB3aXRob3V0IGEgZG91YnQgYSBTeXN0ZW0gaW4gYSBsZWFndWUgb2YgaXRzIG93bi4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bmUsIDIwMDU8L2Rpdj48YnIgLz48YSBocmVmPSIvcmV2aWV3LmFzcHg/Y2FydD1DdWJlY2FydCIgcmVsPSJub2ZvbGxvdyIgc3R5bGU9ImZvbnQtc2l6ZToxLjJlbTtmb250LXdlaWdodDpib2xkOyI+QWRkIFlvdXIgT3duIFJldmlldzwvYT5kZAILDw8WAh8ABZ8CT3V0IG9mIHRoZSBib3ggdGhlIGZlYXR1cmVzIGFyZSBiYXNpYywgYnV0IGl0J3MgdmVyeSBleHRlbnNpYmxlLCBhbHRob3VnaCB0aGF0IHdpbGwgcmVxdWlyZSBzb21lIHRlY2huaWNhbCBza2lsbHMuIE9uZSBncmVhdCBmZWF0dXJlIGlzIHRoYXQgaXQncyBmdWxseSBYSFRNTC9DU1MgYW5kIHVzZXMgYSBwb3dlcmZ1bCB0ZW1wbGF0aW5nIHN5c3RlbS4gVGhhdCBzaG91bGQgbWFrZSB0ZW1wbGF0aW5nIGEgYnJlZXplLiBXaHkgbW9yZSBjYXJ0cyBkb24ndCB3b3JrIHRoaXMgd2F5IGlzIGJleW9uZCBtZSFkZAINDw8WAh8ABeUCPCEtLSBjYS1wdWItMDAxODQxNzM0NzUwMzEwNy9Eb3dubG9hZFBIUENhcnRzXzcyOHg5MF90b3AgLS0+PHNjcmlwdCBhc3luYyBzcmM9Ii8vcGFnZWFkMi5nb29nbGVzeW5kaWNhdGlvbi5jb20vcGFnZWFkL2pzL2Fkc2J5Z29vZ2xlLmpzIj48L3NjcmlwdD48aW5zIGNsYXNzPSJhZHNieWdvb2dsZSJzdHlsZT0iZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6NzI4cHg7aGVpZ2h0OjkwcHgiZGF0YS1hZC1jbGllbnQ9ImNhLXB1Yi0xNzIyMDUxODI4NzI0MzM3ImRhdGEtYWQtc2xvdD0iMzI4MDIwNzczOSI+PC9pbnM+PHNjcmlwdD4oYWRzYnlnb29nbGU9d2luZG93LmFkc2J5Z29vZ2xlfHxbXSkucHVzaCh7fSk7PC9zY3JpcHQ+ZGQCDg8PFgIfAAUUV2luZG93cywgTGludXgsIFVuaXhkZAIPDw8WAh8ABQNQSFBkZAIQDw8WAh8ABQVNeVNRTGRkAhEPDxYCHwAFA1llc2RkAhIPDxYCHwAFAk5vZGQCEw8PFgIfAAUCTm9kZAIUDw8WAh8ABQJOb2RkAhUPDxYCHwAFA1llc2RkAhYPDxYCHwAFAk5vZGQCFw8PFgIfAAUDWWVzZGQCGA8PFgIfAAUCTm9kZAIZDw8WAh8ABQNZZXNkZAIaDw8WAh8ABQNZZXNkZAIbDw8WAh8ABQJOb2RkAhwPDxYCHwAFAk5vZGQCHQ8PFgIfAAUDWWVzZGQCHg8PFgIfAAUJM3JkIHBhcnR5ZGQCHw8PFgIfAAUDWWVzZGQCIA8PFgIfAAUCTm9kZAIiDw8WAh8ABegCPCEtLSBjYS1wdWItMDAxODQxNzM0NzUwMzEwNy9Eb3dubG9hZFBIUENhcnRzXzcyOHg5MF9taWRkbGUgLS0+PHNjcmlwdCBhc3luYyBzcmM9Ii8vcGFnZWFkMi5nb29nbGVzeW5kaWNhdGlvbi5jb20vcGFnZWFkL2pzL2Fkc2J5Z29vZ2xlLmpzIj48L3NjcmlwdD48aW5zIGNsYXNzPSJhZHNieWdvb2dsZSJzdHlsZT0iZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6NzI4cHg7aGVpZ2h0OjkwcHgiZGF0YS1hZC1jbGllbnQ9ImNhLXB1Yi0xNzIyMDUxODI4NzI0MzM3ImRhdGEtYWQtc2xvdD0iMzI4MDIwNzczOSI+PC9pbnM+PHNjcmlwdD4oYWRzYnlnb29nbGU9d2luZG93LmFkc2J5Z29vZ2xlfHxbXSkucHVzaCh7fSk7PC9zY3JpcHQ+ZGQCIw8PFgIfAAUDWWVzZGQCJA8PFgIfAAUDWWVzZGQCJQ8PFgIfAAUDWWVzZGQCJg8PFgIfAAUDWWVzZGQCJw8PFgIfAAUCTm9kZAIoDw8WAh8ABQJOb2RkAikPDxYCHwAFAk5vZGQCKg8PFgIfAAUCTm9kZAIrDw8WAh8ABQNZZXNkZAIsDw8WAh8ABQNZZXNkZAItDw8WAh8ABQJOb2RkAi4PDxYCHwAFA1llc2RkAi8PDxYCHwAFAk5vZGQCMA8PFgIfAAUDWWVzZGQCMQ8PFgIfAAUCTm9kZAIyDw8WAh8ABQNZZXNkZAIzDw8WAh8ABQNZZXNkZAI0Dw8WAh8ABQJOb2RkAjUPDxYCHwAFA1llc2RkAjYPDxYCHwAFA1llc2RkAjcPDxYCHwAFAk5vZGQCOA8PFgIfAAUDWWVzZGQCOg8PFgIfAAXoAjwhLS0gY2EtcHViLTAwMTg0MTczNDc1MDMxMDcvRG93bmxvYWRQSFBDYXJ0c183Mjh4OTBfYm90dG9tIC0tPjxzY3JpcHQgYXN5bmMgc3JjPSIvL3BhZ2VhZDIuZ29vZ2xlc3luZGljYXRpb24uY29tL3BhZ2VhZC9qcy9hZHNieWdvb2dsZS5qcyI+PC9zY3JpcHQ+PGlucyBjbGFzcz0iYWRzYnlnb29nbGUic3R5bGU9ImRpc3BsYXk6aW5saW5lLWJsb2NrO3dpZHRoOjcyOHB4O2hlaWdodDo5MHB4ImRhdGEtYWQtY2xpZW50PSJjYS1wdWItMTcyMjA1MTgyODcyNDMzNyJkYXRhLWFkLXNsb3Q9IjMyODAyMDc3MzkiPjwvaW5zPjxzY3JpcHQ+KGFkc2J5Z29vZ2xlPXdpbmRvdy5hZHNieWdvb2dsZXx8W10pLnB1c2goe30pOzwvc2NyaXB0PmRkAjsPDxYCHwAFdTxhIHJlbD0ibm9mb2xsb3ciIGhyZWY9Ii9yZXBvcnQuYXNweD9uYW1lPUN1YmVjYXJ0JnR5cGU9Q2FydCI+SXMgdGhlcmUgYW4gZXJyb3Igb24gdGhpcyBwYWdlIG9yIGFuIHVwZGF0ZSBuZWVkZWQ/PC9hPmRkAjwPDxYCHwAFCzEzIEZlYiAyMDEzZGQCAQ8PFgIfAAWABDx1bCBjbGFzcz0ibGF0ZXN0Ij48bGk+PGEgaHJlZj0iL2NhcnRzL0FkdmFuY2VkLUNhcnQuYXNweCI+QWR2YW5jZWQgQ2FydCBSZXZpZXcgICZyYXF1bzs8L2E+PC9saT48bGk+PGEgaHJlZj0iL2NhcnRzL0NsZWFyQ2FydC5hc3B4Ij5DbGVhckNhcnQgUmV2aWV3ICAmcmFxdW87PC9hPjwvbGk+PGxpPjxhIGhyZWY9Ii9jYXJ0cy9TcXVpcnJlbC1DYXJ0LmFzcHgiPlNxdWlycmVsY2FydCBSZXZpZXcgICZyYXF1bzs8L2E+PC9saT48bGk+PGEgaHJlZj0iL2NhcnRzL1NlYXJjaEZpdC5hc3B4Ij5TZWFyY2hGaXQgUmV2aWV3ICAmcmFxdW87PC9hPjwvbGk+PGxpPjxhIGhyZWY9Ii9jYXJ0cy9TaG9wLWEtbGEtQ2FydC5hc3B4Ij5TaG9wIGEgbGEgQ2FydCBSZXZpZXcgICZyYXF1bzs8L2E+PC9saT48bGkgc3R5bGU9J21hcmdpbi10b3A6IDhweDsnPjxzdHJvbmc+PGEgaHJlZj0nL2FsbC1zaG9wcGluZy1jYXJ0cy5hc3B4Jz5BbGwgMjAwKyBzaG9wcGluZyBjYXJ0czwvYT48L3N0cm9uZz48L2xpPjwvdWw+ZGRkQWPYa9uZhlJThas+UgC1twc7ZdU3S1PF3dswKTAb4Bo=" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="0C1F84DE" />
        <div align="center">
            
    <div id="ads1" align="center">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Top -->
                <ins class="adsbygoogle"
                    style="display: block"
                    data-ad-client="ca-pub-1388311751127083"
                    data-ad-slot="8765540533"
                    data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>

        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
Shopping Cart Details

                    </h2>
                </div>
                <div class="inpage">
                    
   
<script type="text/javascript">
    
function pop(anchor){

window.open('/glossarypop.aspx#' + anchor,'mywindow','width=400,height=200');
}
</script>

   <script type="text/javascript">
       var CurrentCartName = "Cubecart";
       var CurrentCartImage = "/img/cartlogo/cubecart.png";
     </script>

<div id="_ctl0_contentBody_hreviewmaster" class="hreview-aggregate">	
<!-- body master table -->
<table width="737" border="0" cellspacing="0" cellpadding="0" class="masterTable">
<tr>
	<td id="tBody">
   

    <span id="_ctl0_contentBody_lblHeading"><h1>CubeCart Review</h1></span>
    	<span id="_ctl0_contentBody_lblReview"><a href="/review.aspx?cart=Cubecart" rel="nofollow">Review this cart!</a></span>
    <br />
	<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Basic Information</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230" style="font-size: 120%"><strong>Company name</strong><div class="compQ"><a href="javascript:pop('companyname')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst" style="font-size: 120%">
				<strong><span id="_ctl0_contentBody_lblCompanyName"><a target="_blank" href="http://www.cubecart.com/" onClick="_gaq.push(['_trackEvent','OutboundStores', 'Click', 'CubeCart']);">Devellion Limited</a></span></strong></td>
		</tr>
		<tr>
			<td class="compCol" style="font-size: 120%">Product name<div class="compQ"><a href="javascript:pop('productname')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst" style="font-size: 120%">
				<strong><span id="_ctl0_contentBody_lblProductName"><div class="item"><span class="fn">CubeCart</span></div></span></strong></td>
		</tr>
		<tr>
			<td class="compCol">Version<div class="compQ"><a href="javascript:pop('version')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblVersion">3.0</span></td>
		</tr>
		<tr>
			<td class="compCol">Sample customer sites<div class="compQ"><a href="javascript:pop('sample1')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSample1"><a rel="nofollow" target="_blank" href="http://www.smartpoppy.com.au/">http://www.smartpoppy.com.au/</a></span><br />
				<span id="_ctl0_contentBody_lblSample2"><a rel="nofollow" target="_blank" href="http://www.ezimp3.com/">http://www.ezimp3.com/</a></span><br />
				<span id="_ctl0_contentBody_lblSample3"></span>
				</td>
		</tr>
		<tr>
			<td class="compCol">Price<div class="compQ"><a href="javascript:pop('price')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPrice">$US69</span></td>
		</tr>
		<tr>
			<td class="compCol">Average review score<div class="compQ"><a href="javascript:pop('reviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReviewScore"><div class="rating"><span class="average"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" title="2.5 star rating" alt="2.5 star rating"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif"><img src="http://cdn.ecommercespot.com/images/cart1Half.gif"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif">Average: 2.5</span></div>(<span class="count">18</span>)</span></td>
		</tr>
		<tr>
			<td class="compCol" valign=top>User reviews<div class="compQ"><a href="javascript:pop('reviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReviews">Reviewed by: Chris<br />"Moving to cubecart was the worst decision I have ever made for my online shop, I have lost tens of thousands of pounds in orders.

On the face of it, it looks ok, easy enough to use, but the back end is terrible.

The supposedly search engine URLS it generates causes google to think it has 2 URLS, so we lost our place on google within weeks of switching to cube. Also there is a bug in it where people keep on trying to log in and it logs them out again; the only way round this is to delete your cookies, but I dread to think how many of our customers gave up.

The language tool, which we have now disabled, also created even more duplicate pages for you to lose your place even further on google.

Do not touch Cube Cart with a barge poll, it is awful."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: October, 2015 &nbsp;&nbsp;Version reviewed: 3.0</div><br />Reviewed by: Niki Buskell<br />"Cube Cart is a very simple and effective online store at a great price. The Back end is very useful for retailers.

I found the support quick and effective and the forums equally helpful. The problems I incurred were resolved swiftly."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: January, 2013 &nbsp;&nbsp;Version reviewed: 3.0</div><br />Reviewed by: Lilian<br />"Steer clear from Cubecart. You never know for how long your store will be working properly. Every upgrade is full of bugs, so you have to test the entire store all over again to avoid problems, let alone you will need to customize side boxes and templates all over again. I lost customers, money and months of hard work uploading products and customizing. I'm closing the store and switching provider. "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: October, 2012 &nbsp;&nbsp;Version reviewed: 3.0</div><br />Reviewed by: David Anscomb<br />"Very frustrating experience, works on a very crude level if that's all you need, though no better than free carts, poor support, very buggy,the developers seem to be overwhelmed, and are therefore not very helpful. even the bug tracker didn't work last time i used it. So- an ok basic system, but no better than free carts out there. Read their support forums before committing."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: January, 2012 &nbsp;&nbsp;Version reviewed: 3.0</div><br />Reviewed by: Peter<br />"Terrible.  The upgrade broke our cart and we wrote them for a refund, denied.  No customer service at all.  A functioning busy cart down because of broken code.  Stay away from cubecart.  One day their server went down and WE could not login the admin of OUR site as it gets approval first from their server.  Dumb....just dumb."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: November, 2011 &nbsp;&nbsp;Version reviewed: 3.0</div><br />Reviewed by: Jason<br />"Without doubt CubeCart is the most userfriendly cart i've ever used but thats where it ends.

V3 is very basic but a good starting point. The problem with V3 is it is the most basic cart on the market, even opencart has more features! This leaves you with no choice but to buy mods but once youve modded the code support is refused.

V4 is far more feature rich but as buggy as hell! I sell mp3's and i chose cubecart because it downloadable products capability but when V4 was released it was and still is advertised as having the ability to manually create orders. This was really exciting to me so i paid the $130 to get the upgrade. Sadly this feature doesn't actually work for digital downloads! There have been complaints on the forum about this and someone officially reported it as a bug on their bug site but the developers refuse to accept its a bug and say its a feature request! How can you advertise a feature which is an excellent selling point but not actually make it work? The problem is while you can manually create an order, a download link isn't created so theres no way for your customer to download their purchase!
Then there's the cart emptying issue where a lot of people, including myself are finding that customers are reporting losing their cart contents and having to start again but obviously no one is going to start again and who blames them! If its not the cart emptying then its people who login to their account, click on the account link and get logged out. Again all this is reported but nothing is done about it. They are now working on Version 5. How can they start working on a new version before fixing the current one?

I was using a customised version of their Classic skin which was customised so much that you wouldn't know it was CubeCart. I then ask for support about the problems and support is instantly refused because im using a custom skin so i get told to contact the skin designer but i did it. Im now goin to magento!

Dont waste your m"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2009</div><br />Reviewed by: Vcanfield<br />"I was impressed with this cart until I found out I could not actually add it to my site unless I knew some coding.  This is not for the beginner unless you are willing to let the cart act as your website.  I could be wrong on this, but customizing it takes more knowledge then the average Joe knows.  I would have given it a four if I could customize it without extensive html knowledge."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: January, 2008</div><br />Reviewed by: Cartbuilder25<br />"I used this cart for about a year and I had my fair share of problems with it. It's buggy and you need a lot of extra work to customize the look and functionality. The features offered are very basic and you need to add a lot of 3rd party mods(which are not free) if you want more than the basic stuff. 
I would not recommend this cart, currently I'm looking for a replacement."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: October, 2007</div><br />Reviewed by: Klaus<br />"Was searching far and wide for a shopping cart, and we luckily stumbled upon cubecart, I agree with version 3 alot of features you would like are not missing and need to buy addons, but version 4 seems to have fixed alot of this, and its so easy to update and change, for the price, you cant really ask for more!"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2007</div><br />Reviewed by: K.L. Phair<br />"I saw a lot of complaints here abotu CubeCart, but also good reviews. CubeCart is excellent if you know how to program it. Thats the key, kniowing how to program it. Yes the Mods and Add ons cost money, but what doesnt? By far CaubeCart offers a very powerful solution without being complex. Even if you are not a programmer, CaubeCart cna still work for you, because the add ons can be installed for you for a fee that is listed by the seller. CubeCart by far is the most cusomizeable with some great features and is a great buy for the money."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: March, 2007</div><br />Reviewed by: Jim<br />"I had nothing but problems with this cart. It was one thing after another. The support was good, but you shouldn't need support that often.. I purchased CS-Cart and have had very little problems and a ton more features."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: February, 2007</div><br />Reviewed by: Soulman<br />"Ugly. Man, going through the websites using this shopping cart is like traveling the bizarro world. One ugly site after another. People please!!!"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: October, 2006</div><br />Reviewed by: Andi<br />"I moved to CubeCart nearly a year ago from oScommerce and couldnt be happier.  As previously mentioned it does currently miss some features like discount coupons but the third party mods are very cheap and very simple to install.  The template system is its best feature, using HTML and .CSS which makes for easy customisation.

There have been some security issues but they are addressed immediately with a patch released within hours.  The next version (3.1.0) will be feature rich according to their blog and the support has been excellent."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2006</div><br />Reviewed by: Herules<br />"For installation on Windows using MySQL 5, some type errors happened. According to their staff, it works on Linux system. Do they only serve Linux users? It's a problem."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: August, 2006</div><br />Reviewed by: Marie<br />"It's an ok basic cart, but a bit buggy. The features out of the box are very simple, it's missing what I would consider basic features (such as discount coupons). There are a lot of "mods" available to add extra functions, but a "mod" means modifying the source code, which isn't for the beginner and creates problems when you want to upgrade to a newer version of cubecart.

If you want something super basic and have got some basic technical skills, it's a good choice, but for anyone other than that, keep looking."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: January, 2006</div><br />Reviewed by: Degsey<br />"This shopping cart is one of the most user friendly if you want to mod your store your self. Unlike oscommerce you can get new skins at a reasonable price and the forums are informative and friendly. The admin area is easy to use and there are no complications, a text editor is included.
The license fee of $69 is a steal but you do not have to pay for it to get a fully functional shopping cart."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: November, 2005</div><br />Reviewed by: Adam<br />"I had quite a look at quite a few carts before settling on cube cart. It's not the most feature rich or most powerful, in fact out of the box it's fairly basic. What it does have  going for it is a lovely simplicity that's easy to use, skinning that puts the rest of the industry  to shame, an extensive range of 3rd party add ons that add the functionality the core software doesn't have, and a very busy, friendly user forum. Those things more than make up for the weaknesses.

Unless your needs are very basic, you should budget to spend a bit more money on 3rd party add ons as well (typically $20 - $30 each), but it's still cheap including them."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: November, 2005</div><br />Reviewed by: Pete<br />"CubeCart3 goes beyond the standards of Ecommerce solutions, by allowing XHTML/CSS2 layouts, full payment gateway options(including orderform option),and more. Feature packed, easy to install and setup, CubeCart is without a doubt a System in a league of its own."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2005</div><br /><a href="/review.aspx?cart=Cubecart" rel="nofollow" style="font-size:1.2em;font-weight:bold;">Add Your Own Review</a></span></td>
		</tr>
		
		
		<tr>
			<td class="compCol" valign=top>
				Ecommerce Spot Comments
			</td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblComments">Out of the box the features are basic, but it's very extensible, although that will require some technical skills. One great feature is that it's fully XHTML/CSS and uses a powerful templating system. That should make templating a breeze. Why more carts don't work this way is beyond me!</span>
			</td>
		</tr>
			
		
		
		
		</table>

<div style="margin: 5px 0 5px -20px;">

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=Cubecart" target="_blank" > <img src="/img/scebanners/set2/728x90.png" /> </a> 
</div>


    
</div>
		
		<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Technology</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Supported operating systems<div class="compQ"><a href="javascript:pop('os')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblOperatingSystem">Windows, Linux, Unix</span></td>
		</tr>
		<tr>
			<td class="compCol">Language<div class="compQ"><a href="javascript:pop('lang')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLanguage">PHP</span></td>
		</tr>
		<tr>
			<td class="compCol">Database<div class="compQ"><a href="javascript:pop('db')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblDatabase">MySQL</span></td>
		</tr>
		<tr>
			<td class="compCol">Source code<div class="compQ"><a href="javascript:pop('sourcecode')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSourceCode">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Reseller discounts<div class="compQ"><a href="javascript:pop('reseller')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReseller">No</span></td>
		</tr>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Features</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Product limit<div class="compQ"><a href="javascript:pop('productlimit')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblProductlimit">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Category limit<div class="compQ"><a href="javascript:pop('categorylimit')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCategoryLimit">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Multi-language<div class="compQ"><a href="javascript:pop('multilanguage')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblMultilanguage">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Gift certificates<div class="compQ"><a href="javascript:pop('giftcertificates')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblGiftcertificates">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Loyalty program<div class="compQ"><a href="javascript:pop('loyalty')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLoyalty">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Email merchant on order<div class="compQ"><a href="javascript:pop('emailorder')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblEmailOrder">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Affiliates program<div class="compQ"><a href="javascript:pop('affiliates')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblAffiliates">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Site search<div class="compQ"><a href="javascript:pop('sitesearch')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSiteSearch">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Search optimization tools<div class="compQ"><a href="javascript:pop('seotools')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSeotools">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Product reviews<div class="compQ"><a href="javascript:pop('productreviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblProductreviews">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Newsletters<div class="compQ"><a href="javascript:pop('newsletters')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblNewsletters">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Discount coupons<div class="compQ"><a href="javascript:pop('discountcoupons')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblDiscountcoupons">3rd party</span></td>
		</tr>
		<tr>
			<td class="compCol">Customer registrations<div class="compQ"><a href="javascript:pop('customerregistration')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCustomerregistration">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Wish list<div class="compQ"><a href="javascript:pop('wishlist')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWishlist">No</span></td>
		</tr>
		</table>
<div style="margin: 5px 0 5px -20px;">

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=Cubecart" target="_blank" > <img src="/img/scebanners/set2/728x90.png" /> </a> 
</div>


    
</div>
		<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>	
		
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Shipping</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Shipping price range<div class="compQ"><a href="javascript:pop('pricerangeshipping')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblpricerangeshipping">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Shipping weight range<div class="compQ"><a href="javascript:pop('weightrangeshipping')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWeightrangeshipping">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">UPS lookup<div class="compQ"><a href="javascript:pop('upslookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblUpslookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">USPS lookup<div class="compQ"><a href="javascript:pop('uspslookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblUspslookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Fedex lookup<div class="compQ"><a href="javascript:pop('fedexlookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblFedexlookup">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Canada Post lookup<div class="compQ"><a href="javascript:pop('canadapostlookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCanadapostlookup">No</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Tax &amp; Payment</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Tax by state<div class="compQ"><a href="javascript:pop('taxbystate')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblTaxbystate">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Tax by country<div class="compQ"><a href="javascript:pop('taxbycountry')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblTaxbycountry">No</span></td>
		</tr>
		<tr>
			<td class="compCol">PayPal<div class="compQ"><a href="javascript:pop('paypal')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPaypal">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Authorize.Net<div class="compQ"><a href="javascript:pop('authorizenet')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblAuthorizenet">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Verisign<div class="compQ"><a href="javascript:pop('verisign')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblVerisign">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Worldpay<div class="compQ"><a href="javascript:pop('worldpay')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWorldpay">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Secure Trading<div class="compQ"><a href="javascript:pop('securetrading')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSecuretrading">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Others<div class="compQ"><a href="javascript:pop('others')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblOthers">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Non credit card options<div class="compQ"><a href="javascript:pop('nonccoptions')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblNonccoptions">No</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Support</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Customer forums<div class="compQ"><a href="javascript:pop('customerforums')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCustomerforum">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Free support<div class="compQ"><a href="javascript:pop('freesupport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblFreeSupport">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Paid support<div class="compQ"><a href="javascript:pop('paidsupport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPaidsupport">No</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Reports</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Sales reports<div class="compQ"><a href="javascript:pop('salesreport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSalesreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Search reports<div class="compQ"><a href="javascript:pop('searchreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_Lblsearchreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Low stock reports<div class="compQ"><a href="javascript:pop('lowstockreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLowstockreports">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Inventory reports<div class="compQ"><a href="javascript:pop('inventoryreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblInventoryreports">Yes</span></td>
		</tr>
	</table>
	<p>&nbsp;</p>
<div style="margin: 5px 0 5px -20px;">	

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=Cubecart" target="_blank" > <img src="/img/scebanners/set2/728x90.png" /> </a> 
</div>


    
</div>
		<span id="_ctl0_contentBody_lblReport"><a rel="nofollow" href="/report.aspx?name=Cubecart&type=Cart">Is there an error on this page or an update needed?</a></span><br /><br />
	<span style="color: #ddd; font-size: 80%;"><p>Last updated:
		<span id="_ctl0_contentBody_lblReviewedDate">13 Feb 2013</span><br /><br /></p></span>


		

</td>
<td align=left width=1 id="cart_gads">



	</td>
</tr>
</table>
</div>


<div id="upNext" style ="display:none;">
<div style="width:310px;"><h6>More Reviews</h6>
<span id="_ctl0_contentBody_lblCrossLinks"><ul class="latest"><li><a href="/carts/Advanced-Cart.aspx">Advanced Cart Review  &raquo;</a></li><li><a href="/carts/ClearCart.aspx">ClearCart Review  &raquo;</a></li><li><a href="/carts/Squirrel-Cart.aspx">Squirrelcart Review  &raquo;</a></li><li><a href="/carts/SearchFit.aspx">SearchFit Review  &raquo;</a></li><li><a href="/carts/Shop-a-la-Cart.aspx">Shop a la Cart Review  &raquo;</a></li><li style='margin-top: 8px;'><strong><a href='/all-shopping-carts.aspx'>All 200+ shopping carts</a></strong></li></ul></span>
</div></div>


                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
