

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	Review of Mal's e-commerce Shopping Cart - Read User Reviews &amp; Feature Listings for Mal's e-commerce Shopping Cart Shopping Cart
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<link href="../App_Themes/Cart/StyleSheet.css" type="text/css" rel="stylesheet" /><meta name="Description" content="Recent User Review: Here is my experience w/Mal&#39;s support:

I wrote:
We just printed out 7 online orders, and clicked to pick up payments.  We hit the back button to go back and see how many orders there were, since we couldn&#39;t remember, and when we went back, all of the orders had disappeared.  So, we are unable to retrieve the payment info for them now.  Is there any way to retrieve this info?  We don&#39;t know what happened.  We didn&#39;t delete them.  They just disappeared.

Mal wrote:
I checked the database backups for 3rd and 4th of May but there was nothing in your account on either date.  I&#39;m afraid you must have deleted them before they had a chance to be in a backup.

I wrote:
Thank you for your reply, but as I said in my email, we did not delete the records.  They disappeared.

Mal wrote:
Yes sure, I believe you.

I wrote:
I&#39;m sorry.  I must be misinterpreting the tone of your response.  Surely you do not mean to condescend with sarcasm...right?

Mal wrote:
Yes, I&#39;m 100% certain you did delete the orders, they don&#39;t ever just &quot;disappear&quot; on their own.  You don&#39;t have to admit the mistake to me but don&#39;t fool yourself, otherwise there is a risk you will end up doing it again.

So, though the business I work for has been using Mal&#39;s Ecommerce for years without any trouble, you can see that the one time we do have trouble the issue is not only not taken seriously, but the customer is ridiculed and made to be at fault.  Let&#39;s hope you never have any trouble."></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./Mals-ecommerce-cart.aspx?cartname=Mals-ecommerce-cart" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE2OTE4OTY5NTcPZBYCZg9kFgICAw9kFgICAg9kFgRmD2QWdGYPDxYCHgRUZXh0BS48aDE+TWFsJ3MgZS1jb21tZXJjZSBTaG9wcGluZyBDYXJ0IFJldmlldzwvaDE+ZGQCAQ8PFgIfAAVUPGEgaHJlZj0iL3Jldmlldy5hc3B4P2NhcnQ9TWFscy1lY29tbWVyY2UtY2FydCIgcmVsPSJub2ZvbGxvdyI+UmV2aWV3IHRoaXMgY2FydCE8L2E+ZGQCAg8PFgIfAAWvATxhIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vd3d3Lm1hbHMtZS5jb20vIiBvbkNsaWNrPSJfZ2FxLnB1c2goWydfdHJhY2tFdmVudCcsJ091dGJvdW5kU3RvcmVzJywgJ0NsaWNrJywgJ01hbCdzIGUtY29tbWVyY2UgU2hvcHBpbmcgQ2FydCddKTsiPk1hbCdzIGUtY29tbWVyY2UgTGltaXRlZDwvYT5kZAIDDw8WAh8ABU48ZGl2IGNsYXNzPSJpdGVtIj48c3BhbiBjbGFzcz0iZm4iPk1hbCdzIGUtY29tbWVyY2UgU2hvcHBpbmcgQ2FydDwvc3Bhbj48L2Rpdj5kZAIEDw8WAh8ABQhTdGFuZGFyZGRkAgUPDxYCHwAFXDxhIHJlbD0ibm9mb2xsb3ciIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vd3d3LmFuZ2ltYWMuY29tLyI+aHR0cDovL3d3dy5hbmdpbWFjLmNvbS88L2E+ZGQCBg8PFgIfAAVqPGEgcmVsPSJub2ZvbGxvdyIgdGFyZ2V0PSJfYmxhbmsiIGhyZWY9Imh0dHA6Ly93d3cuYmFieWdpZnRzdXBwbHkuY29tLyI+aHR0cDovL3d3dy5iYWJ5Z2lmdHN1cHBseS5jb20vPC9hPmRkAgcPDxYCHwBlZGQCCA8PFgIfAAUERnJlZWRkAgkPDxYCHwAFxAM8ZGl2IGNsYXNzPSJyYXRpbmciPjxzcGFuIGNsYXNzPSJhdmVyYWdlIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHRpdGxlPSIzLjUgc3RhciByYXRpbmciIGFsdD0iMy41IHN0YXIgcmF0aW5nIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxSGFsZi5naWYiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIj5BdmVyYWdlOiAzLjU8L3NwYW4+PC9kaXY+KDxzcGFuIGNsYXNzPSJjb3VudCI+MTk8L3NwYW4+KWRkAgoPDxYCHwAF8JsBUmV2aWV3ZWQgYnk6IE5hb21pPGJyIC8+IkhlcmUgaXMgbXkgZXhwZXJpZW5jZSB3L01hbCdzIHN1cHBvcnQ6DQoNCkkgd3JvdGU6DQpXZSBqdXN0IHByaW50ZWQgb3V0IDcgb25saW5lIG9yZGVycywgYW5kIGNsaWNrZWQgdG8gcGljayB1cCBwYXltZW50cy4gIFdlIGhpdCB0aGUgYmFjayBidXR0b24gdG8gZ28gYmFjayBhbmQgc2VlIGhvdyBtYW55IG9yZGVycyB0aGVyZSB3ZXJlLCBzaW5jZSB3ZSBjb3VsZG4ndCByZW1lbWJlciwgYW5kIHdoZW4gd2Ugd2VudCBiYWNrLCBhbGwgb2YgdGhlIG9yZGVycyBoYWQgZGlzYXBwZWFyZWQuICBTbywgd2UgYXJlIHVuYWJsZSB0byByZXRyaWV2ZSB0aGUgcGF5bWVudCBpbmZvIGZvciB0aGVtIG5vdy4gIElzIHRoZXJlIGFueSB3YXkgdG8gcmV0cmlldmUgdGhpcyBpbmZvPyAgV2UgZG9uJ3Qga25vdyB3aGF0IGhhcHBlbmVkLiAgV2UgZGlkbid0IGRlbGV0ZSB0aGVtLiAgVGhleSBqdXN0IGRpc2FwcGVhcmVkLg0KDQpNYWwgd3JvdGU6DQpJIGNoZWNrZWQgdGhlIGRhdGFiYXNlIGJhY2t1cHMgZm9yIDNyZCBhbmQgNHRoIG9mIE1heSBidXQgdGhlcmUgd2FzIG5vdGhpbmcgaW4geW91ciBhY2NvdW50IG9uIGVpdGhlciBkYXRlLiAgSSdtIGFmcmFpZCB5b3UgbXVzdCBoYXZlIGRlbGV0ZWQgdGhlbSBiZWZvcmUgdGhleSBoYWQgYSBjaGFuY2UgdG8gYmUgaW4gYSBiYWNrdXAuDQoNCkkgd3JvdGU6DQpUaGFuayB5b3UgZm9yIHlvdXIgcmVwbHksIGJ1dCBhcyBJIHNhaWQgaW4gbXkgZW1haWwsIHdlIGRpZCBub3QgZGVsZXRlIHRoZSByZWNvcmRzLiAgVGhleSBkaXNhcHBlYXJlZC4NCg0KTWFsIHdyb3RlOg0KWWVzIHN1cmUsIEkgYmVsaWV2ZSB5b3UuDQoNCkkgd3JvdGU6DQpJJ20gc29ycnkuICBJIG11c3QgYmUgbWlzaW50ZXJwcmV0aW5nIHRoZSB0b25lIG9mIHlvdXIgcmVzcG9uc2UuICBTdXJlbHkgeW91IGRvIG5vdCBtZWFuIHRvIGNvbmRlc2NlbmQgd2l0aCBzYXJjYXNtLi4ucmlnaHQ/DQoNCk1hbCB3cm90ZToNClllcywgSSdtIDEwMCUgY2VydGFpbiB5b3UgZGlkIGRlbGV0ZSB0aGUgb3JkZXJzLCB0aGV5IGRvbid0IGV2ZXIganVzdCAiZGlzYXBwZWFyIiBvbiB0aGVpciBvd24uICBZb3UgZG9uJ3QgaGF2ZSB0byBhZG1pdCB0aGUgbWlzdGFrZSB0byBtZSBidXQgZG9uJ3QgZm9vbCB5b3Vyc2VsZiwgb3RoZXJ3aXNlIHRoZXJlIGlzIGEgcmlzayB5b3Ugd2lsbCBlbmQgdXAgZG9pbmcgaXQgYWdhaW4uDQoNClNvLCB0aG91Z2ggdGhlIGJ1c2luZXNzIEkgd29yayBmb3IgaGFzIGJlZW4gdXNpbmcgTWFsJ3MgRWNvbW1lcmNlIGZvciB5ZWFycyB3aXRob3V0IGFueSB0cm91YmxlLCB5b3UgY2FuIHNlZSB0aGF0IHRoZSBvbmUgdGltZSB3ZSBkbyBoYXZlIHRyb3VibGUgdGhlIGlzc3VlIGlzIG5vdCBvbmx5IG5vdCB0YWtlbiBzZXJpb3VzbHksIGJ1dCB0aGUgY3VzdG9tZXIgaXMgcmlkaWN1bGVkIGFuZCBtYWRlIHRvIGJlIGF0IGZhdWx0LiAgTGV0J3MgaG9wZSB5b3UgbmV2ZXIgaGF2ZSBhbnkgdHJvdWJsZS4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IE1heSwgMjAxNSAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiBTdGFuZGFyZDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBJc2FhYzxiciAvPiJJdCB3b3JrcyEgYW5kIGl0cyBkZWFkIHNpbXBsZSB0byB1c2UuLi4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEFwcmlsLCAyMDE1ICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IFN0YW5kYXJkPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEFtYW5kYTxiciAvPiJJIGZvdW5kIHRoaXMgY2FydCBjbHVua3ksIGF3a3dhcmQgYW5kIHRpbWUtY29uc3VtaW5nIHRvIHNldCB1cCwgd2l0aCBwb29yIGluc3RydWN0aW9ucy4gIEp1ZGdpbmcgYnkgdGhlIG51bWJlciBvZiBjb21wbGFpbnRzIG9uIHRoZWlyIHVzZXIgZm9ydW0gdGhlcmUgYXJlIGZhciB0b28gbWFueSBpbnRlZ3JhdGlvbiBnbGl0Y2hlcy4gIFRoZSBidXR0b24tbWFraW5nIGZhY2lsaXR5IGlzIHBhcnRpY3VsYXJseSBwb29yLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBGZWJydWFyeSwgMjAxNSAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiBTdGFuZGFyZDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBtaXN0eTxiciAvPiJVbmludHVpdGl2ZSwgZHlzZnVuY3Rpb25hbCBhbmQgdG90YWxseSB1c2VsZXNzLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKdWx5LCAyMDE0ICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IFN0YW5kYXJkPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEpvZWw8YnIgLz4iSSBoYXZlIHRvIGFncmVlIHdpdGggdGhlIG90aGVyIHJldmlld2VycyB3aGVuIGl0IGNvbWVzIHRvIHRoaXMgZ3V5J3MgYXR0aXR1ZGUgYW5kIHVud2lsbGluZ25lc3MgdG8gYm90aCBoZWxwIHdpdGggaXNzdWVzIEFORCBhZG1pdCB0aGF0IHRoZXJlIGNvdWxkIHBvc3NpYmx5IGJlIGFueXRoaW5nIHdyb25nIHdpdGggaGlzIHByb2dyYW1zLiBXZSBhY3R1YWxseSBoYWQgb3JkZXJzIGZyb20gb3RoZXIgc2l0ZXMgc2hvd2luZyB1cCBvbiBvdXIgbGlzdCBvZiBvcmRlcnMgYW5kIGhlIHdhcyB1bndpbGxpbmcgdG8gaGVscCB3aXRoIHRoYXQhIFRvdGFsbHkgdW5hcG9sb2dldGljLiBJZiB5b3UgbmVlZCB0byBoYXZlIHlvdXIgb3JkZXJzIHNlY3VyZSBhbmQgZ2xpdGNoIGZyZWUsIEkgd291bGQgbm90IGNvbnNpZGVyIHRoaXMgc2VydmljZS4gIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IFNlcHRlbWJlciwgMjAxMiAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiBTdGFuZGFyZDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBsb2xhPGJyIC8+Ik9ubHkgc28tc28uICBVbmFibGUgdG8gbW9kIHNoaXBwaW5nIGNhbGNzIHRvIGNvbnNpZGVyIGJ1bGt5IG9yIG1hbnkgaXRlbXM7IHJlc3VsdHMgaW4gaHVnZSBkaWZmZXJlbmNlcy1zb21ldGltZXMgc2hvcnQgYnkgJDUgc29tZXRpbWVzIG92ZXIgYnkgJDIsIG5ldmVyIGNvcnJlY3QgYW5kIG5vIHdheSB0byBjb21wZW5zYXRlIGludGVsbGlnZW50bHkuICBObyBVU1BTIGluc3VyYW5jZSBpbnRlZ3JhdGlvbi4gIENvdXBvbnMgZmVhdHVyZSBpcyBwb29yIChubyByZXN0cmljdGlvbnMgdG8gY2F0ZWdvcmllcyBvciBwYXJ0aWN1bGFyIHR5cGUgb2YgaXRlbSkuICBCZXN0IGZvciBzbWFsbCBvbmxpbmUgc3RvcmVzIHdpdGggbmFycm93L3NpbWlsYXIgcmFuZ2Ugb2YgcHJvZHVjdHMuICBJJ20gbG9va2luZyBmb3IgYW5vdGhlciBjaG9pY2UgYWZ0ZXIgbG9zaW5nIHF1aXRlIGEgbG90IG9uIGluY29ycmVjdCBzaGlwcGluZy4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEF1Z3VzdCwgMjAxMiAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiBTdGFuZGFyZDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBDbGF1ZGluZTxiciAvPiJJIGhhdmUgYmVlbiB1c2luZyB0aGUgY2FydCBmb3IgOCB5ZWFycyAmIGxvdmUgaXQuIEl0J3Mgc28gZWFzeSB0byB1c2UsIHdvcmtzIHdlbGwsIFBheXBhbCAmIEdvb2dsZSBjaGVjayBvdXQuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBNYXJjaCwgMjAxMiAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiBTdGFuZGFyZDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBKb25lczxiciAvPiJUcmllZCB1c2luZyB0aGlzIGZvciBhIHNob3J0IHdoaWxlLCBhbmQgZm91bmQgdGhhdCBpdCB3YXMgZmFyIHRvbyBlYXN5IGZvciBwZW9wbGUgdG8gY2hhbmdlIHRoZSBwcmljZSBvZiB0aGluZ3MgYmVmb3JlIHRoZXkgZ2V0IGFkZGVkIHRvIHRoZSBjYXJ0LiANCg0KTmVlZHMgc29tZSBzb3J0IG9mIHNlY3VyaXR5IGFkZGVkIHRvIHN0b3AgdGhpcywgb3RoZXJ3aXNlIHlvdSBoYXZlIHRvIGNoZWNrIHRoZSBjb3N0cyBvZiBldmVyeSBpdGVtIGluIHRoZSBjYXJ0IGZvciBldmVyeSBvcmRlciB0byBtYWtlIHN1cmUgdGhleSBoYXZlIG5vdCBiZWVuIHRhbXBlcmVkIHdpdGguDQoNCkNhbid0IHJpc2sgdXNpbmcgdGhpcyBmb3IgYSBidXN5IHNpdGUuDQoiPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogTm92ZW1iZXIsIDIwMTEgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogU3RhbmRhcmQ8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogVGVkPGJyIC8+IkkgY2FuIGhpZ2hseSByZWNvbW1lbmQgbWFsJ3MgZWNvbW1lcmNlIGJhc2VkIG9uIG15IGV4cGVyaWVuY2UuIA0KSXQgaXMgdmVyeSBlYXN5IHRvIHVzZSBjb21wYXJlZCB0byBzb21lIGFsdGVybmF0aXZlcyBhbmQgbXkgY2xpZW50IGlzIHZlcnkgcGxlYXNlZCB3aXRoIHdoYXQgSSBzZXR1cCBmb3IgaGlzIHNpdGUgdXNpbmcgbWFscyB3aGljaCBpcyBhIHdpbiB3aW4gc2l0dWF0aW9uLiBTdGFydGVkIG9mZiB1c2luZyB0aGUgZnJlZSB2ZXJzaW9uIHdoaWNoIHdhcyBmaW5lIGJ1dCBJIGVuZGVkIHVwIHVwZ3JhZGluZyB0byBQcmVtaXVtIGZvciAkOCBwZXIgbW9udGggc28gSSBjb3VsZCB1cGxvYWQgbXkgb3duIGNhcnQgdGVtcGxhdGUgc28gbm93IHRoZSBjaGVja291dCBwYWdlIGl0IGxvb2tzIGlkZW50aWNhbCB0byBteSBzaXRlIGRlc2lnbi4gDQpJZiBJIHJ1biBpbiB0byBhbnkgZ290Y2hhcyBJIHdpbGwgcG9zdCBhbm90aGVyIHJldmlldyBidXQgaWYgeW91IGFyZSBsb29raW5nIGZvciBhbiBlYXN5IHRvIHVzZSBmcmVlIGNhcnQgdGhpcyBpcyBkZWZpbml0ZWx5IHdvcnRoIGEgdHJ5LiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogU2VwdGVtYmVyLCAyMDExICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IFN0YW5kYXJkPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IERlYnJhPGJyIC8+IkkgaGF2ZSB1c2VkIHRoaXMgY2FydCBmb3IgbW9yZSB0aGFuIDEwIHllYXJzIChib3RoIFN0YW5kYXJkIGFuZCBQcmVtaXVtKSBhbmQgaGF2ZSBmb3VuZCBNYWwgdG8gYmUgcmVzcG9uc2l2ZSBhbmQgcGVyc29uYWJsZS4gV2hpbGUgaXQncyBjbGVhciB0aGF0IGhlIGRvZXMgbm90IHN1ZmZlciBpZGlvdHMsIGhlIGtub3dzIGhpcyBzdHVmZiBhbmQgaGFzIG1vcmUgdGhhbiBvbmNlIGdvbmUgdGhlIGV4dHJhIGJpdCB0byBtZWV0IG15IG5lZWRzLiBJIGhhdmUgbmV2ZXIgZm91bmQgaGltIChoZXksIG1heWJlIGl0J3MgYSBoZXI/KSB0byBiZSBhbnl0aGluZyBsZXNzIHRoYW4gcGVyZmVjdGx5IGF0dGVudGl2ZSB0byBoaXMgYnVzaW5lc3MuIFdoZW4gaGF2aW5nIGRpZmZpY3VsdHkgd2l0aCBhbnl0aGluZywgaXQncyBhbHdheXMgZ29vZCB0byBjaGVjayB0aGUgYWN0aXZlIGZvcnVtIGFyZWEuIE1hbnkgdXNlcnMgdGFrZSB0aGUgdGltZSB0byBoZWxwIG5ld2JpZXMuICBUaGVyZSdzIGFsc28gYSBmb3JtIHBhZ2Ugd2hlcmUgeW91IGNhbiBjdXQmcGFzdGUgY29kZSB0byBjcmVhdGUgZm9ybXMgZm9yIGp1c3QgYWJvdXQgYW55dGhpbmcgeW91IG1pZ2h0IGltYWdpbmUuIE92ZXIgdGhlIHllYXJzIEkgaGF2ZSBnb25lIGZyb20gZnJlZSwgdG8gcHJlbWl1bSB3aXRoIG9mZi1saW5lIGNyZWRpdCBjYXJkIHByb2Nlc3NpbmcgdG8gKHByZXNlbnQpIHByb2Nlc3NpbmcgdGhyb3VnaCBhbiBvbmxpbmUgYXV0aG9yaXphdGlvbiBwb3J0YWwgKHZpYUtMSVggJiBFbGF2b24pZm9yIGNyZWRpdCBjYXJkcyBhbmQgYWNjZXB0aW5nIEdvb2dsZSBDaGVja291dCBhbmQgUGF5bWVudHMgYnkgQW1hem9uLiBBbGwgdHJhbnNpdGlvbnMgd2VyZSBhY2NvbXBsaXNoZWQgZWFzaWx5IGluIGxlc3MgdGhhbiA1IG1pbnV0ZXMgYW5kIHRoZSBjYXJ0IG1lc2hlcyBwZXJmZWN0bHkgd2l0aCBteSBzaXRlIGFuZCB3aXRoIGFsbCAzIHBheW1lbnQgcHJvY2Vzc29ycy4gWW91IGNhbid0IGJlYXQgZnJlZSBhbmQgUHJlbWl1bSBpcyB2ZXJ5IGZhaXJseSBwcmljZWQuICBXZSBkbyBzaG9wIGFyb3VuZCBldmVyeSBub3cgYW5kIHRoZW4gYW5kIGhhdmUgbmV2ZXIgZm91bmQgYW55dGhpbmcgY2xvc2UgdG8gdGhlIHZhbHVlIGFuZCBzZXJ2aWNlIGF0IE1hbCdzLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogSnVuZSwgMjAxMSAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiBTdGFuZGFyZDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBCREs8YnIgLz4iV2hpbGUgSSB3YXMgc2V0dGluZyB1cCB0aGUgc2VydmljZSwgSSByYW4gYWNyb3NzIGEgcHJvYmxlbSBzZXR0aW5nIHVwIFVTUFMgc2hpcHBpbmcgc2VydmljZXMuICBJIHdlbnQgdG8gZW1haWwgc3VwcG9ydCBidXQgYXMgSSBmb3VuZCwgb25lIG1hbiAsIE1hbCBTdGV3YXJ0LCBpcyBydW5uaW5nIHRoaXMgZW50aXJlIGNvbXBhbnkgaW4gRW5nbGFuZC4gIEFtIEkgc3VwcG9zZWQgdG8gbGVhdmUgbXkgb3JkZXJzIGluIHRoZSBoYW5kcyBvZiBvbmUgbWFuIG9uIHRoZSBvdGhlciBzaWRlIG9mIHRoZSBwbGFuZXQ/ICBJIGRvbid0IHRoaW5rIHNvLiAgSWYgaGlzIHNlcnZpY2Ugd2VudCBkb3duLCB3ZSB3b3VsZCBiZSBzY3Jld2VkIGFuZCBqdWRnaW5nIGZyb20gdGhlIHRvbmUgb2YgaGlzIENvbnRhY3QgVXMgcGFnZSwgd2Ugd291bGRuJ3QgcmVjZWl2ZSBoZWxwLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogTWF5LCAyMDExICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IFN0YW5kYXJkPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IFBhdHJpY2lhPGJyIC8+IkkgaGF2ZSBiZWVuIHVzaW5nIE1hbCdzLWUgc2luY2UgMTk5OS4gQnVpbHQgc2V2ZXJhbCB3ZWIgc2l0ZXMgYW5kIGN1cnJlbnRseSBydW4gMTIgY2FydHMgb24gbXkgc2l0ZS4gKFdlIGhhdmUgdGhhdCBtYW55IHNoaXBwaW5nIGxvY2F0aW9ucyBhbmQgbmVlZCB0aGUgdmVyc2F0aWxpdHkgdGhhdCBubyBvdGhlciBjYXJ0IG9mZmVycy4pIFRoZXkgYXJlIHRoZSBzaW1wbGVzdCB0byB1c2UsIGxlYXN0IHRpbWUgY29uc3VtaW5nIGFuZCBtb3N0IGVmZmljaWVudCBjYXJ0IEkgaGF2ZSB0cmllZCwgZXZlbiB3aGlsZSBjaGVja2luZyBvdXQgc2hvcHBpbmcgY2FydHMgcGVyaW9kaWNhbGx5IHRvIHJldmlldyBmb3Igb3RoZXIgY29tcGFuaWVzIGJ1aWxkaW5nIHdlYiBzaXRlcy4gSXQgaXMgdGhlIG9ubHkgc2hvcHBpbmcgY2FydCBJIGNhbiByZWNvbW1lbmQgdG8gYW55IGJ1c2luZXNzLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogRmVicnVhcnksIDIwMTEgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogU3RhbmRhcmQ8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogQXJuaWU8YnIgLz4iSSBjcmVhdGVkIHR3byB3ZWIgc2l0ZXMgZm9yIGEgY2xpZW50IHdobyB3YW50ZWQgdG8gc2VsbCBwcm9kdWN0LiAgSSBoYWQgbmV2ZXIgc2V0IHVwIGFuIGVjb21tZXJjZSBiYWNrIGVuZCBiZWZvcmUuICBJIG11c3Qgc2F5LCB0aGlzIHdhcyBzbyBlYXN5IHRoYXQgYW4gMTEgeWVhciBvbGQga2lkIGNvdWxkIHNldCBpdCB1cC4NCg0KVGhlIGZyZWUgdmVyc2lvbiBwcm92aWRlcyBmb3IgcXVpdGUgYSBiaXQgb2YgY3VzdG9taXphdGlvbi4gIE11Y2ggbW9yZSB0aGFuIEkgZXhwZWN0ZWQuDQoNCkkgY2FuIHJlY29tbWVuZCBNYWwncyB2ZXJ5IGhpZ2hseS4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IERlY2VtYmVyLCAyMDA5ICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IFN0YW5kYXJkPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEpvaG48YnIgLz4iU28gZmFyIEkgaGF2ZSBiZWVuIGFtYXplZCBhdCBob3cgZWFzeSBpdCB3YXMgZm9yIG1lIHRvIHNldCB1cCBQYXlQYWwgYW5kIEdvb2dsZSBDaGVja291dCB3aXRoIGp1c3QgYSBiYXNpYyBrbm93bGVkZ2Ugb2YgSHRtbC4gIEdyZWF0IGpvYiBNYWwhIC0gYW5kIGdyZWF0IHByaWNlLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogU2VwdGVtYmVyLCAyMDA5ICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IFN0YW5kYXJkPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IFRhbTxiciAvPiJUaGVyZSBpcywgaW4gbXkgb3Bpbmlvbiwgbm8gZWFzaWVyIHdheSB0byBhZGQgYSBzdG9yZSBjaGVja291dCB0byBhbiBleGlzdGluZyBzaXRlIFRoYW4gTWFsJ3MuIEkgd2FzIGhpcmVkIHRvIHJlYnVpbGQgYW4gZXhpc3RpbmcgRWNvbW1lcmNlIHNpdGUgdGhhdCBoYWQgbG9zdCB0aGVpciByZW1vdGUgY2hlY2tvdXQgc2VydmljZS4gQWxvdCBvZiBjYXJ0IHNvZnR3YXJlIHByb21pc2UgZWFzeSBpbnRlZ3JhdGlvbiBmb3IgZXhpc3Rpbmcgc2l0ZXMsIGJ1dCB3aGVuIHB1c2ggY29tZXMgdG8gc2hvdmUsIHRoZSBhY3R1YWwgZGVsaXZlcnkgaXMgbGFja2luZywgYW5kIG9mdGVuIHRpbWUtY29uc3VtaW5nICh3aGljaCB0cmFuc2xhdGVzIHRvIEVYUEVOU0lWRSBmb3IgdGhlIGNsaWVudCkuIEFmdGVyIGV4dGVuc2l2ZSBzaG9wcGluZyBmb3IgYSBzb2x1dGlvbiwgSSBkaXNjb3ZlcmVkIE1hbHMuIE1hbHMgd2FzIGJ5IEZBUiB0aGUgcXVpY2tlc3QsIGVhc2llc3Qgd2F5IHRvIGdldCB0aGUgam9iIGRvbmUuIFRoZSBjaGVja291dCBwYWdlIGRlc2lnbiBpcyBzb21ld2hhdCBzcGFyc2UsIGJ1dCBnb29kIGVub3VnaCB0byBnZXQgdGhlIGpvYiBkb25lIC0tIGFuZCB0aGUgcHJpY2UgaXMgcmlnaHQhIEtub3dsZWRnZSBvZiBodG1sIGZvcm1zIHN0cnVjdHVyZSB3aWxsIGNvbWUgaW4gaGFuZHkgaWYgeW91IHBsYW4gb24gdXNpbmcgZm9ybSBlbGVtZW50cyAoc3VjaCBhcyAiYWRkIHRvIGNhcnQiIGFuZCBjaGVja2JveGVzKSwgYnV0IHNvbWVvbmUgaGFwcHkgdG8gdXNlIHNpbXBsZSBsaW5rcyBzaG91bGQgaGF2ZSBubyB0cm91YmxlIGF0IGFsbCwgaWYgeW91IGtub3cgaG93IHRvIGNvcHkgJiBwYXN0ZS4gQXMgZm9yIHRoZSBwcmV2aW91cyByZXZpZXdlcidzIHRyb3VibGUgd2l0aCBzZXR0aW5nIHVwIHNoaXBwaW5nIHByaWNlcyB1c2luZyB0aGUgdGFibGVzLi4uIEFmdGVyIGEgbGl0dGxlIHRyaWFsIGFuZCBlcnJvciwgSSB3YXMgYWJsZSB0byBzZXQgdGhlIHNoaXBwaW5nIHRhYmxlcyB1cCB0byBjaGFyZ2UgKHBlciBteSBjbGllbnQncyByZXF1ZXN0KSBkaWZmZXJlbnQgc2hpcHBpbmcgcmF0ZXMgZGVwZW5kaW5nIG9uIHRoZSB0b3RhbCBvcmRlciBhbW91bnQuIFdvcmtzIFBFUkZFQ1RMWS4gIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBOb3ZlbWJlciwgMjAwNzwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBKYW48YnIgLz4iSSBoYXZlIGxpa2VkIHRoaXMgc2VydmljZSwgYnV0IHJlY2VudGx5IGhhdmUgaGFkIGEgbG90IG9mIHRyb3VibGUgZ2V0dGluZyB0aGUgY2FydCB0byBjYWxjdWxhdGUgY29ycmVjdCBzaGlwcGluZyBhbmQgaGFuZGxpbmcgY2hhcmdlcyBvZiBteSBwcm9kdWN0cy4gSSBzZW50IDMgZW1haWwgbWVzc2FnZXMgZm9yIGhlbHAgd2l0aCB0aGlzIGFuZCBJIHdhcyB0b2xkIEkgd291bGQgbm90IGJlIGhlbHBlZCBiZWNhdXNlIEkgaGFkIGEgYmFkIGF0dGl0dWRlLiBJIGFza2VkIGZvciBhbm90aGVyIHJlcHJlc2VudGF0aXZlIHRvIHRhbGsgdG8gYW5kIG5vb25lIGNvbnRhY3RlZCBtZS4gVGhpcyBsZWF2ZXMgbWUgdG8gYmVsaWV2ZSB0aGF0IHRoZXkgYWRtaW5pc3RyYXRvcnMvb3duZXJzIG9mIHRoZSBjb21wYW55IGFyZSBub3Qgd2lsbGluZyB0byBzZXJ2aWNlIHRoZWlyIHByb2R1Y3QuIFRoaXMgc2l0dWF0aW9uIGhhcyBiZWVuIGV4dHJlbWVseSBmcnVzdHJhdGluZy4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IFNlcHRlbWJlciwgMjAwNzwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBKZXNzaWNhPGJyIC8+IkkgaGF2ZSB1c2VkIHRoaXMgc2hvcHBpbmcgY2FydCBmb3IgdmFyaW91cyBjbGllbnRzIHdobyByZXF1ZXN0ZWQgaXQsIGFuZCBoYXZlIGhhZCBhIHJhdGhlciBmcnVzdHJhdGluZyBleHBlcmllbmNlIGVhY2ggdGltZS4gIA0KDQpJdCdzIG5vdCBkeW5hbWljIGFuZCB0aGUgZm9ybXMgeW91IHNldCB1cCBjYW4gYmUgY29uZnVzaW5nLiAgDQoNCkkgZGlzbGlrZSB0aGUgYWRtaW4gYW5kIHRoZSBzaGlwcGluZyBvcHRpb25zL3RhYmxlcyBib2dnbGUgdGhlIG1pbmQuICANCg0KSSdkIHJlY29tbWVuZCBTZWN1cmUgTmV0IFNob3Agb3ZlciB0aGlzIGFueSBkYXkuDQoNClRoZSBvd25lciBpcyBoZWxwZnVsIGFuZCBxdWljayB0byBhbnN3ZXIgcXVlc3Rpb25zLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEphbnVhcnksIDIwMDc8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogRGFuaWVsbGU8YnIgLz4iSSBoYXZlIHVzZWQgdGhpcyBzeXN0ZW0gZm9yIHllYXJzIG9uIG1hbnkgc2l0ZXMgYnkgaXRzZWxmIGFuZCB3aXRoIGFkZC1vbiBmcm9udC1lbmQgc3lzdGVtcyBhbmQgY291bGQgbm90IHJlY29tbWVuZCBpdCBtb3JlLiBJdCdzIGdyZWF0IGZvciB0aGUgbW9yZSBhZHZhbmNlZCBkby1pdC15b3Vyc2VsZmVyIHdobyB3YW50cyBmdWxsIGNvbnRyb2wgb3ZlciB0aGVpciB3ZWJzaXRlLCB5ZXQgYWxzbyBwcm92aWRlcyB0aGUgYmVnaW5uZXIgd2l0aCBncmVhdCB0b29scyB0byBoYXZlIGEgcXVhbGl0eSB3ZWJzaXRlIGFzIHdlbGwuIEFub3RoZXIgZ3JlYXQgZmVhdHVyZSBpcyBiZWluZyBhYmxlIGFjY2VwdCBjcmVkaXQgY2FyZHMgd2l0aG91dCBoYXZpbmcgdG8gcHVyY2hhc2UgYW4gU1NMIGNlcnQgYW5kIGRlZGljYXRlZCBJUCBiZWNhdXNlIHRoZSBwYXltZW50IHBhZ2VzIGFyZSBob3N0ZWQgb24gTWFsJ3Mgc2VydmVyIGFuZCBhcmUgc2VjdXJlLiBPdmVyYWxsIGEgZ3JlYXQgc3lzdGVtIHdpdGggbG90cyBvZiBmbGV4aWJpbGl0eSwgZmVhdHVyZXMsIGFuZCBpbnRlZ3JhdGVkIHNoaXBwZXJzIGFuZCBwYXltZW50IGdhdGV3YXlzLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogT2N0b2JlciwgMjAwNjwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBNaXRjaDxiciAvPiJXb3JrcyB2ZXJ5IHdlbGwhICBZb3UgaGF2ZSBhIGxvdCBvZiBjb250cm9sIG92ZXIgaXQuICBUbyB1c2UgdGhlIFVQUyByYXRlIGNhbGN1bGF0b3IgeW91IGhhdmUgdG8gdXBncmFkZSB0byB0aGUgcGFpZCB2ZXJzaW9uLCBidXQgYXQgJDgvbW9udGggaXQgaXMgd2VsbCB3b3J0aCBpdC4gDQoNCkFsc28gY29tZXMgd2l0aCBzb2Z0d2FyZSBzbyB5b3UgY2FuIGRvd25sb2FkIHlvdXIgb3JkZXJzLiAgVGhhdCB3b3JrcyBqdXN0IE9LLiAgQWdhaW4gdGhlIHBhaWQgdmVyc2lvbiBvZiB0aGUgc29mdHdhcmUgKCQ5NSkgaGFzIG9uZSBrZXkgYWR2YW50YWdlLXlvdSBjYW4gcHJpbnQgcmVwb3J0cyB3aXRoIGl0LiBXaXRoIHRoZSBmcmVlIHZlcnNpb24geW91IGhhdmUgdG8gZXhwb3J0IHlvdXIgZGF0YSB0byBleGNlbCBhbmQgcHJpbnQgZnJvbSB0aGVyZS4NCg0KT3ZlciBhbGwgSSBhbSB2ZXJ5IHBsZWFzZWQgd2l0aCBpdCBhbmQgZmluZCBpdCBhbiBleGNlcHRpb25hbCB2YWx1ZS4NCiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogU2VwdGVtYmVyLCAyMDA2PC9kaXY+PGJyIC8+PGEgaHJlZj0iL3Jldmlldy5hc3B4P2NhcnQ9TWFscy1lY29tbWVyY2UtY2FydCIgcmVsPSJub2ZvbGxvdyIgc3R5bGU9ImZvbnQtc2l6ZToxLjJlbTtmb250LXdlaWdodDpib2xkOyI+QWRkIFlvdXIgT3duIFJldmlldzwvYT5kZAILDw8WAh8ABekBVGhpcyBpcyBhIHZlcnkgZ29vZCBjYXJ0LCB3aGljaCBjb21lcyBhdCBmcmVlIG9mIGNvc3QuIEl0IGhhcyBhIHZlcnkgZ29vZCByZXBvcnQgZ2VuZXJhdGlvbiB0b29sLCBidXQgdGhhdCB0b29sIGlzIGEgbGl0dGxlIGNvbXBsZXggdG8gaGFuZGxlLg0KDQpXaGlsZSBpdCBpcyB0ZWNobmljYWxseSBhIGhvc3RlZCBwcm9kdWN0LCBpdCBmdWxseSBpbnRlZ3JhdGVzIHdpdGggeW91ciBleGlzdGluZyBzaXRlLiBkZAINDw8WAh8ABeUCPCEtLSBjYS1wdWItMDAxODQxNzM0NzUwMzEwNy9Eb3dubG9hZFBIUENhcnRzXzcyOHg5MF90b3AgLS0+PHNjcmlwdCBhc3luYyBzcmM9Ii8vcGFnZWFkMi5nb29nbGVzeW5kaWNhdGlvbi5jb20vcGFnZWFkL2pzL2Fkc2J5Z29vZ2xlLmpzIj48L3NjcmlwdD48aW5zIGNsYXNzPSJhZHNieWdvb2dsZSJzdHlsZT0iZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6NzI4cHg7aGVpZ2h0OjkwcHgiZGF0YS1hZC1jbGllbnQ9ImNhLXB1Yi0xNzIyMDUxODI4NzI0MzM3ImRhdGEtYWQtc2xvdD0iMzI4MDIwNzczOSI+PC9pbnM+PHNjcmlwdD4oYWRzYnlnb29nbGU9d2luZG93LmFkc2J5Z29vZ2xlfHxbXSkucHVzaCh7fSk7PC9zY3JpcHQ+ZGQCDg8PFgIfAAUUV2luZG93cywgTGludXgsIFVuaXhkZAIPDw8WAh8ABQNQSFBkZAIQDw8WAh8ABQVNeVNRTGRkAhEPDxYCHwAFA1llc2RkAhIPDxYCHwAFAk5vZGQCEw8PFgIfAAUCTm9kZAIUDw8WAh8ABQJOb2RkAhUPDxYCHwAFA1llc2RkAhYPDxYCHwAFA1llc2RkAhcPDxYCHwAFAk5vZGQCGA8PFgIfAAUDWWVzZGQCGQ8PFgIfAAUDWWVzZGQCGg8PFgIfAAUDWWVzZGQCGw8PFgIfAAUDWWVzZGQCHA8PFgIfAAUCTm9kZAIdDw8WAh8ABQJOb2RkAh4PDxYCHwAFA1llc2RkAh8PDxYCHwAFA1llc2RkAiAPDxYCHwAFAk5vZGQCIg8PFgIfAAXoAjwhLS0gY2EtcHViLTAwMTg0MTczNDc1MDMxMDcvRG93bmxvYWRQSFBDYXJ0c183Mjh4OTBfbWlkZGxlIC0tPjxzY3JpcHQgYXN5bmMgc3JjPSIvL3BhZ2VhZDIuZ29vZ2xlc3luZGljYXRpb24uY29tL3BhZ2VhZC9qcy9hZHNieWdvb2dsZS5qcyI+PC9zY3JpcHQ+PGlucyBjbGFzcz0iYWRzYnlnb29nbGUic3R5bGU9ImRpc3BsYXk6aW5saW5lLWJsb2NrO3dpZHRoOjcyOHB4O2hlaWdodDo5MHB4ImRhdGEtYWQtY2xpZW50PSJjYS1wdWItMTcyMjA1MTgyODcyNDMzNyJkYXRhLWFkLXNsb3Q9IjMyODAyMDc3MzkiPjwvaW5zPjxzY3JpcHQ+KGFkc2J5Z29vZ2xlPXdpbmRvdy5hZHNieWdvb2dsZXx8W10pLnB1c2goe30pOzwvc2NyaXB0PmRkAiMPDxYCHwAFA1llc2RkAiQPDxYCHwAFA1llc2RkAiUPDxYCHwAFA1llc2RkAiYPDxYCHwAFA1llc2RkAicPDxYCHwAFA1llc2RkAigPDxYCHwAFAk5vZGQCKQ8PFgIfAAUDWWVzZGQCKg8PFgIfAAUDWWVzZGQCKw8PFgIfAAUDWWVzZGQCLA8PFgIfAAUDWWVzZGQCLQ8PFgIfAAUDWWVzZGQCLg8PFgIfAAUDWWVzZGQCLw8PFgIfAAUCTm9kZAIwDw8WAh8ABQNZZXNkZAIxDw8WAh8ABQNZZXNkZAIyDw8WAh8ABQNZZXNkZAIzDw8WAh8ABQNZZXNkZAI0Dw8WAh8ABQJOb2RkAjUPDxYCHwAFA1llc2RkAjYPDxYCHwAFA1llc2RkAjcPDxYCHwAFA1llc2RkAjgPDxYCHwAFA1llc2RkAjoPDxYCHwAF6AI8IS0tIGNhLXB1Yi0wMDE4NDE3MzQ3NTAzMTA3L0Rvd25sb2FkUEhQQ2FydHNfNzI4eDkwX2JvdHRvbSAtLT48c2NyaXB0IGFzeW5jIHNyYz0iLy9wYWdlYWQyLmdvb2dsZXN5bmRpY2F0aW9uLmNvbS9wYWdlYWQvanMvYWRzYnlnb29nbGUuanMiPjwvc2NyaXB0PjxpbnMgY2xhc3M9ImFkc2J5Z29vZ2xlInN0eWxlPSJkaXNwbGF5OmlubGluZS1ibG9jazt3aWR0aDo3MjhweDtoZWlnaHQ6OTBweCJkYXRhLWFkLWNsaWVudD0iY2EtcHViLTE3MjIwNTE4Mjg3MjQzMzciZGF0YS1hZC1zbG90PSIzMjgwMjA3NzM5Ij48L2lucz48c2NyaXB0PihhZHNieWdvb2dsZT13aW5kb3cuYWRzYnlnb29nbGV8fFtdKS5wdXNoKHt9KTs8L3NjcmlwdD5kZAI7Dw8WAh8ABYABPGEgcmVsPSJub2ZvbGxvdyIgaHJlZj0iL3JlcG9ydC5hc3B4P25hbWU9TWFscy1lY29tbWVyY2UtY2FydCZ0eXBlPUNhcnQiPklzIHRoZXJlIGFuIGVycm9yIG9uIHRoaXMgcGFnZSBvciBhbiB1cGRhdGUgbmVlZGVkPzwvYT5kZAI8Dw8WAh8ABQsyMiBPY3QgMjAxNGRkAgEPDxYCHwAF6gM8dWwgY2xhc3M9ImxhdGVzdCI+PGxpPjxhIGhyZWY9Ii9jYXJ0cy9hYmFudGUtY2FydC5hc3B4Ij5BYmFudGVDYXJ0IFJldmlldyAgJnJhcXVvOzwvYT48L2xpPjxsaT48YSBocmVmPSIvY2FydHMvb3NDb21tZXJjZS5hc3B4Ij5vc0NvbW1lcmNlIFJldmlldyAgJnJhcXVvOzwvYT48L2xpPjxsaT48YSBocmVmPSIvY2FydHMvUXVpY2stQ2FydC5hc3B4Ij5RdWljay5DYXJ0IFJldmlldyAgJnJhcXVvOzwvYT48L2xpPjxsaT48YSBocmVmPSIvY2FydHMvWmVuLUNhcnQuYXNweCI+WmVuIENhcnQgUmV2aWV3ICAmcmFxdW87PC9hPjwvbGk+PGxpPjxhIGhyZWY9Ii9jYXJ0cy9PcGVuQ2FydC5hc3B4Ij5PcGVuQ2FydCBSZXZpZXcgICZyYXF1bzs8L2E+PC9saT48bGkgc3R5bGU9J21hcmdpbi10b3A6IDhweDsnPjxzdHJvbmc+PGEgaHJlZj0nL2FsbC1zaG9wcGluZy1jYXJ0cy5hc3B4Jz5BbGwgMjAwKyBzaG9wcGluZyBjYXJ0czwvYT48L3N0cm9uZz48L2xpPjwvdWw+ZGRkX/mYTIiQ9PQamyJH/8mBsqTRVxiaRTTWI1XpaTikeBw=" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="0C1F84DE" />
        <div align="center">
            
    <div id="ads1" align="center">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Top -->
                <ins class="adsbygoogle"
                    style="display: block"
                    data-ad-client="ca-pub-1388311751127083"
                    data-ad-slot="8765540533"
                    data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>

        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
Shopping Cart Details

                    </h2>
                </div>
                <div class="inpage">
                    
   
<script type="text/javascript">
    
function pop(anchor){

window.open('/glossarypop.aspx#' + anchor,'mywindow','width=400,height=200');
}
</script>

   <script type="text/javascript">
       var CurrentCartName = "Mals-ecommerce-cart";
       var CurrentCartImage = "/img/cartlogo/Mals-E-Commerce.png";
     </script>

<div id="_ctl0_contentBody_hreviewmaster" class="hreview-aggregate">	
<!-- body master table -->
<table width="737" border="0" cellspacing="0" cellpadding="0" class="masterTable">
<tr>
	<td id="tBody">
   

    <span id="_ctl0_contentBody_lblHeading"><h1>Mal's e-commerce Shopping Cart Review</h1></span>
    	<span id="_ctl0_contentBody_lblReview"><a href="/review.aspx?cart=Mals-ecommerce-cart" rel="nofollow">Review this cart!</a></span>
    <br />
	<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Basic Information</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230" style="font-size: 120%"><strong>Company name</strong><div class="compQ"><a href="javascript:pop('companyname')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst" style="font-size: 120%">
				<strong><span id="_ctl0_contentBody_lblCompanyName"><a target="_blank" href="http://www.mals-e.com/" onClick="_gaq.push(['_trackEvent','OutboundStores', 'Click', 'Mal's e-commerce Shopping Cart']);">Mal's e-commerce Limited</a></span></strong></td>
		</tr>
		<tr>
			<td class="compCol" style="font-size: 120%">Product name<div class="compQ"><a href="javascript:pop('productname')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst" style="font-size: 120%">
				<strong><span id="_ctl0_contentBody_lblProductName"><div class="item"><span class="fn">Mal's e-commerce Shopping Cart</span></div></span></strong></td>
		</tr>
		<tr>
			<td class="compCol">Version<div class="compQ"><a href="javascript:pop('version')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblVersion">Standard</span></td>
		</tr>
		<tr>
			<td class="compCol">Sample customer sites<div class="compQ"><a href="javascript:pop('sample1')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSample1"><a rel="nofollow" target="_blank" href="http://www.angimac.com/">http://www.angimac.com/</a></span><br />
				<span id="_ctl0_contentBody_lblSample2"><a rel="nofollow" target="_blank" href="http://www.babygiftsupply.com/">http://www.babygiftsupply.com/</a></span><br />
				<span id="_ctl0_contentBody_lblSample3"></span>
				</td>
		</tr>
		<tr>
			<td class="compCol">Price<div class="compQ"><a href="javascript:pop('price')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPrice">Free</span></td>
		</tr>
		<tr>
			<td class="compCol">Average review score<div class="compQ"><a href="javascript:pop('reviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReviewScore"><div class="rating"><span class="average"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" title="3.5 star rating" alt="3.5 star rating"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif"><img src="http://cdn.ecommercespot.com/images/cart1Half.gif"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif">Average: 3.5</span></div>(<span class="count">19</span>)</span></td>
		</tr>
		<tr>
			<td class="compCol" valign=top>User reviews<div class="compQ"><a href="javascript:pop('reviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReviews">Reviewed by: Naomi<br />"Here is my experience w/Mal's support:

I wrote:
We just printed out 7 online orders, and clicked to pick up payments.  We hit the back button to go back and see how many orders there were, since we couldn't remember, and when we went back, all of the orders had disappeared.  So, we are unable to retrieve the payment info for them now.  Is there any way to retrieve this info?  We don't know what happened.  We didn't delete them.  They just disappeared.

Mal wrote:
I checked the database backups for 3rd and 4th of May but there was nothing in your account on either date.  I'm afraid you must have deleted them before they had a chance to be in a backup.

I wrote:
Thank you for your reply, but as I said in my email, we did not delete the records.  They disappeared.

Mal wrote:
Yes sure, I believe you.

I wrote:
I'm sorry.  I must be misinterpreting the tone of your response.  Surely you do not mean to condescend with sarcasm...right?

Mal wrote:
Yes, I'm 100% certain you did delete the orders, they don't ever just "disappear" on their own.  You don't have to admit the mistake to me but don't fool yourself, otherwise there is a risk you will end up doing it again.

So, though the business I work for has been using Mal's Ecommerce for years without any trouble, you can see that the one time we do have trouble the issue is not only not taken seriously, but the customer is ridiculed and made to be at fault.  Let's hope you never have any trouble."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: May, 2015 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Isaac<br />"It works! and its dead simple to use..."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: April, 2015 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Amanda<br />"I found this cart clunky, awkward and time-consuming to set up, with poor instructions.  Judging by the number of complaints on their user forum there are far too many integration glitches.  The button-making facility is particularly poor."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: February, 2015 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: misty<br />"Unintuitive, dysfunctional and totally useless."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: July, 2014 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Joel<br />"I have to agree with the other reviewers when it comes to this guy's attitude and unwillingness to both help with issues AND admit that there could possibly be anything wrong with his programs. We actually had orders from other sites showing up on our list of orders and he was unwilling to help with that! Totally unapologetic. If you need to have your orders secure and glitch free, I would not consider this service. "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2012 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: lola<br />"Only so-so.  Unable to mod shipping calcs to consider bulky or many items; results in huge differences-sometimes short by $5 sometimes over by $2, never correct and no way to compensate intelligently.  No USPS insurance integration.  Coupons feature is poor (no restrictions to categories or particular type of item).  Best for small online stores with narrow/similar range of products.  I'm looking for another choice after losing quite a lot on incorrect shipping."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: August, 2012 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Claudine<br />"I have been using the cart for 8 years & love it. It's so easy to use, works well, Paypal & Google check out."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: March, 2012 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Jones<br />"Tried using this for a short while, and found that it was far too easy for people to change the price of things before they get added to the cart. 

Needs some sort of security added to stop this, otherwise you have to check the costs of every item in the cart for every order to make sure they have not been tampered with.

Can't risk using this for a busy site.
"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: November, 2011 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Ted<br />"I can highly recommend mal's ecommerce based on my experience. 
It is very easy to use compared to some alternatives and my client is very pleased with what I setup for his site using mals which is a win win situation. Started off using the free version which was fine but I ended up upgrading to Premium for $8 per month so I could upload my own cart template so now the checkout page it looks identical to my site design. 
If I run in to any gotchas I will post another review but if you are looking for an easy to use free cart this is definitely worth a try."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2011 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Debra<br />"I have used this cart for more than 10 years (both Standard and Premium) and have found Mal to be responsive and personable. While it's clear that he does not suffer idiots, he knows his stuff and has more than once gone the extra bit to meet my needs. I have never found him (hey, maybe it's a her?) to be anything less than perfectly attentive to his business. When having difficulty with anything, it's always good to check the active forum area. Many users take the time to help newbies.  There's also a form page where you can cut&paste code to create forms for just about anything you might imagine. Over the years I have gone from free, to premium with off-line credit card processing to (present) processing through an online authorization portal (viaKLIX & Elavon)for credit cards and accepting Google Checkout and Payments by Amazon. All transitions were accomplished easily in less than 5 minutes and the cart meshes perfectly with my site and with all 3 payment processors. You can't beat free and Premium is very fairly priced.  We do shop around every now and then and have never found anything close to the value and service at Mal's."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2011 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: BDK<br />"While I was setting up the service, I ran across a problem setting up USPS shipping services.  I went to email support but as I found, one man , Mal Stewart, is running this entire company in England.  Am I supposed to leave my orders in the hands of one man on the other side of the planet?  I don't think so.  If his service went down, we would be screwed and judging from the tone of his Contact Us page, we wouldn't receive help."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: May, 2011 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Patricia<br />"I have been using Mal's-e since 1999. Built several web sites and currently run 12 carts on my site. (We have that many shipping locations and need the versatility that no other cart offers.) They are the simplest to use, least time consuming and most efficient cart I have tried, even while checking out shopping carts periodically to review for other companies building web sites. It is the only shopping cart I can recommend to any business."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: February, 2011 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Arnie<br />"I created two web sites for a client who wanted to sell product.  I had never set up an ecommerce back end before.  I must say, this was so easy that an 11 year old kid could set it up.

The free version provides for quite a bit of customization.  Much more than I expected.

I can recommend Mal's very highly."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: December, 2009 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: John<br />"So far I have been amazed at how easy it was for me to set up PayPal and Google Checkout with just a basic knowledge of Html.  Great job Mal! - and great price."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2009 &nbsp;&nbsp;Version reviewed: Standard</div><br />Reviewed by: Tam<br />"There is, in my opinion, no easier way to add a store checkout to an existing site Than Mal's. I was hired to rebuild an existing Ecommerce site that had lost their remote checkout service. Alot of cart software promise easy integration for existing sites, but when push comes to shove, the actual delivery is lacking, and often time-consuming (which translates to EXPENSIVE for the client). After extensive shopping for a solution, I discovered Mals. Mals was by FAR the quickest, easiest way to get the job done. The checkout page design is somewhat sparse, but good enough to get the job done -- and the price is right! Knowledge of html forms structure will come in handy if you plan on using form elements (such as "add to cart" and checkboxes), but someone happy to use simple links should have no trouble at all, if you know how to copy & paste. As for the previous reviewer's trouble with setting up shipping prices using the tables... After a little trial and error, I was able to set the shipping tables up to charge (per my client's request) different shipping rates depending on the total order amount. Works PERFECTLY. "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: November, 2007</div><br />Reviewed by: Jan<br />"I have liked this service, but recently have had a lot of trouble getting the cart to calculate correct shipping and handling charges of my products. I sent 3 email messages for help with this and I was told I would not be helped because I had a bad attitude. I asked for another representative to talk to and noone contacted me. This leaves me to believe that they administrators/owners of the company are not willing to service their product. This situation has been extremely frustrating."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2007</div><br />Reviewed by: Jessica<br />"I have used this shopping cart for various clients who requested it, and have had a rather frustrating experience each time.  

It's not dynamic and the forms you set up can be confusing.  

I dislike the admin and the shipping options/tables boggle the mind.  

I'd recommend Secure Net Shop over this any day.

The owner is helpful and quick to answer questions."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: January, 2007</div><br />Reviewed by: Danielle<br />"I have used this system for years on many sites by itself and with add-on front-end systems and could not recommend it more. It's great for the more advanced do-it-yourselfer who wants full control over their website, yet also provides the beginner with great tools to have a quality website as well. Another great feature is being able accept credit cards without having to purchase an SSL cert and dedicated IP because the payment pages are hosted on Mal's server and are secure. Overall a great system with lots of flexibility, features, and integrated shippers and payment gateways."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: October, 2006</div><br />Reviewed by: Mitch<br />"Works very well!  You have a lot of control over it.  To use the UPS rate calculator you have to upgrade to the paid version, but at $8/month it is well worth it. 

Also comes with software so you can download your orders.  That works just OK.  Again the paid version of the software ($95) has one key advantage-you can print reports with it. With the free version you have to export your data to excel and print from there.

Over all I am very pleased with it and find it an exceptional value.
"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2006</div><br /><a href="/review.aspx?cart=Mals-ecommerce-cart" rel="nofollow" style="font-size:1.2em;font-weight:bold;">Add Your Own Review</a></span></td>
		</tr>
		
		
		<tr>
			<td class="compCol" valign=top>
				Ecommerce Spot Comments
			</td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblComments">This is a very good cart, which comes at free of cost. It has a very good report generation tool, but that tool is a little complex to handle.

While it is technically a hosted product, it fully integrates with your existing site. </span>
			</td>
		</tr>
			
		
		
		
		</table>

<div style="margin: 5px 0 5px -20px;">

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=Mals-ecommerce-cart" target="_blank" > <img src="/img/scebanners/set1/728x90.png" /> </a> 
</div>


    
</div>
		
		<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Technology</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Supported operating systems<div class="compQ"><a href="javascript:pop('os')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblOperatingSystem">Windows, Linux, Unix</span></td>
		</tr>
		<tr>
			<td class="compCol">Language<div class="compQ"><a href="javascript:pop('lang')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLanguage">PHP</span></td>
		</tr>
		<tr>
			<td class="compCol">Database<div class="compQ"><a href="javascript:pop('db')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblDatabase">MySQL</span></td>
		</tr>
		<tr>
			<td class="compCol">Source code<div class="compQ"><a href="javascript:pop('sourcecode')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSourceCode">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Reseller discounts<div class="compQ"><a href="javascript:pop('reseller')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReseller">No</span></td>
		</tr>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Features</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Product limit<div class="compQ"><a href="javascript:pop('productlimit')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblProductlimit">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Category limit<div class="compQ"><a href="javascript:pop('categorylimit')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCategoryLimit">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Multi-language<div class="compQ"><a href="javascript:pop('multilanguage')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblMultilanguage">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Gift certificates<div class="compQ"><a href="javascript:pop('giftcertificates')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblGiftcertificates">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Loyalty program<div class="compQ"><a href="javascript:pop('loyalty')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLoyalty">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Email merchant on order<div class="compQ"><a href="javascript:pop('emailorder')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblEmailOrder">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Affiliates program<div class="compQ"><a href="javascript:pop('affiliates')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblAffiliates">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Site search<div class="compQ"><a href="javascript:pop('sitesearch')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSiteSearch">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Search optimization tools<div class="compQ"><a href="javascript:pop('seotools')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSeotools">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Product reviews<div class="compQ"><a href="javascript:pop('productreviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblProductreviews">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Newsletters<div class="compQ"><a href="javascript:pop('newsletters')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblNewsletters">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Discount coupons<div class="compQ"><a href="javascript:pop('discountcoupons')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblDiscountcoupons">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Customer registrations<div class="compQ"><a href="javascript:pop('customerregistration')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCustomerregistration">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Wish list<div class="compQ"><a href="javascript:pop('wishlist')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWishlist">No</span></td>
		</tr>
		</table>
<div style="margin: 5px 0 5px -20px;">

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=Mals-ecommerce-cart" target="_blank" > <img src="/img/scebanners/set1/728x90.png" /> </a> 
</div>


    
</div>
		<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>	
		
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Shipping</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Shipping price range<div class="compQ"><a href="javascript:pop('pricerangeshipping')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblpricerangeshipping">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Shipping weight range<div class="compQ"><a href="javascript:pop('weightrangeshipping')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWeightrangeshipping">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">UPS lookup<div class="compQ"><a href="javascript:pop('upslookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblUpslookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">USPS lookup<div class="compQ"><a href="javascript:pop('uspslookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblUspslookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Fedex lookup<div class="compQ"><a href="javascript:pop('fedexlookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblFedexlookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Canada Post lookup<div class="compQ"><a href="javascript:pop('canadapostlookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCanadapostlookup">No</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Tax &amp; Payment</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Tax by state<div class="compQ"><a href="javascript:pop('taxbystate')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblTaxbystate">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Tax by country<div class="compQ"><a href="javascript:pop('taxbycountry')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblTaxbycountry">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">PayPal<div class="compQ"><a href="javascript:pop('paypal')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPaypal">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Authorize.Net<div class="compQ"><a href="javascript:pop('authorizenet')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblAuthorizenet">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Verisign<div class="compQ"><a href="javascript:pop('verisign')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblVerisign">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Worldpay<div class="compQ"><a href="javascript:pop('worldpay')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWorldpay">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Secure Trading<div class="compQ"><a href="javascript:pop('securetrading')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSecuretrading">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Others<div class="compQ"><a href="javascript:pop('others')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblOthers">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Non credit card options<div class="compQ"><a href="javascript:pop('nonccoptions')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblNonccoptions">Yes</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Support</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Customer forums<div class="compQ"><a href="javascript:pop('customerforums')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCustomerforum">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Free support<div class="compQ"><a href="javascript:pop('freesupport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblFreeSupport">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Paid support<div class="compQ"><a href="javascript:pop('paidsupport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPaidsupport">No</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Reports</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Sales reports<div class="compQ"><a href="javascript:pop('salesreport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSalesreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Search reports<div class="compQ"><a href="javascript:pop('searchreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_Lblsearchreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Low stock reports<div class="compQ"><a href="javascript:pop('lowstockreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLowstockreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Inventory reports<div class="compQ"><a href="javascript:pop('inventoryreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblInventoryreports">Yes</span></td>
		</tr>
	</table>
	<p>&nbsp;</p>
<div style="margin: 5px 0 5px -20px;">	

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=Mals-ecommerce-cart" target="_blank" > <img src="/img/scebanners/set1/728x90.png" /> </a> 
</div>


    
</div>
		<span id="_ctl0_contentBody_lblReport"><a rel="nofollow" href="/report.aspx?name=Mals-ecommerce-cart&type=Cart">Is there an error on this page or an update needed?</a></span><br /><br />
	<span style="color: #ddd; font-size: 80%;"><p>Last updated:
		<span id="_ctl0_contentBody_lblReviewedDate">22 Oct 2014</span><br /><br /></p></span>


		

</td>
<td align=left width=1 id="cart_gads">



	</td>
</tr>
</table>
</div>


<div id="upNext" style ="display:none;">
<div style="width:310px;"><h6>More Reviews</h6>
<span id="_ctl0_contentBody_lblCrossLinks"><ul class="latest"><li><a href="/carts/abante-cart.aspx">AbanteCart Review  &raquo;</a></li><li><a href="/carts/osCommerce.aspx">osCommerce Review  &raquo;</a></li><li><a href="/carts/Quick-Cart.aspx">Quick.Cart Review  &raquo;</a></li><li><a href="/carts/Zen-Cart.aspx">Zen Cart Review  &raquo;</a></li><li><a href="/carts/OpenCart.aspx">OpenCart Review  &raquo;</a></li><li style='margin-top: 8px;'><strong><a href='/all-shopping-carts.aspx'>All 200+ shopping carts</a></strong></li></ul></span>
</div></div>


                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
