

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	Review of VevoCart Community - Read User Reviews &amp; Feature Listings for VevoCart Community Shopping Cart
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<link href="../App_Themes/Cart/StyleSheet.css" type="text/css" rel="stylesheet" /><meta name="Description" content="Recent User Review: Buying vevocart was the worst thing I did. After selecting this for a client, we couldn&#39;t get it to work, when we did, it was slow, overcomplicated, paypal failed to work. Contacting support was entirely useless, half the time they didn&#39;t understand what I was asking, when they did they made pointless responses and it doesn&#39;t feel like they know the system at all. Do yourself a Favour buy something else. "></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./VevoCart.aspx?cartname=VevoCart" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTE2OTE4OTY5NTcPZBYCZg9kFgICAw9kFgICAg9kFgRmD2QWdGYPDxYCHgRUZXh0BSI8aDE+VmV2b0NhcnQgQ29tbXVuaXR5IFJldmlldzwvaDE+ZGQCAQ8PFgIfAAVJPGEgaHJlZj0iL3Jldmlldy5hc3B4P2NhcnQ9VmV2b0NhcnQiIHJlbD0ibm9mb2xsb3ciPlJldmlldyB0aGlzIGNhcnQhPC9hPmRkAgIPDxYCHwAFnwE8YSB0YXJnZXQ9Il9ibGFuayIgaHJlZj0iaHR0cDovL3d3dy52ZXZvY2FydC5jb20iIG9uQ2xpY2s9Il9nYXEucHVzaChbJ190cmFja0V2ZW50JywnT3V0Ym91bmRTdG9yZXMnLCAnQ2xpY2snLCAnVmV2b0NhcnQgQ29tbXVuaXR5J10pOyI+VmV2byBTeXN0ZW1zLiwgTHRkLjwvYT5kZAIDDw8WAh8ABUI8ZGl2IGNsYXNzPSJpdGVtIj48c3BhbiBjbGFzcz0iZm4iPlZldm9DYXJ0IENvbW11bml0eTwvc3Bhbj48L2Rpdj5kZAIEDw8WAh8ABQM2LjBkZAIFDw8WAh8ABWI8YSByZWw9Im5vZm9sbG93IiB0YXJnZXQ9Il9ibGFuayIgaHJlZj0iaHR0cDovL3d3dy5lbmVyZ3ljbHViLmNvbS8iPmh0dHA6Ly93d3cuZW5lcmd5Y2x1Yi5jb20vPC9hPmRkAgYPDxYCHwAFYDxhIHJlbD0ibm9mb2xsb3ciIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vd3d3LmFxdWFkdXguY28udWsvIj5odHRwOi8vd3d3LmFxdWFkdXguY28udWsvPC9hPmRkAgcPDxYCHwAFejxhIHJlbD0ibm9mb2xsb3ciIHRhcmdldD0iX2JsYW5rIiBocmVmPSJodHRwOi8vd3d3LmRpc2NvdW50ZGlyZWN0Zmxvb3JpbmcuY29tLyI+aHR0cDovL3d3dy5kaXNjb3VudGRpcmVjdGZsb29yaW5nLmNvbS88L2E+ZGQCCA8PFgIfAAUERnJlZWRkAgkPDxYCHwAFvgM8ZGl2IGNsYXNzPSJyYXRpbmciPjxzcGFuIGNsYXNzPSJhdmVyYWdlIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHRpdGxlPSIzIHN0YXIgcmF0aW5nIiBhbHQ9IjMgc3RhciByYXRpbmciPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiPkF2ZXJhZ2U6IDM8L3NwYW4+PC9kaXY+KDxzcGFuIGNsYXNzPSJjb3VudCI+MTg8L3NwYW4+KWRkAgoPDxYCHwAFlqQBUmV2aWV3ZWQgYnk6IEdyYW50IENhcmR3ZWxsPGJyIC8+IkJ1eWluZyB2ZXZvY2FydCB3YXMgdGhlIHdvcnN0IHRoaW5nIEkgZGlkLiBBZnRlciBzZWxlY3RpbmcgdGhpcyBmb3IgYSBjbGllbnQsIHdlIGNvdWxkbid0IGdldCBpdCB0byB3b3JrLCB3aGVuIHdlIGRpZCwgaXQgd2FzIHNsb3csIG92ZXJjb21wbGljYXRlZCwgcGF5cGFsIGZhaWxlZCB0byB3b3JrLiBDb250YWN0aW5nIHN1cHBvcnQgd2FzIGVudGlyZWx5IHVzZWxlc3MsIGhhbGYgdGhlIHRpbWUgdGhleSBkaWRuJ3QgdW5kZXJzdGFuZCB3aGF0IEkgd2FzIGFza2luZywgd2hlbiB0aGV5IGRpZCB0aGV5IG1hZGUgcG9pbnRsZXNzIHJlc3BvbnNlcyBhbmQgaXQgZG9lc24ndCBmZWVsIGxpa2UgdGhleSBrbm93IHRoZSBzeXN0ZW0gYXQgYWxsLiBEbyB5b3Vyc2VsZiBhIEZhdm91ciBidXkgc29tZXRoaW5nIGVsc2UuICI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBOb3ZlbWJlciwgMjAxNSAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiA0PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IGluZmx1ZW5jZXVrPGJyIC8+IkkgcHVyY2hhc2VkIHRoaXMgc29sdXRpb24gdG8gdXNlIGZvciBvbmUgb2YgbXkgY2xpZW50cywgaSBtdXN0IHNheSB0aGUgd2hvbGUgZXhwZXJpZW5jZSBoYXMgYmVlbiBhIHRlcnJpYmxlIGV4cGVyaWVuY2UgZm9yIGJvdGggb2YgdXMhDQoNClRoZSBzdXBwb3J0IGFyZSB1c2VsZXNzLCBhbmQgZG9udCBldmVuIGtub3cgdGhlaXIgb3duIHByb2R1Y3QuIEFmdGVyIHNhbGVzIGFyZSB2ZXJ5IHJ1ZGUgYW5kIGFyZSBub3Qgd2lsbGluZyB0byBoZWxwLiBXaXRoIGNvbnN0YW50IGVycm9ycywgYW5kIGlzc3VlcyBoYXBwZW5pbmcgYXQgYWxtb3N0IGV2ZXJ5IHR1cm4hIE1vc3Qgb2YgdGhlIGlzc3VlcyBmYWNlZCBpIGhhdmUgaGFkIHRvIHJlc29sdmUgbXlzZWxmLCBhbmQgdGhlbiBtb3JlIGlzc3VlcyBwb3BwZWQgdXAhIFRoaXMgaXMgdmVyeSBwb29ybHkgY29kZWQsIGFuZCBpcyBub3QgZXZlbiB3b3J0aCB5b3VyIHRpbWUgY29uc2lkZXJpbmcuDQoNCkZvciAkMzAwIHlvdSB3b3VsZCBleHBlY3QgYSBsaXR0bGUgbW9yZSBmcm9tIHRoZSBzb2x1dGlvbiBob3dldmVyIGlmIHlvdXIgbG9va2luZyBmb3IgYSByZWxpYWJsZSBzb2x1dGlvbiwgQVZPSUQgdGhpcyBhdCBhbGwgY29zdHMhIQ0KDQpJc3N1ZXMgZmFjZWQNCi0gUGF5cGFsIGVycm9yaW5nLCBvciBub3QgcmVkaXJlY3RpbmcgdG8gcGF5bWVudCBzY3JlZW4uDQotIE9mZmxpbmUgQ3JlZGl0IGNhcmQgcGF5bWVudHMgZXJyb3JpbmcgaWYgQ1ZWIG9wdGlvbiBpcyBlbmFibGVkICh0aGlzIGlzIGR1ZSB0byB0aGVpciBWZXZvUGF5IGFkZG9uIG5vdCBhbGxvd2luZyBDVlYgdG8gYmUgc3RvcmVkKQ0KLSBSYW5kb20gRGF0YWJhc2UgY3Jhc2hlcw0KLSBTaXRlIGRvd250aW1lDQotIFNlcnZlciBDcmFzaGVzDQoNClRoZXNlIGFyZSBqdXN0IHNvbWUgb2YgdGhlIGlzc3VlcyBmYWNlZCwgaGF2aW5nIHRvIGFjdHVhbGx5IHJlLXdyaXRlIGNvZGUgdG8gZ2V0IHRoaW5ncyB3b3JraW5nIGFzIHRoZXkgc2hvdWxkIGlzIG5vdCBhbiBhY2NlcHRhYmxlIHN1cHBvcnQgcmVwbHkhISI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBPY3RvYmVyLCAyMDE1ICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IDQ8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogRnJ1c3RyYXRlZDxiciAvPiINCiBHZXR0aW5nIHlvdXIgU2l0ZSB1cCBhbmQgcnVubmluZyB3aWxsIGJlIGEgY2hhbGxlbmdlLiAgV2ViIHN1cHBvcnQgaXMgbWluaW1hbC4gWW91IHdpbGwgYmUgb24geW91ciBvd24uICAiPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bmUsIDIwMTUgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBKZWZmPGJyIC8+Ikkgc3BlY2lmaWNhbGx5IGRlY2lkZWQgb24gYSBwYXJ0aWN1bGFyIGhvc3Rpbmcgc29sdXRpb24gYmVjYXVzZSB0aGV5IG9mZmVyZWQgVmV2b0NhcnQuIEkgcGFpZCBmb3IgdGhlIGZpcnN0IHllYXIgKCQyMjkpIGFuZCB3aXRoaW4gdGhhdCBmaXJzdCB5ZWFyIHdhcyB1bmFibGUgdG8gZmluZCB0aGUgdGltZSB0byBnZXQgdGhlIHN0b3JlIHVwIGFuZCBydW5uaW5nIChidXNpbmVzcyBpc3N1ZXMsIGZhbWlseSBwcm9ibGVtcykuIE5vYm9keSdzIGZhdWx0IGJ1dCBteSBvd24sIGJ1dCB0aGVuIEkgcmVuZXdlZCAoJDkwKSBpbiB0aGUgaG9wZXMgb2YgZmluYWxseSBnZXR0aW5nIHRvIGdldCBteSBzdG9yZSB1cCBhbmQgcnVubmluZyBvbmx5IHRvIGZpbmQgdGhhdCBvdXQgdGhhdCBteSBob3N0aW5nIHNvbHV0aW9uIGRyb3BwZWQgVmV2b0NhcnQuIEkgdHJpZWQgdG8gZ2V0IGp1c3QgdGhlIHJlbmV3YWwgbW9uZXkgYmFjayBmcm9tIFZldm9DYXJ0LCBidXQgdGhleSB3aWxsIG5vdCBpc3N1ZSBhIHJlZnVuZCBmb3IgdGhlIHJlbmV3YWwhIFVsdGltYXRlbHksIEkgcGFpZCBmb3IgYSBwcm9kdWN0IEkgbmV2ZXIgZ290IHRvIHVzZS4gSSB3b3VsZCBub3QgcmVjb21tZW5kIFZldm9DYXJ0IG9yIHRoZSBob3N0aW5nIHNvbHV0aW9uIHRoYXQgSSBhbSBhbHNvIHBsYW5uaW5nIHRvIGxlYXZlLCBFYXN5Q0dJIChmb3JtZXJseSwgV2ViU3RyaWtlKS4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogTWFyY2gsIDIwMTUgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBlYXN0bGlmZTxiciAvPiJJIGFtIHZlcnkgaW1wcmVzc2l2ZSBhYm91dCB0aGlzIHNvZnR3YXJlLiBJdCBwcm92aWRlIGEgbG90IG9mIGltcG9ydGFudCBmZWF0dXJlIGZvciBvbmxpbmUgc3RvcmUgYnV0IGl0J3MgZnJlZS4gSSBsaWtlIHByb2R1Y3QgbGlnaHRib3ggZmVhdHVyZSB0aGF0IGhlbHAgbXkgY3VzdG9tZXIgZG9uJ3QgbmVlZCB0byBnbyBiYWNrIHRvIHByb2R1Y3QgbGlzdCBwYWdlIHdoZW4gdGhleSBoYXZlIGFscmVhZHkgc2VlbiBwcm9kdWN0IGRldGFpbC4gSSB0aGluayB0aGlzIGFkdmFudGFnZSBpbmNyZWFzZSBjaGFuY2Ugb2YgcmVwcmVzZW50IHByb2R1Y3QgaW4gbXkgc3RvcmUuIEF0IGxhc3QgSSB3YW5uYSBzYXkgdmV2b2NhcnQgaXMgd29ydGh5IHRvIHRyeS4gICI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogQXVndXN0LCAyMDEzICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IDYuMDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBrc2FuPGJyIC8+IlRoaXMgY2FydCBpcyBqdW5rLiBMb3RzIG9mIGVycm9ycy4gUG9vciBzdXBwb3J0LiBQb29yIGRvY3VtZW50YXRpb24gICI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKdWx5LCAyMDEzICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IDYuMDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBEaWFuYTxiciAvPiJJIHJlYWxseSBsaWtlIFZldm9DYXJ0LiBUaGV5IGhhdmUgYWxsIHRoZSB0b29scyBJIG5lZWQuIEkgbGlrZSBob3cgdGhleSBwcm92aWRlIHNldmVyYWwgdXNlZnVsIHByb2R1Y3QgZmVhdHVyZXMgZm9yIGEgY3VzdG9tZXIgdG8gcGxheSB3aXRoLiBRdWljayB2aWV3IGlzIGEgZ3JlYXQgd2F5IHRvIG1ha2UgdGhlIHNpdGUgbG9vayBtb2Rlcm4sIGxheWVyZWQgbmF2aWdhdGlvbiBpcyByZWFsbHkgZXNzZW50aWFsIGluIGZpbHRlcmluZyBkb3duIGEgY2F0YWxvZyBieSBwcm9kdWN0IGF0dHJpYnV0ZXMuIFRoZXJlIGFyZSBhbHNvIHZhcmlvdXMgbWFya2V0aW5nIGZlYXR1cmVzIDsgY291cG9uIGZlYXR1cmUsIHF1YW50aXR5IGRpc2NvdW50LCBnaWZ0IGNlcnRpZmljYXRlLCBhbmQgcHJvbW90aW9uIGdyb3VwLCBqdXN0IHRvIG5hbWUgYSBmZXcuIHRoZWlyIHN1cHBvcnRzIGFyZSBxdWlyZSByZXNwb25zaXZlLCBhbmQgbGFzdGx5LCB0aGUgbGljZW5zZSBwcmljZSBpcyByZWFzb25hYmxlLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogSnVseSwgMjAxMyAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiA2LjA8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogQ2hvbnJ1ZGVlPGJyIC8+IlRoZSBzdG9yZWZyb2504oCZcyBkZXNpZ24gaXMgcHJldHR5IGdvb2QuIEkgYW0gYWJsZSB0byBjaGFuZ2UgdG8gY3NzIHRvIGhhdmUgbXkgcHJlZmVycmVkIGNvbG9yLiAgVGhlIGZlYXR1cmVzIGFyZSByZWFsbHkgcGxlbnR5IGZvciBhIGZyZWUgc29mdHdhcmUuDQoNCiAgICAgICB0aGFua3MgZm9yIGdpdmluZyB0aGlzLiBPaC4uLiBJdCB3b3VsZCBiZSBuaWNlIGlmIHRoZSB0b3AgbWVudSBzdHlsZSBpcyBjb25maWd1cmFibGUuIEkgbmVlZCBzb21lIHRpbWUgdG8gZmluZCBvdXQgaG93IHRvIGNoYW5nZSB0b3AgbWVudSBhcyBhIGRyb3Bkb3duIHN0eWxlLg0KDQogICAgICBpdCB0dXJucyBvdXQgSSB3b3VsZCBuZWVkIHRvIG1ha2UgYSBjb2RlIGNoYW5nZSBldmVuIHRob3VnaCBpdOKAmXMgcG9zdGVkIGluIHRoZSBmb3J1bSBidXQgaXTigJlzIG11Y2ggYmV0dGVyIHRvIG1ha2UgaXQgY29uZmlndXJhYmxlLiBUaGUgYnJvd3NpbmcgZmVhdHVyZSBpcyByZWFsbHkgbmljZS4NCg0KICAgICAgVmlzaXRvcnMgYXJlIGFibGUgdG8gbmFycm93IGRvd24gdGhlIHNlYXJjaCB1c2luZyBmaWx0ZXJpbmcgb3B0aW9ucyBvbiB0aGUgbGVmdC4gZ29vZCBzb2Z0d2FyZS4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bHksIDIwMTMgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNi4wPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IFB1cHBMRTxiciAvPiJWZXZvQ2FydCBzdG9yZSBpcyByaWNoIGluIGZlYXR1cmVzLiAgIEkgbGlrZSB0aGUgZmFjdCB0aGF0IHRoZXJlIGlzIGEgYnVpbHQtaW4gaW1hZ2Ugc2xpZGVyICBidXQgdGhleSBzaG91bGQgYWxzbyBhZGQgdGhlIGxhbmd1YWdlIGNoYW5nZSBmdW5jdGlvbi4NCiANCkkgcmVhbGx5IGxpa2UgdGhlIGJhY2sgb2ZmaWNlIGRlc2lnbi4gSXTigJlzIG1vZGVybiBhbmQgdXNlci1mcmllbmRseS4gSSBhbSBhYmxlIHRvIG1hbmFnZSBteSBzdG9yZSB3aXRob3V0IHByb2dyYW1taW5nIGtub3dsZWRnZS4NCkkgd2lzaCB0byBzZWUgbW9yZSBza2lucyBzaW5jZSBJIGNhbiBub3QgY3JlYXRlIGEgc2tpbiBteXNlbGYuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBKdWx5LCAyMDEzICZuYnNwOyZuYnNwO1ZlcnNpb24gcmV2aWV3ZWQ6IDYuMDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBQYXVsYTxiciAvPiJJ4oCZbSBvbmUgb2YgdGhlIFZldm9jYXJ0IHVzZXJzIHVzaW5nIHZlcnNpb24gNi4gSSBmZWVsIHRoYXQgdGhpcyBlLWNvbW1lcmNlIHNvbHV0aW9uIGlzIHdvcnRoIHVzaW5nLiBJIGFtIGFibGUgdG8gc2V0IHVwIG15IHN0b3JlIHdpdGhpbiBhIGZldyBkYXlzLiBUaGUgYXBwbGljYXRpb24gcnVucyBzdGFibHkuICBXaGVuIEkgaGFkIGEgcHJvYmxlbSB3aXRoIHNldHRpbmcgdXAgYSBsYXlvdXQsIHRoZSBzdXBwb3J0IGd1eXMgaGVscCBtZSBzb2x2aW5nIG15IHByb2JsZW1zLiAgTGFzbHR5LCBJIGxpa2UgdGhhdCBpdCBwcm92aWRlcyBhIHNvdXJjZSBjb2RlIGZvciBjdXN0b21pemF0aW9uLiBJIGhpcmVkIG15IGRldmVsb3BlciB0byBoYXZlIGEgbGl0dGxlIGN1c3RvbWl6YXRpb24gZm9yIG15IHN0b3JlIGFuZCB3ZSB0aGluayB0aGF0IGl04oCZcyBxdWl0ZSBmbGV4aWJsZS4gICAiPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogQXByaWwsIDIwMTMgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNS4zPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEpheTxiciAvPiJQdXJjaGFzZWQgYmFjayBpbiAyMDExLi4gYm90aCBwcm92aWRlcnMgY29tbWVudGVkIG9uIGhvdyBoYXJkIGl0IHdhcyB0byBpbnN0YWxsLi4gdGhlcmUgaGF2ZSBiZWVuIG51bWVyb3VzIGVycm9ycyBhbmQgdGhlIGMjIHByb2dyYW1tZXIgSSBoaXJlZCBoYXMgY29tbWVudGVkIG9uIGhvdyBwb29ybHkgdGhlIGNvZGUgaXMgd3JpdHRlbi4gRE9OJ1QgQlVZISI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBNYXJjaCwgMjAxMyAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiA1LjM8L2Rpdj48YnIgLz5SZXZpZXdlZCBieTogTWVobWV0aGFuPGJyIC8+IkkgaGF2ZSBiZWVuIHdvcmtpbmcgaW4gSVQgc2VjdG9yIGZvciBmb3VydGVlbiB5ZWFycy4gSSBoYXZlIHNvIG1hbnkgc3BlY2lhbHRpZXMgc3VjaCBhcyBXZWIgRGV2ZWxvcG1lbnQgKEMjLCBWQiksIFN5c3RlbSBJbnRlZ3JhdGlvbiwgQ29uc3VsdGFuY3kgZXRjLiBBcyBhbiBJVCBTb2x1dGlvbiBhbmQgU2VydmljZSBwcm92aWRlciBjb21wYW5pZXMgb3duZXIsIG15IHBvbGljeSB0byBjaG9vc2UgdGhlIGJlc3QgSVQgY29tcGFuaWVzIGluIHRoZWlyIGZpZWxkIGFzIG91ciBwYXJ0bmVyLiBJIGRvIGN1c3RvbWl6ZWQgQVNQLk5FVCBzb2x1dGlvbnMgYW5kIHRvb2xzIGZvciBvdXIgY2xpZW50cywgYnV0IHdlIG5lZWQgYSBjb29sIEFzcCAuTmV0IHNob3BwaW5nIHNvZnR3YXJlLiAgSSBoYXZlIHRlc3RlZCBzbyBtYW55IEFTUC5ORVQgc2hvcHBpbmcgc29mdHdhcmUgYW5kIGUtY29tbWVyY2UgaW4gdGhlIG1hcmtldCBhbmQgaSByZWFsaXplZCB0aGF0IFZldm9jYXJ0IGlzIG9uZSBvZiB0aG9zZSB3b3J0aCBtZW50aW9uaW5nIEFTUC5ORVQgZS1jb21tZXJjZSBzb2x1dGlvbi4gTXkgQ3VzdG9tZXJzIGFyZSB2ZXJ5IGhhcHB5IGZyb20gb3VyIGUtY29tbWVyY2UgZGV2ZWxvcG1lbnQgc2VydmljZXMgKFZldm9DYXJ0IGJhc2VkIGUtY29tbWVyY2Ugc29sdXRpb25zKS4gSXTigJlzIGNoZWFwLCBlYXN5IHRvIGluc3RhbGwsIGZsZXhpYmxlLCBjdXN0b21pemFibGUsIHNlY3VyZSBhbmQgcmVsaWFibGUuIEFuZCBwZXJoYXBzIHRoZSBtb3N0IGltcG9ydGFudCB0aGluZyBpcyB3aGVuIHlvdSBuZWVkIGhlbHAgVmV2b0NhcnQgaGFzIGEgdmVyeSBnb29kIHN1cHBvcnQuIFRoYW5rIHlvdSBWZXZvQ2FydCB0byBmYWNpbGl0YXRlIGFuZCBicmFjZSBvdXIgZS1jb21tZXJjZSBkZXZlbG9wbWVudCBzZXJ2aWNlcy4gDQoNCk15IENlcnRpZmljYXRpb25zOiBQTVAsIE1DREJBLCBDIyBEZXZlbG9wZXIsIE1TIFNoYXJlcG9pbnQgRGV2ZWxvcGVyLCBNQ1NFLVMsIFZDUCwgVlNQLCBWVFNQIGV0Yy4gDQoiPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bHksIDIwMTIgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNS4zPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEFtZXI8YnIgLz4iKSBJJ20gYSBDIyBkZXZlbG9wZXIgYXMgd2VsbCBhcyBydW5uaW5nIGEgc21hbGwgYnVzaW5lc3MuICBJIHN0YXJ0ZWQgd3JpdGluZyBzaG9wcGluZyBjYXJ0cyBmb3IgbXkgY2xpZW50cyBmZXcgeWVhcnMgYmFjay4gIE15IGNsaWVudHMgd2VyZSBzbWFsbCBjbGllbnRzIHRob3NlIHdlcmUgbG9va2luZyBmb3IgY3VzdG9taXplZCBzaG9wcGluZyBjYXJ0IHNvbHV0aW9ucyBhdCBhIHByaWNlIHRoYXQgdGhleSBjb3VsZCBhZmZvcmQuICBJIHNvb25lciByZWFsaXplZCB0aGF0IHRoZSBwcmljZSBJIHJlY2VpdmUgZnJvbSBteSBjbGllbnRzIGZvciB3cml0aW5nIGFuZCBtYWludGFpbmluZyBjdXN0b21pemVkIHNob3BwaW5nIGNhcnRzIGlzIHRvbyBzbWFsbCBjb21wYXJpbmcgdG8gbnVtYmVyIG9mIGhvdXJzIEkgc3BlbmQgb24gdGhvc2UgcHJvamVjdHMuICBJIHRoZW4gc3RhcnRlZCBsb29raW5nIGZvciAzcmQgcGFydHkgc2hvcHBpbmcgY2FydHMgdGhhdCByZXF1aXJlIG1pbmltdW0gY29kaW5nIGVmZm9ydCBhbmQgYWxsb3cgY3VzdG9taXphdGlvbiBhcyBwZXIgbXkgY2xpZW50IG5lZWRzLiAgSSBmYWNlZCB0d28gcHJvYmxlbXMgZHVyaW5nIG15IHNlYXJjaC4gIEZpcnN0LCB0aGVyZSB3ZXJlIG5vdCBtdWNoIEFTUC5OZXQgc2hvcHBpbmcgY2FydHMgYXZhaWxhYmxlLg0KU2Vjb25kLCB0aGUgYXZhaWxhYmxlIHNob3BwaW5nIGNhcnRzIGRpZCBub3QgcHJvdmlkZSBjdXN0b21pemVkIHNvbHV0aW9ucyBvciB0aGV5IHdlcmUgbWlzc2luZyBmZWF0dXJlcyByZXF1aXJlZCBieSBteSBjbGllbnRzLiAgVGhlbiBJIGZvdW5kIFZldm9DYXJ0Lg0KSSB3YXMgc28gaGFwcHkgYWZ0ZXIgSSB1c2VkIHRoaXMgdGhhdCBJIGNhbm5vdCBmaW5kIHdvcmRzIHRvIGRlc2NyaWJlIHRoaXMuDQpJIGhhdmUgbmV2ZXIgZm91bmQgYSBzaG9wcGluZyBjYXJ0LCBleGNlcHQgVmV2b0NhcnQsIHRoYXQgcHJvdmlkZXMgc28gbWFueSBvcHRpb25zIG9mIGN1c3RvbWl6YXRpb24gd2l0aCBsYXJnZSBudW1iZXIgb2YgZmVhdHVyZXMgYXQgYSBwcmljZSB0aGF0IGlzIGFic29sdXRlbHkgYWZmb3JkYWJsZS4gIE15IGNvZGluZyBlZmZvcnQgaGFzIHJlZHVjZWQgdG8ganVzdCAyNSUgbm93IHVzaW5nIFZldm9DYXJ0IGFuZCBJJ3ZlIG5ldmVyIGZvdW5kIGEgc2NlbmFyaW8gd2hlcmUgYSBmZWF0dXJlIHdhcyByZXF1ZXN0ZWQgYnkgbXkgY2xpZW50IHRoYXQgd2FzIG1pc3NpbmcgaW4gVmV2b0NhcnQgb3IgSSBjb3VsZG4ndCBkbyBpdCBpbiBWZXZvQ2FydCB1c2luZyBpdHMgYXZhaWxhYmxlIHNvdXJjZSBjb2RlLiAgQXQgdGhlIHNhbWUgdGltZSBJIHdhbnQgdG8gc3VnZ2VzdCB0aGF0IG5leHQgdmVyc2lvbnMgb2YgVmV2b0NhcnQgc2hvdWxkIGZvY3VzIG9uIG1ha2luZyBGcm9udC1lbmQgYW5kIEJhY2stZW5kIG1vcmUgbG9vc2VseSBjb3VwbGVkLiAgU29tZXRpbWUgSSd2ZSBmZWVsaW5nIHRoYXQgVmV2b0NhcnQgZnJvbnQtZW5kIGlzIGludGVncmF0ZWQgd2l0aCBiYWNrLWVuZCBpbiBzdWNoIGEgd2F5IHRoYXQgaWYgc29tZSBvZiBteSBjbGllbnQgc29tZWRheSByZXF1aXJlcyBhIGZyb250LWVuZCBkZXNpZ24gdGhhdCBpcyB0b3RhbGx5IGRpZmZlcmVudCB0aGFuIHRoZSBsYXlvdXQgVmV2b0NhcnQgdGVtcGxhdGVzIHByb3ZpZGUgaXQnbGwgYmUgYSBkaWZmaWN1bHQgdGFzayB0byBhY2hpZXZlLg0KIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bmUsIDIwMTIgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNS4zPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IE5laWw8YnIgLz4iDQpJIG11c3Qgc2F5IHRoYXQgVmV2b0NhcnQgaXMgIHRoZSBmZWF0dXJlLXJpY2ggc2hvcHBpbmcgY2FydC4gSXQgaW5jbHVkZXMgYWxsIGZlYXR1cmVzIGkgcmVxdWlyZSBlc3BlY2lhbGx5IHNlbyAmIG1hcmtldGluZyB0b29sLiBJIHN3aXRjaCBmcm9tIGFuIG91dGRhdGVkIGFzcCBjYXJ0IGFuZCBpdCBydW5zIG11Y2ggZmFzdGVyLiBJIGFtIGFibGUgdG8gc3RhcnQgbXkgc3RvcmUgaW4gMiB3ZWVrcy4gQXQgZmlyc3QsIGkgZG8gbm90IGtub3cgdGhhdCBhIFZldm9DYXJ0IGxpY2Vuc2UgYWxyZWFkeSBpbmNsdWRlcyBWZXZvUGF5LCB0aGUgc3VwcG9ydCBzdGFmZiBoZWxwcyBtZSBzZXQgaXQgYWxsIHVwIHF1aWNrbHkuIFRoZSBHVUkgaXMgZmFpcmx5IGludHVpdGl2ZSAsIGkgYW0gYWJsZSB0byBhZG1pbmlzdGVyIHRoZSBzaXRlIG15c2VsZi4gQWxzbywgSSByZWFsbHkgbGlrZSB0aGF0IGZhY3QgdGhhdCBpdCdzIFNFTyBmcmllbmRseSB1bmxpa2UgYXNwIGNhcnQgaSB1c2VkIGluIHRoZSBwYXN0LiBJIGRvIG5vdCBuZWVkIHRvIGhpcmUgYSBkZXZlbG9wZXIgdG8gcmV3cml0ZSBVUkwsIGkgZG8gbm90IG5lZWQgdG8gcHVyY2hhc2UgYWRkcyBvbiBmb3IgYSBmZWF0dXJlLg0KDQpWZXZvQ2FydCBVUkwgaXMgc2VvIGZyaWVuZGx5LiBNZXRhIHRpdGxlIGFuZCBkZXNjcmlwdGlvbiBhcmUgY29uZmlndXJhYmxlIGFuZCBhdXRvbWF0aWMgcG9wdWxhdGUuIExhc3RseSwgYWxsIGZlYXR1cmVzIGFyZSBpbmNsdWRlZCAsIG5vIGFkZHMgb24gcmVxdWlyZWQuICBJIHRydWx5IHJlY29tbWVuZCBWZXZvQ2FydCB0byBhbnlvbmUuDQoiPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bmUsIDIwMTIgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNS4zPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IENocmlzPGJyIC8+IkZpdmUgeWVhcnMgYWdvIHdlIHdlcmUgbG9va2luZyBmb3IgYW4gYWZmb3JkYWJsZSBzaG9wcGluZyBjYXJ0IHNvbHV0aW9uLiBPbmUgb2YgdGhlIHJlcXVpcmVtZW50cyBmb3IgdGhlIHNvbHV0aW9uIHdhcyB0aGF0IGl0IG5lZWRlZCB0byBpbmNsdWRlIHRoZSBzb3VyY2UgY29kZSwgYmUgd3JpdHRlbiBpbiBDIyBhbmQgaGF2ZSBhIGNsZWFuIHNlcGFyYXRpb24gb2YgdGhlIFVJIGFuZCBjb2RlIGJlaGluZC4gQWZ0ZXIgYW4gZXhoYXVzdGl2ZSBzZWFyY2gsIHdoaWNoIGluY2x1ZGVkIG1hbnkgb2YgdGhlIHRvcCBjYXJ0cyBhdCB0aGUgdGltZSwgd2UgZGV0ZXJtaW5lZCB0aGF0IFZldm9DYXJ0IG1ldCBhbGwgb3VyIG5lZWRzLg0KDQpPdmVyIHRoZSBwYXN0IGZpdmUgeWVhcnMsIHdlIGhhdmUgYmVlbiBhYmxlIHRvIGdyb3cgb3VyIHdlYnNpdGUgYXMgb3VyIG5lZWRzIGhhdmUgaW5jcmVhc2VkLiBUaGlzIHdvdWxkIG5vdCBoYXZlIGJlZW4gcG9zc2libGUgaGFkIFZldm9DYXJ0IG5vdCBiZWVuIHdyaXR0ZW4gc28gd2VsbC4gSXTigJlzIHZhcmlvdXMgY29udHJvbHMgYW5kIG1vZHVsZXMgYXJlIGVhc3kgdG8gZmluZC91bmRlcnN0YW5kIGFuZCwgaWYgbmVlZGVkLCBhbHRlciB0byBmaXQgb3VyIGJ1c2luZXNzIG5lZWQuIEZvciBvdXIgd2Vic2l0ZSwgd2Ugd2VyZSBhYmxlIHRvIGNvbXBsZXRlbHkgcmVza2luIHRoZSBzb2x1dGlvbiB5ZXQgc3RpbGwga2VlcCBhbGwgdGhlIHVuZGVybHlpbmcgVmV2b0NhcnQgZnVuY3Rpb25hbGl0eS4gIEJlaW5nIGFibGUgdG8gZG8gdGhpcywgd2l0aG91dCBjb21wcmlzaW5nIGZ1bmN0aW9uYWxpdHksIHJlYWxseSBpbGx1c3RyYXRlcyB0aGUgcm9idXN0bmVzcyBvZiB0aGlzIHNvbHV0aW9uLiBPdGhlciBncmVhdCBhdHRyaWJ1dGVzIG9mIHRoZSBzb2x1dGlvbjogZWFzeSBwYXltZW50IHBvcnRhbCBpbnRlZ3JhdGlvbiBhbmQgdGhlIHNpbXBsZSBwcm9kdWN0IGFuZCBvcHRpb24gbWFuYWdlbWVudC4gDQoNCk92ZXJhbGwsIHRoZSBncmVhdCB0aGluZyBhYm91dCB0aGlzIHNvbHV0aW9uIGlzIHRoYXQgaXQgZ2l2ZXMgeW91IGEgbG90IG9mIGZsZXhpYmlsaXR5IGluIHJlZ2FyZHMgdG8gaG93IG11Y2ggY3VzdG9taXphdGlvbiB5b3Ugd2FudCB0byBwdXQgaW50byB5b3VyIHdlYnNpdGUuIFlvdSBjYW4gcnVuIHN0cmFpZ2h0IG91dCBvZiB0aGUgYm94LCB1dGlsaXppbmcgdGhlIG1hbnkgdGVtcGxhdGVzIHRoZXkgaGF2ZSBhdmFpbGFibGUgb3IgZGl2ZSBpbnRvIHRoZSBjb2RlLCBhbHRlcmluZyB3aGF0ZXZlciBpcyBuZWVkZWQgdG8gZml0IHlvdXIgd2Vic2l0ZeKAmXMgbmVlZHMuIjxiciAvPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBNYXksIDIwMTIgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNS4zPC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IEVyaWM8YnIgLz4iSXQncyBiZWVuIGEgcGFpbiBpbiB0aGUgYnV0dCB0byBpbnN0YWxsLCBidXQgb3ZlcmFsbCBJJ3ZlIGJlZW4gYWJsZSB0byBkbyBpdCBlaXRoZXIgbXlzZWxmIG9yIHdpdGggdGhlIHByb21wdCAoYW5kLCB1bmZvcnR1bmF0ZWx5LCBnZW5lcmFsbHkgcmlnaHQpIGFpZGUgb2YgY3VzdG9tZXIgc2VydmljZS4gIEkndmUgYmVlbiBhYmxlIHRvIHdvcmsgb3V0IHF1aXRlIGEgYml0IG9mIGl0LiAgSSBkb24ndCByZWNjb21tZW5kIGl0IGZvciBhbnlvbmUgdGhhdCBkb2Vzbid0IGtub3cgd2hhdCB0aGV5J3JlIGRvaW5nLCBidXQgaWYgeW91J3JlIHdpbGxpbmcgdG8gbWVzcyBhcm91bmQgd2l0aCBpdCBmb3IgYSBjb3VwbGUgb2YgaG91cnMgdG8gZ2V0IGl0IGdvaW5nLCBpdCBhcHBlYXJzIHRvIGJlIGEgcHJldHR5IHNvbGlkIHByb2plY3QuICBJIGp1c3Qgd2lzaCB0aGF0IHRoZXkgZGlkIGEgbGl0dGxlIGJpdCBiZXR0ZXIgb24gc2VwYXJhdGluZyB0aGUgbXVsdGktZWRpdGlvbiBhcyB3ZWxsIGFzIHJlbHlpbmcgb24gQUpBWCBsZXNzLiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxR3JleS5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGJyIC8+PGRpdiBjbGFzcz0nZGF0ZVZlcnNpb24nPlJldmlldyBkYXRlOiBTZXB0ZW1iZXIsIDIwMTEgJm5ic3A7Jm5ic3A7VmVyc2lvbiByZXZpZXdlZDogNDwvZGl2PjxiciAvPlJldmlld2VkIGJ5OiBHZW9yZ2U8YnIgLz4iVGhpcyBwcm9kdWN0IGlzIHByZXR0eSBnb29kIG91dCBvZiB0aGUgYm94IGZlYXR1cmVzLiBXaXRoIG15IHJlcXVpcmVtZW50cywgSSBzdGlsbCBuZWVkIHRvIGN1c3RvbWl6ZSBhIGJpdC4gSSB0aGluayBpdCdzIGJldHRlciB0byBoYXZlIGNvbW1lbnQgaW4gdGhlIGNvZGUgZm9yIGN1c3RvbWl6YXRpb24gbmVlZC4gT3ZlcmFsbCwgaSBsaWtlIHRoZSBhcHBsaWNhdGlvbi4gSSB0aGluayBpdCdzIHZlcnkgZ29vZCBpZiB5b3UgcmVxdWlyZSBubyBjdXN0b21pemF0aW9uIHNpbmNlIHRoZXkgZG8gbm90IHN1cHBvcnQgY3VzdG9taXphdGlvbi4iPGJyIC8+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUdyZXkuZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxiciAvPjxkaXYgY2xhc3M9J2RhdGVWZXJzaW9uJz5SZXZpZXcgZGF0ZTogSmFudWFyeSwgMjAxMSAmbmJzcDsmbmJzcDtWZXJzaW9uIHJldmlld2VkOiA0PC9kaXY+PGJyIC8+UmV2aWV3ZWQgYnk6IG1hbm9qPGJyIC8+IlRoaXMgaXMgZ29vZCBpZiB5b3UgYXJlIGdvaW5nIGZvciB0aGUgb3V0IG9mIHRoZSBib3ggZmVhdHVyZXMuIEJ1dCBpZiB5b3Ugd2FudCB0byBtYWtlIGFueSBjdXN0b21pemF0aW9ucywgZG8gbm90IGV4cGVjdCBtdWNoIHN1cHBvcnQgZnJvbSBWZXZvY2FydCBzdXBwb3J0LiBUaGV5IGRvbid0IGV2ZW4gaGF2ZSBhIHRlY2huaWNhbCBzdXBwb3J0IGRvY3VtZW50IGZvciB0aGVpciBBUElzLiBJIHJlYWxseSBoYWQgYSBoYXJkIHRpbWUgdHJ5aW5nIHRvIGludGVncmF0ZSBhIHBheW1lbnQgZ2F0ZXdheSB3aXRoIFZldm9jYXJ0Lg0KDQpUaGVpciBjb2RlIGlzIGFsc28gbm90IGNvbW1lbnRlZCwgc28gaWYgeW91IHdhbm5hIGN1c3RvbWl6ZSBtYWtlIHN1cmUgeW91IGhhdmUgdGhlIHRpbWUgYW5kIHJlc291cmNlcyB0byBkbyB0aGF0LiI8YnIgLz48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFCbGFjay5naWYiIHdpZHRoPSIyMSIgaGVpZ2h0PSIyMSI+PGltZyBzcmM9Imh0dHA6Ly9jZG4uZWNvbW1lcmNlc3BvdC5jb20vaW1hZ2VzL2NhcnQxQmxhY2suZ2lmIiB3aWR0aD0iMjEiIGhlaWdodD0iMjEiPjxpbWcgc3JjPSJodHRwOi8vY2RuLmVjb21tZXJjZXNwb3QuY29tL2ltYWdlcy9jYXJ0MUJsYWNrLmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48aW1nIHNyYz0iaHR0cDovL2Nkbi5lY29tbWVyY2VzcG90LmNvbS9pbWFnZXMvY2FydDFHcmV5LmdpZiIgd2lkdGg9IjIxIiBoZWlnaHQ9IjIxIj48YnIgLz48ZGl2IGNsYXNzPSdkYXRlVmVyc2lvbic+UmV2aWV3IGRhdGU6IEp1bmUsIDIwMDk8L2Rpdj48YnIgLz48YSBocmVmPSIvcmV2aWV3LmFzcHg/Y2FydD1WZXZvQ2FydCIgcmVsPSJub2ZvbGxvdyIgc3R5bGU9ImZvbnQtc2l6ZToxLjJlbTtmb250LXdlaWdodDpib2xkOyI+QWRkIFlvdXIgT3duIFJldmlldzwvYT5kZAILDw8WAh8ABY4BUEEtRFNTIGNlcnRpZmllZC4gSGFzIGdyZWF0IHN1cHBvcnQgZm9yIG11bHRpcGxlIHN0b3JlZnJvbnRzIC0gRmFjZWJvb2ssIE1vYmlsZSBhbmQgZUJheSBpbnRlZ3JhdGlvbi4gR3JlYXQgZm9yIHRoZSBtb3JlIHByb2dyZXNzaXZlIG1lcmNoYW50IWRkAg0PDxYCHwAF4QI8IS0tIGNhLXB1Yi0wMDE4NDE3MzQ3NTAzMTA3L0Rvd25sb2FkQVNQQ2FydHNfNzI4eDkwIC0tPjxzY3JpcHQgYXN5bmMgc3JjPSIvL3BhZ2VhZDIuZ29vZ2xlc3luZGljYXRpb24uY29tL3BhZ2VhZC9qcy9hZHNieWdvb2dsZS5qcyI+PC9zY3JpcHQ+PGlucyBjbGFzcz0iYWRzYnlnb29nbGUic3R5bGU9ImRpc3BsYXk6aW5saW5lLWJsb2NrO3dpZHRoOjcyOHB4O2hlaWdodDo5MHB4ImRhdGEtYWQtY2xpZW50PSJjYS1wdWItMTcyMjA1MTgyODcyNDMzNyJkYXRhLWFkLXNsb3Q9IjMyODAyMDc3MzkiPjwvaW5zPjxzY3JpcHQ+KGFkc2J5Z29vZ2xlPXdpbmRvdy5hZHNieWdvb2dsZXx8W10pLnB1c2goe30pOzwvc2NyaXB0PmRkAg4PDxYCHwAFB1dpbmRvd3NkZAIPDw8WAh8ABQdBU1AuTkVUZGQCEA8PFgIfAAUKU1FMIFNlcnZlcmRkAhEPDxYCHwAFA1llc2RkAhIPDxYCHwAFA1llc2RkAhMPDxYCHwAFAk5vZGQCFA8PFgIfAAUCTm9kZAIVDw8WAh8ABQNZZXNkZAIWDw8WAh8ABQNZZXNkZAIXDw8WAh8ABQNZZXNkZAIYDw8WAh8ABQNZZXNkZAIZDw8WAh8ABQNZZXNkZAIaDw8WAh8ABQNZZXNkZAIbDw8WAh8ABQNZZXNkZAIcDw8WAh8ABQNZZXNkZAIdDw8WAh8ABQNZZXNkZAIeDw8WAh8ABQNZZXNkZAIfDw8WAh8ABQNZZXNkZAIgDw8WAh8ABQNZZXNkZAIiDw8WAh8ABeUCPCEtLSBjYS1wdWItMDAxODQxNzM0NzUwMzEwNy9Eb3dubG9hZEFTUENhcnRzXzcyOHg5MF9NaWQgLS0+PHNjcmlwdCBhc3luYyBzcmM9Ii8vcGFnZWFkMi5nb29nbGVzeW5kaWNhdGlvbi5jb20vcGFnZWFkL2pzL2Fkc2J5Z29vZ2xlLmpzIj48L3NjcmlwdD48aW5zIGNsYXNzPSJhZHNieWdvb2dsZSJzdHlsZT0iZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6NzI4cHg7aGVpZ2h0OjkwcHgiZGF0YS1hZC1jbGllbnQ9ImNhLXB1Yi0xNzIyMDUxODI4NzI0MzM3ImRhdGEtYWQtc2xvdD0iMzI4MDIwNzczOSI+PC9pbnM+PHNjcmlwdD4oYWRzYnlnb29nbGU9d2luZG93LmFkc2J5Z29vZ2xlfHxbXSkucHVzaCh7fSk7PC9zY3JpcHQ+ZGQCIw8PFgIfAAUDWWVzZGQCJA8PFgIfAAUDWWVzZGQCJQ8PFgIfAAUDWWVzZGQCJg8PFgIfAAUDWWVzZGQCJw8PFgIfAAUDWWVzZGQCKA8PFgIfAAUCTm9kZAIpDw8WAh8ABQNZZXNkZAIqDw8WAh8ABQNZZXNkZAIrDw8WAh8ABQNZZXNkZAIsDw8WAh8ABQNZZXNkZAItDw8WAh8ABQJOb2RkAi4PDxYCHwAFA1llc2RkAi8PDxYCHwAFA1llc2RkAjAPDxYCHwAFA1llc2RkAjEPDxYCHwAFA1llc2RkAjIPDxYCHwAFA1llc2RkAjMPDxYCHwAFA1llc2RkAjQPDxYCHwAFA1llc2RkAjUPDxYCHwAFA1llc2RkAjYPDxYCHwAFA1llc2RkAjcPDxYCHwAFA1llc2RkAjgPDxYCHwAFA1llc2RkAjoPDxYCHwAF6AI8IS0tIGNhLXB1Yi0wMDE4NDE3MzQ3NTAzMTA3L0Rvd25sb2FkQVNQQ2FydHNfNzI4eDkwX0JvdHRvbSAtLT48c2NyaXB0IGFzeW5jIHNyYz0iLy9wYWdlYWQyLmdvb2dsZXN5bmRpY2F0aW9uLmNvbS9wYWdlYWQvanMvYWRzYnlnb29nbGUuanMiPjwvc2NyaXB0PjxpbnMgY2xhc3M9ImFkc2J5Z29vZ2xlInN0eWxlPSJkaXNwbGF5OmlubGluZS1ibG9jazt3aWR0aDo3MjhweDtoZWlnaHQ6OTBweCJkYXRhLWFkLWNsaWVudD0iY2EtcHViLTE3MjIwNTE4Mjg3MjQzMzciZGF0YS1hZC1zbG90PSIzMjgwMjA3NzM5Ij48L2lucz48c2NyaXB0PihhZHNieWdvb2dsZT13aW5kb3cuYWRzYnlnb29nbGV8fFtdKS5wdXNoKHt9KTs8L3NjcmlwdD5kZAI7Dw8WAh8ABXU8YSByZWw9Im5vZm9sbG93IiBocmVmPSIvcmVwb3J0LmFzcHg/bmFtZT1WZXZvQ2FydCZ0eXBlPUNhcnQiPklzIHRoZXJlIGFuIGVycm9yIG9uIHRoaXMgcGFnZSBvciBhbiB1cGRhdGUgbmVlZGVkPzwvYT5kZAI8Dw8WAh8ABQsxNiBKYW4gMjAxNGRkAgEPDxYCHwAFrwQ8dWwgY2xhc3M9ImxhdGVzdCI+PGxpPjxhIGhyZWY9Ii9jYXJ0cy9ub3BDb21tZXJjZS5hc3B4Ij5ub3BDb21tZXJjZSBSZXZpZXcgICZyYXF1bzs8L2E+PC9saT48bGk+PGEgaHJlZj0iL2NhcnRzL0FzcERvdE5ldFN0b3JlZnJvbnQtbWwuYXNweCI+QXNwRG90TmV0U3RvcmVmcm9udCBNTDggUmV2aWV3ICAmcmFxdW87PC9hPjwvbGk+PGxpPjxhIGhyZWY9Ii9jYXJ0cy9BYmxlQ29tbWVyY2UuYXNweCI+QWJsZUNvbW1lcmNlIFJldmlldyAgJnJhcXVvOzwvYT48L2xpPjxsaT48YSBocmVmPSIvY2FydHMvQWJsZUNvbW1lcmNlLUFTUE5FVC5hc3B4Ij5BYmxlQ29tbWVyY2UgKEFTUC5ORVQpIFJldmlldyAgJnJhcXVvOzwvYT48L2xpPjxsaT48YSBocmVmPSIvY2FydHMvY2F0YWxvb2suYXNweCI+Q0FUQUxvb0submV0IFN0b3JlIFBybyBSZXZpZXcgICZyYXF1bzs8L2E+PC9saT48bGkgc3R5bGU9J21hcmdpbi10b3A6IDhweDsnPjxzdHJvbmc+PGEgaHJlZj0nL2FsbC1zaG9wcGluZy1jYXJ0cy5hc3B4Jz5BbGwgMjAwKyBzaG9wcGluZyBjYXJ0czwvYT48L3N0cm9uZz48L2xpPjwvdWw+ZGRkO8X3BR+w4nlTXKda5lgWSOXrEohD/ExRvxkK0UIcW2c=" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="0C1F84DE" />
        <div align="center">
            
    <div id="ads1" align="center">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Top -->
                <ins class="adsbygoogle"
                    style="display: block"
                    data-ad-client="ca-pub-1388311751127083"
                    data-ad-slot="8765540533"
                    data-ad-format="auto"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>

        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
Shopping Cart Details

                    </h2>
                </div>
                <div class="inpage">
                    
   
<script type="text/javascript">
    
function pop(anchor){

window.open('/glossarypop.aspx#' + anchor,'mywindow','width=400,height=200');
}
</script>

   <script type="text/javascript">
       var CurrentCartName = "VevoCart";
       var CurrentCartImage = "/img/cartlogo/vevocart.png";
     </script>

<div id="_ctl0_contentBody_hreviewmaster" class="hreview-aggregate">	
<!-- body master table -->
<table width="737" border="0" cellspacing="0" cellpadding="0" class="masterTable">
<tr>
	<td id="tBody">
   

    <span id="_ctl0_contentBody_lblHeading"><h1>VevoCart Community Review</h1></span>
    	<span id="_ctl0_contentBody_lblReview"><a href="/review.aspx?cart=VevoCart" rel="nofollow">Review this cart!</a></span>
    <br />
	<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Basic Information</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230" style="font-size: 120%"><strong>Company name</strong><div class="compQ"><a href="javascript:pop('companyname')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst" style="font-size: 120%">
				<strong><span id="_ctl0_contentBody_lblCompanyName"><a target="_blank" href="http://www.vevocart.com" onClick="_gaq.push(['_trackEvent','OutboundStores', 'Click', 'VevoCart Community']);">Vevo Systems., Ltd.</a></span></strong></td>
		</tr>
		<tr>
			<td class="compCol" style="font-size: 120%">Product name<div class="compQ"><a href="javascript:pop('productname')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst" style="font-size: 120%">
				<strong><span id="_ctl0_contentBody_lblProductName"><div class="item"><span class="fn">VevoCart Community</span></div></span></strong></td>
		</tr>
		<tr>
			<td class="compCol">Version<div class="compQ"><a href="javascript:pop('version')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblVersion">6.0</span></td>
		</tr>
		<tr>
			<td class="compCol">Sample customer sites<div class="compQ"><a href="javascript:pop('sample1')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSample1"><a rel="nofollow" target="_blank" href="http://www.energyclub.com/">http://www.energyclub.com/</a></span><br />
				<span id="_ctl0_contentBody_lblSample2"><a rel="nofollow" target="_blank" href="http://www.aquadux.co.uk/">http://www.aquadux.co.uk/</a></span><br />
				<span id="_ctl0_contentBody_lblSample3"><a rel="nofollow" target="_blank" href="http://www.discountdirectflooring.com/">http://www.discountdirectflooring.com/</a></span>
				</td>
		</tr>
		<tr>
			<td class="compCol">Price<div class="compQ"><a href="javascript:pop('price')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPrice">Free</span></td>
		</tr>
		<tr>
			<td class="compCol">Average review score<div class="compQ"><a href="javascript:pop('reviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReviewScore"><div class="rating"><span class="average"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" title="3 star rating" alt="3 star rating"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif">Average: 3</span></div>(<span class="count">18</span>)</span></td>
		</tr>
		<tr>
			<td class="compCol" valign=top>User reviews<div class="compQ"><a href="javascript:pop('reviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReviews">Reviewed by: Grant Cardwell<br />"Buying vevocart was the worst thing I did. After selecting this for a client, we couldn't get it to work, when we did, it was slow, overcomplicated, paypal failed to work. Contacting support was entirely useless, half the time they didn't understand what I was asking, when they did they made pointless responses and it doesn't feel like they know the system at all. Do yourself a Favour buy something else. "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: November, 2015 &nbsp;&nbsp;Version reviewed: 4</div><br />Reviewed by: influenceuk<br />"I purchased this solution to use for one of my clients, i must say the whole experience has been a terrible experience for both of us!

The support are useless, and dont even know their own product. After sales are very rude and are not willing to help. With constant errors, and issues happening at almost every turn! Most of the issues faced i have had to resolve myself, and then more issues popped up! This is very poorly coded, and is not even worth your time considering.

For $300 you would expect a little more from the solution however if your looking for a reliable solution, AVOID this at all costs!!

Issues faced
- Paypal erroring, or not redirecting to payment screen.
- Offline Credit card payments erroring if CVV option is enabled (this is due to their VevoPay addon not allowing CVV to be stored)
- Random Database crashes
- Site downtime
- Server Crashes

These are just some of the issues faced, having to actually re-write code to get things working as they should is not an acceptable support reply!!"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: October, 2015 &nbsp;&nbsp;Version reviewed: 4</div><br />Reviewed by: Frustrated<br />"
 Getting your Site up and running will be a challenge.  Web support is minimal. You will be on your own.  "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2015 &nbsp;&nbsp;Version reviewed: 4</div><br />Reviewed by: Jeff<br />"I specifically decided on a particular hosting solution because they offered VevoCart. I paid for the first year ($229) and within that first year was unable to find the time to get the store up and running (business issues, family problems). Nobody's fault but my own, but then I renewed ($90) in the hopes of finally getting to get my store up and running only to find that out that my hosting solution dropped VevoCart. I tried to get just the renewal money back from VevoCart, but they will not issue a refund for the renewal! Ultimately, I paid for a product I never got to use. I would not recommend VevoCart or the hosting solution that I am also planning to leave, EasyCGI (formerly, WebStrike)."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: March, 2015 &nbsp;&nbsp;Version reviewed: 4</div><br />Reviewed by: eastlife<br />"I am very impressive about this software. It provide a lot of important feature for online store but it's free. I like product lightbox feature that help my customer don't need to go back to product list page when they have already seen product detail. I think this advantage increase chance of represent product in my store. At last I wanna say vevocart is worthy to try.  "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: August, 2013 &nbsp;&nbsp;Version reviewed: 6.0</div><br />Reviewed by: ksan<br />"This cart is junk. Lots of errors. Poor support. Poor documentation  "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: July, 2013 &nbsp;&nbsp;Version reviewed: 6.0</div><br />Reviewed by: Diana<br />"I really like VevoCart. They have all the tools I need. I like how they provide several useful product features for a customer to play with. Quick view is a great way to make the site look modern, layered navigation is really essential in filtering down a catalog by product attributes. There are also various marketing features ; coupon feature, quantity discount, gift certificate, and promotion group, just to name a few. their supports are quire responsive, and lastly, the license price is reasonable."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: July, 2013 &nbsp;&nbsp;Version reviewed: 6.0</div><br />Reviewed by: Chonrudee<br />"The storefront’s design is pretty good. I am able to change to css to have my preferred color.  The features are really plenty for a free software.

       thanks for giving this. Oh... It would be nice if the top menu style is configurable. I need some time to find out how to change top menu as a dropdown style.

      it turns out I would need to make a code change even though it’s posted in the forum but it’s much better to make it configurable. The browsing feature is really nice.

      Visitors are able to narrow down the search using filtering options on the left. good software."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: July, 2013 &nbsp;&nbsp;Version reviewed: 6.0</div><br />Reviewed by: PuppLE<br />"VevoCart store is rich in features.   I like the fact that there is a built-in image slider  but they should also add the language change function.
 
I really like the back office design. It’s modern and user-friendly. I am able to manage my store without programming knowledge.
I wish to see more skins since I can not create a skin myself."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: July, 2013 &nbsp;&nbsp;Version reviewed: 6.0</div><br />Reviewed by: Paula<br />"I’m one of the Vevocart users using version 6. I feel that this e-commerce solution is worth using. I am able to set up my store within a few days. The application runs stably.  When I had a problem with setting up a layout, the support guys help me solving my problems.  Laslty, I like that it provides a source code for customization. I hired my developer to have a little customization for my store and we think that it’s quite flexible.   "<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: April, 2013 &nbsp;&nbsp;Version reviewed: 5.3</div><br />Reviewed by: Jay<br />"Purchased back in 2011.. both providers commented on how hard it was to install.. there have been numerous errors and the c# programmer I hired has commented on how poorly the code is written. DON'T BUY!"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: March, 2013 &nbsp;&nbsp;Version reviewed: 5.3</div><br />Reviewed by: Mehmethan<br />"I have been working in IT sector for fourteen years. I have so many specialties such as Web Development (C#, VB), System Integration, Consultancy etc. As an IT Solution and Service provider companies owner, my policy to choose the best IT companies in their field as our partner. I do customized ASP.NET solutions and tools for our clients, but we need a cool Asp .Net shopping software.  I have tested so many ASP.NET shopping software and e-commerce in the market and i realized that Vevocart is one of those worth mentioning ASP.NET e-commerce solution. My Customers are very happy from our e-commerce development services (VevoCart based e-commerce solutions). It’s cheap, easy to install, flexible, customizable, secure and reliable. And perhaps the most important thing is when you need help VevoCart has a very good support. Thank you VevoCart to facilitate and brace our e-commerce development services. 

My Certifications: PMP, MCDBA, C# Developer, MS Sharepoint Developer, MCSE-S, VCP, VSP, VTSP etc. 
"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: July, 2012 &nbsp;&nbsp;Version reviewed: 5.3</div><br />Reviewed by: Amer<br />") I'm a C# developer as well as running a small business.  I started writing shopping carts for my clients few years back.  My clients were small clients those were looking for customized shopping cart solutions at a price that they could afford.  I sooner realized that the price I receive from my clients for writing and maintaining customized shopping carts is too small comparing to number of hours I spend on those projects.  I then started looking for 3rd party shopping carts that require minimum coding effort and allow customization as per my client needs.  I faced two problems during my search.  First, there were not much ASP.Net shopping carts available.
Second, the available shopping carts did not provide customized solutions or they were missing features required by my clients.  Then I found VevoCart.
I was so happy after I used this that I cannot find words to describe this.
I have never found a shopping cart, except VevoCart, that provides so many options of customization with large number of features at a price that is absolutely affordable.  My coding effort has reduced to just 25% now using VevoCart and I've never found a scenario where a feature was requested by my client that was missing in VevoCart or I couldn't do it in VevoCart using its available source code.  At the same time I want to suggest that next versions of VevoCart should focus on making Front-end and Back-end more loosely coupled.  Sometime I've feeling that VevoCart front-end is integrated with back-end in such a way that if some of my client someday requires a front-end design that is totally different than the layout VevoCart templates provide it'll be a difficult task to achieve.
"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2012 &nbsp;&nbsp;Version reviewed: 5.3</div><br />Reviewed by: Neil<br />"
I must say that VevoCart is  the feature-rich shopping cart. It includes all features i require especially seo & marketing tool. I switch from an outdated asp cart and it runs much faster. I am able to start my store in 2 weeks. At first, i do not know that a VevoCart license already includes VevoPay, the support staff helps me set it all up quickly. The GUI is fairly intuitive , i am able to administer the site myself. Also, I really like that fact that it's SEO friendly unlike asp cart i used in the past. I do not need to hire a developer to rewrite URL, i do not need to purchase adds on for a feature.

VevoCart URL is seo friendly. Meta title and description are configurable and automatic populate. Lastly, all features are included , no adds on required.  I truly recommend VevoCart to anyone.
"<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2012 &nbsp;&nbsp;Version reviewed: 5.3</div><br />Reviewed by: Chris<br />"Five years ago we were looking for an affordable shopping cart solution. One of the requirements for the solution was that it needed to include the source code, be written in C# and have a clean separation of the UI and code behind. After an exhaustive search, which included many of the top carts at the time, we determined that VevoCart met all our needs.

Over the past five years, we have been able to grow our website as our needs have increased. This would not have been possible had VevoCart not been written so well. It’s various controls and modules are easy to find/understand and, if needed, alter to fit our business need. For our website, we were able to completely reskin the solution yet still keep all the underlying VevoCart functionality.  Being able to do this, without comprising functionality, really illustrates the robustness of this solution. Other great attributes of the solution: easy payment portal integration and the simple product and option management. 

Overall, the great thing about this solution is that it gives you a lot of flexibility in regards to how much customization you want to put into your website. You can run straight out of the box, utilizing the many templates they have available or dive into the code, altering whatever is needed to fit your website’s needs."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: May, 2012 &nbsp;&nbsp;Version reviewed: 5.3</div><br />Reviewed by: Eric<br />"It's been a pain in the butt to install, but overall I've been able to do it either myself or with the prompt (and, unfortunately, generally right) aide of customer service.  I've been able to work out quite a bit of it.  I don't reccommend it for anyone that doesn't know what they're doing, but if you're willing to mess around with it for a couple of hours to get it going, it appears to be a pretty solid project.  I just wish that they did a little bit better on separating the multi-edition as well as relying on AJAX less."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: September, 2011 &nbsp;&nbsp;Version reviewed: 4</div><br />Reviewed by: George<br />"This product is pretty good out of the box features. With my requirements, I still need to customize a bit. I think it's better to have comment in the code for customization need. Overall, i like the application. I think it's very good if you require no customization since they do not support customization."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: January, 2011 &nbsp;&nbsp;Version reviewed: 4</div><br />Reviewed by: manoj<br />"This is good if you are going for the out of the box features. But if you want to make any customizations, do not expect much support from Vevocart support. They don't even have a technical support document for their APIs. I really had a hard time trying to integrate a payment gateway with Vevocart.

Their code is also not commented, so if you wanna customize make sure you have the time and resources to do that."<br /><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Black.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><img src="http://cdn.ecommercespot.com/images/cart1Grey.gif" width="21" height="21"><br /><div class='dateVersion'>Review date: June, 2009</div><br /><a href="/review.aspx?cart=VevoCart" rel="nofollow" style="font-size:1.2em;font-weight:bold;">Add Your Own Review</a></span></td>
		</tr>
		
		
		<tr>
			<td class="compCol" valign=top>
				Ecommerce Spot Comments
			</td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblComments">PA-DSS certified. Has great support for multiple storefronts - Facebook, Mobile and eBay integration. Great for the more progressive merchant!</span>
			</td>
		</tr>
			
		
		
		
		</table>

<div style="margin: 5px 0 5px -20px;">

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=VevoCart" target="_blank" > <img src="/img/scebanners/set2/728x90.png" /> </a> 
</div>


    
</div>
		
		<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Technology</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Supported operating systems<div class="compQ"><a href="javascript:pop('os')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblOperatingSystem">Windows</span></td>
		</tr>
		<tr>
			<td class="compCol">Language<div class="compQ"><a href="javascript:pop('lang')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLanguage">ASP.NET</span></td>
		</tr>
		<tr>
			<td class="compCol">Database<div class="compQ"><a href="javascript:pop('db')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblDatabase">SQL Server</span></td>
		</tr>
		<tr>
			<td class="compCol">Source code<div class="compQ"><a href="javascript:pop('sourcecode')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSourceCode">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Reseller discounts<div class="compQ"><a href="javascript:pop('reseller')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblReseller">Yes</span></td>
		</tr>
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Features</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Product limit<div class="compQ"><a href="javascript:pop('productlimit')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblProductlimit">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Category limit<div class="compQ"><a href="javascript:pop('categorylimit')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCategoryLimit">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Multi-language<div class="compQ"><a href="javascript:pop('multilanguage')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblMultilanguage">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Gift certificates<div class="compQ"><a href="javascript:pop('giftcertificates')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblGiftcertificates">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Loyalty program<div class="compQ"><a href="javascript:pop('loyalty')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLoyalty">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Email merchant on order<div class="compQ"><a href="javascript:pop('emailorder')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblEmailOrder">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Affiliates program<div class="compQ"><a href="javascript:pop('affiliates')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblAffiliates">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Site search<div class="compQ"><a href="javascript:pop('sitesearch')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSiteSearch">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Search optimization tools<div class="compQ"><a href="javascript:pop('seotools')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSeotools">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Product reviews<div class="compQ"><a href="javascript:pop('productreviews')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblProductreviews">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Newsletters<div class="compQ"><a href="javascript:pop('newsletters')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblNewsletters">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Discount coupons<div class="compQ"><a href="javascript:pop('discountcoupons')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblDiscountcoupons">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Customer registrations<div class="compQ"><a href="javascript:pop('customerregistration')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCustomerregistration">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Wish list<div class="compQ"><a href="javascript:pop('wishlist')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWishlist">Yes</span></td>
		</tr>
		</table>
<div style="margin: 5px 0 5px -20px;">

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=VevoCart" target="_blank" > <img src="/img/scebanners/set2/728x90.png" /> </a> 
</div>


    
</div>
		<table border=0 cellspacing=2 cellpadding=5 class="compTable" width=650>	
		
		<tr>
			<td colSpan="2">
				<h2 class="compHeader">Shipping</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol" width="230">Shipping price range<div class="compQ"><a href="javascript:pop('pricerangeshipping')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblpricerangeshipping">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Shipping weight range<div class="compQ"><a href="javascript:pop('weightrangeshipping')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWeightrangeshipping">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">UPS lookup<div class="compQ"><a href="javascript:pop('upslookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblUpslookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">USPS lookup<div class="compQ"><a href="javascript:pop('uspslookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblUspslookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Fedex lookup<div class="compQ"><a href="javascript:pop('fedexlookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblFedexlookup">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Canada Post lookup<div class="compQ"><a href="javascript:pop('canadapostlookup')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCanadapostlookup">No</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Tax &amp; Payment</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Tax by state<div class="compQ"><a href="javascript:pop('taxbystate')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblTaxbystate">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Tax by country<div class="compQ"><a href="javascript:pop('taxbycountry')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblTaxbycountry">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">PayPal<div class="compQ"><a href="javascript:pop('paypal')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPaypal">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Authorize.Net<div class="compQ"><a href="javascript:pop('authorizenet')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblAuthorizenet">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Verisign<div class="compQ"><a href="javascript:pop('verisign')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblVerisign">No</span></td>
		</tr>
		<tr>
			<td class="compCol">Worldpay<div class="compQ"><a href="javascript:pop('worldpay')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblWorldpay">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Secure Trading<div class="compQ"><a href="javascript:pop('securetrading')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSecuretrading">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Others<div class="compQ"><a href="javascript:pop('others')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblOthers">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Non credit card options<div class="compQ"><a href="javascript:pop('nonccoptions')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblNonccoptions">Yes</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Support</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Customer forums<div class="compQ"><a href="javascript:pop('customerforums')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblCustomerforum">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Free support<div class="compQ"><a href="javascript:pop('freesupport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblFreeSupport">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Paid support<div class="compQ"><a href="javascript:pop('paidsupport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblPaidsupport">Yes</span></td>
		</tr>
		<tr>
			<td colSpan="2" width="230">
				<h2 class="compHeader">Reports</H2>
			</td>
		</tr>
		<tr>
			<td class="compCol">Sales reports<div class="compQ"><a href="javascript:pop('salesreport')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblSalesreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Search reports<div class="compQ"><a href="javascript:pop('searchreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_Lblsearchreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Low stock reports<div class="compQ"><a href="javascript:pop('lowstockreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblLowstockreports">Yes</span></td>
		</tr>
		<tr>
			<td class="compCol">Inventory reports<div class="compQ"><a href="javascript:pop('inventoryreports')"><img src="http://cdn.ecommercespot.com/images/question.gif" width="13" height="18" alt="Help" border="0"></a></div></td>
			<td class="compFirst">
				<span id="_ctl0_contentBody_lblInventoryreports">Yes</span></td>
		</tr>
	</table>
	<p>&nbsp;</p>
<div style="margin: 5px 0 5px -20px;">	

    

<div id ="adbanner" style="text-align:center">
    <a href="https://www.shoppingcartelite.com/?source=ecommercespot&adnetwork=banner&adcreative=VevoCart" target="_blank" > <img src="/img/scebanners/set2/728x90.png" /> </a> 
</div>


    
</div>
		<span id="_ctl0_contentBody_lblReport"><a rel="nofollow" href="/report.aspx?name=VevoCart&type=Cart">Is there an error on this page or an update needed?</a></span><br /><br />
	<span style="color: #ddd; font-size: 80%;"><p>Last updated:
		<span id="_ctl0_contentBody_lblReviewedDate">16 Jan 2014</span><br /><br /></p></span>


		

</td>
<td align=left width=1 id="cart_gads">



	</td>
</tr>
</table>
</div>


<div id="upNext" style ="display:none;">
<div style="width:310px;"><h6>More Reviews</h6>
<span id="_ctl0_contentBody_lblCrossLinks"><ul class="latest"><li><a href="/carts/nopCommerce.aspx">nopCommerce Review  &raquo;</a></li><li><a href="/carts/AspDotNetStorefront-ml.aspx">AspDotNetStorefront ML8 Review  &raquo;</a></li><li><a href="/carts/AbleCommerce.aspx">AbleCommerce Review  &raquo;</a></li><li><a href="/carts/AbleCommerce-ASPNET.aspx">AbleCommerce (ASP.NET) Review  &raquo;</a></li><li><a href="/carts/catalook.aspx">CATALooK.net Store Pro Review  &raquo;</a></li><li style='margin-top: 8px;'><strong><a href='/all-shopping-carts.aspx'>All 200+ shopping carts</a></strong></li></ul></span>
</div></div>


                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
