

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	AmeriCommerce indepth review
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<meta name="Description" content="AmeriCommerce indepth review"></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./AmeriCommerce-Review.aspx?sArticlename=AmeriCommerce-Review" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTExODI3Mzg0NjMPZBYCZg9kFgICAw9kFgQCAQ9kFgICAQ9kFgICAQ8PFgIeBFRleHQFHEFtZXJpQ29tbWVyY2UgaW5kZXB0aCByZXZpZXdkZAICD2QWBmYPDxYCHwAFHTxoMT5BbWVyaUNvbW1lcmNlIFJldmlldzwvaDE+ZGQCAQ8PFgIfAAWKVjxzY3JpcHQgbGFuZ3VhZ2U9IkphdmFzY3JpcHQiPiANCjwhLS0NCgkJZnVuY3Rpb24gUG9wdXBQaWMoc1BpY1VSTCkgeyANCgkJd2luZG93Lm9wZW4oIi9wb3B1cC5odG1sPyIrc1BpY1VSTCwgIiIsICJyZXNpemFibGU9MSxIRUlHSFQ9MjUwLFdJRFRIPTMwMCIpOw0KCQl9DQovLyAtLT4NCg0KPC9zY3JpcHQ+DQoNCjxwPkhhdmluZyBiZWVuIHRocm91Z2ggdGhlIHNlYXJjaCBvZiBhIHNob3BwaW5nIGNhcnQgc29sdXRpb24gDQppbiB0aGUgcGFzdCwgSSB2YWx1ZWQgaW5wdXQgYWJvdXQgZGlmZmVyZW50IHNvbHV0aW9ucywgZXNwZWNpYWxseSBmcm9tIG90aGVyIA0Kc3RvcmVvd25lcnMgd2hvIGhhZCB1c2VkIHRoZSBwcm9kdWN0LiBJIGhhdmUgc2luY2Ugc3RhcnRpbmcgb3V0IGNoYW5nZWQgbXkgDQpzb2x1dGlvbiBwcm92aWRlciBvbmNlIGFuZCBJIGFtIG5vdyB1c2luZyBBbWVyaUNvbW1lcmNlLiBJIG1hbmFnZSB0d28gd2Vic2l0ZXMgDQpvbiB0aGUgQW1lcmlDb21tZXJjZSBwbGF0Zm9ybTogDQo8YSBocmVmPSJodHRwOi8vd3d3LnBpcHBpbm1jZ2VlLmNvbSI+UGlwcGluIE1jR2VlIOKAkyBhIGNoaWxkcmVu4oCZcyBmdXJuaXR1cmUgc3RvcmU8L2E+IHNpbmNlIEZlYiAyMDA3IA0KYW5kIDxhIGhyZWY9Imh0dHA6Ly93d3cub212aWxsYWdlLmNvbSI+T20gVmlsbGFnZSDigJMgYSBtZXRhcGh5c2ljYWwgYW5kIGhlYWxpbmcgDQphcnQgc3RvcmU8L2E+DQp3aGljaCBJIG1vdmVkIG92ZXIgdG8gQW1lcmlDb21tZXJjZSBpbiBOb3YgMjAwNy48L3A+DQo8cD5BZnRlciBoYXZpbmcgdXNlZCBpdCBmb3IgOS0xMCBtb250aHMgbm93LCBJIGJlbGlldmUgSSBoYXZlIA0KZm91bmQgYSBwcm9kdWN0IHRoYXQgbWVldHMgbXkgbG9uZy10ZXJtIGJ1c2luZXNzIG5lZWRzIGFuZCBJ4oCZZCBsaWtlIHRvIHNoYXJlIG15IA0KZXhwZXJpZW5jZSBhbmQgZGVzY3JpYmUgc29tZSBvZiB0aGUgZmVhdHVyZXMgaW4gc29tZSBkZXB0aC4gSSBob3BlIHRoaXMgYXJ0aWNsZSANCmdpdmVzIHlvdSBzb21lIGluc2lnaHQgaW50byB0aGUgc29sdXRpb24gZnJvbSBhIHVzZXIgcGVyc3BlY3RpdmUgdG8gZ2F1Z2UgaWYgDQp0aGlzIHNvbHV0aW9uIG1pZ2h0IG1lZXQgeW91ciBidXNpbmVzcyBuZWVkcy48L3A+DQo8aDM+SW5zdGFsbGF0aW9uL1N0YXJ0IFVwIHByb2Nlc3M8L2gzPg0KPHA+QW1lcmlDb21tZXJjZSBvZmZlcmVkIGEgMTQgZGF5IGZyZWUgdHJpYWwgKHdpdGhvdXQgYSBjcmVkaXQgDQpjYXJkKSBhbmQgdGhhdCBoZWxwZWQgbWUganVtcCBpbnRvIHRoZSBiYWNrZW5kIGFuZCByZXZpZXcgdGhlIGZlYXR1cmVzLiBPbmNlIEkgDQpmb3VuZCBpdCBoYWQgYWxsIHRoZSBjb3JlIGZlYXR1cmVzIEkgbmVlZGVkIEkgdGFsa2VkIHdpdGggdGhlbSBhYm91dCBzb21lIA0KZmVhdHVyZXMgd2UgbmVlZGVkIGN1c3RvbSBkZXZlbG9wZWQgYW5kIHRoZXkgd2VyZSB0aGUgb25seSBlY29tbWVyY2Ugc29sdXRpb24gDQpwcm92aWRlcnMgd2lsbGluZyB0byBkbyBjdXN0b20gZmVhdHVyZSBkZXZlbG9wbWVudC4gVGhlIHNpZ24gdXAgYW5kIHN0YXJ0dXAgDQpwcm9jZXNzIHdhcyBzaW1wbGUuPC9wPg0KPGgzPkRlc2lnbi9DdXN0b21pemluZy9PbmUgUGFnZSBDaGVja291dCAtIHVzYWJpbGl0eSBmYWN0b3JzPC9oMz4NCjxwPkNvbnRyb2wgb3ZlciA5NSUgb2YgdGhlIGRlc2lnbiBlbGVtZW50cy4gSWYgeW91IGtub3cgSFRNTCwgDQpDU1MgYW5kIGJhc2ljIEphdmFTY3JpcHQg4oCTIHlvdSBjYW4gZ28gYW55d2hlcmUgeW91IGxpa2Ugd2l0aCB5b3VyIGRlc2lnbi4mbmJzcDsgSWYgDQp5b3UgZG9u4oCZdCwgeW91IGNhbiBzdGlsbCBoYXZlIGEgdmVyeSBwcm9mZXNzaW9uYWwgbG9va2luZyB3ZWJzaXRlLg0KPGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvVGhlbWVTZXR0aW5ncy5qcGcnKSI+PGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvVGhlbWVTZXR0aW5ncy5qcGciIHdpZHRoPSIyMjUiIGhlaWdodD0iMTU2IiBhbGlnbj0icmlnaHQiPjwvYT48L3A+DQo8cD5UaGUgcGFydCBJIGZvdW5kIG1vc3QgdXNlZnVsIHdhcyBvbiB0aGUgcHJvZHVjdCBkZXRhaWxzIA0KcGFnZSwgSSBjb3VsZCBjdXN0b21pemUgdGhlIGVsZW1lbnRzIGZyb20gYSB1c2FiaWxpdHkgYW5kIGNvbnZlcnNpb24gDQpwZXJzcGVjdGl2ZS4gSSB3YXMgYWJsZSB0byBhZGQgdGhlIHJpZ2h0IGhhbmQgc2lkZSBjb2x1bW4gd2l0aCBhIOKAmG1heSB3ZSBoZWxwIA0KeW914oCZIHNlY3Rpb24gc28gdGhlIGJ1eWVyIGhhcyBpbW1lZGlhdGUgYWNjZXNzIHRvIGl0IGFuZCBjYW4gZ2V0IHF1ZXN0aW9ucyANCmFuc3dlcmVkIHJpZ2h0IGF3YXkuIDwvcD4NCjxwPkFub3RoZXIgZmVhdHVyZSB3aGljaCBpcyBrZXkgdG8gb3VyIHN1Y2Nlc3MgaXMgdGhlIGFiaWxpdHkgDQp0byBkaXNwbGF5IGhpZ2ggcmVzb2x1dGlvbiBwcm9kdWN0IGltYWdlcy4gV2Ugc2VsbCBjaGlsZHJlbuKAmXMgZnVybml0dXJlIGFuZCBpdCANCmlzIGltcG9ydGFudCBmb3Igb3VyIGN1c3RvbWVycyB0byBiZSBhYmxlIHRvIHNlZSB0aGUgZnVybml0dXJlIGluIGdyZWF0IGRldGFpbC4gDQpTY2VuZTcgY2FuIGJlIHByb2hpYml0aXZlIGF0ICQxMCwwMDAgYSB5ZWFyIChhdCB0aGUgdGltZSBvZiBvdXIgaW5xdWlyeSkgZm9yIA0Kc21hbGwgYnVzaW5lc3Nlcy4gSGF2aW5nIHRoZSBhYmlsaXR5IHRvIGRpc3BsYXkgaGktcmVzIGltYWdlcyBpbnRlZ3JhdGVkIGludG8gDQp0aGUgc3RhbmRhcmQgc29sdXRpb24gaGFzIGJlZW4gYSBodWdlIHNhdmluZyE8L3A+DQo8cD5UbyB2aXN1YWxseSBzZWUgdGhlIGFib3ZlIG1lbnRpb25lZCBmZWF0dXJlcyAobWF5IHdlIGhlbHAgDQp5b3UsIHpvb21pbmcgaW50byBhIGhpLXJlcyBpbWFnZSkgdGFrZSBhIGxvb2sgYXQgb3VyIA0KPGEgaHJlZj0iaHR0cDovL3d3dy5waXBwaW5tY2dlZS5jb20vc3RvcmUvcC8xNDc1LUwtU2hhcGVkLUJpLUxvZnQtQmVkLURlZXItUnVuLVNlcmllcy1ieS1MZWEuYXNweCI+DQpMZWEgRnVybml0dXJlLCBsb2Z0IGJlZCBwYWdlPC9hPi48L3A+DQo8cD5PbmUgcGFnZSBjaGVja291dCBpcyBidWlsdCBpbiBhbmQgYSBnb29kIHVzYWJpbGl0eSBhbmQgDQpjb252ZXJzaW9uIHN0YW5kYXJkLiBUaGlzIGZlYXR1cmUgaXMgbm90IHVuaXF1ZSB0byBBbWVyaUNvbW1lcmNlLiBJdOKAmXMgYSANCnN0YW5kYXJkLiBUaGV5IG9mZmVyIGVhc3kgaW50ZWdyYXRpb24gd2l0aCBQYXlwYWwgYXMgYW4gYWx0ZXJuYXRlIGNoZWNrb3V0IA0Kb3B0aW9uLiBHb29nbGUgY2hlY2tvdXQgaXMgbm90IHlldCBpbnRlZ3JhdGVkLCBidXQgaW4gdGhlIHdvcmtzIGFuZCBzaG91bGQgYmUgDQpyb2xsZWQgb3V0IHNob3J0bHkuIFRoaXMgaXMgYSBrZXkgZmVhdHVyZSBhbmQgSSB3b3VsZCBoYXZlIGxpa2VkIHRvIGhhdmUgc2VlbiBpdCANCnJvbGxlZCBvdXQgc29vbmVyLjwvcD4NCjxoMz5Qcm9kdWN0IE1hbmFnZW1lbnQ8L2gzPg0KPHA+QW1lcmlDb21tZXJjZSBoYXMgYm90aCwgYSBzaW1wbGUgYnV0IGRldGFpbGVkIG1hbnVhbCANCnByb2R1Y3QgbWFuYWdlbWVudCBpbnRlcmZhY2UgYW5kIGEgdmVyeSBkZXRhaWxlZCBzcHJlYWRzaGVldC4gVGhpcyBvbmNlIGFnYWluLCANCmlzIHN0YW5kYXJkIGluIG1hbnkgc2hvcHBpbmcgY2FydHMuIFRoZSBwYXJ0IEkgaGF2ZSBub3Qgc2VlbiBvbiBzb21lIG9mIHRoZSANCm90aGVyIGNhcnRzIGJ1dCBmaW5kIHZlcnkgdXNlZnVsIGluIEFtZXJpQ29tbWVyY2UgaXM6PC9wPg0KPG9sPg0KCTxsaT7igJhMaXZlIERlc2lnbuKAmSDigJMgd2hlbiBJ4oCZbSBsb2dnZWQgaW4gYW5kIGJyb3dzaW5nIG15IHdlYnNpdGUsIGlmIEkgbmVlZCB0byANCmNoYW5nZSBzb21ldGhpbmcgb3V0IHF1aWNrbHksIEkgY2FuIGVkaXQgdGhlIGNhdGVnb3J5LCBtYW51ZmFjdHVyZXIsIHByb2R1Y3QgDQpkZXRhaWxzIHJpZ2h0IGZyb20gdGhlcmUgd2l0aCB0aGUgY2xpY2sgb2YgYSBidXR0b24uDQo8L2xpPg0KPGxpPk1hc3MgRWRpdG9yIHdpdGggZmlsdGVyaW5nIG9wdGlvbnMg4oCTIGFsdGhvdWdoIG1hc3MgcHJvZHVjdCBlZGl0aW5nIGlzIG5vdCANCnVuY29tbW9uLCBBbWVyaUNvbW1lcmNlIGFsbG93cyBmaWx0ZXJpbmcgb2YgcHJvZHVjdHMgYnkgY2F0ZWdvcnksIHN1YmNhdGVnb3J5IA0KYW5kIG1hbnVmYWN0dXJlci4gQW55IHRpbWUgYSBtYW51ZmFjdHVyZXIgY2hhbmdlcyBwcm9kdWN0IHByaWNpbmcsIHNoaXBwaW5nIHRpbWUgDQpldGMg4oCTIGhhdmluZyB0aGUgbWFudWZhY3R1cmVyIGZpbHRlciBpcyBleHRyZW1lbHkgdXNlZnVsIGluIHF1aWNrIHByb2R1Y3QgDQp1cGRhdGVzLjwvbGk+PC9vbD4NCjwvc3Bhbj4NCjxhIGhyZWY9ImphdmFzY3JpcHQ6UG9wdXBQaWMoJy9hcnRpY2xlaW1hZ2VzL1NuYXBzaG90LUxpdmUtRGVzaWduLVByb2R1Yy5qcGcnKSI+PGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvU25hcHNob3QtTGl2ZS1EZXNpZ24tUHJvZHVjLmpwZyIgd2lkdGg9IjIyNSIgaGVpZ2h0PSIyMzciPjwvYT4NCjxhIGhyZWY9ImphdmFzY3JpcHQ6UG9wdXBQaWMoJy9hcnRpY2xlaW1hZ2VzL1NuYXBzaG90LUxpdmUtRGVzaWduX1Byb2R1Yy5qcGcnKSI+PGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvU25hcHNob3QtTGl2ZS1EZXNpZ25fUHJvZHVjLmpwZyIgd2lkdGg9IjIyNSIgaGVpZ2h0PSIxMzIiPjwvYT48cD5UaGVyZSBhcmUgc2V2ZXJhbCB3YXlzIHRvIG1hc3MgDQplZGl0IHByb2R1Y3RzIHdpdGggc3ByZWFkc2hlZXRzLCBidXQgaXQgaXMgaGVscGZ1bCB0byBoYXZlIGEgdmVyeSB1c2VyLWZyaWVuZGx5IA0KaW50ZXJmYWNlIGZvciBxdWljayBlZGl0cyBhbmQgYWxzbyB0byB0cmFpbiBub24tdGVjaG5pY2FsIGFuZCBjdXN0b21lciBzZXJ2aWNlIA0Kc3RhZmYgdG8gdXNlIHRoaXMgaW50ZXJmYWNlIGZvciBxdWljayBlZGl0cy48L3A+DQo8aDM+U0VPPC9oMz4NCjxwPiANCjxhIGhyZWY9ImphdmFzY3JpcHQ6UG9wdXBQaWMoJy9hcnRpY2xlaW1hZ2VzL1NpdGVFeHBsb3Jlci5qcGcnKSI+PGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvU2l0ZUV4cGxvcmVyLmpwZyIgd2lkdGg9IjIyNSIgaGVpZ2h0PSIxNjAiIGFsaWduPSJyaWdodCI+PC9hPlZlcnkgU0VPIGZyaWVuZGx5LiBQcm92aWRlcyBmb3IgDQptZXRhIHRhZ3MsIHBhZ2UgdGl0bGVzLCBjdXN0b20gVVJMcyBmb3IgYWxsIHBhZ2VzIChjYXRlZ29yeSwgc3ViLWNhdGVnb3J5LCANCnByb2R1Y3QgZGV0YWlscywgbWFudWZhY3R1cmVyIGFuZCBjb250ZW50IHBhZ2VzKSwgMzAxIHJlZGlyZWN0cywgYW5kIGV4dHJlbWVseSANCmVhc3kgdG8gYWRkIGNvbnRlbnQgdG8gYWxsIHRoZSBwYWdlcy4mbmJzcDsgPC9wPg0KPHA+T24gb3VyIGNhdGVnb3J5IHBhZ2VzIGZvcg0KPGEgaHJlZj0iaHR0cDovL3d3dy5vbXZpbGxhZ2UuY29tL3lvZ2EtYXJ0Lmh0bSI+WW9nYSBBcnQ8L2E+IA0KYW5kIA0KPGEgaHJlZj0iaHR0cDovL3d3dy5vbXZpbGxhZ2UuY29tL21lZGl0YXRpb24tYXJ0Lmh0bSI+TWVkaXRhdGlvbiBBcnQ8L2E+IA0Kd2UgdXNlZCBtZXRhIHRpdGxlcywgZGVzY3JpcHRpb25zLCBjdXN0b20gVVJMcywgY3VzdG9tIGhlYWRpbmdzLCBjb250ZW50IGZvciBvbiANCnBhZ2Ugb3B0aW1pemF0aW9uIGFuZCBoYWQgZXhjZWxsZW50IHJlc3VsdHMgd2l0aCBvbiBwYWdlIG9wdGltaXphdGlvbi48L3A+DQo8aDM+TWFya2V0aW5nPC9oMz4NCjxwPkFmZmlsaWF0ZSBzeXN0ZW1zLCBhdXRvIHN1Ym1pc3Npb25zIHRvIEdvb2dsZSBCYXNlIGZlZWQsIA0KeWFob28gc2hvcHBpbmcgYW5kIFNob3B6aWxsYSwgb24gc2l0ZSBiYW5uZXJzLiBJIGhhdmUgb25seSB1c2VkIHRoZSBHb29nbGUgQmFzZSANCmZlZWQgdG8gZGF0ZS4gQW1lcmlDb21tZXJjZSBvZmZlcnMgdGhlIGFiaWxpdHkgdG8gcGljayB1cCBkZXNjcmlwdGlvbnMgb2YgdGhlIA0KcHJvZHVjdHMgZnJvbSBkaWZmZXJlbnQgZmllbGRzIGdpdmluZyB1cyBzb21lIGRhdGEgZmVlZCBvcHRpbWl6YXRpb24gY29udHJvbC4gDQpUaGlzIGhhcyB3b3JrZWQgdmVyeSB3ZWxsIGZvciB1cyBhbGxvd2luZyB1cyB0byBwaWNrdXAgZ29vZCB0cmFmZmljIGZyb20gDQpHb29nbGXigJlzIHByb2R1Y3Qgc2VhcmNoZXMuIDwvcD4NCjxwPkFub3RoZXIgZmVhdHVyZSB3b3J0aCBsb29raW5nIGF0IGlzIHRoZSDigJhBZGQgdG8gQ2FydOKAmSBMaW5rIA0KR2VuZXJhdG9yIOKAkyB0aGlzIGFsbG93cyB1cyB0byBnZW5lcmF0ZSBjb2RlIGZvciDigJhBZGQgdG8gQ2FydOKAmSBidXR0b25zIGZvciBhbnkgDQpwcm9kdWN0IG9mIG91ciBjaG9pY2UuIFdlIGFyZSB3b3JraW5nIG9uIGEgY2FtcGFpZ24gdG8gZGlyZWN0bHkgaW5zZXJ0IHRoZXNlIA0K4oCYQWRkIHRvIENhcnTigJkgYnV0dG9ucyBpbiBvdXIgZW1haWxzLiBUaGlzIGFsbG93cyBhIGN1c3RvbWVyIHRvIGFkZCB0aGUgcHJvZHVjdCANCmRpcmVjdGx5IGludG8gdGhlIHNob3BwaW5nIGNhcnQgZnJvbSB0aGUgZW1haWwuIFdvcmtzIHZlcnkgd2VsbCBmb3Ig4oCYSW1wdWxzZeKAmSANCmJ1eSBwcm9kdWN0cy4gDQo8L3A+DQo8aDM+UmVwb3J0aW5nL0FiYW5kb25lZCBDYXJ0cy9QYXRoIExvZ2dpbmc8L2gzPg0KPHA+IA0KR3JlYXQgcmVwb3J0aW5nIOKAkyBldmVyeSBzZXNzaW9uIGlzIGxvZ2dlZCBhbmQgeW91IGNhbiBnZXQgDQppbnRvIHRoZSBiYWNrZW5kIGFuZCBzZWUgdGhlIGV4YWN0IHBhdGggYSB2aXNpdG9yIGZvbGxvd2VkIGFuZCBhdCB3aGF0IHBvaW50IA0KdGhleSBsZWZ0IHRoZSBzaXRlLiBJIGhhdmUgZm91bmQgdGhpcyBleHRyZW1lbHkgdXNlZnVsLiA8L3A+DQo8cD5JZiBJIGhhdmUgYW4gYWJhbmRvbmVkIGNhcnQsIEkgY2FuIGRpZyBkZWVwZXIgdG8gc2VlIGlmIGl0IA0KbWF5IGJlIGEg4oCYd2luZG93IHNob3BwZXLigJkgd2hvIGRpZG7igJl0IGdvIHRvIHRoZSBjaGVja291dCBwYWdlIG9yIGlmIGl0IHdhcyBhIA0KdmlzaXRvciB0aGF0IHdlbnQgdG8gdGhlIGNoZWNrb3V0IHBhZ2UgYnV0IGFmdGVyIHRoYXQgd2VudCB0byB0aGUgc2hpcHBpbmcgb3IgDQpyZXR1cm5zIHBhZ2UgYW5kIGJhaWxlZCBvdXQgYXQgdGhhdCBwb2ludC4gSXQgaXMgdmVyeSBpbnRlcmVzdGluZyBhbmQgdXNlZnVsIHRvIA0Kc3R1ZHkgdGhlIHZpc2l0b3IgcGF0aHMgYW5kIGhlbHBzIHVzIGZ1cnRoZXIgb3B0aW1pemUgdGhlIGNvbnZlcnNpb24gcGF0aC4gDQo8L3A+DQo8cD4gDQpBbHNvLCBpZiBhIHZpc2l0b3IgaGFkIHN0YXJ0ZWQgdG8gY2hlY2tvdXQgYW5kIGxlZnQgDQppbmZvcm1hdGlvbiBvbiB0aGUgcGFnZSDigJMgaXQgZ2V0cyBsb2dnZWQgYW5kIHdlIGhhdmUgZm9sbG93ZWQgdXAgd2l0aCB0aGUgDQpjdXN0b21lciB0byBjbG9zZSB0aG9zZSBzYWxlcyBhbG1vc3QgOTUlIG9mIHRoZSB0aW1lLjwvcD4NCjxwPiANCiZuYnNwOzxhIGhyZWY9ImphdmFzY3JpcHQ6UG9wdXBQaWMoJy9hcnRpY2xlaW1hZ2VzL1Nlc3Npb25Mb2cuanBnJykiPjxpbWcgYm9yZGVyPSIwIiBzcmM9Ii9hcnRpY2xlaW1hZ2VzL3RodW1iL1Nlc3Npb25Mb2cuanBnIiB3aWR0aD0iMjI1IiBoZWlnaHQ9IjE2NyI+PC9hPiZuYnNwOyANCjxhIGhyZWY9ImphdmFzY3JpcHQ6UG9wdXBQaWMoJy9hcnRpY2xlaW1hZ2VzL0FkZFRvQ2FydExpbmtHZW5lcmF0b3IuanBnJykiPg0KPGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvQWRkVG9DYXJ0TGlua0dlbmVyYXRvci5qcGciIHdpZHRoPSIyMjUiIGhlaWdodD0iMTU2Ij48L2E+PC9wPjxiciBjbGVhcj1hbGw+DQoNCjxwPiANCjwvcD4NCjxoMz48YnI+DQpTdXBwb3J0L0tub3dsZWRnZWJhc2UgKFByb2R1Y3QgdHV0b3JpYWxzIGFuZCB2aWRlb3MpPC9oMz4NCjxwPiANCjxhIGhyZWY9ImphdmFzY3JpcHQ6UG9wdXBQaWMoJy9hcnRpY2xlaW1hZ2VzL0FiYW5kb25lZENhcnRzLmpwZycpIj4NCjxpbWcgYm9yZGVyPSIwIiBzcmM9Ii9hcnRpY2xlaW1hZ2VzL3RodW1iL0FiYW5kb25lZENhcnRzLmpwZyIgd2lkdGg9IjIyNSIgaGVpZ2h0PSIxNjUiIGFsaWduPSJyaWdodCI+PC9hPlRoZSB0dXRvcmlhbHMgYW5kIEZBUXMgY292ZXIgYWxsIG9mIHRoZSBmZWF0dXJlcyBhbmQgdGhlIA0KYmFjayBlbmQgdXNlciBpbnRlcmZhY2UgaXMgd2VsbCBjYXRlZ29yaXplZCBhbmQgc3RydWN0dXJlZC4gSW50dWl0aXZlIGFuZCB2ZXJ5IA0KZWFzeSB0byB1c2UuPC9wPg0KPHA+VGhleSBkb27igJl0IG9mZmVyIDI0LzcgdGVsZXBob25lIHN1cHBvcnQuIEhhdmluZyBzYWlkIHRoYXQsIA0KSSBoYXZlbuKAmXQgaGFkIHRvIHJlYWNoIHRoZW0gb3V0c2lkZSBvZiBidXNpbmVzcyBob3Vycy4gVGhlaXIgc3lzdGVtIGFuZCBob3N0aW5nIA0KaGFzIGJlZW4gc3RhYmxlIGFuZCBpcyBtb25pdG9yZWQuIE9uIG9jY2FzaW9uIHdoZW4gSSBoYXZlIG5lZWRlZCB0byBzcGVhayB3aXRoIA0Kc29tZW9uZSBkdXJpbmcgYnVzaW5lc3MgaG91cnMsIEkgaGF2ZSBmb3VuZCB0aGVtIHRvIGJlIHZlcnkgaGVscGZ1bC48L3A+DQo8cD5CZWluZyBhIHZpc3VhbCBsZWFybmVyLCBJIHBlcnNvbmFsbHkgbGlrZSB2aWRlb3MgYW5kIA0KbGVhcm5pbmcgdGhyb3VnaCB2aWRlb3MuIEFtZXJpQ29tbWVyY2UgZG9lc27igJl0IG9mZmVyIHZpZGVvcyBhcyB5ZXQuIEFsdGhvdWdoIEkgDQpkb27igJl0IGhhdmUgdXNlIGZvciBpdCBhbnltb3JlLCBpdCB3b3VsZCBiZSBhIHZhbHVhYmxlIGFkZGl0aW9uIHRvIHNvbWVvbmUgbmV3IHRvIA0KdGhlIHN5c3RlbSAoYXNzdW1pbmcgdGhleSBsaWtlIHRvIGxlYXJuIHZpc3VhbGx5KS4gSSBoYXZlIHRvIGFkbWl0IEFtZXJpQ29tbWVyY2UgDQpoYXMgYXNrZWQgZm9yIGZlZWRiYWNrIG9uIHRoaXMgZnJvbSBjdXN0b21lcnMgYW5kIEkgbWlzc2VkIHJlc3BvbmRpbmcgYW5kIGdpdmluZyANCm15IGlucHV0LiA8L3A+DQo8cD5WaWRlbyB0dXRvcmlhbHMgYW5kIHRyYWluaW5nIGlzIHRoZSBvbmx5IGFyZWEgSSBjb3VsZCANCnJlYWxseSBmaW5kIGEgbWFyZ2luYWwgZG93bnNpZGUgd2l0aCBBbWVyaUNvbW1lcmNlLiBIb3dldmVyLCB0aGV5IGRvIG1ha2UgdXAgZm9yIA0KaXQgd2l0aCBhIHZlcnkgcmVzcG9uc2l2ZSBzdXBwb3J0IHRpY2tldCBzeXN0ZW0uIFRoZWlyIHRlY2huaWNhbCBzdXBwb3J0IHRlYW0gaXMgDQp2ZXJ5IGtub3dsZWRnZWFibGUgYW5kIHF1aWNrIHRvIHJlc3BvbmQuPC9wPg0KPGgzPkN1c3RvbSBEZXZlbG9wbWVudDwvaDM+DQo8cD5UaGlzIHdhcyBhIGtleSBmYWN0b3IgaW4gb3VyIGRlY2lzaW9uIHRvIGNob29zZSANCkFtZXJpQ29tbWVyY2UuJm5ic3A7IFRoZWlyIHdpbGxpbmduZXNzIHRvIGN1c3RvbSBkZXZlbG9wIGZlYXR1cmVzIGhlbHBzIHVzIGhhdmUgYSANCnNvbHV0aW9uIHBhcnRuZXIgb3ZlciBqdXN0IGEgc29sdXRpb24gcHJvdmlkZXIuIFRoZXkgaGF2ZSBhIOKAmGRldmVsb3BtZW50IHNoYXJl4oCZIA0KcHJvZ3JhbSB3aGVyZSBBbWVyaUNvbW1lcmNlIHNoYXJlcyBoYWxmIHRoZSBjb3N0IG9mIGRldmVsb3BtZW50LCB0aGUgcmVtYWluaW5nIA0KaGFsZiBjYW4gYmUgY292ZXJlZCBieSB0aGUgc3RvcmVvd25lciByZXF1ZXN0aW5nIHRoZSBmZWF0dXJlIG9yIHB1dCBvdXQgYSANCnJlcXVlc3QgdG8gb3RoZXIgc3RvcmVvd25lcnMuIElmIG90aGVyIHN0b3Jlb3duZXJzIGFyZSBpbnRlcmVzdGVkIGluIGhhdmluZyB0aGUgDQpmZWF0dXJlIGRldmVsb3BlZCwgdGhlbiB0aGUgY29zdHMgYXJlIHNoYXJlZC4gT25jZSBhIGZlYXR1cmUgaXMgY3VzdG9tIGRldmVsb3BlZCANCmZvciB0aGUgc3RvcmVvd25lcnMgcmVxdWVzdGluZyB0aGUgZmVhdHVyZSwgaXQgaXMgcm9sbGVkIG91dCB0byBhbGwgdGhlIHN0b3JlcyANCmFuZCBldmVyeSBjdXN0b21lciBiZW5lZml0cy4gSXTigJlzIGEgZ3JlYXQgYnVzaW5lc3MgYW5kIGNvbW11bml0eSBtb2RlbCB0aGF0IA0KYmVuZWZpdHMgYWxsIHN0b3Jlb3duZXJzLiA8L3A+DQo8aDM+SW4gQ29uY2x1c2lvbjwvaDM+DQo8cD5UaGUgYWJvdmUgbGlzdCBvZiBmZWF0dXJlcyB0b3VjaGVkIHVwb24gYXJlIGZlYXR1cmVzIHdlIA0KaGF2ZSBmb3VuZCB1c2VmdWwgZm9yIG91ciBzaXRlcy4gVGhlIGxpc3QgaXMgY2VydGFpbmx5IG5vdCBjb21wbGV0ZSBhbmQgaXMgDQphbHdheXMgZ3Jvd2luZyDigJMgZm9yIGEgZGV0YWlsZWQgYW5kIHVwZGF0ZWQgbGlzdCwgaXQgd291bGQgYmUgYmVzdCB0byByZXZpZXcgdGhlIA0KZmVhdHVyZSBsaXN0IGF0IA0KPGEgaHJlZj0iaHR0cDovL3d3dy5BbWVyaUNvbW1lcmNlLmNvbS9zdG9yZS9wZy8zLVNob3BwaW5nLUNhcnQtU29mdHdhcmUtRmVhdHVyZS1MaXN0LmFzcHgiPkFtZXJpQ29tbWVyY2XigJlzIA0Kd2Vic2l0ZTwvYT4uPC9wPg0KPHA+QXMgd2l0aCBhbnkgc29mdHdhcmUgYW5kIGNvbXBhbnksIHRoZXJlIGlzIGFsd2F5cyByb29tIGZvciANCmdyb3d0aC4gTW9yZSBzbywgaW4gYSBkeW5hbWljIGFuZCBmYXN0IGNoYW5naW5nIG9ubGluZSBhbmQgdGVjaG5vbG9neSANCmVudmlyb25tZW50LiBUaGUga2V5IHJlYWxseSBsaWVzIGluIGRlZmluaW5nIG1pZCB0byBsb25nIHRlcm0gYnVzaW5lc3MgbmVlZHMgYW5kIA0KcmV2aWV3aW5nIHNvbHV0aW9uIHByb3ZpZGVycy9wYXJ0bmVycyBiYXNlZCBvbiB0aGF0LiA8L3A+DQo8cD5NYW5qdWxhIEhpZ2dpbmJvdGhhbSwgRWNvbW1lcmNlIE1hbmFnZXIgKDxhIGhyZWY9Imh0dHA6Ly93d3cub212aWxsYWdlLmNvbS8iPnd3dy5vbXZpbGxhZ2UuY29tPC9hPiANCmFuZA0KPGEgaHJlZj0iaHR0cDovL3d3dy5waXBwaW5tY2dlZS5jb20vIj4NCnd3dy5waXBwaW5tY2dlZS5jb208L2E+KTwvcD4NCjxwPjxlbT5Ob3RlOiBhYm91dCBhIHllYXIgYWZ0ZXIgdGhpcyByZXZpZXcgd2FzIHdyaXR0ZW4sIHRoZSBhdXRob3IgYWNjZXB0ZWQgYSBqb2IgYXQgQW1lcmlDb21tZXJjZS4gVGhpcyBpcyBub3RlZCBoZXJlIHRvIHByb3ZpZGUgZnVsbCB0cmFuc3BhcmVuY3k8L2VtPjwvcD4NCjxkaXYgc3R5bGU9ImZsb2F0OmxlZnQiPg0KPC9kaXY+ZGQCAg8PFgIfAAWFVzxoMT5BbWVyaUNvbW1lcmNlIFJldmlldzwvaDE+PHNjcmlwdCBsYW5ndWFnZT0iSmF2YXNjcmlwdCI+IA0KPCEtLQ0KCQlmdW5jdGlvbiBQb3B1cFBpYyhzUGljVVJMKSB7IA0KCQl3aW5kb3cub3BlbigiL3BvcHVwLmh0bWw/IitzUGljVVJMLCAiIiwgInJlc2l6YWJsZT0xLEhFSUdIVD0yNTAsV0lEVEg9MzAwIik7DQoJCX0NCi8vIC0tPg0KDQo8L3NjcmlwdD4NCg0KPHA+SGF2aW5nIGJlZW4gdGhyb3VnaCB0aGUgc2VhcmNoIG9mIGEgc2hvcHBpbmcgY2FydCBzb2x1dGlvbiANCmluIHRoZSBwYXN0LCBJIHZhbHVlZCBpbnB1dCBhYm91dCBkaWZmZXJlbnQgc29sdXRpb25zLCBlc3BlY2lhbGx5IGZyb20gb3RoZXIgDQpzdG9yZW93bmVycyB3aG8gaGFkIHVzZWQgdGhlIHByb2R1Y3QuIEkgaGF2ZSBzaW5jZSBzdGFydGluZyBvdXQgY2hhbmdlZCBteSANCnNvbHV0aW9uIHByb3ZpZGVyIG9uY2UgYW5kIEkgYW0gbm93IHVzaW5nIEFtZXJpQ29tbWVyY2UuIEkgbWFuYWdlIHR3byB3ZWJzaXRlcyANCm9uIHRoZSBBbWVyaUNvbW1lcmNlIHBsYXRmb3JtOiANCjxhIGhyZWY9Imh0dHA6Ly93d3cucGlwcGlubWNnZWUuY29tIj5QaXBwaW4gTWNHZWUg4oCTIGEgY2hpbGRyZW7igJlzIGZ1cm5pdHVyZSBzdG9yZTwvYT4gc2luY2UgRmViIDIwMDcgDQphbmQgPGEgaHJlZj0iaHR0cDovL3d3dy5vbXZpbGxhZ2UuY29tIj5PbSBWaWxsYWdlIOKAkyBhIG1ldGFwaHlzaWNhbCBhbmQgaGVhbGluZyANCmFydCBzdG9yZTwvYT4NCndoaWNoIEkgbW92ZWQgb3ZlciB0byBBbWVyaUNvbW1lcmNlIGluIE5vdiAyMDA3LjwvcD4NCjxwPkFmdGVyIGhhdmluZyB1c2VkIGl0IGZvciA5LTEwIG1vbnRocyBub3csIEkgYmVsaWV2ZSBJIGhhdmUgDQpmb3VuZCBhIHByb2R1Y3QgdGhhdCBtZWV0cyBteSBsb25nLXRlcm0gYnVzaW5lc3MgbmVlZHMgYW5kIEnigJlkIGxpa2UgdG8gc2hhcmUgbXkgDQpleHBlcmllbmNlIGFuZCBkZXNjcmliZSBzb21lIG9mIHRoZSBmZWF0dXJlcyBpbiBzb21lIGRlcHRoLiBJIGhvcGUgdGhpcyBhcnRpY2xlIA0KZ2l2ZXMgeW91IHNvbWUgaW5zaWdodCBpbnRvIHRoZSBzb2x1dGlvbiBmcm9tIGEgdXNlciBwZXJzcGVjdGl2ZSB0byBnYXVnZSBpZiANCnRoaXMgc29sdXRpb24gbWlnaHQgbWVldCB5b3VyIGJ1c2luZXNzIG5lZWRzLjwvcD4NCjxoMz5JbnN0YWxsYXRpb24vU3RhcnQgVXAgcHJvY2VzczwvaDM+DQo8cD5BbWVyaUNvbW1lcmNlIG9mZmVyZWQgYSAxNCBkYXkgZnJlZSB0cmlhbCAod2l0aG91dCBhIGNyZWRpdCANCmNhcmQpIGFuZCB0aGF0IGhlbHBlZCBtZSBqdW1wIGludG8gdGhlIGJhY2tlbmQgYW5kIHJldmlldyB0aGUgZmVhdHVyZXMuIE9uY2UgSSANCmZvdW5kIGl0IGhhZCBhbGwgdGhlIGNvcmUgZmVhdHVyZXMgSSBuZWVkZWQgSSB0YWxrZWQgd2l0aCB0aGVtIGFib3V0IHNvbWUgDQpmZWF0dXJlcyB3ZSBuZWVkZWQgY3VzdG9tIGRldmVsb3BlZCBhbmQgdGhleSB3ZXJlIHRoZSBvbmx5IGVjb21tZXJjZSBzb2x1dGlvbiANCnByb3ZpZGVycyB3aWxsaW5nIHRvIGRvIGN1c3RvbSBmZWF0dXJlIGRldmVsb3BtZW50LiBUaGUgc2lnbiB1cCBhbmQgc3RhcnR1cCANCnByb2Nlc3Mgd2FzIHNpbXBsZS48L3A+DQo8aDM+RGVzaWduL0N1c3RvbWl6aW5nL09uZSBQYWdlIENoZWNrb3V0IC0gdXNhYmlsaXR5IGZhY3RvcnM8L2gzPg0KPHA+Q29udHJvbCBvdmVyIDk1JSBvZiB0aGUgZGVzaWduIGVsZW1lbnRzLiBJZiB5b3Uga25vdyBIVE1MLCANCkNTUyBhbmQgYmFzaWMgSmF2YVNjcmlwdCDigJMgeW91IGNhbiBnbyBhbnl3aGVyZSB5b3UgbGlrZSB3aXRoIHlvdXIgZGVzaWduLiZuYnNwOyBJZiANCnlvdSBkb27igJl0LCB5b3UgY2FuIHN0aWxsIGhhdmUgYSB2ZXJ5IHByb2Zlc3Npb25hbCBsb29raW5nIHdlYnNpdGUuDQo8YSBocmVmPSJqYXZhc2NyaXB0OlBvcHVwUGljKCcvYXJ0aWNsZWltYWdlcy9UaGVtZVNldHRpbmdzLmpwZycpIj48aW1nIGJvcmRlcj0iMCIgc3JjPSIvYXJ0aWNsZWltYWdlcy90aHVtYi9UaGVtZVNldHRpbmdzLmpwZyIgd2lkdGg9IjIyNSIgaGVpZ2h0PSIxNTYiIGFsaWduPSJyaWdodCI+PC9hPjwvcD4NCjxwPlRoZSBwYXJ0IEkgZm91bmQgbW9zdCB1c2VmdWwgd2FzIG9uIHRoZSBwcm9kdWN0IGRldGFpbHMgDQpwYWdlLCBJIGNvdWxkIGN1c3RvbWl6ZSB0aGUgZWxlbWVudHMgZnJvbSBhIHVzYWJpbGl0eSBhbmQgY29udmVyc2lvbiANCnBlcnNwZWN0aXZlLiBJIHdhcyBhYmxlIHRvIGFkZCB0aGUgcmlnaHQgaGFuZCBzaWRlIGNvbHVtbiB3aXRoIGEg4oCYbWF5IHdlIGhlbHAgDQp5b3XigJkgc2VjdGlvbiBzbyB0aGUgYnV5ZXIgaGFzIGltbWVkaWF0ZSBhY2Nlc3MgdG8gaXQgYW5kIGNhbiBnZXQgcXVlc3Rpb25zIA0KYW5zd2VyZWQgcmlnaHQgYXdheS4gPC9wPg0KPHA+QW5vdGhlciBmZWF0dXJlIHdoaWNoIGlzIGtleSB0byBvdXIgc3VjY2VzcyBpcyB0aGUgYWJpbGl0eSANCnRvIGRpc3BsYXkgaGlnaCByZXNvbHV0aW9uIHByb2R1Y3QgaW1hZ2VzLiBXZSBzZWxsIGNoaWxkcmVu4oCZcyBmdXJuaXR1cmUgYW5kIGl0IA0KaXMgaW1wb3J0YW50IGZvciBvdXIgY3VzdG9tZXJzIHRvIGJlIGFibGUgdG8gc2VlIHRoZSBmdXJuaXR1cmUgaW4gZ3JlYXQgZGV0YWlsLiANClNjZW5lNyBjYW4gYmUgcHJvaGliaXRpdmUgYXQgJDEwLDAwMCBhIHllYXIgKGF0IHRoZSB0aW1lIG9mIG91ciBpbnF1aXJ5KSBmb3IgDQpzbWFsbCBidXNpbmVzc2VzLiBIYXZpbmcgdGhlIGFiaWxpdHkgdG8gZGlzcGxheSBoaS1yZXMgaW1hZ2VzIGludGVncmF0ZWQgaW50byANCnRoZSBzdGFuZGFyZCBzb2x1dGlvbiBoYXMgYmVlbiBhIGh1Z2Ugc2F2aW5nITwvcD4NCjxwPlRvIHZpc3VhbGx5IHNlZSB0aGUgYWJvdmUgbWVudGlvbmVkIGZlYXR1cmVzIChtYXkgd2UgaGVscCANCnlvdSwgem9vbWluZyBpbnRvIGEgaGktcmVzIGltYWdlKSB0YWtlIGEgbG9vayBhdCBvdXIgDQo8YSBocmVmPSJodHRwOi8vd3d3LnBpcHBpbm1jZ2VlLmNvbS9zdG9yZS9wLzE0NzUtTC1TaGFwZWQtQmktTG9mdC1CZWQtRGVlci1SdW4tU2VyaWVzLWJ5LUxlYS5hc3B4Ij4NCkxlYSBGdXJuaXR1cmUsIGxvZnQgYmVkIHBhZ2U8L2E+LjwvcD4NCjxwPk9uZSBwYWdlIGNoZWNrb3V0IGlzIGJ1aWx0IGluIGFuZCBhIGdvb2QgdXNhYmlsaXR5IGFuZCANCmNvbnZlcnNpb24gc3RhbmRhcmQuIFRoaXMgZmVhdHVyZSBpcyBub3QgdW5pcXVlIHRvIEFtZXJpQ29tbWVyY2UuIEl04oCZcyBhIA0Kc3RhbmRhcmQuIFRoZXkgb2ZmZXIgZWFzeSBpbnRlZ3JhdGlvbiB3aXRoIFBheXBhbCBhcyBhbiBhbHRlcm5hdGUgY2hlY2tvdXQgDQpvcHRpb24uIEdvb2dsZSBjaGVja291dCBpcyBub3QgeWV0IGludGVncmF0ZWQsIGJ1dCBpbiB0aGUgd29ya3MgYW5kIHNob3VsZCBiZSANCnJvbGxlZCBvdXQgc2hvcnRseS4gVGhpcyBpcyBhIGtleSBmZWF0dXJlIGFuZCBJIHdvdWxkIGhhdmUgbGlrZWQgdG8gaGF2ZSBzZWVuIGl0IA0Kcm9sbGVkIG91dCBzb29uZXIuPC9wPg0KPGgzPlByb2R1Y3QgTWFuYWdlbWVudDwvaDM+DQo8cD5BbWVyaUNvbW1lcmNlIGhhcyBib3RoLCBhIHNpbXBsZSBidXQgZGV0YWlsZWQgbWFudWFsIA0KcHJvZHVjdCBtYW5hZ2VtZW50IGludGVyZmFjZSBhbmQgYSB2ZXJ5IGRldGFpbGVkIHNwcmVhZHNoZWV0LiBUaGlzIG9uY2UgYWdhaW4sIA0KaXMgc3RhbmRhcmQgaW4gbWFueSBzaG9wcGluZyBjYXJ0cy4gVGhlIHBhcnQgSSBoYXZlIG5vdCBzZWVuIG9uIHNvbWUgb2YgdGhlIA0Kb3RoZXIgY2FydHMgYnV0IGZpbmQgdmVyeSB1c2VmdWwgaW4gQW1lcmlDb21tZXJjZSBpczo8L3A+DQo8b2w+DQoJPGxpPuKAmExpdmUgRGVzaWdu4oCZIOKAkyB3aGVuIEnigJltIGxvZ2dlZCBpbiBhbmQgYnJvd3NpbmcgbXkgd2Vic2l0ZSwgaWYgSSBuZWVkIHRvIA0KY2hhbmdlIHNvbWV0aGluZyBvdXQgcXVpY2tseSwgSSBjYW4gZWRpdCB0aGUgY2F0ZWdvcnksIG1hbnVmYWN0dXJlciwgcHJvZHVjdCANCmRldGFpbHMgcmlnaHQgZnJvbSB0aGVyZSB3aXRoIHRoZSBjbGljayBvZiBhIGJ1dHRvbi4NCjwvbGk+DQo8bGk+TWFzcyBFZGl0b3Igd2l0aCBmaWx0ZXJpbmcgb3B0aW9ucyDigJMgYWx0aG91Z2ggbWFzcyBwcm9kdWN0IGVkaXRpbmcgaXMgbm90IA0KdW5jb21tb24sIEFtZXJpQ29tbWVyY2UgYWxsb3dzIGZpbHRlcmluZyBvZiBwcm9kdWN0cyBieSBjYXRlZ29yeSwgc3ViY2F0ZWdvcnkgDQphbmQgbWFudWZhY3R1cmVyLiBBbnkgdGltZSBhIG1hbnVmYWN0dXJlciBjaGFuZ2VzIHByb2R1Y3QgcHJpY2luZywgc2hpcHBpbmcgdGltZSANCmV0YyDigJMgaGF2aW5nIHRoZSBtYW51ZmFjdHVyZXIgZmlsdGVyIGlzIGV4dHJlbWVseSB1c2VmdWwgaW4gcXVpY2sgcHJvZHVjdCANCnVwZGF0ZXMuPC9saT48L29sPg0KPC9zcGFuPg0KPGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvU25hcHNob3QtTGl2ZS1EZXNpZ24tUHJvZHVjLmpwZycpIj48aW1nIGJvcmRlcj0iMCIgc3JjPSIvYXJ0aWNsZWltYWdlcy90aHVtYi9TbmFwc2hvdC1MaXZlLURlc2lnbi1Qcm9kdWMuanBnIiB3aWR0aD0iMjI1IiBoZWlnaHQ9IjIzNyI+PC9hPg0KPGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvU25hcHNob3QtTGl2ZS1EZXNpZ25fUHJvZHVjLmpwZycpIj48aW1nIGJvcmRlcj0iMCIgc3JjPSIvYXJ0aWNsZWltYWdlcy90aHVtYi9TbmFwc2hvdC1MaXZlLURlc2lnbl9Qcm9kdWMuanBnIiB3aWR0aD0iMjI1IiBoZWlnaHQ9IjEzMiI+PC9hPjxwPlRoZXJlIGFyZSBzZXZlcmFsIHdheXMgdG8gbWFzcyANCmVkaXQgcHJvZHVjdHMgd2l0aCBzcHJlYWRzaGVldHMsIGJ1dCBpdCBpcyBoZWxwZnVsIHRvIGhhdmUgYSB2ZXJ5IHVzZXItZnJpZW5kbHkgDQppbnRlcmZhY2UgZm9yIHF1aWNrIGVkaXRzIGFuZCBhbHNvIHRvIHRyYWluIG5vbi10ZWNobmljYWwgYW5kIGN1c3RvbWVyIHNlcnZpY2UgDQpzdGFmZiB0byB1c2UgdGhpcyBpbnRlcmZhY2UgZm9yIHF1aWNrIGVkaXRzLjwvcD4NCjxoMz5TRU88L2gzPg0KPHA+IA0KPGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvU2l0ZUV4cGxvcmVyLmpwZycpIj48aW1nIGJvcmRlcj0iMCIgc3JjPSIvYXJ0aWNsZWltYWdlcy90aHVtYi9TaXRlRXhwbG9yZXIuanBnIiB3aWR0aD0iMjI1IiBoZWlnaHQ9IjE2MCIgYWxpZ249InJpZ2h0Ij48L2E+VmVyeSBTRU8gZnJpZW5kbHkuIFByb3ZpZGVzIGZvciANCm1ldGEgdGFncywgcGFnZSB0aXRsZXMsIGN1c3RvbSBVUkxzIGZvciBhbGwgcGFnZXMgKGNhdGVnb3J5LCBzdWItY2F0ZWdvcnksIA0KcHJvZHVjdCBkZXRhaWxzLCBtYW51ZmFjdHVyZXIgYW5kIGNvbnRlbnQgcGFnZXMpLCAzMDEgcmVkaXJlY3RzLCBhbmQgZXh0cmVtZWx5IA0KZWFzeSB0byBhZGQgY29udGVudCB0byBhbGwgdGhlIHBhZ2VzLiZuYnNwOyA8L3A+DQo8cD5PbiBvdXIgY2F0ZWdvcnkgcGFnZXMgZm9yDQo8YSBocmVmPSJodHRwOi8vd3d3Lm9tdmlsbGFnZS5jb20veW9nYS1hcnQuaHRtIj5Zb2dhIEFydDwvYT4gDQphbmQgDQo8YSBocmVmPSJodHRwOi8vd3d3Lm9tdmlsbGFnZS5jb20vbWVkaXRhdGlvbi1hcnQuaHRtIj5NZWRpdGF0aW9uIEFydDwvYT4gDQp3ZSB1c2VkIG1ldGEgdGl0bGVzLCBkZXNjcmlwdGlvbnMsIGN1c3RvbSBVUkxzLCBjdXN0b20gaGVhZGluZ3MsIGNvbnRlbnQgZm9yIG9uIA0KcGFnZSBvcHRpbWl6YXRpb24gYW5kIGhhZCBleGNlbGxlbnQgcmVzdWx0cyB3aXRoIG9uIHBhZ2Ugb3B0aW1pemF0aW9uLjwvcD4NCjxoMz5NYXJrZXRpbmc8L2gzPg0KPHA+QWZmaWxpYXRlIHN5c3RlbXMsIGF1dG8gc3VibWlzc2lvbnMgdG8gR29vZ2xlIEJhc2UgZmVlZCwgDQp5YWhvbyBzaG9wcGluZyBhbmQgU2hvcHppbGxhLCBvbiBzaXRlIGJhbm5lcnMuIEkgaGF2ZSBvbmx5IHVzZWQgdGhlIEdvb2dsZSBCYXNlIA0KZmVlZCB0byBkYXRlLiBBbWVyaUNvbW1lcmNlIG9mZmVycyB0aGUgYWJpbGl0eSB0byBwaWNrIHVwIGRlc2NyaXB0aW9ucyBvZiB0aGUgDQpwcm9kdWN0cyBmcm9tIGRpZmZlcmVudCBmaWVsZHMgZ2l2aW5nIHVzIHNvbWUgZGF0YSBmZWVkIG9wdGltaXphdGlvbiBjb250cm9sLiANClRoaXMgaGFzIHdvcmtlZCB2ZXJ5IHdlbGwgZm9yIHVzIGFsbG93aW5nIHVzIHRvIHBpY2t1cCBnb29kIHRyYWZmaWMgZnJvbSANCkdvb2dsZeKAmXMgcHJvZHVjdCBzZWFyY2hlcy4gPC9wPg0KPHA+QW5vdGhlciBmZWF0dXJlIHdvcnRoIGxvb2tpbmcgYXQgaXMgdGhlIOKAmEFkZCB0byBDYXJ04oCZIExpbmsgDQpHZW5lcmF0b3Ig4oCTIHRoaXMgYWxsb3dzIHVzIHRvIGdlbmVyYXRlIGNvZGUgZm9yIOKAmEFkZCB0byBDYXJ04oCZIGJ1dHRvbnMgZm9yIGFueSANCnByb2R1Y3Qgb2Ygb3VyIGNob2ljZS4gV2UgYXJlIHdvcmtpbmcgb24gYSBjYW1wYWlnbiB0byBkaXJlY3RseSBpbnNlcnQgdGhlc2UgDQrigJhBZGQgdG8gQ2FydOKAmSBidXR0b25zIGluIG91ciBlbWFpbHMuIFRoaXMgYWxsb3dzIGEgY3VzdG9tZXIgdG8gYWRkIHRoZSBwcm9kdWN0IA0KZGlyZWN0bHkgaW50byB0aGUgc2hvcHBpbmcgY2FydCBmcm9tIHRoZSBlbWFpbC4gV29ya3MgdmVyeSB3ZWxsIGZvciDigJhJbXB1bHNl4oCZIA0KYnV5IHByb2R1Y3RzLiANCjwvcD4NCjxoMz5SZXBvcnRpbmcvQWJhbmRvbmVkIENhcnRzL1BhdGggTG9nZ2luZzwvaDM+DQo8cD4gDQpHcmVhdCByZXBvcnRpbmcg4oCTIGV2ZXJ5IHNlc3Npb24gaXMgbG9nZ2VkIGFuZCB5b3UgY2FuIGdldCANCmludG8gdGhlIGJhY2tlbmQgYW5kIHNlZSB0aGUgZXhhY3QgcGF0aCBhIHZpc2l0b3IgZm9sbG93ZWQgYW5kIGF0IHdoYXQgcG9pbnQgDQp0aGV5IGxlZnQgdGhlIHNpdGUuIEkgaGF2ZSBmb3VuZCB0aGlzIGV4dHJlbWVseSB1c2VmdWwuIDwvcD4NCjxwPklmIEkgaGF2ZSBhbiBhYmFuZG9uZWQgY2FydCwgSSBjYW4gZGlnIGRlZXBlciB0byBzZWUgaWYgaXQgDQptYXkgYmUgYSDigJh3aW5kb3cgc2hvcHBlcuKAmSB3aG8gZGlkbuKAmXQgZ28gdG8gdGhlIGNoZWNrb3V0IHBhZ2Ugb3IgaWYgaXQgd2FzIGEgDQp2aXNpdG9yIHRoYXQgd2VudCB0byB0aGUgY2hlY2tvdXQgcGFnZSBidXQgYWZ0ZXIgdGhhdCB3ZW50IHRvIHRoZSBzaGlwcGluZyBvciANCnJldHVybnMgcGFnZSBhbmQgYmFpbGVkIG91dCBhdCB0aGF0IHBvaW50LiBJdCBpcyB2ZXJ5IGludGVyZXN0aW5nIGFuZCB1c2VmdWwgdG8gDQpzdHVkeSB0aGUgdmlzaXRvciBwYXRocyBhbmQgaGVscHMgdXMgZnVydGhlciBvcHRpbWl6ZSB0aGUgY29udmVyc2lvbiBwYXRoLiANCjwvcD4NCjxwPiANCkFsc28sIGlmIGEgdmlzaXRvciBoYWQgc3RhcnRlZCB0byBjaGVja291dCBhbmQgbGVmdCANCmluZm9ybWF0aW9uIG9uIHRoZSBwYWdlIOKAkyBpdCBnZXRzIGxvZ2dlZCBhbmQgd2UgaGF2ZSBmb2xsb3dlZCB1cCB3aXRoIHRoZSANCmN1c3RvbWVyIHRvIGNsb3NlIHRob3NlIHNhbGVzIGFsbW9zdCA5NSUgb2YgdGhlIHRpbWUuPC9wPg0KPHA+IA0KJm5ic3A7PGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvU2Vzc2lvbkxvZy5qcGcnKSI+PGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvU2Vzc2lvbkxvZy5qcGciIHdpZHRoPSIyMjUiIGhlaWdodD0iMTY3Ij48L2E+Jm5ic3A7IA0KPGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvQWRkVG9DYXJ0TGlua0dlbmVyYXRvci5qcGcnKSI+DQo8aW1nIGJvcmRlcj0iMCIgc3JjPSIvYXJ0aWNsZWltYWdlcy90aHVtYi9BZGRUb0NhcnRMaW5rR2VuZXJhdG9yLmpwZyIgd2lkdGg9IjIyNSIgaGVpZ2h0PSIxNTYiPjwvYT48L3A+PGJyIGNsZWFyPWFsbD4NCg0KPHA+IA0KPC9wPg0KPGgzPjxicj4NClN1cHBvcnQvS25vd2xlZGdlYmFzZSAoUHJvZHVjdCB0dXRvcmlhbHMgYW5kIHZpZGVvcyk8L2gzPg0KPHA+IA0KPGEgaHJlZj0iamF2YXNjcmlwdDpQb3B1cFBpYygnL2FydGljbGVpbWFnZXMvQWJhbmRvbmVkQ2FydHMuanBnJykiPg0KPGltZyBib3JkZXI9IjAiIHNyYz0iL2FydGljbGVpbWFnZXMvdGh1bWIvQWJhbmRvbmVkQ2FydHMuanBnIiB3aWR0aD0iMjI1IiBoZWlnaHQ9IjE2NSIgYWxpZ249InJpZ2h0Ij48L2E+VGhlIHR1dG9yaWFscyBhbmQgRkFRcyBjb3ZlciBhbGwgb2YgdGhlIGZlYXR1cmVzIGFuZCB0aGUgDQpiYWNrIGVuZCB1c2VyIGludGVyZmFjZSBpcyB3ZWxsIGNhdGVnb3JpemVkIGFuZCBzdHJ1Y3R1cmVkLiBJbnR1aXRpdmUgYW5kIHZlcnkgDQplYXN5IHRvIHVzZS48L3A+DQo8cD5UaGV5IGRvbuKAmXQgb2ZmZXIgMjQvNyB0ZWxlcGhvbmUgc3VwcG9ydC4gSGF2aW5nIHNhaWQgdGhhdCwgDQpJIGhhdmVu4oCZdCBoYWQgdG8gcmVhY2ggdGhlbSBvdXRzaWRlIG9mIGJ1c2luZXNzIGhvdXJzLiBUaGVpciBzeXN0ZW0gYW5kIGhvc3RpbmcgDQpoYXMgYmVlbiBzdGFibGUgYW5kIGlzIG1vbml0b3JlZC4gT24gb2NjYXNpb24gd2hlbiBJIGhhdmUgbmVlZGVkIHRvIHNwZWFrIHdpdGggDQpzb21lb25lIGR1cmluZyBidXNpbmVzcyBob3VycywgSSBoYXZlIGZvdW5kIHRoZW0gdG8gYmUgdmVyeSBoZWxwZnVsLjwvcD4NCjxwPkJlaW5nIGEgdmlzdWFsIGxlYXJuZXIsIEkgcGVyc29uYWxseSBsaWtlIHZpZGVvcyBhbmQgDQpsZWFybmluZyB0aHJvdWdoIHZpZGVvcy4gQW1lcmlDb21tZXJjZSBkb2VzbuKAmXQgb2ZmZXIgdmlkZW9zIGFzIHlldC4gQWx0aG91Z2ggSSANCmRvbuKAmXQgaGF2ZSB1c2UgZm9yIGl0IGFueW1vcmUsIGl0IHdvdWxkIGJlIGEgdmFsdWFibGUgYWRkaXRpb24gdG8gc29tZW9uZSBuZXcgdG8gDQp0aGUgc3lzdGVtIChhc3N1bWluZyB0aGV5IGxpa2UgdG8gbGVhcm4gdmlzdWFsbHkpLiBJIGhhdmUgdG8gYWRtaXQgQW1lcmlDb21tZXJjZSANCmhhcyBhc2tlZCBmb3IgZmVlZGJhY2sgb24gdGhpcyBmcm9tIGN1c3RvbWVycyBhbmQgSSBtaXNzZWQgcmVzcG9uZGluZyBhbmQgZ2l2aW5nIA0KbXkgaW5wdXQuIDwvcD4NCjxwPlZpZGVvIHR1dG9yaWFscyBhbmQgdHJhaW5pbmcgaXMgdGhlIG9ubHkgYXJlYSBJIGNvdWxkIA0KcmVhbGx5IGZpbmQgYSBtYXJnaW5hbCBkb3duc2lkZSB3aXRoIEFtZXJpQ29tbWVyY2UuIEhvd2V2ZXIsIHRoZXkgZG8gbWFrZSB1cCBmb3IgDQppdCB3aXRoIGEgdmVyeSByZXNwb25zaXZlIHN1cHBvcnQgdGlja2V0IHN5c3RlbS4gVGhlaXIgdGVjaG5pY2FsIHN1cHBvcnQgdGVhbSBpcyANCnZlcnkga25vd2xlZGdlYWJsZSBhbmQgcXVpY2sgdG8gcmVzcG9uZC48L3A+DQo8aDM+Q3VzdG9tIERldmVsb3BtZW50PC9oMz4NCjxwPlRoaXMgd2FzIGEga2V5IGZhY3RvciBpbiBvdXIgZGVjaXNpb24gdG8gY2hvb3NlIA0KQW1lcmlDb21tZXJjZS4mbmJzcDsgVGhlaXIgd2lsbGluZ25lc3MgdG8gY3VzdG9tIGRldmVsb3AgZmVhdHVyZXMgaGVscHMgdXMgaGF2ZSBhIA0Kc29sdXRpb24gcGFydG5lciBvdmVyIGp1c3QgYSBzb2x1dGlvbiBwcm92aWRlci4gVGhleSBoYXZlIGEg4oCYZGV2ZWxvcG1lbnQgc2hhcmXigJkgDQpwcm9ncmFtIHdoZXJlIEFtZXJpQ29tbWVyY2Ugc2hhcmVzIGhhbGYgdGhlIGNvc3Qgb2YgZGV2ZWxvcG1lbnQsIHRoZSByZW1haW5pbmcgDQpoYWxmIGNhbiBiZSBjb3ZlcmVkIGJ5IHRoZSBzdG9yZW93bmVyIHJlcXVlc3RpbmcgdGhlIGZlYXR1cmUgb3IgcHV0IG91dCBhIA0KcmVxdWVzdCB0byBvdGhlciBzdG9yZW93bmVycy4gSWYgb3RoZXIgc3RvcmVvd25lcnMgYXJlIGludGVyZXN0ZWQgaW4gaGF2aW5nIHRoZSANCmZlYXR1cmUgZGV2ZWxvcGVkLCB0aGVuIHRoZSBjb3N0cyBhcmUgc2hhcmVkLiBPbmNlIGEgZmVhdHVyZSBpcyBjdXN0b20gZGV2ZWxvcGVkIA0KZm9yIHRoZSBzdG9yZW93bmVycyByZXF1ZXN0aW5nIHRoZSBmZWF0dXJlLCBpdCBpcyByb2xsZWQgb3V0IHRvIGFsbCB0aGUgc3RvcmVzIA0KYW5kIGV2ZXJ5IGN1c3RvbWVyIGJlbmVmaXRzLiBJdOKAmXMgYSBncmVhdCBidXNpbmVzcyBhbmQgY29tbXVuaXR5IG1vZGVsIHRoYXQgDQpiZW5lZml0cyBhbGwgc3RvcmVvd25lcnMuIDwvcD4NCjxoMz5JbiBDb25jbHVzaW9uPC9oMz4NCjxwPlRoZSBhYm92ZSBsaXN0IG9mIGZlYXR1cmVzIHRvdWNoZWQgdXBvbiBhcmUgZmVhdHVyZXMgd2UgDQpoYXZlIGZvdW5kIHVzZWZ1bCBmb3Igb3VyIHNpdGVzLiBUaGUgbGlzdCBpcyBjZXJ0YWlubHkgbm90IGNvbXBsZXRlIGFuZCBpcyANCmFsd2F5cyBncm93aW5nIOKAkyBmb3IgYSBkZXRhaWxlZCBhbmQgdXBkYXRlZCBsaXN0LCBpdCB3b3VsZCBiZSBiZXN0IHRvIHJldmlldyB0aGUgDQpmZWF0dXJlIGxpc3QgYXQgDQo8YSBocmVmPSJodHRwOi8vd3d3LkFtZXJpQ29tbWVyY2UuY29tL3N0b3JlL3BnLzMtU2hvcHBpbmctQ2FydC1Tb2Z0d2FyZS1GZWF0dXJlLUxpc3QuYXNweCI+QW1lcmlDb21tZXJjZeKAmXMgDQp3ZWJzaXRlPC9hPi48L3A+DQo8cD5BcyB3aXRoIGFueSBzb2Z0d2FyZSBhbmQgY29tcGFueSwgdGhlcmUgaXMgYWx3YXlzIHJvb20gZm9yIA0KZ3Jvd3RoLiBNb3JlIHNvLCBpbiBhIGR5bmFtaWMgYW5kIGZhc3QgY2hhbmdpbmcgb25saW5lIGFuZCB0ZWNobm9sb2d5IA0KZW52aXJvbm1lbnQuIFRoZSBrZXkgcmVhbGx5IGxpZXMgaW4gZGVmaW5pbmcgbWlkIHRvIGxvbmcgdGVybSBidXNpbmVzcyBuZWVkcyBhbmQgDQpyZXZpZXdpbmcgc29sdXRpb24gcHJvdmlkZXJzL3BhcnRuZXJzIGJhc2VkIG9uIHRoYXQuIDwvcD4NCjxwPk1hbmp1bGEgSGlnZ2luYm90aGFtLCBFY29tbWVyY2UgTWFuYWdlciAoPGEgaHJlZj0iaHR0cDovL3d3dy5vbXZpbGxhZ2UuY29tLyI+d3d3Lm9tdmlsbGFnZS5jb208L2E+IA0KYW5kDQo8YSBocmVmPSJodHRwOi8vd3d3LnBpcHBpbm1jZ2VlLmNvbS8iPg0Kd3d3LnBpcHBpbm1jZ2VlLmNvbTwvYT4pPC9wPg0KPHA+PGVtPk5vdGU6IGFib3V0IGEgeWVhciBhZnRlciB0aGlzIHJldmlldyB3YXMgd3JpdHRlbiwgdGhlIGF1dGhvciBhY2NlcHRlZCBhIGpvYiBhdCBBbWVyaUNvbW1lcmNlLiBUaGlzIGlzIG5vdGVkIGhlcmUgdG8gcHJvdmlkZSBmdWxsIHRyYW5zcGFyZW5jeTwvZW0+PC9wPg0KPGRpdiBzdHlsZT0iZmxvYXQ6bGVmdCI+DQo8L2Rpdj48cD48ZW0+QXJ0aWNsZSBjb3VydGVzeSBvZiA8YSBocmVmPSJodHRwOi8vd3d3LmVjb21tZXJjZXNwb3QuY29tIj5FY29tbWVyY2UgU3BvdDwvYT4uPC9lbT48L3A+ZGRkgqS0pMc6Ph0gxwMFSnqeg+X2bQo2S6f2RwIiN/oSYmE=" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="CD96ACFB" />
        <div align="center">
            
            
        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
    <span id="_ctl0_bodyHeader_lblBodyHead">AmeriCommerce indepth review</span>

                    </h2>
                </div>
                <div class="inpage">
                    


    <span id="_ctl0_contentBody_lblTitle"><h1>AmeriCommerce Review</h1></span>
    <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Top -->
        <ins class="adsbygoogle"
            style="display: block"
            data-ad-client="ca-pub-1388311751127083"
            data-ad-slot="8765540533"
            data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        <span id="_ctl0_contentBody_lblBody"><script language="Javascript"> 
<!--
		function PopupPic(sPicURL) { 
		window.open("/popup.html?"+sPicURL, "", "resizable=1,HEIGHT=250,WIDTH=300");
		}
// -->

</script>

<p>Having been through the search of a shopping cart solution 
in the past, I valued input about different solutions, especially from other 
storeowners who had used the product. I have since starting out changed my 
solution provider once and I am now using AmeriCommerce. I manage two websites 
on the AmeriCommerce platform: 
<a href="http://www.pippinmcgee.com">Pippin McGee – a children’s furniture store</a> since Feb 2007 
and <a href="http://www.omvillage.com">Om Village – a metaphysical and healing 
art store</a>
which I moved over to AmeriCommerce in Nov 2007.</p>
<p>After having used it for 9-10 months now, I believe I have 
found a product that meets my long-term business needs and I’d like to share my 
experience and describe some of the features in some depth. I hope this article 
gives you some insight into the solution from a user perspective to gauge if 
this solution might meet your business needs.</p>
<h3>Installation/Start Up process</h3>
<p>AmeriCommerce offered a 14 day free trial (without a credit 
card) and that helped me jump into the backend and review the features. Once I 
found it had all the core features I needed I talked with them about some 
features we needed custom developed and they were the only ecommerce solution 
providers willing to do custom feature development. The sign up and startup 
process was simple.</p>
<h3>Design/Customizing/One Page Checkout - usability factors</h3>
<p>Control over 95% of the design elements. If you know HTML, 
CSS and basic JavaScript – you can go anywhere you like with your design.&nbsp; If 
you don’t, you can still have a very professional looking website.
<a href="javascript:PopupPic('/articleimages/ThemeSettings.jpg')"><img border="0" src="/articleimages/thumb/ThemeSettings.jpg" width="225" height="156" align="right"></a></p>
<p>The part I found most useful was on the product details 
page, I could customize the elements from a usability and conversion 
perspective. I was able to add the right hand side column with a ‘may we help 
you’ section so the buyer has immediate access to it and can get questions 
answered right away. </p>
<p>Another feature which is key to our success is the ability 
to display high resolution product images. We sell children’s furniture and it 
is important for our customers to be able to see the furniture in great detail. 
Scene7 can be prohibitive at $10,000 a year (at the time of our inquiry) for 
small businesses. Having the ability to display hi-res images integrated into 
the standard solution has been a huge saving!</p>
<p>To visually see the above mentioned features (may we help 
you, zooming into a hi-res image) take a look at our 
<a href="http://www.pippinmcgee.com/store/p/1475-L-Shaped-Bi-Loft-Bed-Deer-Run-Series-by-Lea.aspx">
Lea Furniture, loft bed page</a>.</p>
<p>One page checkout is built in and a good usability and 
conversion standard. This feature is not unique to AmeriCommerce. It’s a 
standard. They offer easy integration with Paypal as an alternate checkout 
option. Google checkout is not yet integrated, but in the works and should be 
rolled out shortly. This is a key feature and I would have liked to have seen it 
rolled out sooner.</p>
<h3>Product Management</h3>
<p>AmeriCommerce has both, a simple but detailed manual 
product management interface and a very detailed spreadsheet. This once again, 
is standard in many shopping carts. The part I have not seen on some of the 
other carts but find very useful in AmeriCommerce is:</p>
<ol>
	<li>‘Live Design’ – when I’m logged in and browsing my website, if I need to 
change something out quickly, I can edit the category, manufacturer, product 
details right from there with the click of a button.
</li>
<li>Mass Editor with filtering options – although mass product editing is not 
uncommon, AmeriCommerce allows filtering of products by category, subcategory 
and manufacturer. Any time a manufacturer changes product pricing, shipping time 
etc – having the manufacturer filter is extremely useful in quick product 
updates.</li></ol>
</span>
<a href="javascript:PopupPic('/articleimages/Snapshot-Live-Design-Produc.jpg')"><img border="0" src="/articleimages/thumb/Snapshot-Live-Design-Produc.jpg" width="225" height="237"></a>
<a href="javascript:PopupPic('/articleimages/Snapshot-Live-Design_Produc.jpg')"><img border="0" src="/articleimages/thumb/Snapshot-Live-Design_Produc.jpg" width="225" height="132"></a><p>There are several ways to mass 
edit products with spreadsheets, but it is helpful to have a very user-friendly 
interface for quick edits and also to train non-technical and customer service 
staff to use this interface for quick edits.</p>
<h3>SEO</h3>
<p> 
<a href="javascript:PopupPic('/articleimages/SiteExplorer.jpg')"><img border="0" src="/articleimages/thumb/SiteExplorer.jpg" width="225" height="160" align="right"></a>Very SEO friendly. Provides for 
meta tags, page titles, custom URLs for all pages (category, sub-category, 
product details, manufacturer and content pages), 301 redirects, and extremely 
easy to add content to all the pages.&nbsp; </p>
<p>On our category pages for
<a href="http://www.omvillage.com/yoga-art.htm">Yoga Art</a> 
and 
<a href="http://www.omvillage.com/meditation-art.htm">Meditation Art</a> 
we used meta titles, descriptions, custom URLs, custom headings, content for on 
page optimization and had excellent results with on page optimization.</p>
<h3>Marketing</h3>
<p>Affiliate systems, auto submissions to Google Base feed, 
yahoo shopping and Shopzilla, on site banners. I have only used the Google Base 
feed to date. AmeriCommerce offers the ability to pick up descriptions of the 
products from different fields giving us some data feed optimization control. 
This has worked very well for us allowing us to pickup good traffic from 
Google’s product searches. </p>
<p>Another feature worth looking at is the ‘Add to Cart’ Link 
Generator – this allows us to generate code for ‘Add to Cart’ buttons for any 
product of our choice. We are working on a campaign to directly insert these 
‘Add to Cart’ buttons in our emails. This allows a customer to add the product 
directly into the shopping cart from the email. Works very well for ‘Impulse’ 
buy products. 
</p>
<h3>Reporting/Abandoned Carts/Path Logging</h3>
<p> 
Great reporting – every session is logged and you can get 
into the backend and see the exact path a visitor followed and at what point 
they left the site. I have found this extremely useful. </p>
<p>If I have an abandoned cart, I can dig deeper to see if it 
may be a ‘window shopper’ who didn’t go to the checkout page or if it was a 
visitor that went to the checkout page but after that went to the shipping or 
returns page and bailed out at that point. It is very interesting and useful to 
study the visitor paths and helps us further optimize the conversion path. 
</p>
<p> 
Also, if a visitor had started to checkout and left 
information on the page – it gets logged and we have followed up with the 
customer to close those sales almost 95% of the time.</p>
<p> 
&nbsp;<a href="javascript:PopupPic('/articleimages/SessionLog.jpg')"><img border="0" src="/articleimages/thumb/SessionLog.jpg" width="225" height="167"></a>&nbsp; 
<a href="javascript:PopupPic('/articleimages/AddToCartLinkGenerator.jpg')">
<img border="0" src="/articleimages/thumb/AddToCartLinkGenerator.jpg" width="225" height="156"></a></p><br clear=all>

<p> 
</p>
<h3><br>
Support/Knowledgebase (Product tutorials and videos)</h3>
<p> 
<a href="javascript:PopupPic('/articleimages/AbandonedCarts.jpg')">
<img border="0" src="/articleimages/thumb/AbandonedCarts.jpg" width="225" height="165" align="right"></a>The tutorials and FAQs cover all of the features and the 
back end user interface is well categorized and structured. Intuitive and very 
easy to use.</p>
<p>They don’t offer 24/7 telephone support. Having said that, 
I haven’t had to reach them outside of business hours. Their system and hosting 
has been stable and is monitored. On occasion when I have needed to speak with 
someone during business hours, I have found them to be very helpful.</p>
<p>Being a visual learner, I personally like videos and 
learning through videos. AmeriCommerce doesn’t offer videos as yet. Although I 
don’t have use for it anymore, it would be a valuable addition to someone new to 
the system (assuming they like to learn visually). I have to admit AmeriCommerce 
has asked for feedback on this from customers and I missed responding and giving 
my input. </p>
<p>Video tutorials and training is the only area I could 
really find a marginal downside with AmeriCommerce. However, they do make up for 
it with a very responsive support ticket system. Their technical support team is 
very knowledgeable and quick to respond.</p>
<h3>Custom Development</h3>
<p>This was a key factor in our decision to choose 
AmeriCommerce.&nbsp; Their willingness to custom develop features helps us have a 
solution partner over just a solution provider. They have a ‘development share’ 
program where AmeriCommerce shares half the cost of development, the remaining 
half can be covered by the storeowner requesting the feature or put out a 
request to other storeowners. If other storeowners are interested in having the 
feature developed, then the costs are shared. Once a feature is custom developed 
for the storeowners requesting the feature, it is rolled out to all the stores 
and every customer benefits. It’s a great business and community model that 
benefits all storeowners. </p>
<h3>In Conclusion</h3>
<p>The above list of features touched upon are features we 
have found useful for our sites. The list is certainly not complete and is 
always growing – for a detailed and updated list, it would be best to review the 
feature list at 
<a href="http://www.AmeriCommerce.com/store/pg/3-Shopping-Cart-Software-Feature-List.aspx">AmeriCommerce’s 
website</a>.</p>
<p>As with any software and company, there is always room for 
growth. More so, in a dynamic and fast changing online and technology 
environment. The key really lies in defining mid to long term business needs and 
reviewing solution providers/partners based on that. </p>
<p>Manjula Higginbotham, Ecommerce Manager (<a href="http://www.omvillage.com/">www.omvillage.com</a> 
and
<a href="http://www.pippinmcgee.com/">
www.pippinmcgee.com</a>)</p>
<p><em>Note: about a year after this review was written, the author accepted a job at AmeriCommerce. This is noted here to provide full transparency</em></p>
<div style="float:left">
</div></span>
    </p>
    
    


    <script type="text/javascript">
        function SelectAll(id) {
            document.getElementsByTagName("textarea").item(0).focus();
            document.getElementsByTagName("textarea").item(0).select();
        }

        document.getElementsByTagName("textarea").item(0).onclick = function () { SelectAll() };

    </script>

     <script type="text/javascript">
       var CurrentArticleName = "AmeriCommerce";
       var CurrentArticleImage = "http://i.imgur.com/9Q9L40Y.jpg";
     </script>


    <script type="text/javascript">

        var HidePopupOnPage = "False";

        if (document.location.protocol == 'http:') {
            var Tynt = Tynt || []; Tynt.push('c-yIBWcq8r4lYkadbi-bnq'); Tynt.i = { "st": true };
            (function () { var s = document.createElement('script'); s.async = "async"; s.type = "text/javascript"; s.src = 'http://tcr.tynt.com/ti.js'; var h = document.getElementsByTagName('script')[0]; h.parentNode.insertBefore(s, h); })();
        }
    </script>

                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
