

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	Choosing shopping cart software
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<meta name="Description"></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./Choosing-shopping-cart-software.aspx?sArticlename=Choosing-shopping-cart-software" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTExODI3Mzg0NjMPZBYCZg9kFgICAw9kFgQCAQ9kFgICAQ9kFgICAQ8PFgIeBFRleHQFH0Nob29zaW5nIHNob3BwaW5nIGNhcnQgc29mdHdhcmVkZAICD2QWBmYPDxYCHwAFKDxoMT5DaG9vc2luZyBzaG9wcGluZyBjYXJ0IHNvZnR3YXJlPC9oMT5kZAIBDw8WAh8ABb9RPHA+PGVtPmJ5IE1pY2hhZWwgR3VuaW4sIDwvZW0+PGEgaHJlZj0iaHR0cDovL3F1YWxpdGVhbS5iaXovIj5RdWFsaXRlYW0gU29mdHdhcmU8L2E+LjwvcD4NCg0KPGgyPjxhIG5hbWU9QTM+PC9hPkludHJvZHVjdGlvbjwvaDI+DQoNCjxwPjxzdHJvbmc+Q2hvb3Npbmcgc2hvcHBpbmcgY2FydA0Kc29mdHdhcmUgY2FuIHR1cm4gaW50byBhIHRvdWdoIGpvYiBkdWUgdG8gdGhlIGxhcmdlIG51bWJlciBvZiBlLWNvbW1lcmNlDQpzb2x1dGlvbnMgYXZhaWxhYmxlIG9uIHRoZSBtYXJrZXQuIE92ZXJhbGwsIGl0J3MgYWxtb3N0IGltcG9zc2libGUgdG8gc2F5IHdoaWNoDQpwcm9kdWN0IGlzIHRoZSBiZXN0IG9uZSBzaW5jZSB0aGVpciBmZWF0dXJlIHJpY2huZXNzLCBwcmljaW5nLCBmbGV4aWJpbGl0eSBhbmQNCnRoZSByYW5nZSBvZiBleHRyYSBzZXJ2aWNlcyB2YXJ5IHRvIGEgZ3JlYXQgZXh0ZW50Ljwvc3Ryb25nPjwvcD4NCg0KPHA+VGhlcmVmb3JlLCBidXlpbmcNCnRoZSByaWdodCBwcm9kdWN0IHdoaWNoIGZpdHMgaW50byB5b3VyIGdvYWxzIGNhbiBzYXZlIGEgbG90IG9mIHRpbWUgYW5kDQplZmZvcnQsIHdoaWxlIGEgbWlzdGFrZSBtYXkgdHVybiBpbnRvIGV4dHJhIGNvc3RzLCBhZGRpdGlvbmFsIG1vbnRocyBvZg0Kd29yayBvciBldmVuIGNhdXNlIHN0YXJ0aW5nIHRoZSB3aG9sZSBwcm9qZWN0IGZyb20gc2NyYXRjaC48L3A+DQoNCjxwPlRoZXJlIGFyZSBzZXZlcmFsDQprZXkgZmFjdG9ycyB3aGljaCBzaG91bGQgYmUgY29uc2lkZXJlZCB3aGlsZSBwaWNraW5nIHRoZSByaWdodCBzb2x1dGlvbi4gSW4gdGhpcw0KYXJ0aWNsZSwgSSdsbCB0cnkgdG8gb3V0bGluZSB0aGUgbW9zdCBpbXBvcnRhbnQgc3RlcHMgdGhhdCBkZWZpbml0ZWx5IHNob3VsZA0Kbm90IGJlIG1pc3NlZC4gVGhlIHRhY3RpY3MgZGVzY3JpYmVkIGJlbG93DQptYXkgYmUgdmFyaWVkIGFjY29yZGluZyB0byB5b3VyIGdvYWxzLCBob3dldmVyLCBmb2xsb3dpbmcgdGhpcyBhZHZpY2Ugd2lsbA0KYmUgdXNlZnVsIGluIHRoZSBkZWNpc2lvbi1tYWtpbmcgcHJvY2VzcyBhcyBhIHdob2xlLjwvcD4NCg0KDQoNCg0KPGgyPjxhIG5hbWU9QTQ+PC9hPktleSBncm91cHMgb2YgZmFjdG9yczwvaDI+DQoNCjxoMz5XaG8geW91IGFyZTwvaDM+DQoNCjxwPkluIG15IG9waW5pb24sDQp0aGUgZmlyc3QgdGhpbmcgeW91IHNob3VsZCBhc2sgaXMgdGhlIHJvbGUgaGUncyBnb2luZyB0byBwbGF5IGluDQp0aGUgb25saW5lIHN0b3JlIGZ1bmN0aW9uaW5nIHByb2Nlc3MuIFRoZSBrZXkgZmFjdG9yIG9mIHRoaXMgcm9sZSAoYXQgbGVhc3QgZm9yDQpzbWFsbCBhbmQgbWVkaXVtIGJ1c2luZXNzZXMpIGlzIHRoZSBsZXZlbCBvZiBhIHBlcnNvbidzIHRlY2huaWNhbCBrbm93bGVkZ2UuPC9wPg0KDQo8cD5JbiBtb3N0IGNhc2VzLA0KdGVjaG5vbG9neSBpcyBhbiBpc3N1ZSBmb3IgPGVtPnN0b3JlDQpvd25lcnM8L2VtPiwgPGVtPm1hbmFnZXJzPC9lbT4NCmFuZCA8ZW0+YWRtaW5pc3RyYXRvcnM8L2VtPi4NClNpbmNlIGVhY2ggc3RvcmUgbmVlZHMgaXRzIG93biB1bmlxdWUgZGVzaWduLCBmdW5jdGlvbmFsaXR5IGFuZA0Kc3RvcmVmcm9udCBkZXNpZ24gYWxvbmcgd2l0aCB0aGUgaW5pdGlhbCBzZXR1cCBhbmQgc2VydmVyIGFkbWluaXN0cmF0aW9uLCB5b3Ugc2hvdWxkIGNsZWFybHkgdW5kZXJzdGFuZCBob3cgdGhlc2Ugc2VydmljZXMgY291bGQgYmUgcHVyY2hhc2VkIGFuZCB3aGF0IHRoZQ0KbWFudWZhY3R1cmVyIGhhcyB0byBvZmZlci4gQW5vdGhlciBpbXBvcnRhbnQgaXNzdWUgZm9yIHRoaXMgdGFyZ2V0IGdyb3VwIGlzDQp0aGUgZWFzZSBvZiBhZG1pbmlzdHJhdGlvbiBhbmQgdXNhZ2Ugb2YgYmFzaWMgZnVuY3Rpb25zLjwvcD4NCg0KPHA+QW5vdGhlciBncm91cCBvZg0KdXNlcnMgYXJlIDxlbT53ZWIgZGV2ZWxvcGVyczwvZW0+DQphbmQgPGVtPmRlc2lnbmVyczwvZW0+DQp3aG8gYXJlIHRlY2huaWNhbGx5IHNraWxsZWQgYW5kIHVzdWFsbHkgbWFpbnRhaW4gdGhlIHN0b3JlIGJ5IHRoZW1zZWx2ZXMgb3INCmRldmVsb3AgZS1jb21tZXJjZSBzb2x1dGlvbnMgZm9yIHRoZWlyIGNsaWVudHMgKHdoaWNoIHVzdWFsbHkgaW52b2x2ZXMgY29tcGxleA0KY29kZSBjaGFuZ2VzIGFuZCBkZXZlbG9wbWVudCBvZiBleHRyYSBmdW5jdGlvbmFsaXR5KS4gRm9yIHRoZXNlIHBlb3BsZSwgdGhlDQptb3N0IGltcG9ydGFudCBmYWN0b3JzIGFyZTogdGhlIHF1YWxpdHkgb2YgY29kZSwgdGhlIGVhc2Ugb2YgY3VzdG9taXphdGlvbg0KYW5kIGFkZC1vbnMgaW1wbGVtZW50YXRpb24gYW5kIGZsZXhpYmlsaXR5IG9mIHN0b3JlZnJvbnQgZGVzaWduLjwvcD4NCg0KPGgzPlR5cGVzIG9mIHNob3BwaW5nIGNhcnRzPC9oMz4NCg0KPHA+QWxsIHNob3BwaW5nIGNhcnQNCnNvbHV0aW9ucyBjYW4gYmUgZGl2aWRlZCBpbnRvIHR3byBsYXJnZSBncm91cHM6IGhvc3RlZCBhbmQgZGlzdHJpYnV0ZWQuPC9wPg0KDQo8cD48ZW0+SG9zdGVkPC9lbT4gY2FydHMNCmFyZSB1c3VhbGx5IHByb3ZpZGVkIGluIHRoZSBzYW1lIG1hbm5lciBhcyBob3N0aW5nIHNlcnZpY2VzLCB3aGljaCBtZWFucyB0aGF0IGENCmN1c3RvbWVyIGhhcyBzZXZlcmFsIHByZWRlZmluZWQgcGxhbnMvcGFja2FnZXMgKHZhcnlpbmcgaW4gbnVtYmVyIG9mIHByb2R1Y3RzLA0KbW9udGhseSBiYW5kd2lkdGgsIG51bWJlciBvZiBmZWF0dXJlcywgZXRjKSB0byBjaG9vc2UgZnJvbS4gVGhlIHByaWNpbmcNCnN0cnVjdHVyZSBpcyBhbHNvIGJhc2VkIG9uIHJlZ3VsYXIgKG1vbnRobHkgb3IgeWVhcmx5KSBmZWVzLiBBIGhvc3RpbmcgcGxhdGZvcm0NCmlzIHByb3ZpZGVkIGRpcmVjdGx5IGZyb20gdGhlIG1hbnVmYWN0dXJlciBhbmQgdGhlIGNhcnQgaXMgdXN1YWxseSBhY3RpdmF0ZWQNCndpdGhvdXQgYW55IGFjdGlvbnMgbmVlZGVkIGZyb20gYSBjbGllbnQuPC9wPg0KDQo8cD5Ib3N0ZWQgc2hvcHBpbmcNCmNhcnRzIGFyZSBtYW5hZ2VkIHRocm91Z2ggdGhlIGFkbWluaXN0cmF0aW9uIGFyZWEgd2hpY2ggcHJvdmlkZXMgdGhlIGludGVyZmFjZQ0KdG8gbWFuYWdlIHByb2R1Y3QgY2F0YWxvZyAoYWRkLCByZW1vdmUgaXRlbXMgYW5kIGVkaXQgdGhlaXIgcHJvcGVydGllcyksIGRlZmluZQ0KYW5kIGNoYW5nZSBwcmljZXMgYW5kIHNvIG9uLiBUaGUgc3RvcmVmcm9udCBkZXNpZ24gY2FuIHVzdWFsbHkgYmUgYWx0ZXJlZCBieQ0KbW9kaWZ5aW5nIHRlbXBsYXRlcywgaG93ZXZlciwgdGhlIGFjY2VzcyB0byB0aGUgc291cmNlIGNvZGUgZm9yIGhvc3RlZA0Kc29sdXRpb25zIGlzIHVzdWFsbHkgbGltaXRlZCBhbmQgaXQncyBub3QgYWx3YXlzIHBvc3NpYmxlIHRvIG1vZGlmeSB0aGUNCmZ1bmN0aW9uYWxpdHkuPC9wPg0KDQo8cD48ZW0+RGlzdHJpYnV0ZWQ8L2VtPiBzb2x1dGlvbnMgYXJlDQpzb2xkIGF0IGEgZml4ZWQgcHJpY2UgKG9uZS10aW1lIGZlZSBmb3IgYSBsaWZldGltZSBsaWNlbnNlKSBhcyBhIHNvZnR3YXJlDQpwYWNrYWdlIHdoaWNoIHNob3VsZCBpbnN0YWxsZWQgb24gYW55IGNvbXBhdGlibGUgc2VydmVyIGNob3Nlbg0KYnkgYSBjdXN0b21lci4gQWZ0ZXIgdGhlIGluaXRpYWwgc2V0dXAsIHRoZSBzdG9yZSBjYW4gYWxzbyBiZSBtYW5hZ2VkIHVzaW5nIHRoZQ0KYWRtaW5pc3RyYXRpb24gYXJlYS48L3A+DQoNCjxwPlVzdWFsbHkgc3VjaA0KcHJvZHVjdHMgY29tZSB3aXRoIHNvdXJjZSBjb2RlIGFuZCB0aHVzIGNhbiBiZSBtb2RpZmllZCBvciBleHRlbmRlZCB0bw0Kc3VpdCB5b3VyIG5lZWRzLiBIb3dldmVyLCBzdWNoIG1vZGlmaWNhdGlvbnMgcmVxdWlyZSBnb29kIHRlY2huaWNhbCBhbmQNCnByb2dyYW1taW5nIGtub3dsZWRnZSAob3Igd29ya2luZyB3aXRoIHRob3NlIHRoYXQgaGF2ZSB0aG9zZSBza2lsbHMpLjwvcD4NCg0KPHA+T3ZlcmFsbCwNCmhvc3RlZCBjYXJ0cyBhcmUgb2Z0ZW4gcHJlZmVyYWJsZSBmb3Igc3RvcmUgb3duZXJzIGFzIG1vcmUgZWFzeSB0byB1c2UgYW5kDQphZG1pbmlzdGVyIHdoaWxlIHdlYiBwcm9ncmFtbWVycywgZGVzaWduZXJzIGFuZCBkZXZlbG9wZXJzIG1vc3RseSBjaG9vc2UNCmRpc3RyaWJ1dGVkIHNvbHV0aW9ucyBkdWUgdG8gdGhlaXIgZmxleGliaWxpdHkuPC9wPg0KDQo8aDM+QWRkaXRpb25hbCBzZXJ2aWNlczwvaDM+DQoNCjxwPldoaWxlIG1vc3QNCnNob3BwaW5nIGNhcnQgZmVhdHVyZXMgY2FuIG9mdGVuIGJlIHVzZWQgcmlnaHQgb3V0IG9mIHRoZSBib3gsIGl0J3MgaW1wb3J0YW50DQp0byBub3RlIHRoYXQgaW4gbW9zdCBjYXNlcyBvbmxpbmUgc3RvcmVzIHJlcXVpcmUgc29tZSBhZGRpdGlvbmFsIHByb2Zlc3Npb25hbA0Kc2VydmljZXMuPC9wPg0KDQo8cD5Gb3IgZXhhbXBsZSwgZS1jb21tZXJjZSBzb2Z0d2FyZSBtYXkgY29tZSB3aXRoIGEgbnVtYmVyIG9mIHByZS1pbnN0YWxsZWQgZGVzaWduIHRlbXBsYXRlcywNCmJ1dCBhIHNlcmlvdXMgc3RvcmUgb3duZXIgd291bGQgdXN1YWxseSBoYXZlIGl0cyBvd24gdW5pcXVlIHN0b3JlDQpsb29rIG9yIGludGVncmF0aW5nIGl0J3MgZXhpc3RpbmcgZGVzaWduIGludG8gdGhlIHN0b3JlZnJvbnQuIEFsc28sIHNpbmNlDQppdCdzIGltcG9zc2libGUgZm9yIGFuIGVjb21tZXJjZSBwcm9kdWN0IGNvbnRhaW5pbmcgZWFjaCBhbmQgZXZlcnkNCnBvc3NpYmxlIGZlYXR1cmUgb3Igd29ya2luZyB0aGUgd2F5IHdoaWNoIGlzIHRvdGFsbHkgc3VpdGFibGUgZm9yIGV2ZXJ5b25lLCBhDQpzaG9wcGluZyBjYXJ0IG1hbnVmYWN0dXJlciBwcm92aWRpbmcgY3VzdG9tIHByb2dyYW1taW5nIHNlcnZpY2UgaXMgYSBnb29kIG9wdGlvbg0KaW4gY2FzZSB5b3UncmUgcGxhbm5pbmcgdG8gaW1wbGVtZW50IHNvbWUgZXh0ZW5kZWQgZnVuY3Rpb25hbGl0eS48L3A+DQoNCjxwPkFub3RoZXIgb3B0aW9uDQp3b3J0aCBjaGVja2luZyBpcyB3aGV0aGVyIGl0J3MgcG9zc2libGUgdG8gZ2V0IGEgZnVsbHktY29tcGF0aWJsZSBob3N0aW5nDQpzb2x1dGlvbiAoc2luY2Ugc2hvcHBpbmcgY2FydHMgdXN1YWxseSBoYXZlIHNpZ25pZmljYW50IHNlcnZlci1zaWRlDQpyZXF1aXJlbWVudHMgZHVlIHRvIHRoZWlyIGNvbXBsZXhpdHkpIGFuZCB0ZWNobmljYWwgc3VwcG9ydCAoaW4gY2FzZSB5b3UgbmVlZA0KY29uc3VsdGF0aW9ucyBvciBhc3Npc3RhbmNlIGluIHByb2JsZW0gcmVzb2x1dGlvbikuPC9wPg0KDQo8aDM+SW50ZWdyYXRpb24gd2l0aCBleHRlcm5hbCBzeXN0ZW1zPC9oMz4NCg0KPHA+RWNvbW1lcmNlDQpzb2Z0d2FyZSBzaG91bGQgbm90IGJlIHRyZWF0ZWQgYXMgYSBzdGFuZGFsb25lIHByb2R1Y3QsIGJ1dCByYXRoZXIgYXMgYSBzb2xpZA0KZ3JvdW5kIGZvciBpbnRlcmFjdGlvbiBiZXR3ZWVuIHZhcmlvdXMgY29tcG9uZW50cy48L3A+DQoNCjxwPk5vdCBhbGwNCm9wZXJhdGlvbnMgYXJlIHBlcmZvcm1lZCB3aXRoaW4gdGhlIHNob3BwaW5nIGNhcnQgZW5naW5lLiBNb3N0IG9mdGVuLCBleHRlcm5hbA0Kc2VydmljZXMgYXJlIHVzZWQgZm9yIHBheW1lbnQgcHJvY2Vzc2luZywgcmVhbC10aW1lIHNoaXBwaW5nIHJhdGVzIGNhbGN1bGF0aW9uLA0Kb3JkZXIgcHJvY2Vzc2luZyBzeXN0ZW1zLCBhZmZpbGlhdGUgYW5kIHN0YXRpc3RpY3Mgc29mdHdhcmUsIHByb2R1Y3QgZGlyZWN0b3JpZXMNCmFuZCBzbyBvbi48L3A+DQoNCjxwPlRodXMsIHRoZQ0KcmljaG5lc3Mgb2YgaW50ZWdyYXRpb24gYWxsb3dzIHN0b3JlIG93bmVycyB0byBoYXZlIGEgd2lkZXIgY2hvaWNlIG9mIHNlcnZpY2VzDQpmb3IgdGhlaXIgb25saW5lIGJ1c2luZXNzLjwvcD4NCg0KPGgzPlRlY2huaWNhbCBzdXBwb3J0LCBmb3J1bSAmYW1wOyB0aGlyZC1wYXJ0eSBzb2x1dGlvbnM8L2gzPg0KDQo8cD5SZXNwb25zaXZlDQp0ZWNobmljYWwgc3VwcG9ydCBpcyBhbm90aGVyIGtleSBmYWN0b3Igd2hpY2ggZW5zdXJlcyB0aGF0IHlvdSdyZSBub3QgbGVmdA0KYWxvbmUgd2l0aCB5b3VyIHByb2JsZW1zIGFuZCwgaW4gY2FzZSB0aGUgYXNzaXN0YW5jZSBpcyBuZWVkZWQsIHlvdSBjYW4gYmUgc3VyZQ0KdG8gcmVjZWl2ZSBhIHRob3VnaHRmdWwgcmVzcG9uc2Ugb3IgYSBzb2x1dGlvbiBpbiBhIHJlYXNvbmFibGUgYW1vdW50IG9mIHRpbWUuPC9wPg0KDQo8cD5TdXBwb3J0IHNjaGVtZXMNCmZyb20gZGlmZmVyZW50IGNvbXBhbmllcyBtYXkgdmFyeSBpbiB0eXBlIGFuZCBjb3N0cy4gRm9yIHNob3BwaW5nDQpjYXJ0IHZlbmRvcnMsIHRlY2huaWNhbCBzdXBwb3J0IGlzIG9mdGVuIG9uIGEgcGF5LXBlci1pbmNpZGVudCBiYXNpcywNCm9yIHllYXJseS9tb250aGx5IGZsYXQtZmVlIGNvbnRyYWN0LiBGcmVlIHRlY2huaWNhbCBzdXBwb3J0IGZvciBlY29tbWVyY2UNCnNvbHV0aW9ucyBpcyBxdWl0ZSByYXJlIGFuZCBtYXkgbm90IGFsd2F5cyBiZSBlZmZlY3RpdmUgb3IgdGltZWx5LjwvcD4NCg0KPHA+Rm9ydW0gYWN0aXZpdHkgaXMNCmFsc28gYSBnb29kIGluZGljYXRvciBzaW5jZSBpdCBjYW4gYmUgYSBnb29kLCBmcmVlIHNvdXJjZSBvZiBrbm93bGVkZ2UgYW5kDQphc3Npc3RhbmNlIGZyb20gZXhwZXJpZW5jZSBzb2Z0d2FyZSB1c2Vycy48L3A+DQoNCjxwPkluIGFkZGl0aW9uLCBpdA0KaXMgYWR2aXNhYmxlIHRvIGNoZWNrIGlmIHRoaXJkLXBhcnR5IHZlbmRvcnMgb2ZmZXIgbW9kdWxlcyBvciBzZXJ2aWNlcyByZWxhdGVkDQp0byBhIGNob3NlbiBlLWNvbW1lcmNlIHByb2R1Y3QgdG8gZW5zdXJlIHRoYXQgeW91IHdpbGwgaGF2ZSBhIGRlY2VudCBjaG9pY2Ugb2YNCmV4dHJhIHNvbHV0aW9ucy48L3A+DQoNCjxoMj48YSBuYW1lPUE1PjwvYT5UaXBzIGFuZCBhZHZpY2UgZm9yIHJlc2VhcmNoPC9oMj4NCg0KPGgzPlJlcXVpcmVtZW50czwvaDM+DQoNCjxwPkZpcnN0IG9mIGFsbCwNCmJlZm9yZSBwcm9jZWVkaW5nIHdpdGggdGhlIGFjdHVhbCBwcm9kdWN0IHJlc2VhcmNoLCBJJ2QgYWR2aXNlIHRoYXQgeW91IGNvbGxlY3QNCnRoZSBsaXN0IG9mIGtleSBmZWF0dXJlcyB3aGljaCBhcmUgbmVjZXNzYXJ5IGZvciB5b3VyIHVwY29taW5nIG9ubGluZSBzdG9yZS4NClN1Y2ggYSBjaGVja2xpc3Qgd2lsbCBhbGxvdyB5b3UgdG8gZW5zdXJlIHRoYXQgYWxsIChvciBtb3N0KSBvZiB0aGVtIGFyZQ0KcHJlc2VudCB3aGlsZSBleGFtaW5pbmcgZmVhdHVyZXMgbGlzdHMgZm9yIGNob3NlbiBjYW5kaWRhdGVzLjwvcD4NCg0KPGgzPkxvb2tpbmcgaW4NCnNlYXJjaCBlbmdpbmVzIHVzaW5nIHJlbGV2YW50IHF1ZXJpZXM8L2gzPg0KDQo8cD5OZXh0LCB5b3UgbWF5DQpwcm9jZWVkIHdpdGggcGlja2luZyBwcm9kdWN0cyBmb3IgY29tcGFyaXNvbi4gVG8gZmluZCB0aGUgbW9zdCBwb3B1bGFyDQpzb2x1dGlvbnMsIHN0YXJ0IHNlYXJjaGluZyBpbiBHb29nbGUvWWFob28vTVNOIHVzaW5nIHJlbGV2YW50IHNlYXJjaCBwaHJhc2VzDQpjaGFyYWN0ZXJpemluZyB0aGUgcHJvZHVjdCwgbGlrZSAmcXVvdDtzaG9wcGluZyBjYXJ0IHNvZnR3YXJlJnF1b3Q7LA0KJnF1b3Q7ZWNvbW1lcmNlIHNvbHV0aW9uJnF1b3Q7LCAmcXVvdDtvbmxpbmUgc3RvcmUgYnVpbGRlciZxdW90OyBldGMuPC9wPg0KDQo8cD5Gb3IgZWFjaCBxdWVyeSwNCnBpY2sgcHJvZHVjdHMgZnJvbSB0b3AgdGVuIG9yIHRvcCB0d2VudHkgc2VhcmNoIHJlc3VsdHMuIFZpc2l0IHRoZWlyIHdlYnNpdGVzLA0KY29tcGFyZSBwcm9kdWN0IGZlYXR1cmVzIGFuZCBzZXJ2aWNlcyBwcmVzZW50ZWQgdGhlcmUsIHByaWNpbmcgYW5kIGFueSBvdGhlcg0KaW5mb3JtYXRpb24gdGhhdCB5b3UgbWF5IGNvbnNpZGVyIHJlbGV2YW50LjwvcD4NCg0KPGgzPkxvb2tpbmcgZm9yIHJldmlld3MNCmFuZCBjb21tZW50cyBvbiBmb3J1bXMgYW5kIGRpcmVjdG9yaWVzPC9oMz4NCg0KPHA+Rm9yIGVhY2ggcHJvZHVjdA0KaW4geW91ciBsaXN0LCB5b3Ugd291bGQgc3VyZWx5IGJlIGludGVyZXN0ZWQgdG8ga25vdyB3aGF0IG90aGVycyBoYXZlIHRvIHNheS4NCkluIHRoaXMgY2FzZSwgaW5kZXBlbmRlbnQgc291cmNlcyBwcm92aWRlIHZhbHVhYmxlIGFkZGl0aW9ucyB0byBvZmZpY2lhbA0KaW5mb3JtYXRpb24gZnJvbSBzb2Z0d2FyZSB2ZW5kb3JzLjwvcD4NCg0KPHA+TW9zdCBsaWtlbHksDQpwcm9kdWN0IHByb2ZpbGVzIGFsb25nIHdpdGggY3VzdG9tZXIgcmV2aWV3cyBjYW4gYmUgZm91bmQgb24gbGFyZ2Ugc2NyaXB0IGFuZA0Kc29mdHdhcmUgbGlicmFyaWVzIGxpa2UgPGEgaHJlZj0iaHR0cDovL2hvdHNjcmlwdHMuY29tLyI+SG90U2NyaXB0czwvYT4sIDxhDQpocmVmPSJodHRwOi8vZnJlc2htZWF0Lm5ldC8iPkZyZXNobWVhdDwvYT4gYW5kIDxhIGhyZWY9Imh0dHA6Ly9kb3dubG9hZC5jb20vIj5Eb3dubG9hZC5jb208L2E+Lg0KQWxzbywgY2hlY2sgb3V0IHNvbWUgY29tcGFyaXNvbiBzaXRlcywgZm9yIGV4YW1wbGUsIDxhDQpocmVmPSJodHRwOi8vZXBpbmlvbnMuY29tLyI+RXBpbmlvbnM8L2E+IGFuZCA8YQ0KaHJlZj0iaHR0cDovL3d3dy5zaG9wcGluZy1jYXJ0LXJldmlldy50b3B0ZW5yZXZpZXdzLmNvbS8iPlNob3BwaW5nIENhcnQgUmV2aWV3czwvYT4uDQpBbHNvLCB5b3UgbWF5IHNlYXJjaCB0aHJvdWdoIGFyY2hpdmVzIG9yIHN0YXJ0IGEgbmV3IHRocmVhZCB3aXRoIHlvdXIgcXVlc3Rpb25zDQphdCBwb3B1bGFyIElUIGZvcnVtcywgbGlrZSA8YQ0KaHJlZj0iaHR0cDovL3d3dy5zaXRlcG9pbnQuY29tL2ZvcnVtcy9mb3J1bWRpc3BsYXkucGhwP2Y9NSI+U2l0ZVBvaW50PC9hPiBvciA8YQ0KaHJlZj0iaHR0cDovL3d3dy53ZWJtYXN0ZXJ3b3JsZC5jb20vIj5XZWJtYXN0ZXJXb3JsZDwvYT4uPC9wPg0KDQo8aDM+Q29udGFjdGluZyBzYWxlcyBkZXBhcnRtZW50IHdpdGggeW91ciBxdWVzdGlvbnM8L2gzPg0KDQo8cD5GaW5hbGx5LCBJJ20gc3VyZQ0KdGhhdCBmb3IgeW91ciBzaG9ydCBsaXN0IG9mIHNvbHV0aW9ucywgc29tZQ0KcXVlc3Rpb25zIG1heSBzdGlsbCByZW1haW4uIFRoaXMgaXMgYSBnb29kIHJlYXNvbiB0byBjb250YWN0IGEgdmVuZG9yJ3Mgc2FsZXMNCnRlYW0gdG8gZmluZCBvdXQgdGhlaXIgcmVzcG9uc2VzLiBEbyBub3QgaGVzaXRhdGUgdG8gZG8gaXQsIHNpbmNlIHRoZSBxdWFsaXR5DQpvZiBmZWVkYmFjayBhbmQgYXR0ZW50aW9uIHRvIHlvdSBhcyBhIHBvdGVudGlhbCBjbGllbnQgaXMgd29ydGggY2hlY2tpbmcgYmVmb3JlDQp5b3UgYWN0dWFsbHkgcHJvY2VlZCB3aXRoIHRoZSBwdXJjaGFzZS48L3A+DQoNCjxoMj5Db25jbHVzaW9uPC9oMj4NCg0KPHA+Q2hvb3Npbmcgc2hvcHBpbmcgY2FydCBzb2Z0d2FyZSBtYXkgbm90IHNlZW0gZWFzeSBzaW5jZSBpdCBpbnZvbHZlcyBzaWduaWZpY2FudA0KZWZmb3J0IGZyb20gYSBzZXJpb3VzIGN1c3RvbWVyLiBIb3dldmVyLCB0aGUgcmV3YXJkcyBmb3IgdGhlIGVmZm9ydCBpcyBvYnZpb3VzOiB5b3UgZ2V0IGEgcHJvZHVjdCB3aGljaCBmaXRzIGludG8geW91ciBnb2FscyBhbmQgYWxsb3dzIHlvdSB0bw0KY29uY2VudHJhdGUgb24gc2FsZXMgYW5kIG1hcmtldGluZyB3aXRob3V0IHdvcnJ5aW5nIGFib3V0IHRoZSB0ZWNobmljYWwgc2lkZS4NCk1vcmVvdmVyLCBhcyBhIGNsaWVudCwgeW91IGdldCB0byBrbm93IHRoZSBzb2Z0d2FyZSB2ZW5kb3IgYmVmb3JlIGJ1eWluZyBhDQpwcm9kdWN0IGFuZCBlbnN1cmUgdGhhdCB0aGUgdGVjaG5pY2FsIHNpZGUgY2FuIGJlIGhhbmRsZWQgd2l0aG91dCBhIHByb2JsZW0uPC9wPg0KDQo8cD5BcyBhIHBvc3NpYmxlIG9wdGlvbiwNCkknZCBsaWtlIHRvIHN1Z2dlc3QgdGhhdCB5b3UgdGFrZSBhIGxvb2sgYXQgZWNvbW1lcmNlIHByb2R1Y3RzIGZyb20gdGhlIGNvbXBhbnkNCkkgd29yayBmb3IsIDxhIGhyZWY9Imh0dHA6Ly9xdWFsaXRlYW0uYml6LyI+UXVhbGl0ZWFtIFNvZnR3YXJlPC9hPi4gV2UgYXJlIHRoZQ0KbWFrZXJzIG9mIHR3byBQSFAgc2hvcHBpbmcgY2FydHMsIDxhIGhyZWY9Imh0dHA6Ly94LWNhcnQuY29tLyI+WC1DYXJ0PC9hPiBhbmQgPGENCmhyZWY9Imh0dHA6Ly9saXRlY29tbWVyY2UuY29tLyI+TGl0ZUNvbW1lcmNlPC9hPi4gQm90aCBvZiBvdXIgc29sdXRpb25zIGNvbWUNCndpdGggYW4gb3BlbiBzb3VyY2UgY29kZSBhbmQgY2FuIGJlIHVzZWQgYm90aCBhcyByZWFkeSBvdXQtb2YtdGhlLWJveCBzaG9wcGluZw0KY2FydCBzb2x1dGlvbnMgYW5kIHBvd2VyZnVsIHNob3BwaW5nIGNhcnQgZW5naW5lcyBmb3IgYSBjdXN0b21pemVkIHdlYiBzaG9wLiBXZQ0KYWxzbyBwcm92aWRlIHRoZSB3aG9sZSByYW5nZSBvZiBleHRyYSBzZXJ2aWNlcywgaW5jbHVkaW5nIChidXQgbm90IGxpbWl0ZWQgdG8pOg0Kc2hvcHBpbmcgY2FydCBob3N0aW5nLCBlLWNvbW1lcmNlIHdlYiBzaXRlIGRlc2lnbiwgY3VzdG9tIGRldmVsb3BtZW50LA0KaW5zdGFsbGF0aW9uIHNlcnZpY2VzICZhbXA7IDI0LzcgdGVjaG5pY2FsIHN1cHBvcnQuPC9wPg0KDQo8cD5Hb29kIGx1Y2sgaW4geW91cg0KcmVzZWFyY2ghPC9wPg0KZGQCAg8PFgIfAAXFUjxoMT5DaG9vc2luZyBzaG9wcGluZyBjYXJ0IHNvZnR3YXJlPC9oMT48cD48ZW0+YnkgTWljaGFlbCBHdW5pbiwgPC9lbT48YSBocmVmPSJodHRwOi8vcXVhbGl0ZWFtLmJpei8iPlF1YWxpdGVhbSBTb2Z0d2FyZTwvYT4uPC9wPg0KDQo8aDI+PGEgbmFtZT1BMz48L2E+SW50cm9kdWN0aW9uPC9oMj4NCg0KPHA+PHN0cm9uZz5DaG9vc2luZyBzaG9wcGluZyBjYXJ0DQpzb2Z0d2FyZSBjYW4gdHVybiBpbnRvIGEgdG91Z2ggam9iIGR1ZSB0byB0aGUgbGFyZ2UgbnVtYmVyIG9mIGUtY29tbWVyY2UNCnNvbHV0aW9ucyBhdmFpbGFibGUgb24gdGhlIG1hcmtldC4gT3ZlcmFsbCwgaXQncyBhbG1vc3QgaW1wb3NzaWJsZSB0byBzYXkgd2hpY2gNCnByb2R1Y3QgaXMgdGhlIGJlc3Qgb25lIHNpbmNlIHRoZWlyIGZlYXR1cmUgcmljaG5lc3MsIHByaWNpbmcsIGZsZXhpYmlsaXR5IGFuZA0KdGhlIHJhbmdlIG9mIGV4dHJhIHNlcnZpY2VzIHZhcnkgdG8gYSBncmVhdCBleHRlbnQuPC9zdHJvbmc+PC9wPg0KDQo8cD5UaGVyZWZvcmUsIGJ1eWluZw0KdGhlIHJpZ2h0IHByb2R1Y3Qgd2hpY2ggZml0cyBpbnRvIHlvdXIgZ29hbHMgY2FuIHNhdmUgYSBsb3Qgb2YgdGltZSBhbmQNCmVmZm9ydCwgd2hpbGUgYSBtaXN0YWtlIG1heSB0dXJuIGludG8gZXh0cmEgY29zdHMsIGFkZGl0aW9uYWwgbW9udGhzIG9mDQp3b3JrIG9yIGV2ZW4gY2F1c2Ugc3RhcnRpbmcgdGhlIHdob2xlIHByb2plY3QgZnJvbSBzY3JhdGNoLjwvcD4NCg0KPHA+VGhlcmUgYXJlIHNldmVyYWwNCmtleSBmYWN0b3JzIHdoaWNoIHNob3VsZCBiZSBjb25zaWRlcmVkIHdoaWxlIHBpY2tpbmcgdGhlIHJpZ2h0IHNvbHV0aW9uLiBJbiB0aGlzDQphcnRpY2xlLCBJJ2xsIHRyeSB0byBvdXRsaW5lIHRoZSBtb3N0IGltcG9ydGFudCBzdGVwcyB0aGF0IGRlZmluaXRlbHkgc2hvdWxkDQpub3QgYmUgbWlzc2VkLiBUaGUgdGFjdGljcyBkZXNjcmliZWQgYmVsb3cNCm1heSBiZSB2YXJpZWQgYWNjb3JkaW5nIHRvIHlvdXIgZ29hbHMsIGhvd2V2ZXIsIGZvbGxvd2luZyB0aGlzIGFkdmljZSB3aWxsDQpiZSB1c2VmdWwgaW4gdGhlIGRlY2lzaW9uLW1ha2luZyBwcm9jZXNzIGFzIGEgd2hvbGUuPC9wPg0KDQoNCg0KDQo8aDI+PGEgbmFtZT1BND48L2E+S2V5IGdyb3VwcyBvZiBmYWN0b3JzPC9oMj4NCg0KPGgzPldobyB5b3UgYXJlPC9oMz4NCg0KPHA+SW4gbXkgb3BpbmlvbiwNCnRoZSBmaXJzdCB0aGluZyB5b3Ugc2hvdWxkIGFzayBpcyB0aGUgcm9sZSBoZSdzIGdvaW5nIHRvIHBsYXkgaW4NCnRoZSBvbmxpbmUgc3RvcmUgZnVuY3Rpb25pbmcgcHJvY2Vzcy4gVGhlIGtleSBmYWN0b3Igb2YgdGhpcyByb2xlIChhdCBsZWFzdCBmb3INCnNtYWxsIGFuZCBtZWRpdW0gYnVzaW5lc3NlcykgaXMgdGhlIGxldmVsIG9mIGEgcGVyc29uJ3MgdGVjaG5pY2FsIGtub3dsZWRnZS48L3A+DQoNCjxwPkluIG1vc3QgY2FzZXMsDQp0ZWNobm9sb2d5IGlzIGFuIGlzc3VlIGZvciA8ZW0+c3RvcmUNCm93bmVyczwvZW0+LCA8ZW0+bWFuYWdlcnM8L2VtPg0KYW5kIDxlbT5hZG1pbmlzdHJhdG9yczwvZW0+Lg0KU2luY2UgZWFjaCBzdG9yZSBuZWVkcyBpdHMgb3duIHVuaXF1ZSBkZXNpZ24sIGZ1bmN0aW9uYWxpdHkgYW5kDQpzdG9yZWZyb250IGRlc2lnbiBhbG9uZyB3aXRoIHRoZSBpbml0aWFsIHNldHVwIGFuZCBzZXJ2ZXIgYWRtaW5pc3RyYXRpb24sIHlvdSBzaG91bGQgY2xlYXJseSB1bmRlcnN0YW5kIGhvdyB0aGVzZSBzZXJ2aWNlcyBjb3VsZCBiZSBwdXJjaGFzZWQgYW5kIHdoYXQgdGhlDQptYW51ZmFjdHVyZXIgaGFzIHRvIG9mZmVyLiBBbm90aGVyIGltcG9ydGFudCBpc3N1ZSBmb3IgdGhpcyB0YXJnZXQgZ3JvdXAgaXMNCnRoZSBlYXNlIG9mIGFkbWluaXN0cmF0aW9uIGFuZCB1c2FnZSBvZiBiYXNpYyBmdW5jdGlvbnMuPC9wPg0KDQo8cD5Bbm90aGVyIGdyb3VwIG9mDQp1c2VycyBhcmUgPGVtPndlYiBkZXZlbG9wZXJzPC9lbT4NCmFuZCA8ZW0+ZGVzaWduZXJzPC9lbT4NCndobyBhcmUgdGVjaG5pY2FsbHkgc2tpbGxlZCBhbmQgdXN1YWxseSBtYWludGFpbiB0aGUgc3RvcmUgYnkgdGhlbXNlbHZlcyBvcg0KZGV2ZWxvcCBlLWNvbW1lcmNlIHNvbHV0aW9ucyBmb3IgdGhlaXIgY2xpZW50cyAod2hpY2ggdXN1YWxseSBpbnZvbHZlcyBjb21wbGV4DQpjb2RlIGNoYW5nZXMgYW5kIGRldmVsb3BtZW50IG9mIGV4dHJhIGZ1bmN0aW9uYWxpdHkpLiBGb3IgdGhlc2UgcGVvcGxlLCB0aGUNCm1vc3QgaW1wb3J0YW50IGZhY3RvcnMgYXJlOiB0aGUgcXVhbGl0eSBvZiBjb2RlLCB0aGUgZWFzZSBvZiBjdXN0b21pemF0aW9uDQphbmQgYWRkLW9ucyBpbXBsZW1lbnRhdGlvbiBhbmQgZmxleGliaWxpdHkgb2Ygc3RvcmVmcm9udCBkZXNpZ24uPC9wPg0KDQo8aDM+VHlwZXMgb2Ygc2hvcHBpbmcgY2FydHM8L2gzPg0KDQo8cD5BbGwgc2hvcHBpbmcgY2FydA0Kc29sdXRpb25zIGNhbiBiZSBkaXZpZGVkIGludG8gdHdvIGxhcmdlIGdyb3VwczogaG9zdGVkIGFuZCBkaXN0cmlidXRlZC48L3A+DQoNCjxwPjxlbT5Ib3N0ZWQ8L2VtPiBjYXJ0cw0KYXJlIHVzdWFsbHkgcHJvdmlkZWQgaW4gdGhlIHNhbWUgbWFubmVyIGFzIGhvc3Rpbmcgc2VydmljZXMsIHdoaWNoIG1lYW5zIHRoYXQgYQ0KY3VzdG9tZXIgaGFzIHNldmVyYWwgcHJlZGVmaW5lZCBwbGFucy9wYWNrYWdlcyAodmFyeWluZyBpbiBudW1iZXIgb2YgcHJvZHVjdHMsDQptb250aGx5IGJhbmR3aWR0aCwgbnVtYmVyIG9mIGZlYXR1cmVzLCBldGMpIHRvIGNob29zZSBmcm9tLiBUaGUgcHJpY2luZw0Kc3RydWN0dXJlIGlzIGFsc28gYmFzZWQgb24gcmVndWxhciAobW9udGhseSBvciB5ZWFybHkpIGZlZXMuIEEgaG9zdGluZyBwbGF0Zm9ybQ0KaXMgcHJvdmlkZWQgZGlyZWN0bHkgZnJvbSB0aGUgbWFudWZhY3R1cmVyIGFuZCB0aGUgY2FydCBpcyB1c3VhbGx5IGFjdGl2YXRlZA0Kd2l0aG91dCBhbnkgYWN0aW9ucyBuZWVkZWQgZnJvbSBhIGNsaWVudC48L3A+DQoNCjxwPkhvc3RlZCBzaG9wcGluZw0KY2FydHMgYXJlIG1hbmFnZWQgdGhyb3VnaCB0aGUgYWRtaW5pc3RyYXRpb24gYXJlYSB3aGljaCBwcm92aWRlcyB0aGUgaW50ZXJmYWNlDQp0byBtYW5hZ2UgcHJvZHVjdCBjYXRhbG9nIChhZGQsIHJlbW92ZSBpdGVtcyBhbmQgZWRpdCB0aGVpciBwcm9wZXJ0aWVzKSwgZGVmaW5lDQphbmQgY2hhbmdlIHByaWNlcyBhbmQgc28gb24uIFRoZSBzdG9yZWZyb250IGRlc2lnbiBjYW4gdXN1YWxseSBiZSBhbHRlcmVkIGJ5DQptb2RpZnlpbmcgdGVtcGxhdGVzLCBob3dldmVyLCB0aGUgYWNjZXNzIHRvIHRoZSBzb3VyY2UgY29kZSBmb3IgaG9zdGVkDQpzb2x1dGlvbnMgaXMgdXN1YWxseSBsaW1pdGVkIGFuZCBpdCdzIG5vdCBhbHdheXMgcG9zc2libGUgdG8gbW9kaWZ5IHRoZQ0KZnVuY3Rpb25hbGl0eS48L3A+DQoNCjxwPjxlbT5EaXN0cmlidXRlZDwvZW0+IHNvbHV0aW9ucyBhcmUNCnNvbGQgYXQgYSBmaXhlZCBwcmljZSAob25lLXRpbWUgZmVlIGZvciBhIGxpZmV0aW1lIGxpY2Vuc2UpIGFzIGEgc29mdHdhcmUNCnBhY2thZ2Ugd2hpY2ggc2hvdWxkIGluc3RhbGxlZCBvbiBhbnkgY29tcGF0aWJsZSBzZXJ2ZXIgY2hvc2VuDQpieSBhIGN1c3RvbWVyLiBBZnRlciB0aGUgaW5pdGlhbCBzZXR1cCwgdGhlIHN0b3JlIGNhbiBhbHNvIGJlIG1hbmFnZWQgdXNpbmcgdGhlDQphZG1pbmlzdHJhdGlvbiBhcmVhLjwvcD4NCg0KPHA+VXN1YWxseSBzdWNoDQpwcm9kdWN0cyBjb21lIHdpdGggc291cmNlIGNvZGUgYW5kIHRodXMgY2FuIGJlIG1vZGlmaWVkIG9yIGV4dGVuZGVkIHRvDQpzdWl0IHlvdXIgbmVlZHMuIEhvd2V2ZXIsIHN1Y2ggbW9kaWZpY2F0aW9ucyByZXF1aXJlIGdvb2QgdGVjaG5pY2FsIGFuZA0KcHJvZ3JhbW1pbmcga25vd2xlZGdlIChvciB3b3JraW5nIHdpdGggdGhvc2UgdGhhdCBoYXZlIHRob3NlIHNraWxscykuPC9wPg0KDQo8cD5PdmVyYWxsLA0KaG9zdGVkIGNhcnRzIGFyZSBvZnRlbiBwcmVmZXJhYmxlIGZvciBzdG9yZSBvd25lcnMgYXMgbW9yZSBlYXN5IHRvIHVzZSBhbmQNCmFkbWluaXN0ZXIgd2hpbGUgd2ViIHByb2dyYW1tZXJzLCBkZXNpZ25lcnMgYW5kIGRldmVsb3BlcnMgbW9zdGx5IGNob29zZQ0KZGlzdHJpYnV0ZWQgc29sdXRpb25zIGR1ZSB0byB0aGVpciBmbGV4aWJpbGl0eS48L3A+DQoNCjxoMz5BZGRpdGlvbmFsIHNlcnZpY2VzPC9oMz4NCg0KPHA+V2hpbGUgbW9zdA0Kc2hvcHBpbmcgY2FydCBmZWF0dXJlcyBjYW4gb2Z0ZW4gYmUgdXNlZCByaWdodCBvdXQgb2YgdGhlIGJveCwgaXQncyBpbXBvcnRhbnQNCnRvIG5vdGUgdGhhdCBpbiBtb3N0IGNhc2VzIG9ubGluZSBzdG9yZXMgcmVxdWlyZSBzb21lIGFkZGl0aW9uYWwgcHJvZmVzc2lvbmFsDQpzZXJ2aWNlcy48L3A+DQoNCjxwPkZvciBleGFtcGxlLCBlLWNvbW1lcmNlIHNvZnR3YXJlIG1heSBjb21lIHdpdGggYSBudW1iZXIgb2YgcHJlLWluc3RhbGxlZCBkZXNpZ24gdGVtcGxhdGVzLA0KYnV0IGEgc2VyaW91cyBzdG9yZSBvd25lciB3b3VsZCB1c3VhbGx5IGhhdmUgaXRzIG93biB1bmlxdWUgc3RvcmUNCmxvb2sgb3IgaW50ZWdyYXRpbmcgaXQncyBleGlzdGluZyBkZXNpZ24gaW50byB0aGUgc3RvcmVmcm9udC4gQWxzbywgc2luY2UNCml0J3MgaW1wb3NzaWJsZSBmb3IgYW4gZWNvbW1lcmNlIHByb2R1Y3QgY29udGFpbmluZyBlYWNoIGFuZCBldmVyeQ0KcG9zc2libGUgZmVhdHVyZSBvciB3b3JraW5nIHRoZSB3YXkgd2hpY2ggaXMgdG90YWxseSBzdWl0YWJsZSBmb3IgZXZlcnlvbmUsIGENCnNob3BwaW5nIGNhcnQgbWFudWZhY3R1cmVyIHByb3ZpZGluZyBjdXN0b20gcHJvZ3JhbW1pbmcgc2VydmljZSBpcyBhIGdvb2Qgb3B0aW9uDQppbiBjYXNlIHlvdSdyZSBwbGFubmluZyB0byBpbXBsZW1lbnQgc29tZSBleHRlbmRlZCBmdW5jdGlvbmFsaXR5LjwvcD4NCg0KPHA+QW5vdGhlciBvcHRpb24NCndvcnRoIGNoZWNraW5nIGlzIHdoZXRoZXIgaXQncyBwb3NzaWJsZSB0byBnZXQgYSBmdWxseS1jb21wYXRpYmxlIGhvc3RpbmcNCnNvbHV0aW9uIChzaW5jZSBzaG9wcGluZyBjYXJ0cyB1c3VhbGx5IGhhdmUgc2lnbmlmaWNhbnQgc2VydmVyLXNpZGUNCnJlcXVpcmVtZW50cyBkdWUgdG8gdGhlaXIgY29tcGxleGl0eSkgYW5kIHRlY2huaWNhbCBzdXBwb3J0IChpbiBjYXNlIHlvdSBuZWVkDQpjb25zdWx0YXRpb25zIG9yIGFzc2lzdGFuY2UgaW4gcHJvYmxlbSByZXNvbHV0aW9uKS48L3A+DQoNCjxoMz5JbnRlZ3JhdGlvbiB3aXRoIGV4dGVybmFsIHN5c3RlbXM8L2gzPg0KDQo8cD5FY29tbWVyY2UNCnNvZnR3YXJlIHNob3VsZCBub3QgYmUgdHJlYXRlZCBhcyBhIHN0YW5kYWxvbmUgcHJvZHVjdCwgYnV0IHJhdGhlciBhcyBhIHNvbGlkDQpncm91bmQgZm9yIGludGVyYWN0aW9uIGJldHdlZW4gdmFyaW91cyBjb21wb25lbnRzLjwvcD4NCg0KPHA+Tm90IGFsbA0Kb3BlcmF0aW9ucyBhcmUgcGVyZm9ybWVkIHdpdGhpbiB0aGUgc2hvcHBpbmcgY2FydCBlbmdpbmUuIE1vc3Qgb2Z0ZW4sIGV4dGVybmFsDQpzZXJ2aWNlcyBhcmUgdXNlZCBmb3IgcGF5bWVudCBwcm9jZXNzaW5nLCByZWFsLXRpbWUgc2hpcHBpbmcgcmF0ZXMgY2FsY3VsYXRpb24sDQpvcmRlciBwcm9jZXNzaW5nIHN5c3RlbXMsIGFmZmlsaWF0ZSBhbmQgc3RhdGlzdGljcyBzb2Z0d2FyZSwgcHJvZHVjdCBkaXJlY3Rvcmllcw0KYW5kIHNvIG9uLjwvcD4NCg0KPHA+VGh1cywgdGhlDQpyaWNobmVzcyBvZiBpbnRlZ3JhdGlvbiBhbGxvd3Mgc3RvcmUgb3duZXJzIHRvIGhhdmUgYSB3aWRlciBjaG9pY2Ugb2Ygc2VydmljZXMNCmZvciB0aGVpciBvbmxpbmUgYnVzaW5lc3MuPC9wPg0KDQo8aDM+VGVjaG5pY2FsIHN1cHBvcnQsIGZvcnVtICZhbXA7IHRoaXJkLXBhcnR5IHNvbHV0aW9uczwvaDM+DQoNCjxwPlJlc3BvbnNpdmUNCnRlY2huaWNhbCBzdXBwb3J0IGlzIGFub3RoZXIga2V5IGZhY3RvciB3aGljaCBlbnN1cmVzIHRoYXQgeW91J3JlIG5vdCBsZWZ0DQphbG9uZSB3aXRoIHlvdXIgcHJvYmxlbXMgYW5kLCBpbiBjYXNlIHRoZSBhc3Npc3RhbmNlIGlzIG5lZWRlZCwgeW91IGNhbiBiZSBzdXJlDQp0byByZWNlaXZlIGEgdGhvdWdodGZ1bCByZXNwb25zZSBvciBhIHNvbHV0aW9uIGluIGEgcmVhc29uYWJsZSBhbW91bnQgb2YgdGltZS48L3A+DQoNCjxwPlN1cHBvcnQgc2NoZW1lcw0KZnJvbSBkaWZmZXJlbnQgY29tcGFuaWVzIG1heSB2YXJ5IGluIHR5cGUgYW5kIGNvc3RzLiBGb3Igc2hvcHBpbmcNCmNhcnQgdmVuZG9ycywgdGVjaG5pY2FsIHN1cHBvcnQgaXMgb2Z0ZW4gb24gYSBwYXktcGVyLWluY2lkZW50IGJhc2lzLA0Kb3IgeWVhcmx5L21vbnRobHkgZmxhdC1mZWUgY29udHJhY3QuIEZyZWUgdGVjaG5pY2FsIHN1cHBvcnQgZm9yIGVjb21tZXJjZQ0Kc29sdXRpb25zIGlzIHF1aXRlIHJhcmUgYW5kIG1heSBub3QgYWx3YXlzIGJlIGVmZmVjdGl2ZSBvciB0aW1lbHkuPC9wPg0KDQo8cD5Gb3J1bSBhY3Rpdml0eSBpcw0KYWxzbyBhIGdvb2QgaW5kaWNhdG9yIHNpbmNlIGl0IGNhbiBiZSBhIGdvb2QsIGZyZWUgc291cmNlIG9mIGtub3dsZWRnZSBhbmQNCmFzc2lzdGFuY2UgZnJvbSBleHBlcmllbmNlIHNvZnR3YXJlIHVzZXJzLjwvcD4NCg0KPHA+SW4gYWRkaXRpb24sIGl0DQppcyBhZHZpc2FibGUgdG8gY2hlY2sgaWYgdGhpcmQtcGFydHkgdmVuZG9ycyBvZmZlciBtb2R1bGVzIG9yIHNlcnZpY2VzIHJlbGF0ZWQNCnRvIGEgY2hvc2VuIGUtY29tbWVyY2UgcHJvZHVjdCB0byBlbnN1cmUgdGhhdCB5b3Ugd2lsbCBoYXZlIGEgZGVjZW50IGNob2ljZSBvZg0KZXh0cmEgc29sdXRpb25zLjwvcD4NCg0KPGgyPjxhIG5hbWU9QTU+PC9hPlRpcHMgYW5kIGFkdmljZSBmb3IgcmVzZWFyY2g8L2gyPg0KDQo8aDM+UmVxdWlyZW1lbnRzPC9oMz4NCg0KPHA+Rmlyc3Qgb2YgYWxsLA0KYmVmb3JlIHByb2NlZWRpbmcgd2l0aCB0aGUgYWN0dWFsIHByb2R1Y3QgcmVzZWFyY2gsIEknZCBhZHZpc2UgdGhhdCB5b3UgY29sbGVjdA0KdGhlIGxpc3Qgb2Yga2V5IGZlYXR1cmVzIHdoaWNoIGFyZSBuZWNlc3NhcnkgZm9yIHlvdXIgdXBjb21pbmcgb25saW5lIHN0b3JlLg0KU3VjaCBhIGNoZWNrbGlzdCB3aWxsIGFsbG93IHlvdSB0byBlbnN1cmUgdGhhdCBhbGwgKG9yIG1vc3QpIG9mIHRoZW0gYXJlDQpwcmVzZW50IHdoaWxlIGV4YW1pbmluZyBmZWF0dXJlcyBsaXN0cyBmb3IgY2hvc2VuIGNhbmRpZGF0ZXMuPC9wPg0KDQo8aDM+TG9va2luZyBpbg0Kc2VhcmNoIGVuZ2luZXMgdXNpbmcgcmVsZXZhbnQgcXVlcmllczwvaDM+DQoNCjxwPk5leHQsIHlvdSBtYXkNCnByb2NlZWQgd2l0aCBwaWNraW5nIHByb2R1Y3RzIGZvciBjb21wYXJpc29uLiBUbyBmaW5kIHRoZSBtb3N0IHBvcHVsYXINCnNvbHV0aW9ucywgc3RhcnQgc2VhcmNoaW5nIGluIEdvb2dsZS9ZYWhvby9NU04gdXNpbmcgcmVsZXZhbnQgc2VhcmNoIHBocmFzZXMNCmNoYXJhY3Rlcml6aW5nIHRoZSBwcm9kdWN0LCBsaWtlICZxdW90O3Nob3BwaW5nIGNhcnQgc29mdHdhcmUmcXVvdDssDQomcXVvdDtlY29tbWVyY2Ugc29sdXRpb24mcXVvdDssICZxdW90O29ubGluZSBzdG9yZSBidWlsZGVyJnF1b3Q7IGV0Yy48L3A+DQoNCjxwPkZvciBlYWNoIHF1ZXJ5LA0KcGljayBwcm9kdWN0cyBmcm9tIHRvcCB0ZW4gb3IgdG9wIHR3ZW50eSBzZWFyY2ggcmVzdWx0cy4gVmlzaXQgdGhlaXIgd2Vic2l0ZXMsDQpjb21wYXJlIHByb2R1Y3QgZmVhdHVyZXMgYW5kIHNlcnZpY2VzIHByZXNlbnRlZCB0aGVyZSwgcHJpY2luZyBhbmQgYW55IG90aGVyDQppbmZvcm1hdGlvbiB0aGF0IHlvdSBtYXkgY29uc2lkZXIgcmVsZXZhbnQuPC9wPg0KDQo8aDM+TG9va2luZyBmb3IgcmV2aWV3cw0KYW5kIGNvbW1lbnRzIG9uIGZvcnVtcyBhbmQgZGlyZWN0b3JpZXM8L2gzPg0KDQo8cD5Gb3IgZWFjaCBwcm9kdWN0DQppbiB5b3VyIGxpc3QsIHlvdSB3b3VsZCBzdXJlbHkgYmUgaW50ZXJlc3RlZCB0byBrbm93IHdoYXQgb3RoZXJzIGhhdmUgdG8gc2F5Lg0KSW4gdGhpcyBjYXNlLCBpbmRlcGVuZGVudCBzb3VyY2VzIHByb3ZpZGUgdmFsdWFibGUgYWRkaXRpb25zIHRvIG9mZmljaWFsDQppbmZvcm1hdGlvbiBmcm9tIHNvZnR3YXJlIHZlbmRvcnMuPC9wPg0KDQo8cD5Nb3N0IGxpa2VseSwNCnByb2R1Y3QgcHJvZmlsZXMgYWxvbmcgd2l0aCBjdXN0b21lciByZXZpZXdzIGNhbiBiZSBmb3VuZCBvbiBsYXJnZSBzY3JpcHQgYW5kDQpzb2Z0d2FyZSBsaWJyYXJpZXMgbGlrZSA8YSBocmVmPSJodHRwOi8vaG90c2NyaXB0cy5jb20vIj5Ib3RTY3JpcHRzPC9hPiwgPGENCmhyZWY9Imh0dHA6Ly9mcmVzaG1lYXQubmV0LyI+RnJlc2htZWF0PC9hPiBhbmQgPGEgaHJlZj0iaHR0cDovL2Rvd25sb2FkLmNvbS8iPkRvd25sb2FkLmNvbTwvYT4uDQpBbHNvLCBjaGVjayBvdXQgc29tZSBjb21wYXJpc29uIHNpdGVzLCBmb3IgZXhhbXBsZSwgPGENCmhyZWY9Imh0dHA6Ly9lcGluaW9ucy5jb20vIj5FcGluaW9uczwvYT4gYW5kIDxhDQpocmVmPSJodHRwOi8vd3d3LnNob3BwaW5nLWNhcnQtcmV2aWV3LnRvcHRlbnJldmlld3MuY29tLyI+U2hvcHBpbmcgQ2FydCBSZXZpZXdzPC9hPi4NCkFsc28sIHlvdSBtYXkgc2VhcmNoIHRocm91Z2ggYXJjaGl2ZXMgb3Igc3RhcnQgYSBuZXcgdGhyZWFkIHdpdGggeW91ciBxdWVzdGlvbnMNCmF0IHBvcHVsYXIgSVQgZm9ydW1zLCBsaWtlIDxhDQpocmVmPSJodHRwOi8vd3d3LnNpdGVwb2ludC5jb20vZm9ydW1zL2ZvcnVtZGlzcGxheS5waHA/Zj01Ij5TaXRlUG9pbnQ8L2E+IG9yIDxhDQpocmVmPSJodHRwOi8vd3d3LndlYm1hc3RlcndvcmxkLmNvbS8iPldlYm1hc3RlcldvcmxkPC9hPi48L3A+DQoNCjxoMz5Db250YWN0aW5nIHNhbGVzIGRlcGFydG1lbnQgd2l0aCB5b3VyIHF1ZXN0aW9uczwvaDM+DQoNCjxwPkZpbmFsbHksIEknbSBzdXJlDQp0aGF0IGZvciB5b3VyIHNob3J0IGxpc3Qgb2Ygc29sdXRpb25zLCBzb21lDQpxdWVzdGlvbnMgbWF5IHN0aWxsIHJlbWFpbi4gVGhpcyBpcyBhIGdvb2QgcmVhc29uIHRvIGNvbnRhY3QgYSB2ZW5kb3IncyBzYWxlcw0KdGVhbSB0byBmaW5kIG91dCB0aGVpciByZXNwb25zZXMuIERvIG5vdCBoZXNpdGF0ZSB0byBkbyBpdCwgc2luY2UgdGhlIHF1YWxpdHkNCm9mIGZlZWRiYWNrIGFuZCBhdHRlbnRpb24gdG8geW91IGFzIGEgcG90ZW50aWFsIGNsaWVudCBpcyB3b3J0aCBjaGVja2luZyBiZWZvcmUNCnlvdSBhY3R1YWxseSBwcm9jZWVkIHdpdGggdGhlIHB1cmNoYXNlLjwvcD4NCg0KPGgyPkNvbmNsdXNpb248L2gyPg0KDQo8cD5DaG9vc2luZyBzaG9wcGluZyBjYXJ0IHNvZnR3YXJlIG1heSBub3Qgc2VlbSBlYXN5IHNpbmNlIGl0IGludm9sdmVzIHNpZ25pZmljYW50DQplZmZvcnQgZnJvbSBhIHNlcmlvdXMgY3VzdG9tZXIuIEhvd2V2ZXIsIHRoZSByZXdhcmRzIGZvciB0aGUgZWZmb3J0IGlzIG9idmlvdXM6IHlvdSBnZXQgYSBwcm9kdWN0IHdoaWNoIGZpdHMgaW50byB5b3VyIGdvYWxzIGFuZCBhbGxvd3MgeW91IHRvDQpjb25jZW50cmF0ZSBvbiBzYWxlcyBhbmQgbWFya2V0aW5nIHdpdGhvdXQgd29ycnlpbmcgYWJvdXQgdGhlIHRlY2huaWNhbCBzaWRlLg0KTW9yZW92ZXIsIGFzIGEgY2xpZW50LCB5b3UgZ2V0IHRvIGtub3cgdGhlIHNvZnR3YXJlIHZlbmRvciBiZWZvcmUgYnV5aW5nIGENCnByb2R1Y3QgYW5kIGVuc3VyZSB0aGF0IHRoZSB0ZWNobmljYWwgc2lkZSBjYW4gYmUgaGFuZGxlZCB3aXRob3V0IGEgcHJvYmxlbS48L3A+DQoNCjxwPkFzIGEgcG9zc2libGUgb3B0aW9uLA0KSSdkIGxpa2UgdG8gc3VnZ2VzdCB0aGF0IHlvdSB0YWtlIGEgbG9vayBhdCBlY29tbWVyY2UgcHJvZHVjdHMgZnJvbSB0aGUgY29tcGFueQ0KSSB3b3JrIGZvciwgPGEgaHJlZj0iaHR0cDovL3F1YWxpdGVhbS5iaXovIj5RdWFsaXRlYW0gU29mdHdhcmU8L2E+LiBXZSBhcmUgdGhlDQptYWtlcnMgb2YgdHdvIFBIUCBzaG9wcGluZyBjYXJ0cywgPGEgaHJlZj0iaHR0cDovL3gtY2FydC5jb20vIj5YLUNhcnQ8L2E+IGFuZCA8YQ0KaHJlZj0iaHR0cDovL2xpdGVjb21tZXJjZS5jb20vIj5MaXRlQ29tbWVyY2U8L2E+LiBCb3RoIG9mIG91ciBzb2x1dGlvbnMgY29tZQ0Kd2l0aCBhbiBvcGVuIHNvdXJjZSBjb2RlIGFuZCBjYW4gYmUgdXNlZCBib3RoIGFzIHJlYWR5IG91dC1vZi10aGUtYm94IHNob3BwaW5nDQpjYXJ0IHNvbHV0aW9ucyBhbmQgcG93ZXJmdWwgc2hvcHBpbmcgY2FydCBlbmdpbmVzIGZvciBhIGN1c3RvbWl6ZWQgd2ViIHNob3AuIFdlDQphbHNvIHByb3ZpZGUgdGhlIHdob2xlIHJhbmdlIG9mIGV4dHJhIHNlcnZpY2VzLCBpbmNsdWRpbmcgKGJ1dCBub3QgbGltaXRlZCB0byk6DQpzaG9wcGluZyBjYXJ0IGhvc3RpbmcsIGUtY29tbWVyY2Ugd2ViIHNpdGUgZGVzaWduLCBjdXN0b20gZGV2ZWxvcG1lbnQsDQppbnN0YWxsYXRpb24gc2VydmljZXMgJmFtcDsgMjQvNyB0ZWNobmljYWwgc3VwcG9ydC48L3A+DQoNCjxwPkdvb2QgbHVjayBpbiB5b3VyDQpyZXNlYXJjaCE8L3A+DQo8cD48ZW0+QXJ0aWNsZSBjb3VydGVzeSBvZiA8YSBocmVmPSJodHRwOi8vd3d3LmVjb21tZXJjZXNwb3QuY29tIj5FY29tbWVyY2UgU3BvdDwvYT4uPC9lbT48L3A+ZGRki0+3SCu8mtkI859v/vr7HpCbcOSuIEMmnemYUr+JAEA=" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="CD96ACFB" />
        <div align="center">
            
            
        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
    <span id="_ctl0_bodyHeader_lblBodyHead">Choosing shopping cart software</span>

                    </h2>
                </div>
                <div class="inpage">
                    


    <span id="_ctl0_contentBody_lblTitle"><h1>Choosing shopping cart software</h1></span>
    <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Top -->
        <ins class="adsbygoogle"
            style="display: block"
            data-ad-client="ca-pub-1388311751127083"
            data-ad-slot="8765540533"
            data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        <span id="_ctl0_contentBody_lblBody"><p><em>by Michael Gunin, </em><a href="http://qualiteam.biz/">Qualiteam Software</a>.</p>

<h2><a name=A3></a>Introduction</h2>

<p><strong>Choosing shopping cart
software can turn into a tough job due to the large number of e-commerce
solutions available on the market. Overall, it's almost impossible to say which
product is the best one since their feature richness, pricing, flexibility and
the range of extra services vary to a great extent.</strong></p>

<p>Therefore, buying
the right product which fits into your goals can save a lot of time and
effort, while a mistake may turn into extra costs, additional months of
work or even cause starting the whole project from scratch.</p>

<p>There are several
key factors which should be considered while picking the right solution. In this
article, I'll try to outline the most important steps that definitely should
not be missed. The tactics described below
may be varied according to your goals, however, following this advice will
be useful in the decision-making process as a whole.</p>




<h2><a name=A4></a>Key groups of factors</h2>

<h3>Who you are</h3>

<p>In my opinion,
the first thing you should ask is the role he's going to play in
the online store functioning process. The key factor of this role (at least for
small and medium businesses) is the level of a person's technical knowledge.</p>

<p>In most cases,
technology is an issue for <em>store
owners</em>, <em>managers</em>
and <em>administrators</em>.
Since each store needs its own unique design, functionality and
storefront design along with the initial setup and server administration, you should clearly understand how these services could be purchased and what the
manufacturer has to offer. Another important issue for this target group is
the ease of administration and usage of basic functions.</p>

<p>Another group of
users are <em>web developers</em>
and <em>designers</em>
who are technically skilled and usually maintain the store by themselves or
develop e-commerce solutions for their clients (which usually involves complex
code changes and development of extra functionality). For these people, the
most important factors are: the quality of code, the ease of customization
and add-ons implementation and flexibility of storefront design.</p>

<h3>Types of shopping carts</h3>

<p>All shopping cart
solutions can be divided into two large groups: hosted and distributed.</p>

<p><em>Hosted</em> carts
are usually provided in the same manner as hosting services, which means that a
customer has several predefined plans/packages (varying in number of products,
monthly bandwidth, number of features, etc) to choose from. The pricing
structure is also based on regular (monthly or yearly) fees. A hosting platform
is provided directly from the manufacturer and the cart is usually activated
without any actions needed from a client.</p>

<p>Hosted shopping
carts are managed through the administration area which provides the interface
to manage product catalog (add, remove items and edit their properties), define
and change prices and so on. The storefront design can usually be altered by
modifying templates, however, the access to the source code for hosted
solutions is usually limited and it's not always possible to modify the
functionality.</p>

<p><em>Distributed</em> solutions are
sold at a fixed price (one-time fee for a lifetime license) as a software
package which should installed on any compatible server chosen
by a customer. After the initial setup, the store can also be managed using the
administration area.</p>

<p>Usually such
products come with source code and thus can be modified or extended to
suit your needs. However, such modifications require good technical and
programming knowledge (or working with those that have those skills).</p>

<p>Overall,
hosted carts are often preferable for store owners as more easy to use and
administer while web programmers, designers and developers mostly choose
distributed solutions due to their flexibility.</p>

<h3>Additional services</h3>

<p>While most
shopping cart features can often be used right out of the box, it's important
to note that in most cases online stores require some additional professional
services.</p>

<p>For example, e-commerce software may come with a number of pre-installed design templates,
but a serious store owner would usually have its own unique store
look or integrating it's existing design into the storefront. Also, since
it's impossible for an ecommerce product containing each and every
possible feature or working the way which is totally suitable for everyone, a
shopping cart manufacturer providing custom programming service is a good option
in case you're planning to implement some extended functionality.</p>

<p>Another option
worth checking is whether it's possible to get a fully-compatible hosting
solution (since shopping carts usually have significant server-side
requirements due to their complexity) and technical support (in case you need
consultations or assistance in problem resolution).</p>

<h3>Integration with external systems</h3>

<p>Ecommerce
software should not be treated as a standalone product, but rather as a solid
ground for interaction between various components.</p>

<p>Not all
operations are performed within the shopping cart engine. Most often, external
services are used for payment processing, real-time shipping rates calculation,
order processing systems, affiliate and statistics software, product directories
and so on.</p>

<p>Thus, the
richness of integration allows store owners to have a wider choice of services
for their online business.</p>

<h3>Technical support, forum &amp; third-party solutions</h3>

<p>Responsive
technical support is another key factor which ensures that you're not left
alone with your problems and, in case the assistance is needed, you can be sure
to receive a thoughtful response or a solution in a reasonable amount of time.</p>

<p>Support schemes
from different companies may vary in type and costs. For shopping
cart vendors, technical support is often on a pay-per-incident basis,
or yearly/monthly flat-fee contract. Free technical support for ecommerce
solutions is quite rare and may not always be effective or timely.</p>

<p>Forum activity is
also a good indicator since it can be a good, free source of knowledge and
assistance from experience software users.</p>

<p>In addition, it
is advisable to check if third-party vendors offer modules or services related
to a chosen e-commerce product to ensure that you will have a decent choice of
extra solutions.</p>

<h2><a name=A5></a>Tips and advice for research</h2>

<h3>Requirements</h3>

<p>First of all,
before proceeding with the actual product research, I'd advise that you collect
the list of key features which are necessary for your upcoming online store.
Such a checklist will allow you to ensure that all (or most) of them are
present while examining features lists for chosen candidates.</p>

<h3>Looking in
search engines using relevant queries</h3>

<p>Next, you may
proceed with picking products for comparison. To find the most popular
solutions, start searching in Google/Yahoo/MSN using relevant search phrases
characterizing the product, like &quot;shopping cart software&quot;,
&quot;ecommerce solution&quot;, &quot;online store builder&quot; etc.</p>

<p>For each query,
pick products from top ten or top twenty search results. Visit their websites,
compare product features and services presented there, pricing and any other
information that you may consider relevant.</p>

<h3>Looking for reviews
and comments on forums and directories</h3>

<p>For each product
in your list, you would surely be interested to know what others have to say.
In this case, independent sources provide valuable additions to official
information from software vendors.</p>

<p>Most likely,
product profiles along with customer reviews can be found on large script and
software libraries like <a href="https://hotscripts.com/">HotScripts</a>, <a
href="http://freshmeat.net/">Freshmeat</a> and <a href="http://download.com/">Download.com</a>.
Also, check out some comparison sites, for example, <a
href="http://epinions.com/">Epinions</a> and <a
href="http://www.shopping-cart-review.toptenreviews.com/">Shopping Cart Reviews</a>.
Also, you may search through archives or start a new thread with your questions
at popular IT forums, like <a
href="http://www.sitepoint.com/forums/forumdisplay.php?f=5">SitePoint</a> or <a
href="http://www.webmasterworld.com/">WebmasterWorld</a>.</p>

<h3>Contacting sales department with your questions</h3>

<p>Finally, I'm sure
that for your short list of solutions, some
questions may still remain. This is a good reason to contact a vendor's sales
team to find out their responses. Do not hesitate to do it, since the quality
of feedback and attention to you as a potential client is worth checking before
you actually proceed with the purchase.</p>

<h2>Conclusion</h2>

<p>Choosing shopping cart software may not seem easy since it involves significant
effort from a serious customer. However, the rewards for the effort is obvious: you get a product which fits into your goals and allows you to
concentrate on sales and marketing without worrying about the technical side.
Moreover, as a client, you get to know the software vendor before buying a
product and ensure that the technical side can be handled without a problem.</p>

<p>As a possible option,
I'd like to suggest that you take a look at ecommerce products from the company
I work for, <a href="http://qualiteam.biz/">Qualiteam Software</a>. We are the
makers of two PHP shopping carts, <a href="https://x-cart.com/">X-Cart</a> and <a
href="http://litecommerce.com/">LiteCommerce</a>. Both of our solutions come
with an open source code and can be used both as ready out-of-the-box shopping
cart solutions and powerful shopping cart engines for a customized web shop. We
also provide the whole range of extra services, including (but not limited to):
shopping cart hosting, e-commerce web site design, custom development,
installation services &amp; 24/7 technical support.</p>

<p>Good luck in your
research!</p>
</span>
    </p>
    
    


    <script type="text/javascript">
        function SelectAll(id) {
            document.getElementsByTagName("textarea").item(0).focus();
            document.getElementsByTagName("textarea").item(0).select();
        }

        document.getElementsByTagName("textarea").item(0).onclick = function () { SelectAll() };

    </script>

     <script type="text/javascript">
       var CurrentArticleName = "";
       var CurrentArticleImage = "";
     </script>


    <script type="text/javascript">

        var HidePopupOnPage = "False";

        if (document.location.protocol == 'http:') {
            var Tynt = Tynt || []; Tynt.push('c-yIBWcq8r4lYkadbi-bnq'); Tynt.i = { "st": true };
            (function () { var s = document.createElement('script'); s.async = "async"; s.type = "text/javascript"; s.src = 'http://tcr.tynt.com/ti.js'; var h = document.getElementsByTagName('script')[0]; h.parentNode.insertBefore(s, h); })();
        }
    </script>

                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
