

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	Setting Prices in your Zen Cart
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<meta name="Description" content="Setting Prices in your Zen Cart"></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./setting-prices.aspx?sArticlename=setting-prices" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTExODI3Mzg0NjMPZBYCZg9kFgICAw9kFgQCAQ9kFgICAQ9kFgICAQ8PFgIeBFRleHQFH1NldHRpbmcgUHJpY2VzIGluIHlvdXIgWmVuIENhcnRkZAICD2QWBmYPDxYCHwAFKDxoMT5TZXR0aW5nIFByaWNlcyBpbiB5b3VyIFplbiBDYXJ0PC9oMT5kZAIBDw8WAh8ABflWPGEgaHJlZj0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tIiB0YXJnZXQ9Il9ibGFuayI+VGhhdCBTb2Z0d2FyZSBHdXk8L2E+DQo8YnIgLz4mY29weTsgMjAwNyBBbGwgUmlnaHRzIFJlc2VydmVkDQo8YnIgLz48YnIgLz4NCg0KSWYgeW91IHNlbGwgLSBvciB3YW50IHRvIHNlbGwgLSBwcm9kdWN0cyBvbiB0aGUgSW50ZXJuZXQsIHlvdSBhbHJlYWR5IGtub3cgYWJvdXQgdGhlIGltcG9ydGFuY2UNCm9mIHNlbGVjdGluZyB0aGUgcmlnaHQgZGlzY291bnRpbmcgc3RyYXRlZ3kuICAgV2hhdCB5b3UgbWF5IG5vdCBiZSBhd2FyZSBvZiBhcmUgYWxsIHRoZSBtYW55IHdheXMNCm9mIGltcGxlbWVudGluZyBhIGRpc2NvdW50aW5nIHN0cmF0ZWd5IGluIDxhIGhyZWY9Imh0dHA6Ly93d3cuemVuLWNhcnQuY29tIiB0YXJnZXQ9Il9ibGFuayI+WmVuIENhcnQ8L2E+JnRyYWRlOywgDQphIHBvcHVsYXIgb3Blbi1zb3VyY2Ugc2hvcHBpbmcgY2FydCBwcm9ncmFtLiAgV2UnbGwgbG9vayBhdCBzb21lIG9mIHRoZSBhcHByb2FjaGVzIHlvdSBjYW4gdGFrZSwNCnVzaW5nIGJvdGggYnVpbHQtaW4gZmFjaWxpdGllcyBmcm9tIHRoZSBjYXJ0J3Mgc3RvY2sgZGlzdHJpYnV0aW9uIGFuZCB0aGlyZC1wYXJ0eSBhZGQtb25zIGNhbGxlZA0KImNvbnRyaWJ1dGlvbnMuIg0KPGJyIC8+PGJyIC8+DQo8aDI+DQpEaXNjb3VudGluZyBQaGlsb3NvcGhpZXM8L2gyPg0KQmVmb3JlIHdlIGdldCBpbnRvIHNwZWNpZmljIGRpc2NvdW50aW5nIG1lY2hhbmlzbXMsIGxldCdzIHNwZW5kIA0Kc29tZSB0aW1lIHRoaW5raW5nIGFib3V0IHdoZW4gYW5kIHdoeSBhIGRpc2NvdW50aW5nIHByb2dyYW0gDQptaWdodCBtYWtlIHNlbnNlLg0KPGJyIC8+PGJyIC8+DQpDbGVhcmx5IGRpc2NvdW50aW5nIGlzIGNsb3NlbHkgdGllZCB0byBwcmljaW5nLCBhbmQgYSBwcmljaW5nIA0Kc3RyYXRlZ3kgd2hpY2ggdHJpbXMgbWFyZ2lucyB0byB0aGUgYm9uZSBtYXkgbm90IGJlIGNvbXBhdGlibGUNCndpdGggZGlzY291bnRpbmcuICBJbiBmYWN0LCBtYXJnaW4gZXJvc2lvbiBpcyBhIGNsYXNzaWMgb2JqZWN0aW9uIA0KdG8gZGlzY291bnRpbmcgLSBidXQgaXQgbmVlZCBub3QgYmUgYW4gb2JzdGFjbGUuDQo8dWw+DQo8bGk+V2hhdCBpZiB5b3Ugb25seSBkaXNjb3VudGVkIHlvdXIgaGlnaGVyIG1hcmdpbiBpdGVtcz88L2xpPiAgDQo8bGk+V2hhdCBpZiB5b3UgZGlzY291bnRlZCBsb3dlciBtYXJnaW4gaXRlbXMgb25seSB3aGVuIHB1cmNoYXNlZCBhbG9uZyB3aXRoIGEgaGlnaGVyIG1hcmdpbiBpdGVtcz88L2xpPiAgDQo8bGk+V2hhdCBpZiB5b3Ugb25seSBwcm92aWRlZCBkaXNjb3VudHMgdG8gaGlnaC12YWx1ZSBjdXN0b21lcnM/PC9saT4gICANCg0KPGxpPldoYXQgaWYgeW91IG9ubHkgZGlzY291bnRlZCBzYWxlcyBvdmVyIGEgY2VydGFpbiBkb2xsYXIgdGhyZXNob2xkPzwvbGk+DQo8L3VsPg0KUmF0aGVyIHRoYW4gdGhpbmtpbmcNCmFib3V0IGRpc2NvdW50cyBhcyBhIHJlZHVjdGlvbiBpbiBib3R0b20gbGluZSBwcm9maXRhYmlsaXR5LCANCmRpc2NvdW50aW5nIGNhbiBiZSBzZWVuIGFzIA0KYSB3YXkgdG8gbWFrZSBzYWxlcyB3aGljaCBtaWdodCBvdGhlcndpc2Ugbm90DQpoYXZlIGJlZW4gbWFkZSBhdCBhbGwuICAgSW5kZWVkLCByYXRoZXIgdGhhbiByZWR1Y2luZyBwcm9maXRzLCBkaXNjb3VudGluZw0KY2FuIGJlIHNlZW4gYXMgYSB3YXkgdG8gDQo8dWw+DQo8bGk+RW5jb3VyYWdlIGN1c3RvbWVyIGxveWFsdHk8L2xpPg0KPGxpPkluY2VudCB2b2x1bWUgcHVyY2hhc2VzPC9saT4NCjxsaT5Nb3ZlIHVud2FudGVkIHN0b2NrPC9saT4NCjxsaT5CdWlsZCBnb29kd2lsbDwvbGk+DQo8L3VsPg0KVGhlcmUgaXMgbm8gImJlc3Qgb2YgYnJlZWQiIGRpc2NvdW50aW5nIG1vZGVsOyB5b3VyIA0KZGlzY291bnRpbmcgcHJvZ3JhbSBzaG91bGQgYmUgY3VzdG9tIGRlc2lnbmVkIHRvIGNvbXBsaW1lbnQgeW91ciANCmJ1c2luZXNzIHBsYW4sIHlvdXIgaW52ZW50b3J5IGFuZCB5b3VyIHNhbGVzIG9iamVjdGl2ZXMuIA0KDQo8aDI+DQpQcmljaW5nIE9uIHRoZSBJbnRlcm5ldDwvaDI+DQoNClRoZSBjaGllZiBpbXBlZGltZW50IHRvIGRpc2NvdW50aW5nIGluIHlvdXIgb25saW5lDQpzdG9yZSBtaWdodCB3ZWxsIGJlIHRoZSBsYWNrIG9mIHNvZnR3YXJlIHN1cHBvcnQgZm9yIHlvdXIgZGVzaXJlZCANCmFwcHJvYWNoLiAgIEFzc3VtaW5nIHlvdXIgc2hvcHBpbmcgY2FydCBwZXJtaXRzIG1vZGlmaWNhdGlvbnMsDQp5b3UgaGF2ZSB0d28gb3B0aW9uczogDQo8b2wgdHlwZT0iYSI+DQo8bGk+Q29udHJhY3QgYSBzb2Z0d2FyZSBkZXZlbG9wZXIgdG8gaW1wbGVtZW50IHlvdXIgcHJpY2luZyBhbmQgZGlzY291bnRpbmcgcG9saWNpZXM8L2xpPg0KPGxpPkFsaWduIHlvdXIgcG9saWN5IHdpdGggd2hhdCBkaXNjb3VudGluZyBtZWNoYW5pc21zIHRoYXQgYXJlIGN1cnJlbnRseSBhdmFpbGFibGUgaW4geW91ciBjYXJ0PC9saT4NCjwvb2w+DQpJIHdpbGwgZm9jdXMNCnRoZSByZW1haW5kZXIgb2YgdGhpcyBhcnRpY2xlIG9uIGN1cnJlbnRseSBhdmFpbGFibGUgcHJpY2luZyANCnNvbHV0aW9ucyBpbiBaZW4gQ2FydC4gIE9idmlvdXNseSBnaXZlbiBhIHN1ZmZpY2llbnRseSBsYXJnZSBidWRnZXQsDQphbnkgb2YgdGhlc2UgY291bGQgYmUgdHdlYWtlZCBhbmQgdHVuZWQgdG8gYmVoYXZlIGV4YWN0bHkgYXMgeW91IHdpc2gsDQpidXQgdGhlIHByaWNlIG9mIGJlc3Bva2Ugc29mdHdhcmUgaXMgcHJvaGliaXRpdmUgZm9yIG1hbnkgc21hbGwgbWVyY2hhbnRzLg0KDQo8YnIgLz48YnIgLz4NCjxoMj4NClZpc2liaWxpdHkgb2YgRGlzY291bnRzOiBJbiB0aGUgQ2FydCBvciBBdCBDaGVja291dCBUaW1lPzwvaDI+DQpaZW4gQ2FydCBoYXMgbXVsdGlwbGUgbWVjaGFuaXNtcyBmb3IgYWx0ZXJpbmcgdGhlIGZpbmFsIHByaWNlIG9mIGEgcHJvZHVjdC4NClNvbWUgb2YgdGhlc2UgbWVjaGFuaXNtcyBhZGp1c3QgdGhlIHByaWNlIGRpcmVjdGx5LCBhbmQgYXJlIHZpc2libGUgaW4gdGhlIGNhcnQuDQpPdGhlcnMgY3JlYXRlIGEgImRpc2NvdW50IiBmaWd1cmUgYW5kIGFyZSBub3QgYXZhaWxhYmxlIHVudGlsIGNoZWNrb3V0IHRpbWUuDQpUaGUgbGF0dGVyIGFyZSBjYWxsZWQgIk9yZGVyIFRvdGFsIiBtb2R1bGVzLCBiZWNhdXNlIHRoZXkgYWZmZWN0IHRoZSBvcmRlciB0b3RhbA0KKHJhdGhlciB0aGFuIHRoZSBwcmljZSBvZiBhbnkgcGFydGljdWxhciBpdGVtIGluIHRoZSBvcmRlci4pDQpIZXJlIGFyZSB0d28gaWxsdXN0cmF0aW9uczogDQo8YnIgLz4NCjxiciAvPg0KPHRhYmxlIGJvcmRlcj0iMSI+PHRyPg0KPHRkPjxpbWcgc3JjPSJodHRwOi8vd3d3LnRoYXRzb2Z0d2FyZWd1eS5jb20vc2NyX2FydGljbGUvcHJpY2luZ19hcnRpY2xlXzEucG5nIj48L3RkPjx0ZD5BIHByb2R1Y3Qgd2hvc2UgcHJpY2UgaXMgcmVkdWNlZCBpbiB0aGUgY2FydCAodXNpbmcgdGhlIA0KU3BlY2lhbCBtZWNoYW5pc20gZGlzY3Vzc2VkIGJlbG93KS4gIFRoZSBkaXNwbGF5IG9mIHRoaXMgcHJpY2UgcmVkdWN0aW9uIGNhbiBiZSBzZXQgdG8gZGlzcGxheSBieQ0KZG9sbGFycyBvciBwZXJjZW50YWdlLCBvciBub3QgYXQgYWxsLjwvdGQ+DQoNCjwvdHI+DQo8dHI+DQo8dGQ+PGltZyBzcmM9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbS9zY3JfYXJ0aWNsZS9wcmljaW5nX2FydGljbGVfMi5wbmciPjwvdGQ+PHRkPkFuIG9yZGVyIHdob3NlIHByaWNlIGlzIHJlZHVjZWQgYXQgY2hlY2tvdXQgdGltZSB2aWEgdGhlIEdyb3VwDQpEaXNjb3VudCBPcmRlciBUb3RhbCBNb2R1bGUuICBEaXNjb3VudHMgYXJlIG5vdCBicm9rZW4gb3V0OyBhIHNpbmdsZSBkb2xsYXIgZmlndXJlIGlzIHByb3ZpZGVkLjwvdGQ+DQo8L3RyPg0KPC90YWJsZT4NCjxiciAvPg0KV2h5IHdvdWxkIHlvdSBjaG9vc2UgdG8gZG8gaXQgYXQgY2hlY2tvdXQgaW5zdGVhZCBvZiBpbiB0aGUgY2FydD8NClR5cGljYWxseSB0aGlzIGNob2ljZSBpcyBpbXBvc2VkIG9uIHlvdSBiYXNlZCBvbiB0aGUgZGVzaWduIG9mIHRoZSANCmRpc2NvdW50aW5nIHBhY2thZ2UuICBZb3UgbXVzdCBkZWNpZGUgb24gd2hpY2ggZGlzY291bnRpbmcgbWV0aG9kIG1ha2VzIA0KdGhlIG1vc3Qgc2Vuc2UgZm9yIHlvdXIgYnVzaW5lc3MgZmlyc3QuICBGb3IgaW5zdGFuY2UsIGRvIHlvdSBoYXZlIGEgDQprZXkgZ3JvdXAgb2YgY3VzdG9tZXJzIHRoYXQgZ2V0IDIwJSBvZmYgZXZlcnl0aGluZz8gIFRoZW4gR3JvdXAgRGlzY291bnRzDQooYW4gT3JkZXIgVG90YWwgbW9kdWxlKSBtaWdodCBiZSBhIGdvb2QgY2hvaWNlLiAgV291bGQgeW91IGxpa2UgdG8gDQpvZmZlciBwYWlycyBvZiBwcm9kdWN0cyB3aG9zZSBwcmljZSBpcyByZWR1Y2VkIGlmIGJvdGggYXJlIHB1cmNoYXNlZD8NClRoZW4gbG9vayBhdCBCZXR0ZXIgVG9nZXRoZXIuICBPbiB0aGUgb3RoZXIgaGFuZCwgaWYgeW91IGp1c3Qgd2FudCB0bw0KZGlzY291bnQgb25lIGl0ZW0gb3IgY2F0ZWdvcnkgZm9yIGEgcGVyaW9kIG9mIHRpbWUsIHRoZW4gYSBzYWxlIG9yDQpzcGVjaWFsIGlzIHdoYXQgeW91IHdhbnQgdG8gcnVuLCBhbmQgdGhpcyB3aWxsIHNob3cgdXAgaW4gdGhlIGNhcnQuDQoNCg0KPGJyIC8+PGJyIC8+DQo8aDI+DQpJbiB0aGUgQ2FydDogU2FsZXMgYW5kIFNwZWNpYWxzPC9oMj4NClRoZSB0d28gbW9zdCBjb21tb24gaW4tY2FydCBkaXNjb3VudGluZyBtZWNoYW5pc21zIGFyZSBTYWxlcyBhbmQgU3BlY2lhbHMuDQpUaGV5IG9wZXJhdGUgc2ltaWxhcmx5LCBidXQgaGF2ZSBkaWZmZXJlbnQgc2NvcGU6IHNwZWNpYWxzIGFyZSBmb3IgcHJvZHVjdHMsDQp3aGlsZSBzYWxlcyBhcmUgZm9yIGNhdGVnb3JpZXMgb2YgcHJvZHVjdHMuDQo8YnIgLz48YnIgLz4NCkEgc3BlY2lhbCBzcGVjaWZpZXMgYSBuZXcgcHJpY2UgZm9yIGEgc3BlY2lmaWMgcHJvZHVjdC4gIFRoYXQgcHJpY2UgDQpjYW4gYmUgYSBwZXJjZW50YWdlIGRpc2NvdW50IG9mZiB0aGUgb3JpZ2luYWwNCnByaWNlICgyMCUpLCBvciBhIG5ldyBwcmljZSAoJDIwLjAwKS4gIA0KPGJyIC8+PGJyIC8+DQpBIHNhbGUgc3BlY2lmaWVzIGEgbmV3IHByaWNlIGZvciBhIG9uZSBvciBtb3JlIGNhdGVnb3JpZXMgb2YgcHJvZHVjdHMuDQpUaGUgcHJpY2UgY2FuIGJlIGEgcGVyY2VudGFnZSA8aT5vciBkb2xsYXI8L2k+IGRpc2NvdW50IG9mZiB0aGUgb3JpZ2luYWwgcHJpY2UsIA0Kb3IgYSBuZXcgcHJpY2UuDQoNCjxiciAvPjxiciAvPg0KQm90aCBzcGVjaWFscyBhbmQgc2FsZXMgY2FuIGJlIGNvbnN0cmFpbmVkIHRvIG9ubHkgYXBwbHkgZm9yIGNlcnRhaW4NCmNhbGVuZGFyIHBlcmlvZHMuDQo8YnIgLz48YnIgLz4NCkZyb20gYSBjdXN0b21lcidzIHBlcnNwZWN0aXZlLCBzYWxlcyBhbmQgc3BlY2lhbHMgbG9vayBpZGVudGljYWwgd2hlbiBsb29raW5nDQphdCBhIHNpbmdsZSBwcm9kdWN0LiAgSGVyZSBhcmUgdGhlIHRocmVlIHBvc3NpYmxlIGRpc3BsYXkgcGVybXV0YXRpb25zOiBkaXNwbGF5aW5nDQp0aGUgZGlzY291bnQgYXMgYSBwcmljZSBkaXNjb3VudCwgZGlzcGxheWluZyB0aGUgZGlzY291bnQgYXMgYSBwZXJjZW50YWdlIGRpc2NvdW50LA0KYW5kIG5vdCBkaXNwbGF5aW5nIHRoZSBkaXNjb3VudCBhdCBhbGwuICBOb3RlIHRoYXQgaW4gZWFjaCBjYXNlLCB0aGUgb3JpZ2luYWwgcHJpY2UNCmlzIGRpc3BsYXllZCB3aXRoIHN0cmlrZXRocm91Z2guPGJyIC8+PGJyIC8+DQoNCjx0YWJsZSBib3JkZXI9IjEiPjx0cj4NCjx0ZD48aW1nIHNyYz0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3Njcl9hcnRpY2xlL3ByaWNpbmdfcGVyY2VudC5wbmciPjwvdGQ+PHRkPkRpc3BsYXlpbmcgdGhlIGRpc2NvdW50IGFzIGEgcGVyY2VudGFnZSBvZmYgYmFzZSBwcmljZTwvdGQ+DQo8L3RyPg0KPHRyPg0KPHRkPjxpbWcgc3JjPSJodHRwOi8vd3d3LnRoYXRzb2Z0d2FyZWd1eS5jb20vc2NyX2FydGljbGUvcHJpY2luZ19kb2xsYXJzLnBuZyI+PC90ZD48dGQ+RGlzcGxheWluZyB0aGUgZGlzY291bnQgYXMgYSBkb2xsYXIgZmlndXJlIG9mZiB0aGUgYmFzZSBwcmljZTwvdGQ+DQo8L3RyPg0KPHRyPg0KPHRkPjxpbWcgc3JjPSJodHRwOi8vd3d3LnRoYXRzb2Z0d2FyZWd1eS5jb20vc2NyX2FydGljbGUvcHJpY2luZ19ub19kaXNwbGF5LnBuZyI+PC90ZD48dGQ+Tm90IGRpc3BsYXlpbmcgdGhlIGRpc2NvdW50PC90ZD4NCg0KPC90cj4NCjwvdGFibGU+DQo8YnIgLz48YnIgLz4NClNhbGVzIGFuZCBzcGVjaWFscyBpbnRlcm9wZXJhdGUgaW4gYSBoaWdobHkgY29uZmlndXJhYmxlIG1hbm5lci4gIFNhbGVzIGNhbiBiZSBjb25maWd1cmVkDQp0byBhcHBseSBvbiB0b3Agb2YsIGluc3RlYWQgb2Ygb3Igb25seSBpbiB0aGUgYWJzZW5jZSBvZiBzcGVjaWFscy4gIEhlcmUncyBhbiBleGFtcGxlIA0Kd2l0aCBhIHNhbGUgb24gdG9wIG9mIGEgc3BlY2lhbDoNCjx0YWJsZSBib3JkZXI9IjEiPjx0cj4NCjx0ZD48aW1nIHNyYz0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3Njcl9hcnRpY2xlL3ByaWNpbmdfc2FsZV9zcGVjaWFsLnBuZyI+PC90ZD4NCjx0ZD4kNS4wMCBvZmYgU2FsZSBvbiB0b3Agb2YgMjUlIG9mZiBzcGVjaWFsPC90ZD4NCjwvdHI+PC90YWJsZT4NCjxiciBjbGVhcj0iYWxsIiAvPg0KPGJyIC8+PGJyIC8+DQo8aDI+DQpBdCBDaGVja291dCBUaW1lOiBDb3Vwb25zPC9oMj4NCkV2ZXIgc2luY2UgTXIuIEMuVy4gUG9zdCAob2YgUG9zdCBDZXJlYWwpIGludmVudGVkIHRoZSBjb3Vwb24gaW4gMTg5NSwgY291cG9ucyBoYXZlIGJlZW4NCmFuIGltcG9ydGFudCBjb21wb25lbnQgb2YgcmV0YWlsIHByaWNpbmcgc3RyYXRlZ3kgLSBhcyB3ZWxsIGFzIGENCnBvd2VyZnVsIGJyYW5kIGFuZCBnb29kd2lsbCBidWlsZGluZyBtZWNoYW5pc20uDQpaZW4gQ2FydCBoYXMgYSBidWlsdCBpbiBjb3Vwb24gZmVhdHVyZQ0Kd2hpY2ggcGVybWl0cyBkaXNjb3VudGluZyBieSBhIGZpeGVkIGFtb3VudCBvciBhIHBlcmNlbnRhZ2UNCm9mIHRoZSB0b3RhbC4gIE9uY2UgY3JlYXRlZCwgY291cG9ucyBjYW4gYmUgcmVzdHJpY3RlZCB0byANCmFwcGx5IHRvIHNwZWNpZmljIHByb2R1Y3RzIG9yIGNhdGVnb3JpZXMuICANCkNvdXBvbnMgdXNlIGNhbiBiZSByZXN0cmljdGVkIG9uIGEgcGVyIGN1c3RvbWVyIG9yIGdsb2JhbCBiYXNpcyANCmlmIGRlc2lyZWQsIGFzIHdlbGwgYXMgYSBkYXRlIHJhbmdlLiAgDQo8YnIgLz4NCjxiciAvPg0KDQo8aDI+DQpBdCBDaGVja291dCBUaW1lOiBHcm91cCBEaXNjb3VudHMgYW5kIEJldHRlciBUb2dldGhlcjwvaDI+DQpHcm91cCBEaXNjb3VudHMgYW5kIA0KPGEgaHJlZj0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3plbmNhcnRfYmV0dGVyX3RvZ2V0aGVyLmh0bWwiIHRhcmdldD0iX2JsYW5rIj5CZXR0ZXIgVG9nZXRoZXI8L2E+IGFyZSBleGFtcGxlcyBvZiBPcmRlciBUb3RhbCBNb2R1bGVzLCB3aGljaCANCmNvbXB1dGUgYSBkaXNjb3VudCB3aGljaCBpcyBzaG93biBhdCBjaGVja291dCB0aW1lLiAgR3JvdXAgRGlzY291bnRzIGlzIA0KYnVpbHQgaW4gdG8gWmVuIENhcnQ7IEJldHRlciBUb2dldGhlciBpcyBhbiBhZGQtb24gY29udHJpYnV0aW9uIHdoaWNoIEkgd3JvdGUuDQo8YnIgLz48YnIgLz4NClRoZSBjb25jZXB0IG9mIGdyb3VwIGRpc2NvdW50aW5nIGlzIHNpbXBsZSBhbmQgaW50dWl0aXZlIC0gY3VzdG9tZXJzIGFyZSBhZGRlZCANCnRvIGRpc2NvdW50ICJncm91cHMiIGFuZCBnaXZlbiBwZXJjZW50YWdlIGRpc2NvdW50cywgcG9zc2libHkgaW5jbHVkaW5nIHRheA0KYW5kIHNoaXBwaW5nLCBvbiB0aGVpciB0b3RhbCBwdXJjaGFzZSBhbW91bnRzLiAgPGJyIC8+PGJyIC8+QmV0dGVyIFRvZ2V0aGVyIGlzIG1vcmUgY29tcGxleCwgDQpidXQgc3RpbGwgZmFtaWxpYXIgdG8gbW9zdCBjdXN0b21lcnMgc2luY2UgaXQgaXMgYSBwcm9tb3Rpb24gc3R5bGUgdGhhdCBBbWF6b24uY29tDQp1c2VzLiAgSXRlbXMgYXJlICJsaW5rZWQiIGFuZCBhIGRpc2NvdW50IGlzIHByb3ZpZGVkIHdoZW4gYm90aCBsaW5rZWQgaXRlbXMgYXJlIA0KcHVyY2hhc2VkLiAgIFRoZSBwcm9kdWN0IGRldGFpbCBwYWdlIGZvciBhbiBpdGVtIHByb21vdGVkIGJ5IEJldHRlciBUb2dldGhlciBtaWdodCANCmNvbnRhaW4gdXBzZWxsaW5nIHRleHQgc3VjaCBhcyB0aGlzOg0KPGJyIC8+PGJyIC8+DQo8ZGl2IHN0eWxlPSJtYXJnaW4tbGVmdDogMjVweDsgYm9yZGVyOiAxcHggc29saWQgIzAwMDAwMDsgcGFkZGluZzogNXB4OyI+DQpCdXkgdGhpcyBpdGVtLCBnZXQgYSA8YSBocmVmPSIiPk1pY3Jvc29mdCBJbnRlbGxpbW91c2UgRXhwbG9yZXI8L2E+IGF0IDUwJSBvZmY8YnIgLz4NCg0KPC9kaXY+DQo8YnIgLz4NCklmIGJvdGggaXRlbXMgd2VyZSBwdXJjaGFzZWQsIHRoZSBkaXNjb3VudCB3b3VsZCBiZSBkaXNwbGF5ZWQgYXQgY2hlY2tvdXQgdGltZSANCm9uIHRoZSBmaW5hbCBwYWdlOiANCjx0YWJsZSBib3JkZXI9IjEiPjx0cj4NCjx0ZD48aW1nIHNyYz0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3Njcl9hcnRpY2xlL3ByaWNpbmdfYnQucG5nIj48L3RkPjx0ZD5TaG9wcGluZyBjYXJ0IHNob3dpbmcgQmV0dGVyIFRvZ2V0aGVyIGRpc2NvdW50PC90ZD4NCjwvdHI+DQo8L3RhYmxlPg0KPGJyIC8+DQo8aDI+DQpRdWFudGl0eSBEaXNjb3VudHMgLSBZb3VyIENob2ljZTwvaDI+DQpRdWFudGl0eSBEaXNjb3VudGluZyBpcyBhIHRpbWUtdGVzdGVkIG1lY2hhbmlzbSB0byBnZW5lcmF0ZSANCmxhcmdlciB2b2x1bWUgc2FsZXMuICBUaGUgYXBwcm9hY2ggaXMgc2ltcGxlOiBidXlpbmcgaW4gdm9sdW1lDQpsb3dlcnMgdGhlIHVuaXQgcHJpY2UuICANCjxiciAvPjxiciAvPg0KWmVuIENhcnQgaGFzIHR3byBRdWFudGl0eSBEaXNjb3VudGluZyBtZWNoYW1pc21zOg0KYSBidWlsdCBpbiBvbmUsIHdoaWNoIGFwcGVhcnMNCmluIHRoZSBjYXJ0LCBhbmQgYSB0aGlyZC1wYXJ0eSBjb250cmlidXRpb24sDQp3aGljaCBvcGVyYXRlcyBhcyBhbiBPcmRlciBUb3RhbCBtb2R1bGUuICANCjxiciAvPg0KPGJyIC8+DQoNCjx0YWJsZSB3aWR0aD0iMTAwJSIgYm9yZGVyPSIxIiBjZWxscGFkZGluZz0iNSI+DQo8dHI+DQo8dGQ+PGI+WmVuIENhcnQncyBRdWFudGl0eSBEaXNjb3VudCBmZWF0dXJlPC9iPjwvdGQ+DQo8dGQ+PGI+VGhhdCBTb2Z0d2FyZSBHdXkncyBRdWFudGl0eSBEaXNjb3VudCBDb250cmlidXRpb248L2I+PC90ZD4NCjwvdHI+DQo8dHI+DQo8dGQ+DQpPbmx5IGFsbG93cyBwZXItcHJvZHVjdCBxdWFudGl0eSBkaXNjb3VudHMgIA0KPC90ZD4NCjx0ZD4NCkFsbG93cyB5b3UgdG8gZGlzY291bnQgYnkgaXRlbSwgYnkgcGFyZW50IGNhdGVnb3J5IG9yIGJ5IGFsbCBpdGVtcyANCmluIHRoZSBjYXJ0PC90ZD4NCjwvdHI+DQo8dHI+DQo8dGQ+DQoNCk11c3QgYmUgY29uZmlndXJlZCBmb3IgZXZlcnkgDQpwcm9kdWN0IG9uIHdoaWNoIHlvdSB3YW50IHRvIG9mZmVyIHF1YW50aXR5IGRpc2NvdW50cw0KPC90ZD48dGQ+DQpRdWFudGl0eSBEaXNjb3VudHMgQ29udHJpYnV0aW9uIGFwcGxpZXMgdG8gYWxsIHByb2R1Y3RzIChleGNlcHQgdGhvc2UNCnlvdSBzcGVjaWZpY2FsbHkgZXhlbXB0KTwvdGQ+DQo8L3RyPg0KPHRyPg0KPHRkPkFsbG93cyB1bmxpbWl0ZWQgbnVtYmVycyBvZiBkaXNjb3VudCBsZXZlbHMsIGJ1dCBkaXNjb3VudHMgbXVzdCBiZSBpbmRpdmlkdWFsbHkgY29uZmlndXJlZCBvbiBlYWNoIHByb2R1Y3Q8L3RkPg0KPHRkPkFsbG93cyBvbmx5IGZpdmUgZGlzY291bnQgbGV2ZWxzLCBidXQgZGlzY291bnRpbmcgaXMgYXBwbGllZCB0byBhbGwgcHJvZHVjdHMgZXhjZXB0IHdoZXJlIHNwZWNpZmllZDwvdGQ+DQo8L3RyPg0KPHRyPg0KPHRkPk1hcmtldGluZyB0ZXh0IGlzIGZpeGVkLCBhdXRvbWF0aWNhbGx5IGdlbmVyYXRlZDwvdGQ+DQo8dGQ+TWFya2V0aW5nIHRleHQgbWF5IGJlIGN1c3RvbWl6ZWQgdG8geW91ciBuZWVkcywgYnV0IG11c3QgYmUgYWRkZWQgbWFudWFsbHk8L3RkPg0KPC90cj4NCg0KPC90YWJsZT4NCjxiciAvPg0KPGgyPg0KRGV0ZXJtaW5pbmcgdGhlIFJpZ2h0IFN0cmF0ZWd5PC9oMj4NCkluIGNvbmNsdXNpb24sIGEgZ3JlYXQgbnVtYmVyIG9mIGRpc2NvdW50aW5nIG1lY2hhbmlzbXMgYXJlIGF2YWlsYWJsZQ0KaW4gWmVuIENhcnQuICBEZXRlcm1pbmluZyB3aGljaCBvbmVzIGFyZSB0aGUgYmVzdCBtYXRjaCBmb3IgeW91cg0KYnVzaW5lc3Mgd2lsbCBkZXBlbmQgb24geW91ciBtYXJrZXRpbmcgbWl4Lg0KRGlzY291bnRpbmcgY2FuIG5vdCBvbmx5IGltcHJvdmUgdGhlIGJvdHRvbSBsaW5lLCBidXQgY2FuIGFsc28gaGF2ZQ0KdGhlIGVmZmVjdCBvZiBidWlsZGluZyBnb29kd2lsbCBhbmQgaW5jcmVhc2luZyB0aGUgc3RpY2tpbmVzcyANCm9mIHlvdXIgYnJhbmQuDQpCZXN0IHByYWN0aWNlcyBpbiBkaXNjb3VudGluZyBhcmUgdG8gdGVzdCB2YXJpb3VzIHN0cmF0ZWdpZXMsDQptZWFzdXJlIHRoZWlyIGVmZmVjdGl2ZW5lc3MsIGFuZCBhZGp1c3QgYXMgbmVlZGVkLg0KPGJyIC8+PGJyIC8+DQo8aDI+DQpGdXJ0aGVyIFJlYWRpbmc8L2gyPg0KQSBzdXBlcmIgcmVmZXJlbmNlIGZvciBhbGwgdGhpbmdzIFplbiBDYXJ0IGlzIEdvaCBLb29uIEhvZWsncyBib29rLCANCjxhIGhyZWY9Imh0dHA6Ly93d3cuemVuLWNhcnQuY29tL2luZGV4LnBocD9tYWluX3BhZ2U9cGFnZSZpZD0xNiIgdGFyZ2V0PSJfYmxhbmsiPg0KZS1TdGFydCB5b3VyIFdlYiBTdG9yZSB3aXRoIFplbiBDYXJ0PC9hPi4gIERpc2NvdW50aW5nIGlkZWFzIGFyZSBkaXNjdXNzZWQgaW4gDQpDaGFwdGVyIDE1IGFuZCBDaGFwdGVyIDIxIGluIGdyZWF0IGRldGFpbCwgd2l0aCB0aGUgc3BlY2lmaWMgc2V0dGluZ3MgcmVxdWlyZWQgdG8gZ2V0IA0KdGhlIHJlc3VsdHMgc2hvd24gaGVyZS4NCjxici8+PGJyLz4NCjxhIGhyZWY9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbSI+DQpUaGF0IFNvZnR3YXJlIEd1eTwvYT4gaXMgYSBzb2Z0d2FyZSBkZXZlbG9wZXIgd2l0aCAyMCB5ZWFycyBvZiBleHBlcmllbmNlLg0KTGF0ZWx5IGhlIGhhcyBiZWVuIGZvY3VzZWQgb24gY3VzdG9taXppbmcgWmVuIENhcnQuDQpkZAICDw8WAh8ABf9XPGgxPlNldHRpbmcgUHJpY2VzIGluIHlvdXIgWmVuIENhcnQ8L2gxPjxhIGhyZWY9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbSIgdGFyZ2V0PSJfYmxhbmsiPlRoYXQgU29mdHdhcmUgR3V5PC9hPg0KPGJyIC8+JmNvcHk7IDIwMDcgQWxsIFJpZ2h0cyBSZXNlcnZlZA0KPGJyIC8+PGJyIC8+DQoNCklmIHlvdSBzZWxsIC0gb3Igd2FudCB0byBzZWxsIC0gcHJvZHVjdHMgb24gdGhlIEludGVybmV0LCB5b3UgYWxyZWFkeSBrbm93IGFib3V0IHRoZSBpbXBvcnRhbmNlDQpvZiBzZWxlY3RpbmcgdGhlIHJpZ2h0IGRpc2NvdW50aW5nIHN0cmF0ZWd5LiAgIFdoYXQgeW91IG1heSBub3QgYmUgYXdhcmUgb2YgYXJlIGFsbCB0aGUgbWFueSB3YXlzDQpvZiBpbXBsZW1lbnRpbmcgYSBkaXNjb3VudGluZyBzdHJhdGVneSBpbiA8YSBocmVmPSJodHRwOi8vd3d3Lnplbi1jYXJ0LmNvbSIgdGFyZ2V0PSJfYmxhbmsiPlplbiBDYXJ0PC9hPiZ0cmFkZTssIA0KYSBwb3B1bGFyIG9wZW4tc291cmNlIHNob3BwaW5nIGNhcnQgcHJvZ3JhbS4gIFdlJ2xsIGxvb2sgYXQgc29tZSBvZiB0aGUgYXBwcm9hY2hlcyB5b3UgY2FuIHRha2UsDQp1c2luZyBib3RoIGJ1aWx0LWluIGZhY2lsaXRpZXMgZnJvbSB0aGUgY2FydCdzIHN0b2NrIGRpc3RyaWJ1dGlvbiBhbmQgdGhpcmQtcGFydHkgYWRkLW9ucyBjYWxsZWQNCiJjb250cmlidXRpb25zLiINCjxiciAvPjxiciAvPg0KPGgyPg0KRGlzY291bnRpbmcgUGhpbG9zb3BoaWVzPC9oMj4NCkJlZm9yZSB3ZSBnZXQgaW50byBzcGVjaWZpYyBkaXNjb3VudGluZyBtZWNoYW5pc21zLCBsZXQncyBzcGVuZCANCnNvbWUgdGltZSB0aGlua2luZyBhYm91dCB3aGVuIGFuZCB3aHkgYSBkaXNjb3VudGluZyBwcm9ncmFtIA0KbWlnaHQgbWFrZSBzZW5zZS4NCjxiciAvPjxiciAvPg0KQ2xlYXJseSBkaXNjb3VudGluZyBpcyBjbG9zZWx5IHRpZWQgdG8gcHJpY2luZywgYW5kIGEgcHJpY2luZyANCnN0cmF0ZWd5IHdoaWNoIHRyaW1zIG1hcmdpbnMgdG8gdGhlIGJvbmUgbWF5IG5vdCBiZSBjb21wYXRpYmxlDQp3aXRoIGRpc2NvdW50aW5nLiAgSW4gZmFjdCwgbWFyZ2luIGVyb3Npb24gaXMgYSBjbGFzc2ljIG9iamVjdGlvbiANCnRvIGRpc2NvdW50aW5nIC0gYnV0IGl0IG5lZWQgbm90IGJlIGFuIG9ic3RhY2xlLg0KPHVsPg0KPGxpPldoYXQgaWYgeW91IG9ubHkgZGlzY291bnRlZCB5b3VyIGhpZ2hlciBtYXJnaW4gaXRlbXM/PC9saT4gIA0KPGxpPldoYXQgaWYgeW91IGRpc2NvdW50ZWQgbG93ZXIgbWFyZ2luIGl0ZW1zIG9ubHkgd2hlbiBwdXJjaGFzZWQgYWxvbmcgd2l0aCBhIGhpZ2hlciBtYXJnaW4gaXRlbXM/PC9saT4gIA0KPGxpPldoYXQgaWYgeW91IG9ubHkgcHJvdmlkZWQgZGlzY291bnRzIHRvIGhpZ2gtdmFsdWUgY3VzdG9tZXJzPzwvbGk+ICAgDQoNCjxsaT5XaGF0IGlmIHlvdSBvbmx5IGRpc2NvdW50ZWQgc2FsZXMgb3ZlciBhIGNlcnRhaW4gZG9sbGFyIHRocmVzaG9sZD88L2xpPg0KPC91bD4NClJhdGhlciB0aGFuIHRoaW5raW5nDQphYm91dCBkaXNjb3VudHMgYXMgYSByZWR1Y3Rpb24gaW4gYm90dG9tIGxpbmUgcHJvZml0YWJpbGl0eSwgDQpkaXNjb3VudGluZyBjYW4gYmUgc2VlbiBhcyANCmEgd2F5IHRvIG1ha2Ugc2FsZXMgd2hpY2ggbWlnaHQgb3RoZXJ3aXNlIG5vdA0KaGF2ZSBiZWVuIG1hZGUgYXQgYWxsLiAgIEluZGVlZCwgcmF0aGVyIHRoYW4gcmVkdWNpbmcgcHJvZml0cywgZGlzY291bnRpbmcNCmNhbiBiZSBzZWVuIGFzIGEgd2F5IHRvIA0KPHVsPg0KPGxpPkVuY291cmFnZSBjdXN0b21lciBsb3lhbHR5PC9saT4NCjxsaT5JbmNlbnQgdm9sdW1lIHB1cmNoYXNlczwvbGk+DQo8bGk+TW92ZSB1bndhbnRlZCBzdG9jazwvbGk+DQo8bGk+QnVpbGQgZ29vZHdpbGw8L2xpPg0KPC91bD4NClRoZXJlIGlzIG5vICJiZXN0IG9mIGJyZWVkIiBkaXNjb3VudGluZyBtb2RlbDsgeW91ciANCmRpc2NvdW50aW5nIHByb2dyYW0gc2hvdWxkIGJlIGN1c3RvbSBkZXNpZ25lZCB0byBjb21wbGltZW50IHlvdXIgDQpidXNpbmVzcyBwbGFuLCB5b3VyIGludmVudG9yeSBhbmQgeW91ciBzYWxlcyBvYmplY3RpdmVzLiANCg0KPGgyPg0KUHJpY2luZyBPbiB0aGUgSW50ZXJuZXQ8L2gyPg0KDQpUaGUgY2hpZWYgaW1wZWRpbWVudCB0byBkaXNjb3VudGluZyBpbiB5b3VyIG9ubGluZQ0Kc3RvcmUgbWlnaHQgd2VsbCBiZSB0aGUgbGFjayBvZiBzb2Z0d2FyZSBzdXBwb3J0IGZvciB5b3VyIGRlc2lyZWQgDQphcHByb2FjaC4gICBBc3N1bWluZyB5b3VyIHNob3BwaW5nIGNhcnQgcGVybWl0cyBtb2RpZmljYXRpb25zLA0KeW91IGhhdmUgdHdvIG9wdGlvbnM6IA0KPG9sIHR5cGU9ImEiPg0KPGxpPkNvbnRyYWN0IGEgc29mdHdhcmUgZGV2ZWxvcGVyIHRvIGltcGxlbWVudCB5b3VyIHByaWNpbmcgYW5kIGRpc2NvdW50aW5nIHBvbGljaWVzPC9saT4NCjxsaT5BbGlnbiB5b3VyIHBvbGljeSB3aXRoIHdoYXQgZGlzY291bnRpbmcgbWVjaGFuaXNtcyB0aGF0IGFyZSBjdXJyZW50bHkgYXZhaWxhYmxlIGluIHlvdXIgY2FydDwvbGk+DQo8L29sPg0KSSB3aWxsIGZvY3VzDQp0aGUgcmVtYWluZGVyIG9mIHRoaXMgYXJ0aWNsZSBvbiBjdXJyZW50bHkgYXZhaWxhYmxlIHByaWNpbmcgDQpzb2x1dGlvbnMgaW4gWmVuIENhcnQuICBPYnZpb3VzbHkgZ2l2ZW4gYSBzdWZmaWNpZW50bHkgbGFyZ2UgYnVkZ2V0LA0KYW55IG9mIHRoZXNlIGNvdWxkIGJlIHR3ZWFrZWQgYW5kIHR1bmVkIHRvIGJlaGF2ZSBleGFjdGx5IGFzIHlvdSB3aXNoLA0KYnV0IHRoZSBwcmljZSBvZiBiZXNwb2tlIHNvZnR3YXJlIGlzIHByb2hpYml0aXZlIGZvciBtYW55IHNtYWxsIG1lcmNoYW50cy4NCg0KPGJyIC8+PGJyIC8+DQo8aDI+DQpWaXNpYmlsaXR5IG9mIERpc2NvdW50czogSW4gdGhlIENhcnQgb3IgQXQgQ2hlY2tvdXQgVGltZT88L2gyPg0KWmVuIENhcnQgaGFzIG11bHRpcGxlIG1lY2hhbmlzbXMgZm9yIGFsdGVyaW5nIHRoZSBmaW5hbCBwcmljZSBvZiBhIHByb2R1Y3QuDQpTb21lIG9mIHRoZXNlIG1lY2hhbmlzbXMgYWRqdXN0IHRoZSBwcmljZSBkaXJlY3RseSwgYW5kIGFyZSB2aXNpYmxlIGluIHRoZSBjYXJ0Lg0KT3RoZXJzIGNyZWF0ZSBhICJkaXNjb3VudCIgZmlndXJlIGFuZCBhcmUgbm90IGF2YWlsYWJsZSB1bnRpbCBjaGVja291dCB0aW1lLg0KVGhlIGxhdHRlciBhcmUgY2FsbGVkICJPcmRlciBUb3RhbCIgbW9kdWxlcywgYmVjYXVzZSB0aGV5IGFmZmVjdCB0aGUgb3JkZXIgdG90YWwNCihyYXRoZXIgdGhhbiB0aGUgcHJpY2Ugb2YgYW55IHBhcnRpY3VsYXIgaXRlbSBpbiB0aGUgb3JkZXIuKQ0KSGVyZSBhcmUgdHdvIGlsbHVzdHJhdGlvbnM6IA0KPGJyIC8+DQo8YnIgLz4NCjx0YWJsZSBib3JkZXI9IjEiPjx0cj4NCjx0ZD48aW1nIHNyYz0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3Njcl9hcnRpY2xlL3ByaWNpbmdfYXJ0aWNsZV8xLnBuZyI+PC90ZD48dGQ+QSBwcm9kdWN0IHdob3NlIHByaWNlIGlzIHJlZHVjZWQgaW4gdGhlIGNhcnQgKHVzaW5nIHRoZSANClNwZWNpYWwgbWVjaGFuaXNtIGRpc2N1c3NlZCBiZWxvdykuICBUaGUgZGlzcGxheSBvZiB0aGlzIHByaWNlIHJlZHVjdGlvbiBjYW4gYmUgc2V0IHRvIGRpc3BsYXkgYnkNCmRvbGxhcnMgb3IgcGVyY2VudGFnZSwgb3Igbm90IGF0IGFsbC48L3RkPg0KDQo8L3RyPg0KPHRyPg0KPHRkPjxpbWcgc3JjPSJodHRwOi8vd3d3LnRoYXRzb2Z0d2FyZWd1eS5jb20vc2NyX2FydGljbGUvcHJpY2luZ19hcnRpY2xlXzIucG5nIj48L3RkPjx0ZD5BbiBvcmRlciB3aG9zZSBwcmljZSBpcyByZWR1Y2VkIGF0IGNoZWNrb3V0IHRpbWUgdmlhIHRoZSBHcm91cA0KRGlzY291bnQgT3JkZXIgVG90YWwgTW9kdWxlLiAgRGlzY291bnRzIGFyZSBub3QgYnJva2VuIG91dDsgYSBzaW5nbGUgZG9sbGFyIGZpZ3VyZSBpcyBwcm92aWRlZC48L3RkPg0KPC90cj4NCjwvdGFibGU+DQo8YnIgLz4NCldoeSB3b3VsZCB5b3UgY2hvb3NlIHRvIGRvIGl0IGF0IGNoZWNrb3V0IGluc3RlYWQgb2YgaW4gdGhlIGNhcnQ/DQpUeXBpY2FsbHkgdGhpcyBjaG9pY2UgaXMgaW1wb3NlZCBvbiB5b3UgYmFzZWQgb24gdGhlIGRlc2lnbiBvZiB0aGUgDQpkaXNjb3VudGluZyBwYWNrYWdlLiAgWW91IG11c3QgZGVjaWRlIG9uIHdoaWNoIGRpc2NvdW50aW5nIG1ldGhvZCBtYWtlcyANCnRoZSBtb3N0IHNlbnNlIGZvciB5b3VyIGJ1c2luZXNzIGZpcnN0LiAgRm9yIGluc3RhbmNlLCBkbyB5b3UgaGF2ZSBhIA0Ka2V5IGdyb3VwIG9mIGN1c3RvbWVycyB0aGF0IGdldCAyMCUgb2ZmIGV2ZXJ5dGhpbmc/ICBUaGVuIEdyb3VwIERpc2NvdW50cw0KKGFuIE9yZGVyIFRvdGFsIG1vZHVsZSkgbWlnaHQgYmUgYSBnb29kIGNob2ljZS4gIFdvdWxkIHlvdSBsaWtlIHRvIA0Kb2ZmZXIgcGFpcnMgb2YgcHJvZHVjdHMgd2hvc2UgcHJpY2UgaXMgcmVkdWNlZCBpZiBib3RoIGFyZSBwdXJjaGFzZWQ/DQpUaGVuIGxvb2sgYXQgQmV0dGVyIFRvZ2V0aGVyLiAgT24gdGhlIG90aGVyIGhhbmQsIGlmIHlvdSBqdXN0IHdhbnQgdG8NCmRpc2NvdW50IG9uZSBpdGVtIG9yIGNhdGVnb3J5IGZvciBhIHBlcmlvZCBvZiB0aW1lLCB0aGVuIGEgc2FsZSBvcg0Kc3BlY2lhbCBpcyB3aGF0IHlvdSB3YW50IHRvIHJ1biwgYW5kIHRoaXMgd2lsbCBzaG93IHVwIGluIHRoZSBjYXJ0Lg0KDQoNCjxiciAvPjxiciAvPg0KPGgyPg0KSW4gdGhlIENhcnQ6IFNhbGVzIGFuZCBTcGVjaWFsczwvaDI+DQpUaGUgdHdvIG1vc3QgY29tbW9uIGluLWNhcnQgZGlzY291bnRpbmcgbWVjaGFuaXNtcyBhcmUgU2FsZXMgYW5kIFNwZWNpYWxzLg0KVGhleSBvcGVyYXRlIHNpbWlsYXJseSwgYnV0IGhhdmUgZGlmZmVyZW50IHNjb3BlOiBzcGVjaWFscyBhcmUgZm9yIHByb2R1Y3RzLA0Kd2hpbGUgc2FsZXMgYXJlIGZvciBjYXRlZ29yaWVzIG9mIHByb2R1Y3RzLg0KPGJyIC8+PGJyIC8+DQpBIHNwZWNpYWwgc3BlY2lmaWVzIGEgbmV3IHByaWNlIGZvciBhIHNwZWNpZmljIHByb2R1Y3QuICBUaGF0IHByaWNlIA0KY2FuIGJlIGEgcGVyY2VudGFnZSBkaXNjb3VudCBvZmYgdGhlIG9yaWdpbmFsDQpwcmljZSAoMjAlKSwgb3IgYSBuZXcgcHJpY2UgKCQyMC4wMCkuICANCjxiciAvPjxiciAvPg0KQSBzYWxlIHNwZWNpZmllcyBhIG5ldyBwcmljZSBmb3IgYSBvbmUgb3IgbW9yZSBjYXRlZ29yaWVzIG9mIHByb2R1Y3RzLg0KVGhlIHByaWNlIGNhbiBiZSBhIHBlcmNlbnRhZ2UgPGk+b3IgZG9sbGFyPC9pPiBkaXNjb3VudCBvZmYgdGhlIG9yaWdpbmFsIHByaWNlLCANCm9yIGEgbmV3IHByaWNlLg0KDQo8YnIgLz48YnIgLz4NCkJvdGggc3BlY2lhbHMgYW5kIHNhbGVzIGNhbiBiZSBjb25zdHJhaW5lZCB0byBvbmx5IGFwcGx5IGZvciBjZXJ0YWluDQpjYWxlbmRhciBwZXJpb2RzLg0KPGJyIC8+PGJyIC8+DQpGcm9tIGEgY3VzdG9tZXIncyBwZXJzcGVjdGl2ZSwgc2FsZXMgYW5kIHNwZWNpYWxzIGxvb2sgaWRlbnRpY2FsIHdoZW4gbG9va2luZw0KYXQgYSBzaW5nbGUgcHJvZHVjdC4gIEhlcmUgYXJlIHRoZSB0aHJlZSBwb3NzaWJsZSBkaXNwbGF5IHBlcm11dGF0aW9uczogZGlzcGxheWluZw0KdGhlIGRpc2NvdW50IGFzIGEgcHJpY2UgZGlzY291bnQsIGRpc3BsYXlpbmcgdGhlIGRpc2NvdW50IGFzIGEgcGVyY2VudGFnZSBkaXNjb3VudCwNCmFuZCBub3QgZGlzcGxheWluZyB0aGUgZGlzY291bnQgYXQgYWxsLiAgTm90ZSB0aGF0IGluIGVhY2ggY2FzZSwgdGhlIG9yaWdpbmFsIHByaWNlDQppcyBkaXNwbGF5ZWQgd2l0aCBzdHJpa2V0aHJvdWdoLjxiciAvPjxiciAvPg0KDQo8dGFibGUgYm9yZGVyPSIxIj48dHI+DQo8dGQ+PGltZyBzcmM9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbS9zY3JfYXJ0aWNsZS9wcmljaW5nX3BlcmNlbnQucG5nIj48L3RkPjx0ZD5EaXNwbGF5aW5nIHRoZSBkaXNjb3VudCBhcyBhIHBlcmNlbnRhZ2Ugb2ZmIGJhc2UgcHJpY2U8L3RkPg0KPC90cj4NCjx0cj4NCjx0ZD48aW1nIHNyYz0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3Njcl9hcnRpY2xlL3ByaWNpbmdfZG9sbGFycy5wbmciPjwvdGQ+PHRkPkRpc3BsYXlpbmcgdGhlIGRpc2NvdW50IGFzIGEgZG9sbGFyIGZpZ3VyZSBvZmYgdGhlIGJhc2UgcHJpY2U8L3RkPg0KPC90cj4NCjx0cj4NCjx0ZD48aW1nIHNyYz0iaHR0cDovL3d3dy50aGF0c29mdHdhcmVndXkuY29tL3Njcl9hcnRpY2xlL3ByaWNpbmdfbm9fZGlzcGxheS5wbmciPjwvdGQ+PHRkPk5vdCBkaXNwbGF5aW5nIHRoZSBkaXNjb3VudDwvdGQ+DQoNCjwvdHI+DQo8L3RhYmxlPg0KPGJyIC8+PGJyIC8+DQpTYWxlcyBhbmQgc3BlY2lhbHMgaW50ZXJvcGVyYXRlIGluIGEgaGlnaGx5IGNvbmZpZ3VyYWJsZSBtYW5uZXIuICBTYWxlcyBjYW4gYmUgY29uZmlndXJlZA0KdG8gYXBwbHkgb24gdG9wIG9mLCBpbnN0ZWFkIG9mIG9yIG9ubHkgaW4gdGhlIGFic2VuY2Ugb2Ygc3BlY2lhbHMuICBIZXJlJ3MgYW4gZXhhbXBsZSANCndpdGggYSBzYWxlIG9uIHRvcCBvZiBhIHNwZWNpYWw6DQo8dGFibGUgYm9yZGVyPSIxIj48dHI+DQo8dGQ+PGltZyBzcmM9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbS9zY3JfYXJ0aWNsZS9wcmljaW5nX3NhbGVfc3BlY2lhbC5wbmciPjwvdGQ+DQo8dGQ+JDUuMDAgb2ZmIFNhbGUgb24gdG9wIG9mIDI1JSBvZmYgc3BlY2lhbDwvdGQ+DQo8L3RyPjwvdGFibGU+DQo8YnIgY2xlYXI9ImFsbCIgLz4NCjxiciAvPjxiciAvPg0KPGgyPg0KQXQgQ2hlY2tvdXQgVGltZTogQ291cG9uczwvaDI+DQpFdmVyIHNpbmNlIE1yLiBDLlcuIFBvc3QgKG9mIFBvc3QgQ2VyZWFsKSBpbnZlbnRlZCB0aGUgY291cG9uIGluIDE4OTUsIGNvdXBvbnMgaGF2ZSBiZWVuDQphbiBpbXBvcnRhbnQgY29tcG9uZW50IG9mIHJldGFpbCBwcmljaW5nIHN0cmF0ZWd5IC0gYXMgd2VsbCBhcyBhDQpwb3dlcmZ1bCBicmFuZCBhbmQgZ29vZHdpbGwgYnVpbGRpbmcgbWVjaGFuaXNtLg0KWmVuIENhcnQgaGFzIGEgYnVpbHQgaW4gY291cG9uIGZlYXR1cmUNCndoaWNoIHBlcm1pdHMgZGlzY291bnRpbmcgYnkgYSBmaXhlZCBhbW91bnQgb3IgYSBwZXJjZW50YWdlDQpvZiB0aGUgdG90YWwuICBPbmNlIGNyZWF0ZWQsIGNvdXBvbnMgY2FuIGJlIHJlc3RyaWN0ZWQgdG8gDQphcHBseSB0byBzcGVjaWZpYyBwcm9kdWN0cyBvciBjYXRlZ29yaWVzLiAgDQpDb3Vwb25zIHVzZSBjYW4gYmUgcmVzdHJpY3RlZCBvbiBhIHBlciBjdXN0b21lciBvciBnbG9iYWwgYmFzaXMgDQppZiBkZXNpcmVkLCBhcyB3ZWxsIGFzIGEgZGF0ZSByYW5nZS4gIA0KPGJyIC8+DQo8YnIgLz4NCg0KPGgyPg0KQXQgQ2hlY2tvdXQgVGltZTogR3JvdXAgRGlzY291bnRzIGFuZCBCZXR0ZXIgVG9nZXRoZXI8L2gyPg0KR3JvdXAgRGlzY291bnRzIGFuZCANCjxhIGhyZWY9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbS96ZW5jYXJ0X2JldHRlcl90b2dldGhlci5odG1sIiB0YXJnZXQ9Il9ibGFuayI+QmV0dGVyIFRvZ2V0aGVyPC9hPiBhcmUgZXhhbXBsZXMgb2YgT3JkZXIgVG90YWwgTW9kdWxlcywgd2hpY2ggDQpjb21wdXRlIGEgZGlzY291bnQgd2hpY2ggaXMgc2hvd24gYXQgY2hlY2tvdXQgdGltZS4gIEdyb3VwIERpc2NvdW50cyBpcyANCmJ1aWx0IGluIHRvIFplbiBDYXJ0OyBCZXR0ZXIgVG9nZXRoZXIgaXMgYW4gYWRkLW9uIGNvbnRyaWJ1dGlvbiB3aGljaCBJIHdyb3RlLg0KPGJyIC8+PGJyIC8+DQpUaGUgY29uY2VwdCBvZiBncm91cCBkaXNjb3VudGluZyBpcyBzaW1wbGUgYW5kIGludHVpdGl2ZSAtIGN1c3RvbWVycyBhcmUgYWRkZWQgDQp0byBkaXNjb3VudCAiZ3JvdXBzIiBhbmQgZ2l2ZW4gcGVyY2VudGFnZSBkaXNjb3VudHMsIHBvc3NpYmx5IGluY2x1ZGluZyB0YXgNCmFuZCBzaGlwcGluZywgb24gdGhlaXIgdG90YWwgcHVyY2hhc2UgYW1vdW50cy4gIDxiciAvPjxiciAvPkJldHRlciBUb2dldGhlciBpcyBtb3JlIGNvbXBsZXgsIA0KYnV0IHN0aWxsIGZhbWlsaWFyIHRvIG1vc3QgY3VzdG9tZXJzIHNpbmNlIGl0IGlzIGEgcHJvbW90aW9uIHN0eWxlIHRoYXQgQW1hem9uLmNvbQ0KdXNlcy4gIEl0ZW1zIGFyZSAibGlua2VkIiBhbmQgYSBkaXNjb3VudCBpcyBwcm92aWRlZCB3aGVuIGJvdGggbGlua2VkIGl0ZW1zIGFyZSANCnB1cmNoYXNlZC4gICBUaGUgcHJvZHVjdCBkZXRhaWwgcGFnZSBmb3IgYW4gaXRlbSBwcm9tb3RlZCBieSBCZXR0ZXIgVG9nZXRoZXIgbWlnaHQgDQpjb250YWluIHVwc2VsbGluZyB0ZXh0IHN1Y2ggYXMgdGhpczoNCjxiciAvPjxiciAvPg0KPGRpdiBzdHlsZT0ibWFyZ2luLWxlZnQ6IDI1cHg7IGJvcmRlcjogMXB4IHNvbGlkICMwMDAwMDA7IHBhZGRpbmc6IDVweDsiPg0KQnV5IHRoaXMgaXRlbSwgZ2V0IGEgPGEgaHJlZj0iIj5NaWNyb3NvZnQgSW50ZWxsaW1vdXNlIEV4cGxvcmVyPC9hPiBhdCA1MCUgb2ZmPGJyIC8+DQoNCjwvZGl2Pg0KPGJyIC8+DQpJZiBib3RoIGl0ZW1zIHdlcmUgcHVyY2hhc2VkLCB0aGUgZGlzY291bnQgd291bGQgYmUgZGlzcGxheWVkIGF0IGNoZWNrb3V0IHRpbWUgDQpvbiB0aGUgZmluYWwgcGFnZTogDQo8dGFibGUgYm9yZGVyPSIxIj48dHI+DQo8dGQ+PGltZyBzcmM9Imh0dHA6Ly93d3cudGhhdHNvZnR3YXJlZ3V5LmNvbS9zY3JfYXJ0aWNsZS9wcmljaW5nX2J0LnBuZyI+PC90ZD48dGQ+U2hvcHBpbmcgY2FydCBzaG93aW5nIEJldHRlciBUb2dldGhlciBkaXNjb3VudDwvdGQ+DQo8L3RyPg0KPC90YWJsZT4NCjxiciAvPg0KPGgyPg0KUXVhbnRpdHkgRGlzY291bnRzIC0gWW91ciBDaG9pY2U8L2gyPg0KUXVhbnRpdHkgRGlzY291bnRpbmcgaXMgYSB0aW1lLXRlc3RlZCBtZWNoYW5pc20gdG8gZ2VuZXJhdGUgDQpsYXJnZXIgdm9sdW1lIHNhbGVzLiAgVGhlIGFwcHJvYWNoIGlzIHNpbXBsZTogYnV5aW5nIGluIHZvbHVtZQ0KbG93ZXJzIHRoZSB1bml0IHByaWNlLiAgDQo8YnIgLz48YnIgLz4NClplbiBDYXJ0IGhhcyB0d28gUXVhbnRpdHkgRGlzY291bnRpbmcgbWVjaGFtaXNtczoNCmEgYnVpbHQgaW4gb25lLCB3aGljaCBhcHBlYXJzDQppbiB0aGUgY2FydCwgYW5kIGEgdGhpcmQtcGFydHkgY29udHJpYnV0aW9uLA0Kd2hpY2ggb3BlcmF0ZXMgYXMgYW4gT3JkZXIgVG90YWwgbW9kdWxlLiAgDQo8YnIgLz4NCjxiciAvPg0KDQo8dGFibGUgd2lkdGg9IjEwMCUiIGJvcmRlcj0iMSIgY2VsbHBhZGRpbmc9IjUiPg0KPHRyPg0KPHRkPjxiPlplbiBDYXJ0J3MgUXVhbnRpdHkgRGlzY291bnQgZmVhdHVyZTwvYj48L3RkPg0KPHRkPjxiPlRoYXQgU29mdHdhcmUgR3V5J3MgUXVhbnRpdHkgRGlzY291bnQgQ29udHJpYnV0aW9uPC9iPjwvdGQ+DQo8L3RyPg0KPHRyPg0KPHRkPg0KT25seSBhbGxvd3MgcGVyLXByb2R1Y3QgcXVhbnRpdHkgZGlzY291bnRzICANCjwvdGQ+DQo8dGQ+DQpBbGxvd3MgeW91IHRvIGRpc2NvdW50IGJ5IGl0ZW0sIGJ5IHBhcmVudCBjYXRlZ29yeSBvciBieSBhbGwgaXRlbXMgDQppbiB0aGUgY2FydDwvdGQ+DQo8L3RyPg0KPHRyPg0KPHRkPg0KDQpNdXN0IGJlIGNvbmZpZ3VyZWQgZm9yIGV2ZXJ5IA0KcHJvZHVjdCBvbiB3aGljaCB5b3Ugd2FudCB0byBvZmZlciBxdWFudGl0eSBkaXNjb3VudHMNCjwvdGQ+PHRkPg0KUXVhbnRpdHkgRGlzY291bnRzIENvbnRyaWJ1dGlvbiBhcHBsaWVzIHRvIGFsbCBwcm9kdWN0cyAoZXhjZXB0IHRob3NlDQp5b3Ugc3BlY2lmaWNhbGx5IGV4ZW1wdCk8L3RkPg0KPC90cj4NCjx0cj4NCjx0ZD5BbGxvd3MgdW5saW1pdGVkIG51bWJlcnMgb2YgZGlzY291bnQgbGV2ZWxzLCBidXQgZGlzY291bnRzIG11c3QgYmUgaW5kaXZpZHVhbGx5IGNvbmZpZ3VyZWQgb24gZWFjaCBwcm9kdWN0PC90ZD4NCjx0ZD5BbGxvd3Mgb25seSBmaXZlIGRpc2NvdW50IGxldmVscywgYnV0IGRpc2NvdW50aW5nIGlzIGFwcGxpZWQgdG8gYWxsIHByb2R1Y3RzIGV4Y2VwdCB3aGVyZSBzcGVjaWZpZWQ8L3RkPg0KPC90cj4NCjx0cj4NCjx0ZD5NYXJrZXRpbmcgdGV4dCBpcyBmaXhlZCwgYXV0b21hdGljYWxseSBnZW5lcmF0ZWQ8L3RkPg0KPHRkPk1hcmtldGluZyB0ZXh0IG1heSBiZSBjdXN0b21pemVkIHRvIHlvdXIgbmVlZHMsIGJ1dCBtdXN0IGJlIGFkZGVkIG1hbnVhbGx5PC90ZD4NCjwvdHI+DQoNCjwvdGFibGU+DQo8YnIgLz4NCjxoMj4NCkRldGVybWluaW5nIHRoZSBSaWdodCBTdHJhdGVneTwvaDI+DQpJbiBjb25jbHVzaW9uLCBhIGdyZWF0IG51bWJlciBvZiBkaXNjb3VudGluZyBtZWNoYW5pc21zIGFyZSBhdmFpbGFibGUNCmluIFplbiBDYXJ0LiAgRGV0ZXJtaW5pbmcgd2hpY2ggb25lcyBhcmUgdGhlIGJlc3QgbWF0Y2ggZm9yIHlvdXINCmJ1c2luZXNzIHdpbGwgZGVwZW5kIG9uIHlvdXIgbWFya2V0aW5nIG1peC4NCkRpc2NvdW50aW5nIGNhbiBub3Qgb25seSBpbXByb3ZlIHRoZSBib3R0b20gbGluZSwgYnV0IGNhbiBhbHNvIGhhdmUNCnRoZSBlZmZlY3Qgb2YgYnVpbGRpbmcgZ29vZHdpbGwgYW5kIGluY3JlYXNpbmcgdGhlIHN0aWNraW5lc3MgDQpvZiB5b3VyIGJyYW5kLg0KQmVzdCBwcmFjdGljZXMgaW4gZGlzY291bnRpbmcgYXJlIHRvIHRlc3QgdmFyaW91cyBzdHJhdGVnaWVzLA0KbWVhc3VyZSB0aGVpciBlZmZlY3RpdmVuZXNzLCBhbmQgYWRqdXN0IGFzIG5lZWRlZC4NCjxiciAvPjxiciAvPg0KPGgyPg0KRnVydGhlciBSZWFkaW5nPC9oMj4NCkEgc3VwZXJiIHJlZmVyZW5jZSBmb3IgYWxsIHRoaW5ncyBaZW4gQ2FydCBpcyBHb2ggS29vbiBIb2VrJ3MgYm9vaywgDQo8YSBocmVmPSJodHRwOi8vd3d3Lnplbi1jYXJ0LmNvbS9pbmRleC5waHA/bWFpbl9wYWdlPXBhZ2UmaWQ9MTYiIHRhcmdldD0iX2JsYW5rIj4NCmUtU3RhcnQgeW91ciBXZWIgU3RvcmUgd2l0aCBaZW4gQ2FydDwvYT4uICBEaXNjb3VudGluZyBpZGVhcyBhcmUgZGlzY3Vzc2VkIGluIA0KQ2hhcHRlciAxNSBhbmQgQ2hhcHRlciAyMSBpbiBncmVhdCBkZXRhaWwsIHdpdGggdGhlIHNwZWNpZmljIHNldHRpbmdzIHJlcXVpcmVkIHRvIGdldCANCnRoZSByZXN1bHRzIHNob3duIGhlcmUuDQo8YnIvPjxici8+DQo8YSBocmVmPSJodHRwOi8vd3d3LnRoYXRzb2Z0d2FyZWd1eS5jb20iPg0KVGhhdCBTb2Z0d2FyZSBHdXk8L2E+IGlzIGEgc29mdHdhcmUgZGV2ZWxvcGVyIHdpdGggMjAgeWVhcnMgb2YgZXhwZXJpZW5jZS4NCkxhdGVseSBoZSBoYXMgYmVlbiBmb2N1c2VkIG9uIGN1c3RvbWl6aW5nIFplbiBDYXJ0Lg0KPHA+PGVtPkFydGljbGUgY291cnRlc3kgb2YgPGEgaHJlZj0iaHR0cDovL3d3dy5lY29tbWVyY2VzcG90LmNvbSI+RWNvbW1lcmNlIFNwb3Q8L2E+LjwvZW0+PC9wPmRkZNa2UouQAFT3rex4IvrQaYrClsbuOXQh8h9DXZz70LJG" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="CD96ACFB" />
        <div align="center">
            
            
        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
    <span id="_ctl0_bodyHeader_lblBodyHead">Setting Prices in your Zen Cart</span>

                    </h2>
                </div>
                <div class="inpage">
                    


    <span id="_ctl0_contentBody_lblTitle"><h1>Setting Prices in your Zen Cart</h1></span>
    <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Top -->
        <ins class="adsbygoogle"
            style="display: block"
            data-ad-client="ca-pub-1388311751127083"
            data-ad-slot="8765540533"
            data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        <span id="_ctl0_contentBody_lblBody"><a href="http://www.thatsoftwareguy.com" target="_blank">That Software Guy</a>
<br />&copy; 2007 All Rights Reserved
<br /><br />

If you sell - or want to sell - products on the Internet, you already know about the importance
of selecting the right discounting strategy.   What you may not be aware of are all the many ways
of implementing a discounting strategy in <a href="https://www.zen-cart.com" target="_blank">Zen Cart</a>&trade;, 
a popular open-source shopping cart program.  We'll look at some of the approaches you can take,
using both built-in facilities from the cart's stock distribution and third-party add-ons called
"contributions."
<br /><br />
<h2>
Discounting Philosophies</h2>
Before we get into specific discounting mechanisms, let's spend 
some time thinking about when and why a discounting program 
might make sense.
<br /><br />
Clearly discounting is closely tied to pricing, and a pricing 
strategy which trims margins to the bone may not be compatible
with discounting.  In fact, margin erosion is a classic objection 
to discounting - but it need not be an obstacle.
<ul>
<li>What if you only discounted your higher margin items?</li>  
<li>What if you discounted lower margin items only when purchased along with a higher margin items?</li>  
<li>What if you only provided discounts to high-value customers?</li>   

<li>What if you only discounted sales over a certain dollar threshold?</li>
</ul>
Rather than thinking
about discounts as a reduction in bottom line profitability, 
discounting can be seen as 
a way to make sales which might otherwise not
have been made at all.   Indeed, rather than reducing profits, discounting
can be seen as a way to 
<ul>
<li>Encourage customer loyalty</li>
<li>Incent volume purchases</li>
<li>Move unwanted stock</li>
<li>Build goodwill</li>
</ul>
There is no "best of breed" discounting model; your 
discounting program should be custom designed to compliment your 
business plan, your inventory and your sales objectives. 

<h2>
Pricing On the Internet</h2>

The chief impediment to discounting in your online
store might well be the lack of software support for your desired 
approach.   Assuming your shopping cart permits modifications,
you have two options: 
<ol type="a">
<li>Contract a software developer to implement your pricing and discounting policies</li>
<li>Align your policy with what discounting mechanisms that are currently available in your cart</li>
</ol>
I will focus
the remainder of this article on currently available pricing 
solutions in Zen Cart.  Obviously given a sufficiently large budget,
any of these could be tweaked and tuned to behave exactly as you wish,
but the price of bespoke software is prohibitive for many small merchants.

<br /><br />
<h2>
Visibility of Discounts: In the Cart or At Checkout Time?</h2>
Zen Cart has multiple mechanisms for altering the final price of a product.
Some of these mechanisms adjust the price directly, and are visible in the cart.
Others create a "discount" figure and are not available until checkout time.
The latter are called "Order Total" modules, because they affect the order total
(rather than the price of any particular item in the order.)
Here are two illustrations: 
<br />
<br />
<table border="1"><tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_article_1.png"></td><td>A product whose price is reduced in the cart (using the 
Special mechanism discussed below).  The display of this price reduction can be set to display by
dollars or percentage, or not at all.</td>

</tr>
<tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_article_2.png"></td><td>An order whose price is reduced at checkout time via the Group
Discount Order Total Module.  Discounts are not broken out; a single dollar figure is provided.</td>
</tr>
</table>
<br />
Why would you choose to do it at checkout instead of in the cart?
Typically this choice is imposed on you based on the design of the 
discounting package.  You must decide on which discounting method makes 
the most sense for your business first.  For instance, do you have a 
key group of customers that get 20% off everything?  Then Group Discounts
(an Order Total module) might be a good choice.  Would you like to 
offer pairs of products whose price is reduced if both are purchased?
Then look at Better Together.  On the other hand, if you just want to
discount one item or category for a period of time, then a sale or
special is what you want to run, and this will show up in the cart.


<br /><br />
<h2>
In the Cart: Sales and Specials</h2>
The two most common in-cart discounting mechanisms are Sales and Specials.
They operate similarly, but have different scope: specials are for products,
while sales are for categories of products.
<br /><br />
A special specifies a new price for a specific product.  That price 
can be a percentage discount off the original
price (20%), or a new price ($20.00).  
<br /><br />
A sale specifies a new price for a one or more categories of products.
The price can be a percentage <i>or dollar</i> discount off the original price, 
or a new price.

<br /><br />
Both specials and sales can be constrained to only apply for certain
calendar periods.
<br /><br />
From a customer's perspective, sales and specials look identical when looking
at a single product.  Here are the three possible display permutations: displaying
the discount as a price discount, displaying the discount as a percentage discount,
and not displaying the discount at all.  Note that in each case, the original price
is displayed with strikethrough.<br /><br />

<table border="1"><tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_percent.png"></td><td>Displaying the discount as a percentage off base price</td>
</tr>
<tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_dollars.png"></td><td>Displaying the discount as a dollar figure off the base price</td>
</tr>
<tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_no_display.png"></td><td>Not displaying the discount</td>

</tr>
</table>
<br /><br />
Sales and specials interoperate in a highly configurable manner.  Sales can be configured
to apply on top of, instead of or only in the absence of specials.  Here's an example 
with a sale on top of a special:
<table border="1"><tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_sale_special.png"></td>
<td>$5.00 off Sale on top of 25% off special</td>
</tr></table>
<br clear="all" />
<br /><br />
<h2>
At Checkout Time: Coupons</h2>
Ever since Mr. C.W. Post (of Post Cereal) invented the coupon in 1895, coupons have been
an important component of retail pricing strategy - as well as a
powerful brand and goodwill building mechanism.
Zen Cart has a built in coupon feature
which permits discounting by a fixed amount or a percentage
of the total.  Once created, coupons can be restricted to 
apply to specific products or categories.  
Coupons use can be restricted on a per customer or global basis 
if desired, as well as a date range.  
<br />
<br />

<h2>
At Checkout Time: Group Discounts and Better Together</h2>
Group Discounts and 
<a href="http://www.thatsoftwareguy.com/zencart_better_together.html" target="_blank">Better Together</a> are examples of Order Total Modules, which 
compute a discount which is shown at checkout time.  Group Discounts is 
built in to Zen Cart; Better Together is an add-on contribution which I wrote.
<br /><br />
The concept of group discounting is simple and intuitive - customers are added 
to discount "groups" and given percentage discounts, possibly including tax
and shipping, on their total purchase amounts.  <br /><br />Better Together is more complex, 
but still familiar to most customers since it is a promotion style that Amazon.com
uses.  Items are "linked" and a discount is provided when both linked items are 
purchased.   The product detail page for an item promoted by Better Together might 
contain upselling text such as this:
<br /><br />
<div style="margin-left: 25px; border: 1px solid #000000; padding: 5px;">
Buy this item, get a <a href="">Microsoft Intellimouse Explorer</a> at 50% off<br />

</div>
<br />
If both items were purchased, the discount would be displayed at checkout time 
on the final page: 
<table border="1"><tr>
<td><img src="http://www.thatsoftwareguy.com/scr_article/pricing_bt.png"></td><td>Shopping cart showing Better Together discount</td>
</tr>
</table>
<br />
<h2>
Quantity Discounts - Your Choice</h2>
Quantity Discounting is a time-tested mechanism to generate 
larger volume sales.  The approach is simple: buying in volume
lowers the unit price.  
<br /><br />
Zen Cart has two Quantity Discounting mechamisms:
a built in one, which appears
in the cart, and a third-party contribution,
which operates as an Order Total module.  
<br />
<br />

<table width="100%" border="1" cellpadding="5">
<tr>
<td><b>Zen Cart's Quantity Discount feature</b></td>
<td><b>That Software Guy's Quantity Discount Contribution</b></td>
</tr>
<tr>
<td>
Only allows per-product quantity discounts  
</td>
<td>
Allows you to discount by item, by parent category or by all items 
in the cart</td>
</tr>
<tr>
<td>

Must be configured for every 
product on which you want to offer quantity discounts
</td><td>
Quantity Discounts Contribution applies to all products (except those
you specifically exempt)</td>
</tr>
<tr>
<td>Allows unlimited numbers of discount levels, but discounts must be individually configured on each product</td>
<td>Allows only five discount levels, but discounting is applied to all products except where specified</td>
</tr>
<tr>
<td>Marketing text is fixed, automatically generated</td>
<td>Marketing text may be customized to your needs, but must be added manually</td>
</tr>

</table>
<br />
<h2>
Determining the Right Strategy</h2>
In conclusion, a great number of discounting mechanisms are available
in Zen Cart.  Determining which ones are the best match for your
business will depend on your marketing mix.
Discounting can not only improve the bottom line, but can also have
the effect of building goodwill and increasing the stickiness 
of your brand.
Best practices in discounting are to test various strategies,
measure their effectiveness, and adjust as needed.
<br /><br />
<h2>
Further Reading</h2>
A superb reference for all things Zen Cart is Goh Koon Hoek's book, 
<a href="https://www.zen-cart.com/index.php?main_page=page&id=16" target="_blank">
e-Start your Web Store with Zen Cart</a>.  Discounting ideas are discussed in 
Chapter 15 and Chapter 21 in great detail, with the specific settings required to get 
the results shown here.
<br/><br/>
<a href="http://www.thatsoftwareguy.com">
That Software Guy</a> is a software developer with 20 years of experience.
Lately he has been focused on customizing Zen Cart.
</span>
    </p>
    
    


    <script type="text/javascript">
        function SelectAll(id) {
            document.getElementsByTagName("textarea").item(0).focus();
            document.getElementsByTagName("textarea").item(0).select();
        }

        document.getElementsByTagName("textarea").item(0).onclick = function () { SelectAll() };

    </script>

     <script type="text/javascript">
       var CurrentArticleName = "";
       var CurrentArticleImage = "";
     </script>


    <script type="text/javascript">

        var HidePopupOnPage = "False";

        if (document.location.protocol == 'http:') {
            var Tynt = Tynt || []; Tynt.push('c-yIBWcq8r4lYkadbi-bnq'); Tynt.i = { "st": true };
            (function () { var s = document.createElement('script'); s.async = "async"; s.type = "text/javascript"; s.src = 'http://tcr.tynt.com/ti.js'; var h = document.getElementsByTagName('script')[0]; h.parentNode.insertBefore(s, h); })();
        }
    </script>

                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
