

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head id="_ctl0_Head1"><meta name="viewport" content="width=device-width, initial-scale=1"><title>
	The differences between Shopify vs Volusion
</title><link href="../style2.css" type="text/css" rel="stylesheet" />
<script type='text/javascript' src="https://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type='text/javascript'>
GS_googleAddAdSenseService("ca-pub-0018417347503107");
GS_googleEnableAllServices();
</script>

<!-- up next -->
<link type="text/css" href="http://cdn.ecommercespot.com/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://cdn.ecommercespot.com/jquery/js/jquery-ui-1.8.16.custom.min.js"></script>


<script type='text/javascript'>
 $(document).ready(function() {
	var shown =0;
    $(window).scroll(function() {
    if ($('body').height() <= ($(window).height() + $(window).scrollTop()+600)) {
		if(shown)
			return;
        $('#upNext').show('slide', {direction: 'right'}, 300);
		shown =1;
	}
	else {
		if(!shown)
			return;
		$('#upNext').hide('slide', {direction: 'right'}, 300);
		shown = 0;
        }
    });
 }); 

</script>
<script type='text/javascript'>
    GA_googleAddSlot("ca-pub-0018417347503107", "Article300x250");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadASPCarts_728x90_Mid");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadCartsMisc728_Middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_middle");
    GA_googleAddSlot("ca-pub-0018417347503107", "DownloadPHPCarts_728x90_top");
    GA_googleAddSlot("ca-pub-0018417347503107", "Gateways");
    GA_googleAddSlot("ca-pub-0018417347503107", "Homepage_Top_Banner");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts");
    GA_googleAddSlot("ca-pub-0018417347503107", "HostedCarts_bottom");
    GA_googleAddSlot("ca-pub-0018417347503107", "Misc_pages_728");
</script>
<script type='text/javascript'>
GA_googleFetchAds();
</script>    
<meta name="Description"></head>
<body>




<div id="page">

<div id="top"><ul>
	<li id="but1"><a href="/">Home</a></li>
	<li id="but2"><a href="/search-for-shopping-carts.aspx">Buy a Cart</a></li>
	<li id="but3"><a href="/search-for-hosted-cart.aspx">Hosted Carts</a></li>
	<li id="but4"><a href="/search-for-gateways.aspx">Gateways</a></li>
	<li id="but5"><a href="/article.aspx">Articles</a></li>
	<li id="but6"><a href="/blog/">Blog</a></li>
	<li id="but7"><a href="/aboutus.aspx">About Us</a></li>
</ul></div>

<div id="top2">
	<a href="/" id="logoTop"><span></span>Ecommerce Spot</a>

  <form id="searchbox_012233088847465414495:fr8duvgbugg" action="/search/">
    <input type="hidden" name="cx" value="012233088847465414495:fr8duvgbugg" />
    <input type="hidden" name="cof" value="FORID:11" />
    <input name="q" type="text" size="20" />
    <input type="submit" name="sa" value="Search" />
  </form>
  <script type="text/javascript" src="https://google.com/coop/cse/brand?form=searchbox_012233088847465414495%3Amg_r01wz7aa"></script>
        
       </div>
        <form name="aspnetForm" method="post" action="./The-differences-between-Shopify-vs-Volusion.aspx?sArticlename=The-differences-between-Shopify-vs-Volusion" id="aspnetForm">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTExODI3Mzg0NjMPZBYCZg9kFgICAw9kFgQCAQ9kFgICAQ9kFgICAQ8PFgIeBFRleHQFK1RoZSBkaWZmZXJlbmNlcyBiZXR3ZWVuIFNob3BpZnkgdnMgVm9sdXNpb25kZAICD2QWBmYPDxYCHwAFNDxoMT5UaGUgZGlmZmVyZW5jZXMgYmV0d2VlbiBTaG9waWZ5IHZzIFZvbHVzaW9uPC9oMT5kZAIBDw8WAh8ABblVPHA+U2VsZWN0aW5nIHRoZSByaWdodCBlLWNvbW1lcmNlIHBsYXRmb3JtIGZvciB5b3VyIGUtY29tbWVyY2UgYnVzaW5lc3MgY2FuIGJlIGFuIG92ZXJ3aGVsbWluZyBwcm9jZXNzIHRoYXQgd2lsbCB0YWtlIHVwIG1vc3Qgb2YgeW91ciB0aW1lLiBTaG9waWZ5IGFuZCBWb2x1c2lvbiBhcmUgYm90aCBwb3B1bGFyIGUtY29tbWVyY2UgcHJvdmlkZXJzIHRoYXQgZ2l2ZSBidXNpbmVzcyBvd25lcnMgdGhlIG9wcG9ydHVuaXRpZXMgdG8gY3JlYXRlIHVuaXF1ZSBvbmxpbmUgc3RvcmVzLiBDb21wYXJpbmcgYm90aCBwbGF0Zm9ybXMgaGFzIHNpZ25pZmljYW50IGluZmx1ZW5jZSB3aGVuIGNob29zaW5nIHRoZSByaWdodCBmaXQgZm9yIHlvdXIgZS1jb21tZXJjZSBidXNpbmVzcy4gVGhlIG1vc3QgcG9wdWxhciBrZXkgZmFjdG9ycyBmb3IgY29tcGFyaW5nICBlLWNvbW1lcmNlIHBsYXRmb3JtcyBhcmU6PC9wPg0KDQo8b2w+DQoNCjxsaT5FYXNlLXRvLXVzZTwvbGk+DQo8bGk+RmVhdHVyZXM8L2xpPg0KPGxpPlByaWNpbmc8L2xpPg0KPGxpPlBheW1lbnQgR2F0ZXdheXM8L2xpPg0KPGxpPlN1cHBvcnQ8L2xpPg0KPGxpPkRlc2lnbiBhbmQgVGVtcGxhdGVzPC9saT4NCg0KPC9vbD4NCg0KPHA+IEkgd2lsbCBiZSB1c2luZyB0aGUgYWJvdmUgZmFjdG9ycyB0byBnaXZlIGEgZGV0YWlsZWQgYW5hbHl0aWMgcmVwb3J0IG9mIFNob3BpZnkgdnMgVm9sdXNpb24uPC9wPg0KDQo8aDM+RWFzZS10by11c2U8L2gzPg0KPHA+VXNlciBzaW1wbGljaXR5IGlzIGEgdmVyeSBpbXBvcnRhbnQgZmVhdHVyZSBmb3IgYW4gZS1jb21tZXJjZSBwbGF0Zm9ybS4gV2hlbiBpdCBjb21lcyB0byBlYXNlLXRvLXVzZSBmcmllbmRsaW5lc3MsIEkgd291bGQgc2F5IFNob3BpZnkgaXMgb24gdG9wIG9mIHRoZWlyIGdhbWUgY29tcGFyZWQgdG8gVm9sdXNpb24uIFRoZSBiaWdnZXN0IGRpZmZlcmVuY2VzIGJldHdlZW4gdGhlIHR3byBwbGF0Zm9ybXMgYXJlOyBTaG9waWZ5IGlzIGJ1aWx0IGZvciBib3RoIGJlZ2lubmVycyBhbmQgYWR2YW5jZWQgdXNlcnMsIHdoaWxlIFZvbHVzaW9uIGlzIGNvbXBsZXggYW5kIGNhbiBiZSBldmVuIGZydXN0cmF0aW5nIGZvciBib3RoIHVzZXJzLiBUaGlzIGdpdmVzIFNob3BpZnkgYSBjb21wZXRpdGl2ZSBhZHZhbnRhZ2Ugd2l0aCBhIHF1aWNrIG1ldGhvZCB0byBzZXR1cCBhbiBvbmxpbmUgc3RvcmUuDQpCb3RoIHBsYXRmb3JtcyBhbGxvdyB0aGUgdXNlciB0byBhY3RpdmVseSB1c2UvZWRpdCB0aGUgZGFzaGJvYXJkIG1lbnUgZm9yIG9yZGVycywgbWFya2V0aW5nLCBjdXN0b21lcnMsIGludmVudG9yeSwgZXRjLjwvcD4NCg0KPGgzPkZlYXR1cmVzPC9oMz4NCjxwPklmIHdlIGFyZSB0YWxraW5nIGFib3V0IGJhc2ljIHN0b3JlIGZ1bmN0aW9uYWxpdHksIGJvdGggU2hvcGlmeSBhbmQgVm9sdXNpb24gb2ZmZXJzIGFsbCB0aGUgcmVxdWlyZWQgZnVuY3Rpb25hbGl0aWVzIHRoYXQgYXJlIGZhaXJseSBwb3dlcmZ1bCB5ZXQgZWFzeSB0byBzZXR1cCwgdXNlIGFuZCBtYWludGFpbi4gQm90aCBwbGF0Zm9ybXMgaGF2ZSBBcHAgc3RvcmUsIHdpdGggU2hvcGlmeSBwcm92aWRpbmcgYSB3aWRlciBsaXN0IG9mIHZhcmlhbnRzIHRoYW4gVm9sdXNpb24uIEFwcHMgYWxsb3cgeW91IHRvIGFkZCBhZGRpdGlvbmFsIGZ1bmN0aW9uYWxpdHkgdG8gYW4gb25saW5lIHN0b3JlLCBhbmQgaW50ZWdyYXRlIHRoaXJkIHBhcnR5IHdlYiBhcHBsaWNhdGlvbnMuDQpWb2x1c2lvbiBoYXMgbXVsdGktbGluZ3VhbCBjYXBhYmlsaXRpZXMsIHRoaXMgbWVhbnMgVm9sdXNpb24gdXNlciBjYW4gZWFzaWx5IGhhdmUgdGhlaXIgZS1jb21tZXJjZSB3ZWJzaXRlIHRyYW5zbGF0ZWQgaW50byBtYW55IGRpZmZlcmVudCBsYW5ndWFnZXMuIEhvd2V2ZXIgU2hvcGlmeSBkb2VzIG5vdCBoYXZlIHRoaXMgZmVhdHVyZSBidWlsdCBpbiB0aGUgc3lzdGVtLCBpdCBjYW4gYmUgZWFzaWx5IGJlIGRvbmUgdGhyb3VnaCBwYWlkIHRoaXJkIHBhcnR5IGV4dGVuc2lvbnMuDQpJbiBteSBvcGluaW9uLCBJIGJlbGlldmUgYm90aCBwbGF0Zm9ybXMgb2ZmZXIgZXh0ZW5zaXZlIFNFTyBjYXBhYmlsaXRpZXMgaW4gb3JkZXIgdG8gYXR0cmFjdCBvcmdhbmljIHRyYWZmaWNzIHRvIHlvdXIgb25saW5lIHN0b3JlIHRocm91Z2ggc2VhcmNoIGVuZ2luZXMgPC9wPg0KDQo8aDM+UHJpY2luZzwvaDM+DQo8cD5QcmljaW5nIGlzIGEgcG93ZXJmdWwgaW5kaWNhdG9yIGluIHRoZSBlLWNvbW1lcmNlIG1hcmtldC4gSXQgd2lsbCBiZSBpbiB5b3VyIGJlc3QgaW50ZXJlc3QgdG8gY2FyZWZ1bGx5IHJlYWQgdGhlIHZhbHVlIG9mIHRoZSBwbGF0Zm9ybSByYXRoZXIgdGhhbiBtYWtpbmcgeW91ciBkZWNpc2lvbiBiYXNlZCB0aGUgY29zdCBvZiB0aGUgc2VydmljZXMuIFlvdSBjb3VsZCBlbmQgdXAgcGF5aW5nIGxlc3MgbW9uZXkgZm9yIGFuIG9ubGluZSBzdG9yZSBhdCB0aGUgYmVnaW5uaW5nIGFuZCBwYXkgbW9yZSBpbiB0aGUgbG9uZy1ydW4uDQpJdCdzIGltcG9ydGFudCB0byBub3RlIGhlcmUgdGhhdCBib3RoIHBsYXRmb3JtcyBkbyBub3QgcmVxdWlyZSBhbnkgc2V0dXAgZmVlcyB0byBzdGFydC4gSW4gZmFjdCwgdGhleSBib3RoIG9mZmVyIDE0LWRheXMgZnJlZSB0cmlhbCwgd2hpY2ggb25lIGNhbiB1c2UgdG8gdGVzdCBhbmQgZXZhbHVhdGUgdGhlIGZ1bmN0aW9uYWxpdHkgYW5kIGNhcGFiaWxpdHkgb2ZmZXJlZCBieSBob3N0aW5nIHlvdXIgZS1jb21tZXJjZSBzdG9yZSB3aXRoIHRoZWlyIHBsYXRmb3JtLg0KVGhlIHByaWNlIHJhbmdlIHRvIGhvc3QgeW91ciBvbmxpbmUgc3RvcmUgd2l0aCBTaG9waWZ5IHN0YXJ0cyBmcm9tICQyOSB0byAkMjk5IHBlciBtb250aCwgd2hpbGUgVm9sdXNpb24gc3RhcnRzIGZyb20gJDE1IHRvICQxMzUgcGVyIG1vbnRoLjwvcD4NCg0KPGgzPlBheW1lbnQgR2F0ZXdheXM8L2gzPg0KPHA+QW5vdGhlciBmYWN0b3IgdG8gY29uc2lkZXIgd2hlbiBjb21wYXJpbmcgdGhlIHR3byBwbGF0Zm9ybXMgaXMgY2hlY2tpbmcgdGhlaXIgcGF5bWVudCBnYXRld2F5IG9wdGlvbnMgbWV0aG9kcy4gQm90aCBwbGF0Zm9ybXMgaW50ZWdyYXRlIHdpdGggYSBsYXJnZSBudW1iZXIgb2YgcGF5bWVudCBnYXRld2F5cywgdGhpcmQtcGFydHkgdG9vbHMgdGhhdCBoZWxwIG9ubGluZSBzdG9yZXMgdG8gcHJvY2VzcyB0cmFuc2FjdGlvbnMgb24gdGhlIHdlYnNpdGUuIEZvcnR1bmF0ZWx5LCBTaG9waWZ5IHN1cnBhc3NlcyBWb2x1c2lvbiBpbiB0aGlzIGNyaXRlcmlhLCBvZiB3aGljaCwgU2hvcGlmeSBob2xkcyA3MCsgYW5kIFZvbHVzaW9uIDM4LiA8L3A+DQogDQo8aDM+U3VwcG9ydHM8L2gzPg0KPHA+U3VwcG9ydCBpcyBlc3NlbnRpYWwgc2VydmljZXMgZm9yIGFueSBzZXJ2aWNlcyBidXNpbmVzcyBhbmQgd2l0aG91dCB0aGlzIG1hbnkgb25saW5lIHN0b3Jlcywgb3duZXJzIHdpbGwgbm90IGJlIGFibGUgdG8gYWNjZXNzIGNyaXRpY2FsIGluZm9ybWF0aW9uLg0KU2hvcGlmeSBwcm92aWRlcyAyNC83IGN1c3RvbWVyIHN1cHBvcnRzLCB1c2luZyBhbiBvd24gYmxvZywgcmVzb3VyY2VzIGFuZCBhIGtub3dsZWRnZSBiYXNlIGh1YiBmb3IgY3VzdG9tZXIgbGVhcm5pbmcuIFRoZXkgb2ZmZXIgbGl2ZSBjaGF0LCBlbWFpbCwgcGhvbmUgYW5kIGZvcnVtIHN1cHBvcnQuDQpWb2x1c2lvbiBzdXBwb3J0IHBhZ2UgaXMgZmlsbGVkIHdpdGggZ29vZGllcywgc3VjaCBhcyBrbm93bGVkZ2UgYmFzZSwgdmlkZW9zIGFuZCBjb250YWN0IGZvcm0uIFRoZSAyNC83IHN1cHBvcnQgaXMgcHJvdmlkZWQgdGhyb3VnaCBsaXZlIGNoYXQsIHBob25lLCBhbmQgZW1haWwuPC9wPg0KIA0KPGgzPkRlc2lnbiBhbmQgVGVtcGxhdGVzPC9oMz4NCjxwPlRoZSBkZXNpZ24gb2YgeW91ciBlLWNvbW1lcmNlIHdlYnNpdGUgaXMgYSBrZXkgZmFjdG9yIHRvIGF0dHJhY3QgbW9yZSB2aXNpdG9ycyB0byB5b3VyIHdlYnNpdGUuIEFuIHVucHJvZmVzc2lvbmFsbHkgZGVzaWduZWQgd2Vic2l0ZSB3aWxsIG5vdCBpbnNwaXJlIHRydXN0IGluIHlvdXIgY3VzdG9tZXIncyBleWVzLCBzbyBpdCBpcyBiZXN0IHRvIGJlIG9uIHRvcCBvZiB5b3VyIGdhbWUgaW4gdGhpcyBpbmRpY2F0b3IuDQpTaG9waWZ5IG9mZmVycyAyMSBmcmVlIHRoZW1lcyBhbmQgYWJvdXQgMTE2IHBhaWQgdGhlbWVzLiBUaGVpciB0aGVtZXMgbG9vayBtb2Rlcm5pemVkIGFuZCBpdCBkb2VzIG5vdCB0YWtlIG11Y2ggdG8gY3VzdG9taXplIHRoZW0gd2l0aG91dCBrbm93aW5nIGhvdyB0byBjdXN0b20gY29kZS4NCk9uIHRoZSBvdGhlciBoYW5kLCBWb2x1c2lvbiBoYXMgMjggZnJlZSB0aGVtZXMgYW5kIDg4IHBhaWQgdGhlbWVzLiBUaGlzIGlzIGFsbW9zdCBhIGNsb3NlIG9mZmVyaW5nIHRvIHdoYXQgeW91IGNhbiBmaW5kIG9uIFNob3BpZnkuIFRoZWlyIGRlc2lnbiBpcyBub3QgYXMgbW9kZXJuIGFuZCBzb3BoaXN0aWNhdGVkLCBob3dldmVyLCB0aGV5IGFyZSBhY2NlcHRhYmxlLiBWb2x1c2lvbiB0aGVtZXMgY2FuIGJlICBhIGxpdHRsZSBiaXQgZGlmZmljdWx0IHRvIGN1c3RvbWl6ZS4NCkl0IGlzIGltcG9ydGFudCB0byBub3RlOyBib3RoIHBsYXRmb3JtcyBvZmZlciBsaW1pdGVkIGZyZWUgcmVzcG9uc2l2ZSB0ZW1wbGF0ZXMgd2l0aCBTaG9waWZ5IHN1cnBhc3NpbmcgVm9sdXNpb24uIFRoZSBnZW5lcmFsIGlkZWFzIGFyZSB0aGVyZSBpcyBhIHBvc3NpYmlsaXR5IGZvciB5b3VyIHdlYnNpdGUgdG8gYmUgbW9iaWxlIGZyaWVuZGx5IHdpdGhvdXQgbXVjaCBvZiBhIGhhc3NsZS4NCiANCkluIGxpZ2h0IG9mIHdoaWNoIHBsYXRmb3JtIGlzIGJldHRlciwgd2UgaGF2ZSBkaXNjdXNzZWQgdGhhdCBtb3N0bHkgU2hvcGlmeSBoYXMgYSBncmVhdGVyIGFkdmFudGFnZSBvbiBWb2x1c2lvbi4gTm90IHRvIHNheSB0aGF0IFZvbHVzaW9uIGlzIGJhZCBmb3IgeW91ciBlLWNvbW1lcmNlIHN0b3JlLCBpdCBpcyBpbXBvcnRhbnQgdG8gbm90ZSB0aGF0IHdoYXQgeW91IHRoaW5rIGlzIGJhZCBmb3IgeW91IG9uIHRoZSBvdGhlciBzaWRlIG1pZ2h0IGJlIGFuIGFkdmFudGFnZSBmb3IgdGhlIG5leHQgcGVyc29uLiBTaW5jZSBib3RoIHBsYXRmb3JtcyBvZmZlciBhIDE0LWRheSBkZW1vIHRyaWFsIHBlcmlvZCBJIHdvdWxkIHN1Z2dlc3QgeW91IHNpZ24gdXAgZm9yIGJvdGggcGxhdGZvcm1zIGFuZCBzZWUgZm9yIHlvdXJzZWxmIHRoZSByZXN1bHRzLiBCZWNhdXNlIHNvbWUgY29tcHJpc2luZyBjYW4gYmUgZmFpcmx5IGJpYXNlZCBhbmQgeW91IG1pZ2h0IGVuZCB1cCBtYWtpbmcgdGhlIHdyb25nIGRlY2lzaW9uIGZvciB5b3VyIGUtY29tbWVyY2UgYnVzaW5lc3MuICJUcnkgbiBFcnJvciIgIGFwcHJvYWNoIGlzIHRoZSBiZXN0IHNvbHV0aW9uIGF2YWlsYWJsZSB0byB0YWNrbGUgdGhpcyBwcm9ibGVtLiA8L3A+DQoNCg0KPGgzPkNvbXBhcmlzb24gb2YgVm9sdXNpb24gdnMgU2hvcGlmeTwvaDM+DQo8cD5Wb2x1c2lvbiBhbmQgU2hvcGlmeSBhcmUgd2hhdCB3ZSBjbGFzc2lmeSBhcyB0aGUgbGVhZGluZyBlLWNvbW1lcmNlIHBsYXRmb3JtIHByb3ZpZGVycyBpbiB0aGUgaW5kdXN0cnkgYW5kIHRoZWlyIGNvbXBhcmlzb24gYmV0d2VlbiBib3RoIGFyZSBhIHZlcnkgZGlmZmljdWx0IGRpc2N1c3Npb24gdG8gY29tcGlsZSBhIGRldGFpbGVkIHJlcG9ydCB3aXRob3V0IGJlaW5nIGJpYXNlZCB0byBvbmUgcGxhdGZvcm0uIEl0IHNob3VsZCBiZSBmYWlybHkgbm90ZWQgdGhhdCBib3RoIHBsYXRmb3JtcyBoYXZlIHRoZWlyIHByb3MgYW5kIGNvbnMgYW5kIHRoZXJlIGlzIG5vIGNsZWFyIGFuc3dlciB0byB3aGljaCBpcyBiZXN0IGluIHRoZSBtYXJrZXQuIERlcGVuZGluZyBvbiB5b3VyIHRlY2huaWNhbCBrbm93LWhvdyBhbmQgYnVkZ2V0LCBpdCBpcyB2ZXJ5IGltcG9ydGFudCB0byB3ZWlnaHQgeW91ciBkZWNpc2lvbiBvbiB3aGF0IHlvdSByZWFsbHkgZXhwZWN0IGZyb20gYW4gZS1jb21tZXJjZSBwbGF0Zm9ybSBPbmUgc2hvdWxkIGFsc28gY29uc2lkZXIgdGhlIHR5cGUgb2YgZnVuY3Rpb25hbGl0eSBmZWF0dXJlcyB5b3UgcmVxdWlyZSBhbmQgd2hhdCBlYWNoIHBsYXRmb3JtIGlzIGZyZWVseSB3aWxsaW5nIHRvIG9mZmVyIGFuZCB3aGljaCBub3QuIEluIG15IHJldmlldyBjb21wYXJpc29uIG9mIHBsYXRmb3JtcywgSSBtb3N0bHkgY29uY2VudHJhdGUgb24gdGhlIHBvcHVsYXIga2V5IGZhY3RvcnMgZm9yIGNvbXBhcmluZyBhbiBlLWNvbW1lcmNlIHBsYXRmb3JtIHN1Y2ggYXM7IHByaWNlcywgZGVzaWduLCBhbmQgdGVtcGxhdGVzLCBjdXN0b21lciBzdXBwb3J0LCBmZWF0dXJlcyBhbmQgZWFzZS10by11c2UuPC9wPg0KIA0KPGgzPlZvbHVzaW9uIHZzIFNob3BpZnk6IFByaWNpbmc8L2gzPg0KPHA+V2UgYWxsIGFncmVlIHRoYXQgODAlIG9mIG91ciBkZWNpc2lvbi1tYWtpbmcgcHJvY2VzcyBpcyBkZXJpdmVkIGZyb20gdGhlIGNvc3Qgb2YgYSBwcm9kdWN0LCBidXQgaW4gdGhlIGUtY29tbWVyY2UsIGluZHVzdHJ5IHByaWNlIGhhcyBhIGNlcnRhaW4gbGltaXRhdGlvbi4gWW91IGNhbiBjaG9vc2UgYSBwbGF0Zm9ybSB3aGljaCBpcyByZWxhdGl2ZWx5IGNoZWFwZXIgdGhhbiB0aGUgY29tcGV0aXRvciwgYnV0IHlvdSB3aWxsIG5vdCBiZSBzYXRpc2ZpZWQgd2l0aCB0aGUgc2VydmljZXMgeW91IHdpbGwgZ2V0IGJlY2F1c2UgaWYgeW91IHVzZSBhIHByaWNlIGFzIHRoZSBvbmx5IGluZGljYXRvciB0aGVuIHlvdSB3aWxsIGVuZCB1cCBmYWlsaW5nIGluIHlvdXIgZS1jb21tZXJjZSBhZHZlbnR1cmUuIFZvbHVzaW9uIHByaWNlIHRhZyBzdGFydHMgZnJvbSAkMTUgdG8gJDEzNSBwZXIgbW9udGggYW5kIGFzIGZvciBTaG9waWZ5IGlzIGZyb20gJDI5IHRvICQyOTkgcGVyIG1vbnRoLiBCb3RoIHBsYXRmb3JtcyBvZmZlciBhIDE0LWRheXMgZnJlZSB0cmlhbCBhbmQgZG8gbm90IHJlcXVpcmUgYW55IHNldHVwIGZlZXMgbm9yIHJlcXVpcmVzIHlvdSB0byBtYWtlIGFueSBjb21taXRtZW50LiBBbGwgeW91IGRvIGlzIHNpZ24gdXAgYW5kIHNlZSBpZiB0aGlzIHRoZSByaWdodCBwbGF0Zm9ybSBmb3IgeW91ciBidXNpbmVzcy48L3A+DQogDQo8aDM+Vm9sdXNpb24gdnMgU2hvcGlmeTogRGVzaWduIGFuZCBUZW1wbGF0ZXM8L2gzPg0KPHA+RXZlcnlib2R5IGtub3dzIHRoYXQgdGhlIGZpcnN0IGltcHJlc3Npb24gcmVhbGx5IG1ha2VzIGEgZGlmZmVyZW5jZSBhbmQgd2hlbiBpdCdzIGNvbWUgdG8gYW4gZS1jb21tZXJjZSB3ZWJzaXRlLCB5b3VyIGJ1c2luZXNzIHdpbGwgYmUganVkZ2VkIGJ5IGhvdyBhcHBlYWxpbmcgYW5kIGF0dHJhY3RpdmUgaXMgeW91ciB3ZWJzaXRlIGRlc2lnbnMuIFBlb3BsZSBsaWtlICJ3b3ciIHJlc3VsdHMsIGFuZCBpZiB5b3VyIHdlYnNpdGUgZG9lcyBub3QgZ2l2ZSB5b3VyIHBvdGVudGlhbCBjdXN0b21lciB0aGF0IHRoZW4gZm9yZ2V0IHRoZW0gc3RheWluZyBvbiB0aGUgd2Vic2l0ZS4NCkJvdGggcGxhdGZvcm1zIG9mZmVyIGEgcmVhc29uYWJsZSBsaXN0IG9mIHRoZW1lcyBmb3IgeW91ciBlLWNvbW1lcmNlIHdlYnNpdGUuIFZvbHVzaW9uIG9mZmVycyAyOCBmcmVlIHRoZW1lcyBhbmQgYWJvdXQgODggcGFpZCB0aGVtZXMuIFRoZWlyIHRoZW1lcyBsb29rIGRlY2VudCB3aGljaCBpcyBhIGdvb2QgZW5vdWdoIGZvciBjdXN0b21pemF0aW9uLiBXaXRoIFNob3BpZnksIHlvdSB3aWxsIGdldCAyMSBmcmVlIHRoZW1lcyBhbmQgMTE2IHBhaWQgdGhlbWUuIFNob3BpZnkgdGhlcmUgYXJlIG11Y2ggbW9yZSBtb2Rlcm4gYW5kIHVwZGF0ZSBhcyB0aGV5IG91dHNvdXJjZSBtYW55IGRlc2lnbmVycyB0byBjcmVhdGUgbW9yZSBnb29kIGF0dHJhY3RpdmUgdGhlbWVzLg0KVGhlIGdvb2QgbmV3cyBpcyB0aGF0IGJvdGggcGxhdGZvcm1zIG9mZmVyIGZyZWUgcmVzcG9uc2l2ZSB0ZW1wbGF0ZXMgd2l0aCBTaG9waWZ5IHByb3ZpZGluZyBtb3JlIG9wdGlvbnMgdG8gY2hvb3NlIGZyb20gdGhhbiBWb2x1c2lvbi4gIFRoZSBpZGVhcyBoZXJlIGlzIHVzaW5nIGJvdGggcGxhdGZvcm1zIHlvdXIgd2Vic2l0ZSB3aWxsIGJlIGZ1bGx5IG1vYmlsZSBmcmllbmRseS4gVGhlIGFkdmFudGFnZSBvZiByZXNwb25zaXZlIHdlYnNpdGUgaXMgdGhhdCB3ZSBsaXZlIGluIGFuIHRlY2hub2xvZ2ljYWwgZXJhLCB3aGVyZSBldmVyeW9uZSBvd25zIGEgU21hcnRwaG9uZS48L3A+DQogDQo8aDM+Vm9sdXNpb24gdnMgU2hvcGlmeTogQ3VzdG9tZXIgU3VwcG9ydDwvaDM+DQo8cD5XaGVuIHlvdXIgZS1jb21tZXJjZSB3ZWJzaXRlIGlzIGRvd24gb3Igc29tZXRoaW5nIGlzIG5vdCB3b3JraW5nIGFzIGl0cyBzdXBwb3NlIHRvLCBpdCBpcyBpbXBvcnRhbnQgdG8gZ2V0IGhvbGQgb2YgeW91ciBwbGF0Zm9ybSBwcm92aWRlciBhcyBzb29uIGFzIHBvc3NpYmxlLiBBcyBldmVyeSBtaW51dGUgeW91ciB3ZWJzaXRlIGlzIGRvd24sIGlzIGEgcG9zc2libGUgbG9zcyBvZiBzYWxlcy4NCkkgd291bGQgc2F5IHRoYXQgYm90aCBwbGF0Zm9ybXMgaGVyZSBoYXZlIGRvbmUgYSBncmVhdCBqb2IgYnkgcHJvdmlkaW5nIDI0LzcgY3VzdG9tZXIgc3VwcG9ydHMgdG8gdGhlIGNsaWVudHMuIEJvdGggcGxhdGZvcm1zIG9mZmVyIHRoZWlyIHNlcnZpY2VzIHVzaW5nIGxpdmUgY2hhdCwgcGhvbmUsIGFuZCBlbWFpbCBhbmQgYXMgYW4gYWRkaXRpb24sIHRoZXkgaGF2ZSBkZXRhaWxlZCByZXNvdXJjZXMgZm9ydW0gZm9yIHRoZWlyIGNsaWVudHMuPC9wPg0KIA0KIA0KPGgzPlZvbHVzaW9uIHZzIFNob3BpZnk6IEZlYXR1cmVzPC9oMz4NCjxwPkJvdGggcGxhdGZvcm1zIG9mZmVyIHNpbWlsYXIgYmFzaWMgZnVuY3Rpb25hbGl0eSBmZWF0dXJlcyB0byBkbyBhbGwga2luZHMgZnVuY3Rpb24geW91IHdvdWxkIGV4cGVjdCBhbiBlLWNvbW1lcmNlIHBsYXRmb3JtIHRvIGV4ZWN1dGU7IHByb2R1Y3QgbWFuYWdlbWVudCwgY3JlYXRlIGEgZGlzY291bnQgY291cG9uLCBhY2NlcHQgZGlmZmVyZW50IG9ubGluZSBwYXltZW50LCBldGMuDQpUaGVyZSBpcyBubyBtdWNoIGRpZmZlcmVuY2Ugd2hlbiBpdCBjb21lcyB0byBmdXR1cmUgY29tcGV0aXRpdmVuZXNzIGFzIGJvdGggcGxhdGZvcm1zIHByb3ZpZGUgYW4gZXh0ZW5zaXZlIGxpc3Qgb2YgYWRkLW9uIGFwcHMgaW4gdGhlaXIgQXBwIFN0b3Jlcy4gVGhlIG9ubHkgdmlzaWJsZSBkaWZmZXJlbmNlcyBiZXR3ZWVuIFZvbHVzaW9uIGFuZCBTaG9waWZ5IGlzIHRoYXQgVm9sdXNpb24gaGFzIGEgcmVhZHkgYnVpbHQtaW4gbXVsdGktbGluZ3VhbCBzeXN0ZW0gd2hpY2ggZW5hYmxlcyB5b3UgdG8gaG9zdCB5b3VyIHdlYnNpdGUgaW4gbWFueSBkaWZmZXJlbnQgbGFuZ3VhZ2VzLiBCdXQgd2l0aCBTaG9waWZ5LCB5b3Ugd2lsbCBuZWVkIGEgM3JkIHBhcnR5IGludGVncmF0aW9uIHRvIGRvIHRoaXMuDQpQYXltZW50IGdhdGV3YXlzIGFyZSBlc3NlbnRpYWwgdG8gZS1jb21tZXJjZSBidXNpbmVzcyBhbmQgYm90aCBwbGF0Zm9ybXMgcHJvdmlkZSB0aGlzLiBPZiBjb3Vyc2UsIFNob3BpZnkgc3VycGFzc2VzIFZvbHVzaW9uIHdpdGggNzArIHBheW1lbnQgZ2F0ZXdheXMgd2hpbGUgdGhlIGNvbXBldGl0b3IgZ290IDM4LjwvcD4NCiANCjxoMz5Wb2x1c2lvbiB2cyBTaG9waWZ5OiBFYXNlLXRvLXVzZTwvaDM+DQo8cD5FLWNvbW1lcmNlIHBsYXRmb3JtIHVzZXJzIGFsd2F5cyBsb29rIGZvciBzaW1wbGljaXR5IGFuZCB3aGVyZSB0aGV5IGNhbiBlYXNpbHkgc2V0dXAgdGhlaXIgb25saW5lIHN0b3Jlcy4gTm8gb25lIHdpbGwgc2V0dGxlIGZvciBhIGNvbXBsaWNhdGVkIHBsYXRmb3JtIHRoYXQgd2lsbCBnaXZlIHRoZW0gbG90cyBvZiBoZWFkYWNoZXMgdG8gdXNlLiBJIGJlbGlldmUgU2hvcGlmeSBoYXMgYSBtb3JlIHVzZXItZnJpZW5kbHkgc3lzdGVtLCB0aGF0IGNhbiBiZSB1c2VkIGJ5IGJvdGggYmVnaW5uZXJzIGFuZCBhZHZhbmNlZCB1c2VyLCB0aGFuIFZvbHVzaW9uLiBTdXJwcmlzaW5nbHksIGJvdGggcGxhdGZvcm1zIGFsbG93IHlvdSB0byBjdXN0b21pemUgeW91ciB3ZWJzaXRlIHRvIGV2ZXJ5b25lIGluZGl2aWR1YWwgbmVlZCwgYnV0IHNob3VsZCBiZSBub3RlZCB0aGF0IGl0J3Mgb25seSB0byBhIGNlcnRhaW4gZGVncmVlLiBZb3Ugd2lsbCwgYWxzbywgaG93ZXZlciwgbGF1bmNoIHlvdXIgZS1jb21tZXJjZSB3ZWJzaXRlIGZhc3RlciB3aXRoIFNob3BpZnkgdGhhbiBWb2x1c2lvbi48L3A+DQogDQo8aDM+Q29uY2x1c2lvbjwvaDM+DQo8cD5FdmVuIHRob3VnaCBib3RoIHBsYXRmb3JtcyBoYXZlIHRoZWlyIGFkdmFudGFnZXMgYW5kIGRpc2FkdmFudGFnZXMsIGl0IGlzIGltcG9ydGFudCB0byBub3RlIHRoYXQgYm90aCBwbGF0Zm9ybXMgY29tcGV0aXRpdmVseSB3aWxsaW5nIHRvIHBvd2VyIHlvdXIgZS1jb21tZXJjZSB3ZWJzaXRlLiBUaGVyZSBpcyBubyByZWFsIGJlc3QgcGxhdGZvcm0gaW4gdGhlIG1hcmtldCBhbmQgd2hlbiBjaG9vc2luZyB0aGUgcmlnaHQgZml0IHdpbGwgZGVwZW5kIG9uIHlvdXIgZmluYW5jaWFsIGJ1ZGdldCBhbmQgdGhlIG5hdHVyZSBvZiB5b3VyIGJ1c2luZXNzLiBCb3RoIHBsYXRmb3JtcyBvZmZlciBkZW1vIHRyaWFsIHBlcmlvZCB3aXRoIG5vIHN0cmluZyBhdHRhY2hlZCBhbmQgaXQncyBpbiB5b3VyIGJlc3QgaW50ZXJlc3QgdG8gZnVsbHkgdXRpbGl6ZSB0aGlzIG9mZmVyIHRlc3QgZWFjaCBwbGF0Zm9ybSBiZWZvcmUgbWFraW5nIHlvdXIgZmluYWwgZGVjaXNpb24NCkEgZnJpZW5kbHkgcmVtZW1iZXIgaWYgdGhlIGFib3ZlIGRvZXMgbm90IGNvbnZpbmNlIHlvdSB0byBjaG9vc2UsIHRoZXJlIGFyZSBwbGVudHkgb2YgZS1jb21tZXJjZSBwbGF0Zm9ybSBpbiB0aGUgaW5kdXN0cnkuIFNvIGRvbid0IGZlZWwgcHJlc3N1cmVkLCBleHBsb3JlIG90aGVyIHNvbHV0aW9uIGFuZCB5b3Ugd2lsbCBzdXJlbHkgZmluZCBvbmUgdGhhdCB3aWxsIGdpdmUgeW91IHRoYXQgIndvdyIgcmVzdWx0LjwvcD5kZAICDw8WAh8ABctWPGgxPlRoZSBkaWZmZXJlbmNlcyBiZXR3ZWVuIFNob3BpZnkgdnMgVm9sdXNpb248L2gxPjxwPlNlbGVjdGluZyB0aGUgcmlnaHQgZS1jb21tZXJjZSBwbGF0Zm9ybSBmb3IgeW91ciBlLWNvbW1lcmNlIGJ1c2luZXNzIGNhbiBiZSBhbiBvdmVyd2hlbG1pbmcgcHJvY2VzcyB0aGF0IHdpbGwgdGFrZSB1cCBtb3N0IG9mIHlvdXIgdGltZS4gU2hvcGlmeSBhbmQgVm9sdXNpb24gYXJlIGJvdGggcG9wdWxhciBlLWNvbW1lcmNlIHByb3ZpZGVycyB0aGF0IGdpdmUgYnVzaW5lc3Mgb3duZXJzIHRoZSBvcHBvcnR1bml0aWVzIHRvIGNyZWF0ZSB1bmlxdWUgb25saW5lIHN0b3Jlcy4gQ29tcGFyaW5nIGJvdGggcGxhdGZvcm1zIGhhcyBzaWduaWZpY2FudCBpbmZsdWVuY2Ugd2hlbiBjaG9vc2luZyB0aGUgcmlnaHQgZml0IGZvciB5b3VyIGUtY29tbWVyY2UgYnVzaW5lc3MuIFRoZSBtb3N0IHBvcHVsYXIga2V5IGZhY3RvcnMgZm9yIGNvbXBhcmluZyAgZS1jb21tZXJjZSBwbGF0Zm9ybXMgYXJlOjwvcD4NCg0KPG9sPg0KDQo8bGk+RWFzZS10by11c2U8L2xpPg0KPGxpPkZlYXR1cmVzPC9saT4NCjxsaT5QcmljaW5nPC9saT4NCjxsaT5QYXltZW50IEdhdGV3YXlzPC9saT4NCjxsaT5TdXBwb3J0PC9saT4NCjxsaT5EZXNpZ24gYW5kIFRlbXBsYXRlczwvbGk+DQoNCjwvb2w+DQoNCjxwPiBJIHdpbGwgYmUgdXNpbmcgdGhlIGFib3ZlIGZhY3RvcnMgdG8gZ2l2ZSBhIGRldGFpbGVkIGFuYWx5dGljIHJlcG9ydCBvZiBTaG9waWZ5IHZzIFZvbHVzaW9uLjwvcD4NCg0KPGgzPkVhc2UtdG8tdXNlPC9oMz4NCjxwPlVzZXIgc2ltcGxpY2l0eSBpcyBhIHZlcnkgaW1wb3J0YW50IGZlYXR1cmUgZm9yIGFuIGUtY29tbWVyY2UgcGxhdGZvcm0uIFdoZW4gaXQgY29tZXMgdG8gZWFzZS10by11c2UgZnJpZW5kbGluZXNzLCBJIHdvdWxkIHNheSBTaG9waWZ5IGlzIG9uIHRvcCBvZiB0aGVpciBnYW1lIGNvbXBhcmVkIHRvIFZvbHVzaW9uLiBUaGUgYmlnZ2VzdCBkaWZmZXJlbmNlcyBiZXR3ZWVuIHRoZSB0d28gcGxhdGZvcm1zIGFyZTsgU2hvcGlmeSBpcyBidWlsdCBmb3IgYm90aCBiZWdpbm5lcnMgYW5kIGFkdmFuY2VkIHVzZXJzLCB3aGlsZSBWb2x1c2lvbiBpcyBjb21wbGV4IGFuZCBjYW4gYmUgZXZlbiBmcnVzdHJhdGluZyBmb3IgYm90aCB1c2Vycy4gVGhpcyBnaXZlcyBTaG9waWZ5IGEgY29tcGV0aXRpdmUgYWR2YW50YWdlIHdpdGggYSBxdWljayBtZXRob2QgdG8gc2V0dXAgYW4gb25saW5lIHN0b3JlLg0KQm90aCBwbGF0Zm9ybXMgYWxsb3cgdGhlIHVzZXIgdG8gYWN0aXZlbHkgdXNlL2VkaXQgdGhlIGRhc2hib2FyZCBtZW51IGZvciBvcmRlcnMsIG1hcmtldGluZywgY3VzdG9tZXJzLCBpbnZlbnRvcnksIGV0Yy48L3A+DQoNCjxoMz5GZWF0dXJlczwvaDM+DQo8cD5JZiB3ZSBhcmUgdGFsa2luZyBhYm91dCBiYXNpYyBzdG9yZSBmdW5jdGlvbmFsaXR5LCBib3RoIFNob3BpZnkgYW5kIFZvbHVzaW9uIG9mZmVycyBhbGwgdGhlIHJlcXVpcmVkIGZ1bmN0aW9uYWxpdGllcyB0aGF0IGFyZSBmYWlybHkgcG93ZXJmdWwgeWV0IGVhc3kgdG8gc2V0dXAsIHVzZSBhbmQgbWFpbnRhaW4uIEJvdGggcGxhdGZvcm1zIGhhdmUgQXBwIHN0b3JlLCB3aXRoIFNob3BpZnkgcHJvdmlkaW5nIGEgd2lkZXIgbGlzdCBvZiB2YXJpYW50cyB0aGFuIFZvbHVzaW9uLiBBcHBzIGFsbG93IHlvdSB0byBhZGQgYWRkaXRpb25hbCBmdW5jdGlvbmFsaXR5IHRvIGFuIG9ubGluZSBzdG9yZSwgYW5kIGludGVncmF0ZSB0aGlyZCBwYXJ0eSB3ZWIgYXBwbGljYXRpb25zLg0KVm9sdXNpb24gaGFzIG11bHRpLWxpbmd1YWwgY2FwYWJpbGl0aWVzLCB0aGlzIG1lYW5zIFZvbHVzaW9uIHVzZXIgY2FuIGVhc2lseSBoYXZlIHRoZWlyIGUtY29tbWVyY2Ugd2Vic2l0ZSB0cmFuc2xhdGVkIGludG8gbWFueSBkaWZmZXJlbnQgbGFuZ3VhZ2VzLiBIb3dldmVyIFNob3BpZnkgZG9lcyBub3QgaGF2ZSB0aGlzIGZlYXR1cmUgYnVpbHQgaW4gdGhlIHN5c3RlbSwgaXQgY2FuIGJlIGVhc2lseSBiZSBkb25lIHRocm91Z2ggcGFpZCB0aGlyZCBwYXJ0eSBleHRlbnNpb25zLg0KSW4gbXkgb3BpbmlvbiwgSSBiZWxpZXZlIGJvdGggcGxhdGZvcm1zIG9mZmVyIGV4dGVuc2l2ZSBTRU8gY2FwYWJpbGl0aWVzIGluIG9yZGVyIHRvIGF0dHJhY3Qgb3JnYW5pYyB0cmFmZmljcyB0byB5b3VyIG9ubGluZSBzdG9yZSB0aHJvdWdoIHNlYXJjaCBlbmdpbmVzIDwvcD4NCg0KPGgzPlByaWNpbmc8L2gzPg0KPHA+UHJpY2luZyBpcyBhIHBvd2VyZnVsIGluZGljYXRvciBpbiB0aGUgZS1jb21tZXJjZSBtYXJrZXQuIEl0IHdpbGwgYmUgaW4geW91ciBiZXN0IGludGVyZXN0IHRvIGNhcmVmdWxseSByZWFkIHRoZSB2YWx1ZSBvZiB0aGUgcGxhdGZvcm0gcmF0aGVyIHRoYW4gbWFraW5nIHlvdXIgZGVjaXNpb24gYmFzZWQgdGhlIGNvc3Qgb2YgdGhlIHNlcnZpY2VzLiBZb3UgY291bGQgZW5kIHVwIHBheWluZyBsZXNzIG1vbmV5IGZvciBhbiBvbmxpbmUgc3RvcmUgYXQgdGhlIGJlZ2lubmluZyBhbmQgcGF5IG1vcmUgaW4gdGhlIGxvbmctcnVuLg0KSXQncyBpbXBvcnRhbnQgdG8gbm90ZSBoZXJlIHRoYXQgYm90aCBwbGF0Zm9ybXMgZG8gbm90IHJlcXVpcmUgYW55IHNldHVwIGZlZXMgdG8gc3RhcnQuIEluIGZhY3QsIHRoZXkgYm90aCBvZmZlciAxNC1kYXlzIGZyZWUgdHJpYWwsIHdoaWNoIG9uZSBjYW4gdXNlIHRvIHRlc3QgYW5kIGV2YWx1YXRlIHRoZSBmdW5jdGlvbmFsaXR5IGFuZCBjYXBhYmlsaXR5IG9mZmVyZWQgYnkgaG9zdGluZyB5b3VyIGUtY29tbWVyY2Ugc3RvcmUgd2l0aCB0aGVpciBwbGF0Zm9ybS4NClRoZSBwcmljZSByYW5nZSB0byBob3N0IHlvdXIgb25saW5lIHN0b3JlIHdpdGggU2hvcGlmeSBzdGFydHMgZnJvbSAkMjkgdG8gJDI5OSBwZXIgbW9udGgsIHdoaWxlIFZvbHVzaW9uIHN0YXJ0cyBmcm9tICQxNSB0byAkMTM1IHBlciBtb250aC48L3A+DQoNCjxoMz5QYXltZW50IEdhdGV3YXlzPC9oMz4NCjxwPkFub3RoZXIgZmFjdG9yIHRvIGNvbnNpZGVyIHdoZW4gY29tcGFyaW5nIHRoZSB0d28gcGxhdGZvcm1zIGlzIGNoZWNraW5nIHRoZWlyIHBheW1lbnQgZ2F0ZXdheSBvcHRpb25zIG1ldGhvZHMuIEJvdGggcGxhdGZvcm1zIGludGVncmF0ZSB3aXRoIGEgbGFyZ2UgbnVtYmVyIG9mIHBheW1lbnQgZ2F0ZXdheXMsIHRoaXJkLXBhcnR5IHRvb2xzIHRoYXQgaGVscCBvbmxpbmUgc3RvcmVzIHRvIHByb2Nlc3MgdHJhbnNhY3Rpb25zIG9uIHRoZSB3ZWJzaXRlLiBGb3J0dW5hdGVseSwgU2hvcGlmeSBzdXJwYXNzZXMgVm9sdXNpb24gaW4gdGhpcyBjcml0ZXJpYSwgb2Ygd2hpY2gsIFNob3BpZnkgaG9sZHMgNzArIGFuZCBWb2x1c2lvbiAzOC4gPC9wPg0KIA0KPGgzPlN1cHBvcnRzPC9oMz4NCjxwPlN1cHBvcnQgaXMgZXNzZW50aWFsIHNlcnZpY2VzIGZvciBhbnkgc2VydmljZXMgYnVzaW5lc3MgYW5kIHdpdGhvdXQgdGhpcyBtYW55IG9ubGluZSBzdG9yZXMsIG93bmVycyB3aWxsIG5vdCBiZSBhYmxlIHRvIGFjY2VzcyBjcml0aWNhbCBpbmZvcm1hdGlvbi4NClNob3BpZnkgcHJvdmlkZXMgMjQvNyBjdXN0b21lciBzdXBwb3J0cywgdXNpbmcgYW4gb3duIGJsb2csIHJlc291cmNlcyBhbmQgYSBrbm93bGVkZ2UgYmFzZSBodWIgZm9yIGN1c3RvbWVyIGxlYXJuaW5nLiBUaGV5IG9mZmVyIGxpdmUgY2hhdCwgZW1haWwsIHBob25lIGFuZCBmb3J1bSBzdXBwb3J0Lg0KVm9sdXNpb24gc3VwcG9ydCBwYWdlIGlzIGZpbGxlZCB3aXRoIGdvb2RpZXMsIHN1Y2ggYXMga25vd2xlZGdlIGJhc2UsIHZpZGVvcyBhbmQgY29udGFjdCBmb3JtLiBUaGUgMjQvNyBzdXBwb3J0IGlzIHByb3ZpZGVkIHRocm91Z2ggbGl2ZSBjaGF0LCBwaG9uZSwgYW5kIGVtYWlsLjwvcD4NCiANCjxoMz5EZXNpZ24gYW5kIFRlbXBsYXRlczwvaDM+DQo8cD5UaGUgZGVzaWduIG9mIHlvdXIgZS1jb21tZXJjZSB3ZWJzaXRlIGlzIGEga2V5IGZhY3RvciB0byBhdHRyYWN0IG1vcmUgdmlzaXRvcnMgdG8geW91ciB3ZWJzaXRlLiBBbiB1bnByb2Zlc3Npb25hbGx5IGRlc2lnbmVkIHdlYnNpdGUgd2lsbCBub3QgaW5zcGlyZSB0cnVzdCBpbiB5b3VyIGN1c3RvbWVyJ3MgZXllcywgc28gaXQgaXMgYmVzdCB0byBiZSBvbiB0b3Agb2YgeW91ciBnYW1lIGluIHRoaXMgaW5kaWNhdG9yLg0KU2hvcGlmeSBvZmZlcnMgMjEgZnJlZSB0aGVtZXMgYW5kIGFib3V0IDExNiBwYWlkIHRoZW1lcy4gVGhlaXIgdGhlbWVzIGxvb2sgbW9kZXJuaXplZCBhbmQgaXQgZG9lcyBub3QgdGFrZSBtdWNoIHRvIGN1c3RvbWl6ZSB0aGVtIHdpdGhvdXQga25vd2luZyBob3cgdG8gY3VzdG9tIGNvZGUuDQpPbiB0aGUgb3RoZXIgaGFuZCwgVm9sdXNpb24gaGFzIDI4IGZyZWUgdGhlbWVzIGFuZCA4OCBwYWlkIHRoZW1lcy4gVGhpcyBpcyBhbG1vc3QgYSBjbG9zZSBvZmZlcmluZyB0byB3aGF0IHlvdSBjYW4gZmluZCBvbiBTaG9waWZ5LiBUaGVpciBkZXNpZ24gaXMgbm90IGFzIG1vZGVybiBhbmQgc29waGlzdGljYXRlZCwgaG93ZXZlciwgdGhleSBhcmUgYWNjZXB0YWJsZS4gVm9sdXNpb24gdGhlbWVzIGNhbiBiZSAgYSBsaXR0bGUgYml0IGRpZmZpY3VsdCB0byBjdXN0b21pemUuDQpJdCBpcyBpbXBvcnRhbnQgdG8gbm90ZTsgYm90aCBwbGF0Zm9ybXMgb2ZmZXIgbGltaXRlZCBmcmVlIHJlc3BvbnNpdmUgdGVtcGxhdGVzIHdpdGggU2hvcGlmeSBzdXJwYXNzaW5nIFZvbHVzaW9uLiBUaGUgZ2VuZXJhbCBpZGVhcyBhcmUgdGhlcmUgaXMgYSBwb3NzaWJpbGl0eSBmb3IgeW91ciB3ZWJzaXRlIHRvIGJlIG1vYmlsZSBmcmllbmRseSB3aXRob3V0IG11Y2ggb2YgYSBoYXNzbGUuDQogDQpJbiBsaWdodCBvZiB3aGljaCBwbGF0Zm9ybSBpcyBiZXR0ZXIsIHdlIGhhdmUgZGlzY3Vzc2VkIHRoYXQgbW9zdGx5IFNob3BpZnkgaGFzIGEgZ3JlYXRlciBhZHZhbnRhZ2Ugb24gVm9sdXNpb24uIE5vdCB0byBzYXkgdGhhdCBWb2x1c2lvbiBpcyBiYWQgZm9yIHlvdXIgZS1jb21tZXJjZSBzdG9yZSwgaXQgaXMgaW1wb3J0YW50IHRvIG5vdGUgdGhhdCB3aGF0IHlvdSB0aGluayBpcyBiYWQgZm9yIHlvdSBvbiB0aGUgb3RoZXIgc2lkZSBtaWdodCBiZSBhbiBhZHZhbnRhZ2UgZm9yIHRoZSBuZXh0IHBlcnNvbi4gU2luY2UgYm90aCBwbGF0Zm9ybXMgb2ZmZXIgYSAxNC1kYXkgZGVtbyB0cmlhbCBwZXJpb2QgSSB3b3VsZCBzdWdnZXN0IHlvdSBzaWduIHVwIGZvciBib3RoIHBsYXRmb3JtcyBhbmQgc2VlIGZvciB5b3Vyc2VsZiB0aGUgcmVzdWx0cy4gQmVjYXVzZSBzb21lIGNvbXByaXNpbmcgY2FuIGJlIGZhaXJseSBiaWFzZWQgYW5kIHlvdSBtaWdodCBlbmQgdXAgbWFraW5nIHRoZSB3cm9uZyBkZWNpc2lvbiBmb3IgeW91ciBlLWNvbW1lcmNlIGJ1c2luZXNzLiAiVHJ5IG4gRXJyb3IiICBhcHByb2FjaCBpcyB0aGUgYmVzdCBzb2x1dGlvbiBhdmFpbGFibGUgdG8gdGFja2xlIHRoaXMgcHJvYmxlbS4gPC9wPg0KDQoNCjxoMz5Db21wYXJpc29uIG9mIFZvbHVzaW9uIHZzIFNob3BpZnk8L2gzPg0KPHA+Vm9sdXNpb24gYW5kIFNob3BpZnkgYXJlIHdoYXQgd2UgY2xhc3NpZnkgYXMgdGhlIGxlYWRpbmcgZS1jb21tZXJjZSBwbGF0Zm9ybSBwcm92aWRlcnMgaW4gdGhlIGluZHVzdHJ5IGFuZCB0aGVpciBjb21wYXJpc29uIGJldHdlZW4gYm90aCBhcmUgYSB2ZXJ5IGRpZmZpY3VsdCBkaXNjdXNzaW9uIHRvIGNvbXBpbGUgYSBkZXRhaWxlZCByZXBvcnQgd2l0aG91dCBiZWluZyBiaWFzZWQgdG8gb25lIHBsYXRmb3JtLiBJdCBzaG91bGQgYmUgZmFpcmx5IG5vdGVkIHRoYXQgYm90aCBwbGF0Zm9ybXMgaGF2ZSB0aGVpciBwcm9zIGFuZCBjb25zIGFuZCB0aGVyZSBpcyBubyBjbGVhciBhbnN3ZXIgdG8gd2hpY2ggaXMgYmVzdCBpbiB0aGUgbWFya2V0LiBEZXBlbmRpbmcgb24geW91ciB0ZWNobmljYWwga25vdy1ob3cgYW5kIGJ1ZGdldCwgaXQgaXMgdmVyeSBpbXBvcnRhbnQgdG8gd2VpZ2h0IHlvdXIgZGVjaXNpb24gb24gd2hhdCB5b3UgcmVhbGx5IGV4cGVjdCBmcm9tIGFuIGUtY29tbWVyY2UgcGxhdGZvcm0gT25lIHNob3VsZCBhbHNvIGNvbnNpZGVyIHRoZSB0eXBlIG9mIGZ1bmN0aW9uYWxpdHkgZmVhdHVyZXMgeW91IHJlcXVpcmUgYW5kIHdoYXQgZWFjaCBwbGF0Zm9ybSBpcyBmcmVlbHkgd2lsbGluZyB0byBvZmZlciBhbmQgd2hpY2ggbm90LiBJbiBteSByZXZpZXcgY29tcGFyaXNvbiBvZiBwbGF0Zm9ybXMsIEkgbW9zdGx5IGNvbmNlbnRyYXRlIG9uIHRoZSBwb3B1bGFyIGtleSBmYWN0b3JzIGZvciBjb21wYXJpbmcgYW4gZS1jb21tZXJjZSBwbGF0Zm9ybSBzdWNoIGFzOyBwcmljZXMsIGRlc2lnbiwgYW5kIHRlbXBsYXRlcywgY3VzdG9tZXIgc3VwcG9ydCwgZmVhdHVyZXMgYW5kIGVhc2UtdG8tdXNlLjwvcD4NCiANCjxoMz5Wb2x1c2lvbiB2cyBTaG9waWZ5OiBQcmljaW5nPC9oMz4NCjxwPldlIGFsbCBhZ3JlZSB0aGF0IDgwJSBvZiBvdXIgZGVjaXNpb24tbWFraW5nIHByb2Nlc3MgaXMgZGVyaXZlZCBmcm9tIHRoZSBjb3N0IG9mIGEgcHJvZHVjdCwgYnV0IGluIHRoZSBlLWNvbW1lcmNlLCBpbmR1c3RyeSBwcmljZSBoYXMgYSBjZXJ0YWluIGxpbWl0YXRpb24uIFlvdSBjYW4gY2hvb3NlIGEgcGxhdGZvcm0gd2hpY2ggaXMgcmVsYXRpdmVseSBjaGVhcGVyIHRoYW4gdGhlIGNvbXBldGl0b3IsIGJ1dCB5b3Ugd2lsbCBub3QgYmUgc2F0aXNmaWVkIHdpdGggdGhlIHNlcnZpY2VzIHlvdSB3aWxsIGdldCBiZWNhdXNlIGlmIHlvdSB1c2UgYSBwcmljZSBhcyB0aGUgb25seSBpbmRpY2F0b3IgdGhlbiB5b3Ugd2lsbCBlbmQgdXAgZmFpbGluZyBpbiB5b3VyIGUtY29tbWVyY2UgYWR2ZW50dXJlLiBWb2x1c2lvbiBwcmljZSB0YWcgc3RhcnRzIGZyb20gJDE1IHRvICQxMzUgcGVyIG1vbnRoIGFuZCBhcyBmb3IgU2hvcGlmeSBpcyBmcm9tICQyOSB0byAkMjk5IHBlciBtb250aC4gQm90aCBwbGF0Zm9ybXMgb2ZmZXIgYSAxNC1kYXlzIGZyZWUgdHJpYWwgYW5kIGRvIG5vdCByZXF1aXJlIGFueSBzZXR1cCBmZWVzIG5vciByZXF1aXJlcyB5b3UgdG8gbWFrZSBhbnkgY29tbWl0bWVudC4gQWxsIHlvdSBkbyBpcyBzaWduIHVwIGFuZCBzZWUgaWYgdGhpcyB0aGUgcmlnaHQgcGxhdGZvcm0gZm9yIHlvdXIgYnVzaW5lc3MuPC9wPg0KIA0KPGgzPlZvbHVzaW9uIHZzIFNob3BpZnk6IERlc2lnbiBhbmQgVGVtcGxhdGVzPC9oMz4NCjxwPkV2ZXJ5Ym9keSBrbm93cyB0aGF0IHRoZSBmaXJzdCBpbXByZXNzaW9uIHJlYWxseSBtYWtlcyBhIGRpZmZlcmVuY2UgYW5kIHdoZW4gaXQncyBjb21lIHRvIGFuIGUtY29tbWVyY2Ugd2Vic2l0ZSwgeW91ciBidXNpbmVzcyB3aWxsIGJlIGp1ZGdlZCBieSBob3cgYXBwZWFsaW5nIGFuZCBhdHRyYWN0aXZlIGlzIHlvdXIgd2Vic2l0ZSBkZXNpZ25zLiBQZW9wbGUgbGlrZSAid293IiByZXN1bHRzLCBhbmQgaWYgeW91ciB3ZWJzaXRlIGRvZXMgbm90IGdpdmUgeW91ciBwb3RlbnRpYWwgY3VzdG9tZXIgdGhhdCB0aGVuIGZvcmdldCB0aGVtIHN0YXlpbmcgb24gdGhlIHdlYnNpdGUuDQpCb3RoIHBsYXRmb3JtcyBvZmZlciBhIHJlYXNvbmFibGUgbGlzdCBvZiB0aGVtZXMgZm9yIHlvdXIgZS1jb21tZXJjZSB3ZWJzaXRlLiBWb2x1c2lvbiBvZmZlcnMgMjggZnJlZSB0aGVtZXMgYW5kIGFib3V0IDg4IHBhaWQgdGhlbWVzLiBUaGVpciB0aGVtZXMgbG9vayBkZWNlbnQgd2hpY2ggaXMgYSBnb29kIGVub3VnaCBmb3IgY3VzdG9taXphdGlvbi4gV2l0aCBTaG9waWZ5LCB5b3Ugd2lsbCBnZXQgMjEgZnJlZSB0aGVtZXMgYW5kIDExNiBwYWlkIHRoZW1lLiBTaG9waWZ5IHRoZXJlIGFyZSBtdWNoIG1vcmUgbW9kZXJuIGFuZCB1cGRhdGUgYXMgdGhleSBvdXRzb3VyY2UgbWFueSBkZXNpZ25lcnMgdG8gY3JlYXRlIG1vcmUgZ29vZCBhdHRyYWN0aXZlIHRoZW1lcy4NClRoZSBnb29kIG5ld3MgaXMgdGhhdCBib3RoIHBsYXRmb3JtcyBvZmZlciBmcmVlIHJlc3BvbnNpdmUgdGVtcGxhdGVzIHdpdGggU2hvcGlmeSBwcm92aWRpbmcgbW9yZSBvcHRpb25zIHRvIGNob29zZSBmcm9tIHRoYW4gVm9sdXNpb24uICBUaGUgaWRlYXMgaGVyZSBpcyB1c2luZyBib3RoIHBsYXRmb3JtcyB5b3VyIHdlYnNpdGUgd2lsbCBiZSBmdWxseSBtb2JpbGUgZnJpZW5kbHkuIFRoZSBhZHZhbnRhZ2Ugb2YgcmVzcG9uc2l2ZSB3ZWJzaXRlIGlzIHRoYXQgd2UgbGl2ZSBpbiBhbiB0ZWNobm9sb2dpY2FsIGVyYSwgd2hlcmUgZXZlcnlvbmUgb3ducyBhIFNtYXJ0cGhvbmUuPC9wPg0KIA0KPGgzPlZvbHVzaW9uIHZzIFNob3BpZnk6IEN1c3RvbWVyIFN1cHBvcnQ8L2gzPg0KPHA+V2hlbiB5b3VyIGUtY29tbWVyY2Ugd2Vic2l0ZSBpcyBkb3duIG9yIHNvbWV0aGluZyBpcyBub3Qgd29ya2luZyBhcyBpdHMgc3VwcG9zZSB0bywgaXQgaXMgaW1wb3J0YW50IHRvIGdldCBob2xkIG9mIHlvdXIgcGxhdGZvcm0gcHJvdmlkZXIgYXMgc29vbiBhcyBwb3NzaWJsZS4gQXMgZXZlcnkgbWludXRlIHlvdXIgd2Vic2l0ZSBpcyBkb3duLCBpcyBhIHBvc3NpYmxlIGxvc3Mgb2Ygc2FsZXMuDQpJIHdvdWxkIHNheSB0aGF0IGJvdGggcGxhdGZvcm1zIGhlcmUgaGF2ZSBkb25lIGEgZ3JlYXQgam9iIGJ5IHByb3ZpZGluZyAyNC83IGN1c3RvbWVyIHN1cHBvcnRzIHRvIHRoZSBjbGllbnRzLiBCb3RoIHBsYXRmb3JtcyBvZmZlciB0aGVpciBzZXJ2aWNlcyB1c2luZyBsaXZlIGNoYXQsIHBob25lLCBhbmQgZW1haWwgYW5kIGFzIGFuIGFkZGl0aW9uLCB0aGV5IGhhdmUgZGV0YWlsZWQgcmVzb3VyY2VzIGZvcnVtIGZvciB0aGVpciBjbGllbnRzLjwvcD4NCiANCiANCjxoMz5Wb2x1c2lvbiB2cyBTaG9waWZ5OiBGZWF0dXJlczwvaDM+DQo8cD5Cb3RoIHBsYXRmb3JtcyBvZmZlciBzaW1pbGFyIGJhc2ljIGZ1bmN0aW9uYWxpdHkgZmVhdHVyZXMgdG8gZG8gYWxsIGtpbmRzIGZ1bmN0aW9uIHlvdSB3b3VsZCBleHBlY3QgYW4gZS1jb21tZXJjZSBwbGF0Zm9ybSB0byBleGVjdXRlOyBwcm9kdWN0IG1hbmFnZW1lbnQsIGNyZWF0ZSBhIGRpc2NvdW50IGNvdXBvbiwgYWNjZXB0IGRpZmZlcmVudCBvbmxpbmUgcGF5bWVudCwgZXRjLg0KVGhlcmUgaXMgbm8gbXVjaCBkaWZmZXJlbmNlIHdoZW4gaXQgY29tZXMgdG8gZnV0dXJlIGNvbXBldGl0aXZlbmVzcyBhcyBib3RoIHBsYXRmb3JtcyBwcm92aWRlIGFuIGV4dGVuc2l2ZSBsaXN0IG9mIGFkZC1vbiBhcHBzIGluIHRoZWlyIEFwcCBTdG9yZXMuIFRoZSBvbmx5IHZpc2libGUgZGlmZmVyZW5jZXMgYmV0d2VlbiBWb2x1c2lvbiBhbmQgU2hvcGlmeSBpcyB0aGF0IFZvbHVzaW9uIGhhcyBhIHJlYWR5IGJ1aWx0LWluIG11bHRpLWxpbmd1YWwgc3lzdGVtIHdoaWNoIGVuYWJsZXMgeW91IHRvIGhvc3QgeW91ciB3ZWJzaXRlIGluIG1hbnkgZGlmZmVyZW50IGxhbmd1YWdlcy4gQnV0IHdpdGggU2hvcGlmeSwgeW91IHdpbGwgbmVlZCBhIDNyZCBwYXJ0eSBpbnRlZ3JhdGlvbiB0byBkbyB0aGlzLg0KUGF5bWVudCBnYXRld2F5cyBhcmUgZXNzZW50aWFsIHRvIGUtY29tbWVyY2UgYnVzaW5lc3MgYW5kIGJvdGggcGxhdGZvcm1zIHByb3ZpZGUgdGhpcy4gT2YgY291cnNlLCBTaG9waWZ5IHN1cnBhc3NlcyBWb2x1c2lvbiB3aXRoIDcwKyBwYXltZW50IGdhdGV3YXlzIHdoaWxlIHRoZSBjb21wZXRpdG9yIGdvdCAzOC48L3A+DQogDQo8aDM+Vm9sdXNpb24gdnMgU2hvcGlmeTogRWFzZS10by11c2U8L2gzPg0KPHA+RS1jb21tZXJjZSBwbGF0Zm9ybSB1c2VycyBhbHdheXMgbG9vayBmb3Igc2ltcGxpY2l0eSBhbmQgd2hlcmUgdGhleSBjYW4gZWFzaWx5IHNldHVwIHRoZWlyIG9ubGluZSBzdG9yZXMuIE5vIG9uZSB3aWxsIHNldHRsZSBmb3IgYSBjb21wbGljYXRlZCBwbGF0Zm9ybSB0aGF0IHdpbGwgZ2l2ZSB0aGVtIGxvdHMgb2YgaGVhZGFjaGVzIHRvIHVzZS4gSSBiZWxpZXZlIFNob3BpZnkgaGFzIGEgbW9yZSB1c2VyLWZyaWVuZGx5IHN5c3RlbSwgdGhhdCBjYW4gYmUgdXNlZCBieSBib3RoIGJlZ2lubmVycyBhbmQgYWR2YW5jZWQgdXNlciwgdGhhbiBWb2x1c2lvbi4gU3VycHJpc2luZ2x5LCBib3RoIHBsYXRmb3JtcyBhbGxvdyB5b3UgdG8gY3VzdG9taXplIHlvdXIgd2Vic2l0ZSB0byBldmVyeW9uZSBpbmRpdmlkdWFsIG5lZWQsIGJ1dCBzaG91bGQgYmUgbm90ZWQgdGhhdCBpdCdzIG9ubHkgdG8gYSBjZXJ0YWluIGRlZ3JlZS4gWW91IHdpbGwsIGFsc28sIGhvd2V2ZXIsIGxhdW5jaCB5b3VyIGUtY29tbWVyY2Ugd2Vic2l0ZSBmYXN0ZXIgd2l0aCBTaG9waWZ5IHRoYW4gVm9sdXNpb24uPC9wPg0KIA0KPGgzPkNvbmNsdXNpb248L2gzPg0KPHA+RXZlbiB0aG91Z2ggYm90aCBwbGF0Zm9ybXMgaGF2ZSB0aGVpciBhZHZhbnRhZ2VzIGFuZCBkaXNhZHZhbnRhZ2VzLCBpdCBpcyBpbXBvcnRhbnQgdG8gbm90ZSB0aGF0IGJvdGggcGxhdGZvcm1zIGNvbXBldGl0aXZlbHkgd2lsbGluZyB0byBwb3dlciB5b3VyIGUtY29tbWVyY2Ugd2Vic2l0ZS4gVGhlcmUgaXMgbm8gcmVhbCBiZXN0IHBsYXRmb3JtIGluIHRoZSBtYXJrZXQgYW5kIHdoZW4gY2hvb3NpbmcgdGhlIHJpZ2h0IGZpdCB3aWxsIGRlcGVuZCBvbiB5b3VyIGZpbmFuY2lhbCBidWRnZXQgYW5kIHRoZSBuYXR1cmUgb2YgeW91ciBidXNpbmVzcy4gQm90aCBwbGF0Zm9ybXMgb2ZmZXIgZGVtbyB0cmlhbCBwZXJpb2Qgd2l0aCBubyBzdHJpbmcgYXR0YWNoZWQgYW5kIGl0J3MgaW4geW91ciBiZXN0IGludGVyZXN0IHRvIGZ1bGx5IHV0aWxpemUgdGhpcyBvZmZlciB0ZXN0IGVhY2ggcGxhdGZvcm0gYmVmb3JlIG1ha2luZyB5b3VyIGZpbmFsIGRlY2lzaW9uDQpBIGZyaWVuZGx5IHJlbWVtYmVyIGlmIHRoZSBhYm92ZSBkb2VzIG5vdCBjb252aW5jZSB5b3UgdG8gY2hvb3NlLCB0aGVyZSBhcmUgcGxlbnR5IG9mIGUtY29tbWVyY2UgcGxhdGZvcm0gaW4gdGhlIGluZHVzdHJ5LiBTbyBkb24ndCBmZWVsIHByZXNzdXJlZCwgZXhwbG9yZSBvdGhlciBzb2x1dGlvbiBhbmQgeW91IHdpbGwgc3VyZWx5IGZpbmQgb25lIHRoYXQgd2lsbCBnaXZlIHlvdSB0aGF0ICJ3b3ciIHJlc3VsdC48L3A+PHA+PGVtPkFydGljbGUgY291cnRlc3kgb2YgPGEgaHJlZj0iaHR0cDovL3d3dy5lY29tbWVyY2VzcG90LmNvbSI+RWNvbW1lcmNlIFNwb3Q8L2E+LjwvZW0+PC9wPmRkZEN8ge/RlRvr8a1ASyv4RYuyKTkW5MlXYgJ/YtKCQHZ/" />

<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="CD96ACFB" />
        <div align="center">
            
            
        </div>
        <div id="content" class="cols">
                <div id="_ctl0_headerSelection" class="headerstandard">
                    <h2>
                        
    <span id="_ctl0_bodyHeader_lblBodyHead">The differences between Shopify vs Volusion</span>

                    </h2>
                </div>
                <div class="inpage">
                    


    <span id="_ctl0_contentBody_lblTitle"><h1>The differences between Shopify vs Volusion</h1></span>
    <p>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Top -->
        <ins class="adsbygoogle"
            style="display: block"
            data-ad-client="ca-pub-1388311751127083"
            data-ad-slot="8765540533"
            data-ad-format="auto"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
        <span id="_ctl0_contentBody_lblBody"><p>Selecting the right e-commerce platform for your e-commerce business can be an overwhelming process that will take up most of your time. Shopify and Volusion are both popular e-commerce providers that give business owners the opportunities to create unique online stores. Comparing both platforms has significant influence when choosing the right fit for your e-commerce business. The most popular key factors for comparing  e-commerce platforms are:</p>

<ol>

<li>Ease-to-use</li>
<li>Features</li>
<li>Pricing</li>
<li>Payment Gateways</li>
<li>Support</li>
<li>Design and Templates</li>

</ol>

<p> I will be using the above factors to give a detailed analytic report of Shopify vs Volusion.</p>

<h3>Ease-to-use</h3>
<p>User simplicity is a very important feature for an e-commerce platform. When it comes to ease-to-use friendliness, I would say Shopify is on top of their game compared to Volusion. The biggest differences between the two platforms are; Shopify is built for both beginners and advanced users, while Volusion is complex and can be even frustrating for both users. This gives Shopify a competitive advantage with a quick method to setup an online store.
Both platforms allow the user to actively use/edit the dashboard menu for orders, marketing, customers, inventory, etc.</p>

<h3>Features</h3>
<p>If we are talking about basic store functionality, both Shopify and Volusion offers all the required functionalities that are fairly powerful yet easy to setup, use and maintain. Both platforms have App store, with Shopify providing a wider list of variants than Volusion. Apps allow you to add additional functionality to an online store, and integrate third party web applications.
Volusion has multi-lingual capabilities, this means Volusion user can easily have their e-commerce website translated into many different languages. However Shopify does not have this feature built in the system, it can be easily be done through paid third party extensions.
In my opinion, I believe both platforms offer extensive SEO capabilities in order to attract organic traffics to your online store through search engines </p>

<h3>Pricing</h3>
<p>Pricing is a powerful indicator in the e-commerce market. It will be in your best interest to carefully read the value of the platform rather than making your decision based the cost of the services. You could end up paying less money for an online store at the beginning and pay more in the long-run.
It's important to note here that both platforms do not require any setup fees to start. In fact, they both offer 14-days free trial, which one can use to test and evaluate the functionality and capability offered by hosting your e-commerce store with their platform.
The price range to host your online store with Shopify starts from $29 to $299 per month, while Volusion starts from $15 to $135 per month.</p>

<h3>Payment Gateways</h3>
<p>Another factor to consider when comparing the two platforms is checking their payment gateway options methods. Both platforms integrate with a large number of payment gateways, third-party tools that help online stores to process transactions on the website. Fortunately, Shopify surpasses Volusion in this criteria, of which, Shopify holds 70+ and Volusion 38. </p>
 
<h3>Supports</h3>
<p>Support is essential services for any services business and without this many online stores, owners will not be able to access critical information.
Shopify provides 24/7 customer supports, using an own blog, resources and a knowledge base hub for customer learning. They offer live chat, email, phone and forum support.
Volusion support page is filled with goodies, such as knowledge base, videos and contact form. The 24/7 support is provided through live chat, phone, and email.</p>
 
<h3>Design and Templates</h3>
<p>The design of your e-commerce website is a key factor to attract more visitors to your website. An unprofessionally designed website will not inspire trust in your customer's eyes, so it is best to be on top of your game in this indicator.
Shopify offers 21 free themes and about 116 paid themes. Their themes look modernized and it does not take much to customize them without knowing how to custom code.
On the other hand, Volusion has 28 free themes and 88 paid themes. This is almost a close offering to what you can find on Shopify. Their design is not as modern and sophisticated, however, they are acceptable. Volusion themes can be  a little bit difficult to customize.
It is important to note; both platforms offer limited free responsive templates with Shopify surpassing Volusion. The general ideas are there is a possibility for your website to be mobile friendly without much of a hassle.
 
In light of which platform is better, we have discussed that mostly Shopify has a greater advantage on Volusion. Not to say that Volusion is bad for your e-commerce store, it is important to note that what you think is bad for you on the other side might be an advantage for the next person. Since both platforms offer a 14-day demo trial period I would suggest you sign up for both platforms and see for yourself the results. Because some comprising can be fairly biased and you might end up making the wrong decision for your e-commerce business. "Try n Error"  approach is the best solution available to tackle this problem. </p>


<h3>Comparison of Volusion vs Shopify</h3>
<p>Volusion and Shopify are what we classify as the leading e-commerce platform providers in the industry and their comparison between both are a very difficult discussion to compile a detailed report without being biased to one platform. It should be fairly noted that both platforms have their pros and cons and there is no clear answer to which is best in the market. Depending on your technical know-how and budget, it is very important to weight your decision on what you really expect from an e-commerce platform One should also consider the type of functionality features you require and what each platform is freely willing to offer and which not. In my review comparison of platforms, I mostly concentrate on the popular key factors for comparing an e-commerce platform such as; prices, design, and templates, customer support, features and ease-to-use.</p>
 
<h3>Volusion vs Shopify: Pricing</h3>
<p>We all agree that 80% of our decision-making process is derived from the cost of a product, but in the e-commerce, industry price has a certain limitation. You can choose a platform which is relatively cheaper than the competitor, but you will not be satisfied with the services you will get because if you use a price as the only indicator then you will end up failing in your e-commerce adventure. Volusion price tag starts from $15 to $135 per month and as for Shopify is from $29 to $299 per month. Both platforms offer a 14-days free trial and do not require any setup fees nor requires you to make any commitment. All you do is sign up and see if this the right platform for your business.</p>
 
<h3>Volusion vs Shopify: Design and Templates</h3>
<p>Everybody knows that the first impression really makes a difference and when it's come to an e-commerce website, your business will be judged by how appealing and attractive is your website designs. People like "wow" results, and if your website does not give your potential customer that then forget them staying on the website.
Both platforms offer a reasonable list of themes for your e-commerce website. Volusion offers 28 free themes and about 88 paid themes. Their themes look decent which is a good enough for customization. With Shopify, you will get 21 free themes and 116 paid theme. Shopify there are much more modern and update as they outsource many designers to create more good attractive themes.
The good news is that both platforms offer free responsive templates with Shopify providing more options to choose from than Volusion.  The ideas here is using both platforms your website will be fully mobile friendly. The advantage of responsive website is that we live in an technological era, where everyone owns a Smartphone.</p>
 
<h3>Volusion vs Shopify: Customer Support</h3>
<p>When your e-commerce website is down or something is not working as its suppose to, it is important to get hold of your platform provider as soon as possible. As every minute your website is down, is a possible loss of sales.
I would say that both platforms here have done a great job by providing 24/7 customer supports to the clients. Both platforms offer their services using live chat, phone, and email and as an addition, they have detailed resources forum for their clients.</p>
 
 
<h3>Volusion vs Shopify: Features</h3>
<p>Both platforms offer similar basic functionality features to do all kinds function you would expect an e-commerce platform to execute; product management, create a discount coupon, accept different online payment, etc.
There is no much difference when it comes to future competitiveness as both platforms provide an extensive list of add-on apps in their App Stores. The only visible differences between Volusion and Shopify is that Volusion has a ready built-in multi-lingual system which enables you to host your website in many different languages. But with Shopify, you will need a 3rd party integration to do this.
Payment gateways are essential to e-commerce business and both platforms provide this. Of course, Shopify surpasses Volusion with 70+ payment gateways while the competitor got 38.</p>
 
<h3>Volusion vs Shopify: Ease-to-use</h3>
<p>E-commerce platform users always look for simplicity and where they can easily setup their online stores. No one will settle for a complicated platform that will give them lots of headaches to use. I believe Shopify has a more user-friendly system, that can be used by both beginners and advanced user, than Volusion. Surprisingly, both platforms allow you to customize your website to everyone individual need, but should be noted that it's only to a certain degree. You will, also, however, launch your e-commerce website faster with Shopify than Volusion.</p>
 
<h3>Conclusion</h3>
<p>Even though both platforms have their advantages and disadvantages, it is important to note that both platforms competitively willing to power your e-commerce website. There is no real best platform in the market and when choosing the right fit will depend on your financial budget and the nature of your business. Both platforms offer demo trial period with no string attached and it's in your best interest to fully utilize this offer test each platform before making your final decision
A friendly remember if the above does not convince you to choose, there are plenty of e-commerce platform in the industry. So don't feel pressured, explore other solution and you will surely find one that will give you that "wow" result.</p></span>
    </p>
    
    


    <script type="text/javascript">
        function SelectAll(id) {
            document.getElementsByTagName("textarea").item(0).focus();
            document.getElementsByTagName("textarea").item(0).select();
        }

        document.getElementsByTagName("textarea").item(0).onclick = function () { SelectAll() };

    </script>

     <script type="text/javascript">
       var CurrentArticleName = "";
       var CurrentArticleImage = "";
     </script>


    <script type="text/javascript">

        var HidePopupOnPage = "False";

        if (document.location.protocol == 'http:') {
            var Tynt = Tynt || []; Tynt.push('c-yIBWcq8r4lYkadbi-bnq'); Tynt.i = { "st": true };
            (function () { var s = document.createElement('script'); s.async = "async"; s.type = "text/javascript"; s.src = 'http://tcr.tynt.com/ti.js'; var h = document.getElementsByTagName('script')[0]; h.parentNode.insertBefore(s, h); })();
        }
    </script>

                </div>
        </div>
        <div id="bot">
            <p>
                Copyright &copy;2019
                PoppyWeb Pty Ltd. Registered trademarks are property of their respective owners.</p>
            <p>
                <a href="/aboutus.aspx">About
                    us</a> | <a href="/privacy.aspx">Privacy Policy</a> | <a href="/sitemap.aspx">Site Map</a>
               </p>
        </div>
    </div>
    </form>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-55587-2']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_trackPageLoadTime']);
    (function () {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
	
//ranking	
if (document.referrer.match(/google\.com/gi) && document.referrer.match(/cd/gi)) {
  var myString = document.referrer;
  var r        = myString.match(/cd=(.*?)&/);
  var rank     = parseInt(r[1]);
  var kw       = myString.match(/q=(.*?)&/);
  
  if (kw[1].length > 0) {
    var keyWord  = decodeURI(kw[1]);
  } else {
    keyWord = "(not provided)";
  }

  var p        = document.location.pathname;
  _gaq.push(['_trackEvent', 'RankTracker', keyWord, p, rank, true]);
}	
</script>

<!-- Google Code for Ecommerce Spot all of site list Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1067845965;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "9YFsCP_U6gEQzZKY_QM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1067845965/?label=9YFsCP_U6gEQzZKY_QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


		<link rel="stylesheet" type="text/css" href="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
		
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		<script type="text/javascript" src="http://cdn.ecommercespot.com/fancybox/jquery.fancybox-1.3.4.pack.js"></script>


<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js'></script>


<script type='text/javascript' src='/hello-overlay-edf-2016.js'></script>

    <!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/57c860240e2ec4134ce4b108/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</body>
</html>
